### ISSUE TITLE
[BUG] FARMER_HOE threw an exception

### ISSUE THREAD

**Issue by ScottDTA** [ldtteam/minecolonies#10133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.629-BETA

### Structurize Version

1.1.0.742-RELEASE

### Related Mods and their Versions

Actually Subtractions   1.2.14.1+mc1.20.1

### Current Behavior

[15:27:29] [Server thread/WARN] [minecolonies/]: Statemachine for state FARMER_HOE threw an exception:
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.player.Player.m_9236_()" because the return value of "net.minecraftforge.event.level.BlockEvent$BlockToolModificationEvent.getPlayer()" is null
	at de.ellpeck.actuallyadditions.mod.items.Worm.onHoe(Worm.java:64) ~[ActuallySubtractions-1.20.1-1.2.14.1+mc1.20.1.jar%23130!/:1.2.14.1+mc1.20.1] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar%23109!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar%23109!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%23109!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%23109!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onToolUse(ForgeEventFactory.java:429) ~[forge-1.20.1-47.3.5-universal.jar%23561!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraftforge.common.extensions.IForgeBlockState.getToolModifiedState(IForgeBlockState.java:661) ~[forge-1.20.1-47.3.5-universal.jar%23561!/:?] {re:computing_frames,re:mixin,re:classloading}
	at steve_gall.minecolonies_compatibility.core.common.block.BlockUtils.getToolModifiedState(BlockUtils.java:30) ~[MineColonies_Compatibility-1.20.1-2.34.jar%23386!/:1.20.1-2.34] {re:mixin,re:classloading}
	at steve_gall.minecolonies_compatibility.core.common.block.BlockUtils.getHoeTilledState(BlockUtils.java:22) ~[MineColonies_Compatibility-1.20.1-2.34.jar%23386!/:1.20.1-2.34] {re:mixin,re:classloading}
	at com.minecolonies.core.entity.ai.workers.production.agriculture.EntityAIWorkFarmer.redirect$dkf000$createCorrectFarmlandForSeed_setBlockAndUpdate(EntityAIWorkFarmer.java:2205) ~[minecolonies-1.20.1-1.1.629-BETA.jar%23385!/:1.20.1-1.1.629-BETA] {re:mixin,re:classloading,pl:mixin:A}
	at com.minecolonies.core.entity.ai.workers.production.agriculture.EntityAIWorkFarmer.createCorrectFarmlandForSeed(EntityAIWorkFarmer.java:616) ~[minecolonies-1.20.1-1.1.629-BETA.jar%23385!/:1.20.1-1.1.629-BETA] {re:mixin,re:classloading,pl:mixin:A}
	at com.minecolonies.core.entity.ai.workers.production.agriculture.EntityAIWorkFarmer.hoeIfAble(EntityAIWorkFarmer.java:591) ~[minecolonies-1.20.1-1.1.629-BETA.jar%23385!/:1.20.1-1.1.629-BETA] {re:mixin,re:classloading,pl:mixin:A}
	at com.minecolonies.core.entity.ai.workers.production.agriculture.EntityAIWorkFarmer.workAtField(EntityAIWorkFarmer.java:531) ~[minecolonies-1.20.1-1.1.629-BETA.jar%23385!/:1.20.1-1.1.629-BETA] {re:mixin,re:classloading,pl:mixin:A}
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:79) ~[minecolonies-1.20.1-1.1.629-BETA.jar%23385!/:1.20.1-1.1.629-BETA] {re:classloading}
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:163) ~[minecolonies-1.20.1-1.1.629-BETA.jar%23385!/:1.20.1-1.1.629-BETA] {re:classloading}
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:149) ~[minecolonies-1.20.1-1.1.629-BETA.jar%23385!/:1.20.1-1.1.629-BETA] {re:classloading}
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:126) ~[minecolonies-1.20.1-1.1.629-BETA.jar%23385!/:1.20.1-1.1.629-BETA] {re:classloading}
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:102) ~[minecolonies-1.20.1-1.1.629-BETA.jar%23385!/:1.20.1-1.1.629-BETA] {re:classloading}
	at com.minecolonies.core.entity.ai.workers.AbstractAISkeleton.tick(AbstractAISkeleton.java:63) ~[minecolonies-1.20.1-1.1.629-BETA.jar%23385!/:1.20.1-1.1.629-BETA] {re:mixin,re:classloading,pl:mixin:A}
	at com.minecolonies.core.entity.ai.workers.CitizenAI.lambda$registerWorkAI$4(CitizenAI.java:97) ~[minecolonies-1.20.1-1.1.629-BETA.jar%23385!/:1.20.1-1.1.629-BETA] {re:classloading}
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:79) ~[minecolonies-1.20.1-1.1.629-BETA.jar%23385!/:1.20.1-1.1.629-BETA] {re:classloading}
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:163) ~[minecolonies-1.20.1-1.1.629-BETA.jar%23385!/:1.20.1-1.1.629-BETA] {re:classloading}
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:149) ~[minecolonies-1.20.1-1.1.629-BETA.jar%23385!/:1.20.1-1.1.629-BETA] {re:classloading}
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:126) ~[minecolonies-1.20.1-1.1.629-BETA.jar%23385!/:1.20.1-1.1.629-BETA] {re:classloading}
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:102) ~[minecolonies-1.20.1-1.1.629-BETA.jar%23385!/:1.20.1-1.1.629-BETA] {re:classloading}
	at com.minecolonies.core.entity.citizen.EntityCitizen.lambda$new$11(EntityCitizen.java:303) ~[minecolonies-1.20.1-1.1.629-BETA.jar%23385!/:1.20.1-1.1.629-BETA] {re:classloading,re:mixin}
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.checkCondition(BasicTransition.java:87) ~[minecolonies-1.20.1-1.1.629-BETA.jar%23385!/:1.20.1-1.1.629-BETA] {re:classloading}
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:138) ~[minecolonies-1.20.1-1.1.629-BETA.jar%23385!/:1.20.1-1.1.629-BETA] {re:classloading}
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:126) ~[minecolonies-1.20.1-1.1.629-BETA.jar%23385!/:1.20.1-1.1.629-BETA] {re:classloading}
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:102) ~[minecolonies-1.20.1-1.1.629-BETA.jar%23385!/:1.20.1-1.1.629-BETA] {re:classloading}
	at com.minecolonies.api.entity.citizen.AbstractEntityCitizen.m_8107_(AbstractEntityCitizen.java:431) ~[minecolonies-1.20.1-1.1.629-BETA.jar%23385!/:1.20.1-1.1.629-BETA] {re:classloading,re:mixin}
	at com.minecolonies.core.entity.citizen.EntityCitizen.m_8107_(EntityCitizen.java:717) ~[minecolonies-1.20.1-1.1.629-BETA.jar%23385!/:1.20.1-1.1.629-BETA] {re:classloading,re:mixin}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2298) ~[client-1.20.1-20230612.114412-srg.jar%23556!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:forge-badoptimizations.mixins.json:entitydata.MixinLivingEntity,pl:mixin:APP:modernfix-forge.mixins.json:perf.forge_cap_retrieval.LivingEntityMixin,pl:mixin:APP:caelus.mixins.json:MixinLivingEntity,pl:mixin:APP:oreberriesreplanted.mixins.json:LivingEntityAccessor,pl:mixin:APP:notenoughanimations.mixins.json:LivingEntityMixin,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.dismount_dead_entities.MixinLivingEntity,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.ladders.MixinLivingEntity,pl:mixin:APP:fruitsdelight.mixins.json:LivingEntityMixin,pl:mixin:APP:adastra-common.mixins.json:common.EntityBelowWorldMixin,pl:mixin:APP:adastra-common.mixins.json:common.LivingEntityAccessor,pl:mixin:APP:adastra-common.mixins.json:common.LivingEntityMixin,pl:mixin:APP:adastra-common.mixins.json:common.radio.LivingEntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:accessors.entity.AccessorLivingEntity,pl:mixin:APP:bookshelf.common.mixins.json:patches.entity.MixinLivingEntity,pl:mixin:APP:copycats-common.mixins.json:copycat.trapdoor.LivingEntityMixin,pl:mixin:APP:mixins.enderio.json:LivingEntityMixin,pl:mixin:APP:freecam.mixins.json:LivingEntityMixin,pl:mixin:APP:dynamiclightsreforged.mixins.json:lightsource.LivingEntityMixin,pl:mixin:APP:scena.mixins.json:common.LivingEntityEquipmentSlotMixin,pl:mixin:APP:mixins.irons_spellbooks.json:LivingEntityMixin,pl:mixin:APP:mixins.shetiphiancore.json:SPC_ThinBlockHandler$_LivingEntity,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:mixins.brandonscore.json:LivingEntityMixin,pl:mixin:APP:mixins.pneumaticcraft.json:coremods.LivingEntityMixin,pl:mixin:APP:mixins.cofhcore.json:LivingEntityMixin,pl:mixin:APP:mna.mixins.json:LivingEntityFireWalkerMixin,pl:mixin:APP:mna.mixins.json:LivingEntityOnClimbableMixin,pl:mixin:APP:mna.mixins.json:LivingEntityElytra,pl:mixin:APP:canary.mixins.json:alloc.enum_values.living_entity.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.unpushable_cramming.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_elytra_check.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_hand_swing.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_powder_snow_check.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.skip_equipment_change_check.LivingEntityMixin,pl:mixin:APP:botania_xplat.mixins.json:LivingEntityAccessor,pl:mixin:APP:tetra.mixins.json:LivingEntityMixin,pl:mixin:APP:netherportalfix.mixins.json:LivingEntityAccessor,pl:mixin:APP:ars_nouveau.mixins.json:LivingAccessor,pl:mixin:APP:ars_nouveau.mixins.json:elytra.MixinLivingEntity,pl:mixin:APP:ars_nouveau.mixins.json:perks.PerkLivingEntity,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:betterdeserttemples.mixins.json:PharaohKilledMixin,pl:mixin:APP:elementalcraft.mixins.json:MixinLivingEntity,pl:mixin:APP:quark.mixins.json:accessor.AccessorLivingEntity,pl:mixin:APP:supplementaries-common.mixins.json:LivingEntityMixin,pl:mixin:APP:supplementaries.mixins.json:LivingEntityMixin,pl:mixin:APP:create.mixins.json:CustomItemUseEffectsMixin,pl:mixin:APP:create.mixins.json:LavaSwimmingMixin,pl:mixin:APP:create.mixins.json:accessor.LivingEntityAccessor,pl:mixin:A}
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:337) ~[client-1.20.1-20230612.114412-srg.jar%23556!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:adastra-common.mixins.json:common.MobMixin,pl:mixin:APP:bookshelf.common.mixins.json:accessors.entity.AccessorMob,pl:mixin:APP:mixins.pneumaticcraft.json:accessors.MobAccess,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.MobMixin,pl:mixin:APP:canary.mixins.json:entity.skip_equipment_change_check.MobMixin,pl:mixin:APP:botania_xplat.mixins.json:MobAccessor,pl:mixin:APP:ars_nouveau.mixins.json:MobAccessor,pl:mixin:APP:ars_nouveau.mixins.json:jar.MobAccessorMixin,pl:mixin:APP:mixins.letmedespawn.json:MobMixin,pl:mixin:APP:moonlight-common.mixins.json:EntityMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[client-1.20.1-20230612.114412-srg.jar%23556!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:mixins.hammerlib.json:ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.faster_structure_location.ServerLevelMixin,pl:mixin:APP:krypton.mixins.json:server.fastchunkentityaccess.ServerWorldMixin,pl:mixin:APP:corgilib-common.mixins.json:MixinServerLevel,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.shipyard_entities.MixinServerLevel,pl:mixin:APP:valkyrienskies-common.mixins.json:server.world.MixinServerLevel,pl:mixin:APP:adastra-common.mixins.json:common.ServerLevelMixin,pl:mixin:APP:adastra-common.mixins.json:common.multipart.ServerLevelMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:ohthetreesyoullgrow.mixins.json:MixinServerLevel,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:chunk.replace_streams.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:profiler.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:util.accessors.ServerLevelAccessor,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerLevelMixin,pl:mixin:APP:ars_elemental.mixins.json:ServerLevelMixin,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:comforts.mixins.json:MixinServerSleepStatus,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[client-1.20.1-20230612.114412-srg.jar%23556!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:twilightforest:cloud,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:cloud,pl:mixin:APP:mixins.hammerlib.json:LevelMixin,pl:mixin:APP:create_new_age.mixins.json:LevelMixin,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.clip_replace.MixinLevel,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.get_entities.MixinLevel,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.world_border.MixinLevel,pl:mixin:APP:valkyrienskies-common.mixins.json:world.level.MixinLevel,pl:mixin:APP:adastra.mixins.json:common.multipart.LevelMixin,pl:mixin:APP:dynamiclightsreforged.mixins.json:WorldMixin,pl:mixin:APP:sliceanddice.mixins.json:LevelMixin,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.LevelMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.intersection.LevelMixin,pl:mixin:APP:canary.mixins.json:util.block_entity_retrieval.LevelMixin,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.LevelMixin,pl:mixin:APP:canary.mixins.json:world.chunk_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_block_access.LevelMixin,pl:mixin:APP:canary.mixins.json:world.inline_height.LevelMixin,pl:mixin:APP:botania_xplat.mixins.json:LevelAccessor,pl:mixin:APP:citadel.mixins.json:LevelMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[client-1.20.1-20230612.114412-srg.jar%23556!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:mixins.hammerlib.json:ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.faster_structure_location.ServerLevelMixin,pl:mixin:APP:krypton.mixins.json:server.fastchunkentityaccess.ServerWorldMixin,pl:mixin:APP:corgilib-common.mixins.json:MixinServerLevel,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.shipyard_entities.MixinServerLevel,pl:mixin:APP:valkyrienskies-common.mixins.json:server.world.MixinServerLevel,pl:mixin:APP:adastra-common.mixins.json:common.ServerLevelMixin,pl:mixin:APP:adastra-common.mixins.json:common.multipart.ServerLevelMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:ohthetreesyoullgrow.mixins.json:MixinServerLevel,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:chunk.replace_streams.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:profiler.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:util.accessors.ServerLevelAccessor,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerLevelMixin,pl:mixin:APP:ars_elemental.mixins.json:ServerLevelMixin,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:comforts.mixins.json:MixinServerSleepStatus,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23556!/:?] {re:mixin,re:classloading,pl:mixin:APP:canary.mixins.json:collections.entity_ticking.EntityTickListMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[client-1.20.1-20230612.114412-srg.jar%23556!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cupboard.mixins.json:ServerAddEntityMixin,pl:mixin:APP:mixins.hammerlib.json:ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ServerLevelMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.faster_structure_location.ServerLevelMixin,pl:mixin:APP:krypton.mixins.json:server.fastchunkentityaccess.ServerWorldMixin,pl:mixin:APP:corgilib-common.mixins.json:MixinServerLevel,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.shipyard_entities.MixinServerLevel,pl:mixin:APP:valkyrienskies-common.mixins.json:server.world.MixinServerLevel,pl:mixin:APP:adastra-common.mixins.json:common.ServerLevelMixin,pl:mixin:APP:adastra-common.mixins.json:common.multipart.ServerLevelMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:ohthetreesyoullgrow.mixins.json:MixinServerLevel,pl:mixin:APP:canary.mixins.json:alloc.chunk_random.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:chunk.replace_streams.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:entity.inactive_navigations.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:profiler.ServerLevelMixin,pl:mixin:APP:canary.mixins.json:util.accessors.ServerLevelAccessor,pl:mixin:APP:canary.mixins.json:world.block_entity_ticking.sleeping.ServerLevelMixin,pl:mixin:APP:botania_xplat.mixins.json:ServerLevelMixin,pl:mixin:APP:ars_elemental.mixins.json:ServerLevelMixin,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:comforts.mixins.json:MixinServerSleepStatus,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23556!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23556!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23556!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:modernfix-common.mixins.json:perf.thread_priorities.IntegratedServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23556!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23556!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Unknown Source) ~[?:?] {re:mixin}
[15:27:29] [Server thread/ERROR] [minecolonies/]: Pausing Citizen Olivia M. Groston[FARMER_HOE] (com.minecolonies.job.farmer) in colony:1 at BlockPos{x=-67, y=70, z=1023} for 6400 Seconds because of error:
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.player.Player.m_9236_()" because the return value of "net.minecraftforge.event.level.BlockEvent$BlockToolModificationEvent.getPlayer()" is null

### Expected Behavior

The farmer to actually hoe

### Reproduction Steps

Run latest minecolonies with actual subtractions.

### Logs

https://pastebin.com/seTjLA1L

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
ActuallySubtractions assumes hoes are only used by players and causes the exception. You would need to report this to them

**Comment by Thodor12** [comment]
There's nothing we can do to fix this, I'll link this issue to their Github and create an issue there.

**Comment by ScottDTA** [comment]
the official version of Actually Additions on 1.20.4 doesn't reference the player, so shouldn't be an issue with future versions, only the backported version.
