### ISSUE TITLE
[BUG] My AI has run into a problem - Build Success - queueSound

### ISSUE THREAD

**Issue by TheRocket81** [ldtteam/minecolonies#10160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [ ] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.624-BETA

### Structurize Version

1.20.1-1.0.742-RELEASE

### Related Mods and their Versions

Sounds-2.0.4+1.20.1+forge.jar
ImmersiveUI-FORGE-0.2.2.jar
OctoLib-FORGE-0.4.2+1.20.1.jar
MRU-1.0.2+1.20.1+forge.jar
architectury-9.2.14-forge.jar

### Reproduction Steps

After installing the related mods above (likely Sounds-2.0.4+1.20.1+forge.jar has an impact here), the following AI error occurs.
No, I'm not running the latest Minecolonies version yet, but I've checked roughly recent fixes and they don't seems to involve the stack trace i'm getting. I will test again with and without the suspected mod, and in the most recent version too if possible.

When a worker completes a building, this error is thrown in the logs, and the Builder says it's AI has run into a problem:

Statemachine for state BUILDING_STEP threw an exception:
java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.toString()" because "p_130086_" is null
	at net.minecraft.network.FriendlyByteBuf.m_130085_(FriendlyByteBuf.java:715) ~[client-1.20.1-20230612.114412-srg.jar%23278!/:?]
	at com.minecolonies.core.network.messages.client.colony.PlaySoundForCitizenMessage.toBytes(PlaySoundForCitizenMessage.java:154) ~[minecolonies-1.20.1-1.1.624-BETA.jar%23245!/:1.20.1-1.1.624-BETA]
	at com.minecolonies.core.network.NetworkChannel.handleSplitting(NetworkChannel.java:427) ~[minecolonies-1.20.1-1.1.624-BETA.jar%23245!/:1.20.1-1.1.624-BETA]
	at com.minecolonies.core.network.NetworkChannel.sendToPosition(NetworkChannel.java:351) ~[minecolonies-1.20.1-1.1.624-BETA.jar%23245!/:1.20.1-1.1.624-BETA]
	at com.minecolonies.core.entity.citizen.EntityCitizen.queueSound(EntityCitizen.java:1926) ~[minecolonies-1.20.1-1.1.624-BETA.jar%23245!/:1.20.1-1.1.624-BETA]
	at com.minecolonies.core.entity.ai.workers.util.BuildingStructureHandler.triggerSuccess(BuildingStructureHandler.java:222) ~[minecolonies-1.20.1-1.1.624-BETA.jar%23245!/:1.20.1-1.1.624-BETA]

Full mod list, sorted by "update date".
[modlist.txt](https://github.com/user-attachments/files/16739203/modlist.txt)

### Logs

https://gist.github.com/TheRocket81/6e7be1852c0693ce49d09e213353f13e

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by TheRocket81** [comment]
Removing the Sounds-2.0.4+1.20.1+forge.jar mod seems to resolve the AI issue.
