### ISSUE TITLE
java.util.UnknownFormatConversionException: Conversion = '.'

### ISSUE THREAD

**Issue by anoxemian** [ldtteam/minecolonies#10215]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.21

### MineColonies Version

1.1.691

### Structurize Version

1.0.751

### Related Mods and their Versions

1. NeoForge 21.1.51
2. BlockUI 1.0.188
3. DO 1.0.203

### Reproduction Steps

Just try to launch client, works server-side.

### Logs

https://pastebin.com/LqvCktkt

### Anything else?

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.Formatter.parse(Formatter.java:2852) ~[?:?] {}
-- Mod loading issue for: minecolonies --
Details:
	Mod file: /home/lucas/.minecraft/mods/minecolonies.jar
	Failure message: MineColonies (minecolonies) has failed to load correctly
		java.util.UnknownFormatConversionException: Conversion = '.'
	Mod version: 1.1.691-1.21.1-snapshot
	Mod issues URL: https://github.com/ldtteam/minecolonies/issues/new/choose
	Exception message: java.util.UnknownFormatConversionException: Conversion = '.'
Stacktrace:
	at java.base/java.util.Formatter.parse(Formatter.java:2852) ~[?:?] {}
	at java.base/java.util.Formatter.format(Formatter.java:2774) ~[?:?] {}
	at java.base/java.util.Formatter.format(Formatter.java:2728) ~[?:?] {}
	at java.base/java.lang.String.formatted(String.java:4452) ~[?:?] {re:mixin}
	at TRANSFORMER/blockui@1.0.188-1.21.1-snapshot/com.ldtteam.common.config.AbstractConfiguration.translate(AbstractConfiguration.java:96) ~[blockui-1.0.188-1.21.1-snapshot.jar%23217!/:1.0.188-1.21.1-snapshot] {re:classloading}
	at TRANSFORMER/blockui@1.0.188-1.21.1-snapshot/com.ldtteam.common.config.AbstractConfiguration.buildBase(AbstractConfiguration.java:85) ~[blockui-1.0.188-1.21.1-snapshot.jar%23217!/:1.0.188-1.21.1-snapshot] {re:classloading}
	at TRANSFORMER/blockui@1.0.188-1.21.1-snapshot/com.ldtteam.common.config.AbstractConfiguration.defineInteger(AbstractConfiguration.java:127) ~[blockui-1.0.188-1.21.1-snapshot.jar%23217!/:1.0.188-1.21.1-snapshot] {re:classloading}
	at TRANSFORMER/minecolonies@1.1.691-1.21.1-snapshot/com.minecolonies.api.configuration.ServerConfiguration.<init>(ServerConfiguration.java:150) ~[minecolonies.jar%23233!/:1.1.691-1.21.1-snapshot] {re:classloading}
	at TRANSFORMER/neoforge@21.1.50/net.neoforged.neoforge.common.ModConfigSpec$Builder.configure(ModConfigSpec.java:872) ~[neoforge-21.1.50-universal.jar%23211!/:?] {re:classloading}
	at TRANSFORMER/blockui@1.0.188-1.21.1-snapshot/com.ldtteam.common.config.Configurations.createConfig(Configurations.java:96) ~[blockui-1.0.188-1.21.1-snapshot.jar%23217!/:1.0.188-1.21.1-snapshot] {re:classloading}
	at TRANSFORMER/blockui@1.0.188-1.21.1-snapshot/com.ldtteam.common.config.Configurations.<init>(Configurations.java:65) ~[blockui-1.0.188-1.21.1-snapshot.jar%23217!/:1.0.188-1.21.1-snapshot] {re:classloading}
	at TRANSFORMER/minecolonies@1.1.691-1.21.1-snapshot/com.minecolonies.core.MineColonies.<init>(MineColonies.java:96) ~[minecolonies.jar%23233!/:1.1.691-1.21.1-snapshot] {re:classloading}
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?] {}
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?] {}
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?] {}
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:115) ~[loader-4.0.24.jar%23109!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.ModLoader.lambda$constructMods$3(ModLoader.java:153) ~[loader-4.0.24.jar%23109!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.ModLoader.lambda$dispatchParallelTask$7(ModLoader.java:231) ~[loader-4.0.24.jar%23109!/:4.0] {}
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[?:?] {re:mixin}
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) ~[?:?] {}
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {}

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
Hello, can you tell us what language do you play in?

**Comment by Aris1008** [comment]
Hello!I have exactly the same problem, the mods and dependencies are the same used,the same version of the loader.What is the reason for this problem?The language is Russian in minecraft.

**Comment by Aris1008** [comment]
And if the language in Minecraft is English, then there is no mistake.

**Comment by Nightenom** [comment]
Fixed in latest blockui

**Comment by Aris1008** [comment]
Hurray!Thank You Very Much!
