### ISSUE TITLE
AI log upload

### ISSUE THREAD

**Issue by pwaksman973** [ldtteam/minecolonies#10230]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.21

### MineColonies Version

minecolonies-1.1.700-1.21.1-snapshot

### Structurize Version

structurize-1.0.751-1.21.1-snapshot

### Related Mods and their Versions

FTB Presents Direwolf20 1.21

### Reproduction Steps

No idea.
Curier will stop working after a good amount of time, was working fine for like 3 buildings.
Then it get stuck saying its waiting me to place 16 torches, eventhough there is no request.
And then change to this message, and loop back to waiting 16 torches.

I killed the npc with some fire, short after the next currier got the same message.
I wish there was any log to send.

### Logs

There is no latest.log, the game doesn't crash, the npc keep saying its ai is broken and asking to send the latest.log, which just doesn't exists since there is no crash.

### Anything else?

There is no latest.log, the game doesn't crash, the npc keep saying its ai is broken and asking to send the latest.log, which just doesn't exists since there is no crash.

![Untitled](https://github.com/user-attachments/assets/c11e9abe-2353-4f0d-afd8-42787b273b29)

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Talyda** [comment]
Latest.log always exists.
In your instance folder, in the logs folder, usually right down the bottom of the file list. It's literally called "latest.log"

The 16 torches is a quest BTW not a request =)

**Comment by pwaksman973** [comment]
Lol, I was sure it should be in crash report or just down the root folder.
dang, thanks.

`[18Sep2024 03:18:44.563] [Render thread/ERROR] [com.mojang.blaze3d.platform.Window/]: ########## GL ERROR ##########
[18Sep2024 03:18:44.564] [Render thread/ERROR] [com.mojang.blaze3d.platform.Window/]: @ Render
[18Sep2024 03:18:44.564] [Render thread/ERROR] [com.mojang.blaze3d.platform.Window/]: 65540: Invalid scancode 115
[18Sep2024 03:19:14.360] [Render thread/ERROR] [com.mojang.blaze3d.audio.OpenAlUtil/]: Deleting stream buffers: Invalid operation.
[18Sep2024 03:19:26.442] [Server thread/ERROR] [minecolonies/]: java.lang.IllegalStateException: Cannot encode empty ItemStack
[18Sep2024 03:19:29.244] [Server thread/WARN] [minecolonies/]: Statemachine for state DELIVERY threw an exception:
java.lang.NullPointerException: Cannot invoke "com.minecolonies.api.colony.requestsystem.request.IRequest.childStateUpdated(com.minecolonies.api.colony.requestsystem.manager.IRequestManager, com.minecolonies.api.colony.requestsystem.token.IToken)" because the return value of "com.minecolonies.api.colony.requestsystem.manager.IRequestManager.getRequestForToken(com.minecolonies.api.colony.requestsystem.token.IToken)" is null
	at TRANSFORMER/minecolonies@1.1.700-1.21.1-snapshot/com.minecolonies.core.colony.requestsystem.requests.AbstractRequest.setState(AbstractRequest.java:147) ~[minecolonies-1.1.700-1.21.1-snapshot.jar%23574!/:1.1.700-1.21.1-snapshot]
	at TRANSFORMER/minecolonies@1.1.700-1.21.1-snapshot/com.minecolonies.core.colony.requestsystem.management.manager.StandardRequestManager.updateRequestState(StandardRequestManager.java:300) ~[minecolonies-1.1.700-1.21.1-snapshot.jar%23574!/:1.1.700-1.21.1-snapshot]
	at TRANSFORMER/minecolonies@1.1.700-1.21.1-snapshot/com.minecolonies.core.colony.jobs.JobDeliveryman.finishRequest(JobDeliveryman.java:334) ~[minecolonies-1.1.700-1.21.1-snapshot.jar%23574!/:1.1.700-1.21.1-snapshot]
	at TRANSFORMER/minecolonies@1.1.700-1.21.1-snapshot/com.minecolonies.core.entity.ai.workers.service.EntityAIWorkDeliveryman.deliver(EntityAIWorkDeliveryman.java:462) ~[minecolonies-1.1.700-1.21.1-snapshot.jar%23574!/:1.1.700-1.21.1-snapshot]
	at TRANSFORMER/minecolonies@1.1.700-1.21.1-snapshot/com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:79) ~[minecolonies-1.1.700-1.21.1-snapshot.jar%23574!/:1.1.700-1.21.1-snapshot]
	at TRANSFORMER/minecolonies@1.1.700-1.21.1-snapshot/com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:163) ~[minecolonies-1.1.700-1.21.1-snapshot.jar%23574!/:1.1.700-1.21.1-snapshot]
	at TRANSFORMER/minecolonies@1.1.700-1.21.1-snapshot/com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:149) ~[minecolonies-1.1.700-1.21.1-snapshot.jar%23574!/:1.1.700-1.21.1-snapshot]
	at TRANSFORMER/minecolonies@1.1.700-1.21.1-snapshot/com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:126) ~[minecolonies-1.1.700-1.21.1-snapshot.jar%23574!/:1.1.700-1.21.1-snapshot]
	at TRANSFORMER/minecolonies@1.1.700-1.21.1-snapshot/com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:102) ~[minecolonies-1.1.700-1.21.1-snapshot.jar%23574!/:1.1.700-1.21.1-snapshot]
	at TRANSFORMER/minecolonies@1.1.700-1.21.1-snapshot/com.minecolonies.core.entity.ai.workers.AbstractAISkeleton.tick(AbstractAISkeleton.java:64) ~[minecolonies-1.1.700-1.21.1-snapshot.jar%23574!/:1.1.700-1.21.1-snapshot]
	at TRANSFORMER/minecolonies@1.1.700-1.21.1-snapshot/com.minecolonies.core.entity.ai.workers.CitizenAI.lambda$registerWorkAI$4(CitizenAI.java:97) ~[minecolonies-1.1.700-1.21.1-snapshot.jar%23574!/:1.1.700-1.21.1-snapshot]
	at TRANSFORMER/minecolonies@1.1.700-1.21.1-snapshot/com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:79) ~[minecolonies-1.1.700-1.21.1-snapshot.jar%23574!/:1.1.700-1.21.1-snapshot]
	at TRANSFORMER/minecolonies@1.1.700-1.21.1-snapshot/com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:163) ~[minecolonies-1.1.700-1.21.1-snapshot.jar%23574!/:1.1.700-1.21.1-snapshot]
	at TRANSFORMER/minecolonies@1.1.700-1.21.1-snapshot/com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:149) ~[minecolonies-1.1.700-1.21.1-snapshot.jar%23574!/:1.1.700-1.21.1-snapshot]
	at TRANSFORMER/minecolonies@1.1.700-1.21.1-snapshot/com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:126) ~[minecolonies-1.1.700-1.21.1-snapshot.jar%23574!/:1.1.700-1.21.1-snapshot]
	at TRANSFORMER/minecolonies@1.1.700-1.21.1-snapshot/com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:102) ~[minecolonies-1.1.700-1.21.1-snapshot.jar%23574!/:1.1.700-1.21.1-snapshot]
	at TRANSFORMER/minecolonies@1.1.700-1.21.1-snapshot/com.minecolonies.core.entity.citizen.EntityCitizen.lambda$new$11(EntityCitizen.java:309) ~[minecolonies-1.1.700-1.21.1-snapshot.jar%23574!/:1.1.700-1.21.1-snapshot]
	at TRANSFORMER/minecolonies@1.1.700-1.21.1-snapshot/com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.checkCondition(BasicTransition.java:87) ~[minecolonies-1.1.700-1.21.1-snapshot.jar%23574!/:1.1.700-1.21.1-snapshot]
	at TRANSFORMER/minecolonies@1.1.700-1.21.1-snapshot/com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:138) ~[minecolonies-1.1.700-1.21.1-snapshot.jar%23574!/:1.1.700-1.21.1-snapshot]
	at TRANSFORMER/minecolonies@1.1.700-1.21.1-snapshot/com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:126) ~[minecolonies-1.1.700-1.21.1-snapshot.jar%23574!/:1.1.700-1.21.1-snapshot]
	at TRANSFORMER/minecolonies@1.1.700-1.21.1-snapshot/com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:102) ~[minecolonies-1.1.700-1.21.1-snapshot.jar%23574!/:1.1.700-1.21.1-snapshot]
	at TRANSFORMER/minecolonies@1.1.700-1.21.1-snapshot/com.minecolonies.api.entity.citizen.AbstractEntityCitizen.aiStep(AbstractEntityCitizen.java:437) ~[minecolonies-1.1.700-1.21.1-snapshot.jar%23574!/:1.1.700-1.21.1-snapshot]
	at TRANSFORMER/minecolonies@1.1.700-1.21.1-snapshot/com.minecolonies.core.entity.citizen.EntityCitizen.aiStep(EntityCitizen.java:708) ~[minecolonies-1.1.700-1.21.1-snapshot.jar%23574!/:1.1.700-1.21.1-snapshot]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2431) ~[client-1.21.1-20240808.144430-srg.jar%23424!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.entity.Mob.tick(Mob.java:351) ~[client-1.21.1-20240808.144430-srg.jar%23424!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:774) ~[client-1.21.1-20240808.144430-srg.jar%23424!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.Level.guardEntityTick(Level.java:570) ~[client-1.21.1-20240808.144430-srg.jar%23424!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerLevel.lambda$tick$2(ServerLevel.java:420) ~[client-1.21.1-20240808.144430-srg.jar%23424!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:54) ~[client-1.21.1-20240808.144430-srg.jar%23424!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:400) ~[client-1.21.1-20240808.144430-srg.jar%23424!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1037) ~[client-1.21.1-20240808.144430-srg.jar%23424!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:917) ~[client-1.21.1-20240808.144430-srg.jar%23424!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:110) ~[client-1.21.1-20240808.144430-srg.jar%23424!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:707) ~[client-1.21.1-20240808.144430-srg.jar%23424!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[client-1.21.1-20240808.144430-srg.jar%23424!/:?]
	at java.base/java.lang.Thread.run(Unknown Source) [?:?]
[18Sep2024 03:19:29.251] [Server thread/ERROR] [minecolonies/]: Pausing Citizen Kade M. Gobberd (com.minecolonies.job.deliveryman) in colony:1 at BlockPos{x=194, y=72, z=-872} for 100 Seconds because of error:`

[latest.log](https://github.com/user-attachments/files/17042450/latest.log)

**Comment by Thodor12** [comment]
Please upload your log to [gist](https://gist.github.com)

**Comment by pwaksman973** [comment]
I don't know, seems like everything just stopped working after that error.
They don't do anything anymore, I manually gave all required items to the builder and yet it does not continue build, don't have any request, and don't complain about missing something or doesn't say why it isn't working.
The only thing they do is go to tavern at night and move back to their workshop at day.

Here the latest log again, without the message for broken AI, but I guess it still broken some how.
[latest.log](https://github.com/user-attachments/files/17045304/latest.log)

there is this duplicated discovered animal id crash, that I'm not sure if it is related
`
[18Sep2024 14:09:47.249] [Server thread/WARN] [minecolonies/]: Starting Compat Discovery
[18Sep2024 14:09:47.416] [Server thread/INFO] [minecolonies/]: Finished discovering Ores 70 37
[18Sep2024 14:09:47.416] [Server thread/INFO] [minecolonies/]: Finished discovering saplings 170
[18Sep2024 14:09:47.416] [Server thread/INFO] [minecolonies/]: Finished discovering plantables 19
[18Sep2024 14:09:47.416] [Server thread/INFO] [minecolonies/]: Finished discovering food 273 309
[18Sep2024 14:09:47.416] [Server thread/INFO] [minecolonies/]: Finished discovering fuel 4262
[18Sep2024 14:09:47.416] [Server thread/INFO] [minecolonies/]: Finished discovering flowers 34
[18Sep2024 14:09:47.416] [Server thread/INFO] [minecolonies/]: Finished discovering items 21318
[18Sep2024 14:09:47.416] [Server thread/INFO] [minecolonies/]: Finished discovering lucky oreBlocks 6
[18Sep2024 14:09:47.416] [Server thread/INFO] [minecolonies/]: Finished discovering recruitment costs
[18Sep2024 14:09:47.417] [Server thread/INFO] [minecolonies/]: Finished discovering diseases
[18Sep2024 14:09:47.445] [Server thread/INFO] [minecolonies/]: Finished discovering compostables 1143
[18Sep2024 14:09:47.535] [Server thread/ERROR] [minecolonies/]: Couldnt analyze animal
java.lang.IllegalArgumentException: Duplicate id value for 17!
`

![requestlist](https://github.com/user-attachments/assets/09a50d02-b67e-4817-b9ea-93803dec0922)
![items](https://github.com/user-attachments/assets/fd7a19cc-da66-4d7b-84ff-be68b0edfaf8)
![npcrequest](https://github.com/user-attachments/assets/feb20164-91cc-4911-bd42-80453f06e12b)
![npcinfo](https://github.com/user-attachments/assets/c9b67d48-9e7a-475f-b261-e14617ec2059)

**Comment by Thodor12** [comment]
Don't upload the raw log file and attach it to the issue. Paste the file into a gist please.

**Comment by pwaksman973** [comment]
Oh, sorry, added the logs as link in the comment itself, but
there is the gitgist:

first with the AI broken message: https://gist.github.com/pwaksman973/28c48ceec0eae78b46f1065e4359a1fa

Second: https://gist.github.com/pwaksman973/b02d896f3b23b1213824ee7de6b51bd7

**Comment by Raycoms** [comment]
Somewhere this:

[18Sep2024 02:59:27.192] [Server thread/ERROR] [minecolonies/]: java.lang.IllegalStateException: Cannot encode empty ItemStack

Is called

**Comment by Thodor12** [comment]
I also see a nullpointer in the request system.
Can you run `/mc colony requestsystem-reset <colony id>`, that way that issue will also go away.

**Comment by pwaksman973** [comment]
It says that the command is disabled in the config
I changed `enabledebuglogging = true` but I guess that is not the right config.
nvm found it, running again

**Comment by pwaksman973** [comment]
Oh yah does make it work, builder and forester are now active working again!
Please let me know if there is any more info that I can provide to helping with the source issue.
Yah, after while it does come back with the same error, repeating the command make it works, so I guess I can keep running this for now

**Comment by Raycoms** [comment]
solved
