### ISSUE TITLE
Guidebook

### ISSUE THREAD

**Issue by ShenShuss** [ldtteam/minecolonies#10311]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.20

### MineColonies Version

1.12.2-0.11.841-BETA

### Structurize Version

i dont have it

### Current Behavior

I put this mod into an existing 1.12.2 minecraft multiplayer aternos server world that has the modpack Dungeons Dragons and Space Shuttles in it and i didnt get a guidebook.I alraedy have the guidebook mod in but i didnt get a guidebook

### Expected Behavior

Getting a guide book when i log into the world

### Reproduction Steps

1.make an aternos server with the curseforge modpack Dungeons Dragons and Space Shuttles. 2.Put in the minecolonies modpack after you already logged in a few times into the world.

### Logs

.

### Anything else?

Latest log:
[18:45:11] [main/INFO]: Loading tweak class name org.tlauncher.tweaker.Tweaker
[18:45:11] [main/INFO]: Using primary tweak class name org.tlauncher.tweaker.Tweaker
[18:45:11] [main/INFO]: Calling tweak class org.tlauncher.tweaker.Tweaker
[18:45:12] [main/INFO]: Launching wrapped minecraft [net.minecraft.client.main.Main]
[18:45:14] [Datafixer Bootstrap/INFO]: 226 Datafixer optimizations took 575 milliseconds
[18:45:19] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[18:45:19] [Render thread/INFO]: Setting user: ShenShus
[18:45:19] [Render thread/INFO]: Backend library: LWJGL version 3.3.3+5
[18:45:22] [Render thread/INFO]: Reloading ResourceManager: vanilla
[18:45:22] [Worker-Main-2/INFO]: Found unifont_all_no_pua-15.1.05.hex, loading
[18:45:23] [Worker-Main-3/INFO]: Found unifont_jp_patch-15.1.05.hex, loading
[18:45:23] [Render thread/INFO]: Stopping!
[18:45:23] [Render thread/ERROR]: Shutdown failure!
java.util.ConcurrentModificationException: null
	at java.base/java.util.HashMap.forEach(HashMap.java:1432) ~[?:?]
	at gqm.close(SourceFile:173) ~[gqm.class:?]
	at fgo.close(SourceFile:1203) [fgo.class:?]
	at fgo.n(SourceFile:1176) [fgo.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:263) [Main.class:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:136) [tl_skin_cape_1.21_1.21.1-1.35.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:31) [tl_skin_cape_1.21_1.21.1-1.35.jar:?]

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
We don't have a guidebook
