### ISSUE TITLE
Crashing when citizen dies 

### ISSUE THREAD

**Issue by Sakeme** [ldtteam/minecolonies#10531]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta/release** version of MineColonies for my Minecraft version.
I am also running the latest versions of other mods that are part of my problem.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [ ] Single Player
- [X] Multi Player

### Minecraft Version

1.21

### MineColonies Version

1.1.820-1.21.1-snapshot

### Structurize Version

1.0.758-1.21.1-snapshot

### Current Behavior

When citizen dies, my game crashes

### Expected Behavior

Not crashing the game when citizen dies.

### Reproduction Steps

Citizen dies - game crashes

### Logs

https://mclo.gs/ilcC53F

### Anything else?

![2024-12-12_18_53_43-NBTExplorer](https://github.com/user-attachments/assets/edf2b740-3635-4e02-a92e-67c56c98bc51)
[colony1Export.zip](https://github.com/user-attachments/files/18115859/colony1Export.zip)

Got that as a probable cause, switched packs and problem still applies

### Footer

---
## Viewers
* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Sakeme** [comment]
[crash-2024-12-12_20.55.12-client.txt](https://github.com/user-attachments/files/18116942/crash-2024-12-12_20.55.12-client.txt)
[latest.log](https://github.com/user-attachments/files/18116944/latest.log)
Adding 2 new logs, crashed again after civilian's death. Already switched colony style pack to official (caledonia) and deleted previous colony and started a fresh new one. (ATM10)

**Comment by Raycoms** [comment]
@uecasm 

java.lang.NullPointerException: Cannot invoke "journeymap.api.v2.common.waypoint.WaypointGroup.isEnabled()" because the return value of "journeymap.common.waypoint.WaypointImpl.getGroup()" is null
	at TRANSFORMER/journeymap@1.21.1-6.0.0-beta.32/journeymap.common.waypoint.WaypointImpl.isEnabled(WaypointImpl.java:463) ~[journeymap-neoforge-1.21.1-6.0.0-beta.32.jar%23754!/:1.21.1-6.0.0-beta.32] {re:classloading}
	at TRANSFORMER/journeymap@1.21.1-6.0.0-beta.32/journeymap.client.render.ingame.WaypointRenderer.canDrawWaypoint(WaypointRenderer.java:40) ~[journeymap-neoforge-1.21.1-6.0.0-beta.32.jar%23754!/:1.21.1-6.0.0-beta.32] {re:classloading}
	at TRANSFORMER/journeymap@1.21.1-6.0.0-beta.32/journeymap.client.render.ingame.WaypointBeaconRenderer.render(WaypointBeaconRenderer.java:33) ~[journeymap-neoforge-1.21.1-6.0.0-beta.32.jar%23754!/:1.21.1-6.0.0-beta.32] {re:classloading}
	at TRANSFORMER/journeymap@1.21.1-6.0.0-beta.32/journeymap.client.event.handlers.WaypointBeaconHandler.onRenderWaypoints(WaypointBeaconHandler.java:40) ~[journeymap-neoforge-1.21.1-6.0.0-beta.32.jar%23754!/:1.21.1-6.0.0-beta.32] {re:classloading}
	at TRANSFORMER/journeymap@1.21.1-6.0.0-beta.32/journeymap.client.event.handlers.WaypointBeaconHandler.onRenderWaypoints(WaypointBeaconHandler.java:54) ~[journeymap-neoforge-1.21.1-6.0.0-beta.32.jar%23754!/:1.21.1-6.0.0-beta.32] {re:classloading}
	at TRANSFORMER/journeymap@1.21.1-6.0.0-beta.32/journeymap.client.event.NeoForgeRenderLevelStageEvent.onRenderWorldLastEvent(NeoForgeRenderLevelStageEvent.java:27) ~[journeymap-neoforge-1.21.1-6.0.0-beta.32.jar%23754!/:1.21.1-6.0.0-beta.32] {re:classloading}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.2.jar%23121!/:?] {}
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315) ~[bus-8.0.2.jar%23121!/:?] {}
