### ISSUE TITLE
fancy park crashing game

### ISSUE THREAD

**Issue by LocoMinerDad** [ldtteam/minecolonies#1182]
### Minecolonies version

version 1.11.2-08.1784 or curse X.X.XX

### Expected behavior

- XXX

### Actual behaviour

- while using the builder's wand. I try to place a fancy park and then esc to view it and my game crashes. I tried it in two different worlds, same effect.

### Steps to reproduce the problem

1. XYZ
2. ZYX
3. ...
4. Profit

**Comment by Asherslab** [comment]
Could you post a crash log please?

**Comment by LocoMinerDad** [comment]
I dont have one. I have to go into task manager and close java to make it stop.

**Comment by Raycoms** [comment]
The log should be in your minecraft root folder.

2017-06-14 22:14 GMT-03:00 LocoMinerDad <notifications@github.com>:

**Comment by LocoMinerDad** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-1.7.6-1.11.2.jar)
  ForgelinPlugin (Forgelin-1.5.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.62.jar)
  literalascension (literalascension-1.11.2-1.0.2.2.jar)
  BCModPlugin (zz-backpacks 1.11.2 - 3.1.9.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 6/14/17 1:38 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at flaxbeard.cyberware.common.item.ItemMuscleUpgrade.getLastBoostSpeed(ItemMuscleUpgrade.java:255)
	at flaxbeard.cyberware.common.item.ItemMuscleUpgrade.handleLivingUpdate(ItemMuscleUpgrade.java:218)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_71_ItemMuscleUpgrade_handleLivingUpdate_CyberwareUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at flaxbeard.cyberware.common.handler.EssentialsMissingHandler.triggerCyberwareEvent(EssentialsMissingHandler.java:78)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_362_EssentialsMissingHandler_triggerCyberwareEvent_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:531)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2005)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:296)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:46)
	at net.minecraft.world.World.func_72866_a(World.java:1965)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1748)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at flaxbeard.cyberware.common.item.ItemMuscleUpgrade.getLastBoostSpeed(ItemMuscleUpgrade.java:255)
	at flaxbeard.cyberware.common.item.ItemMuscleUpgrade.handleLivingUpdate(ItemMuscleUpgrade.java:218)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_71_ItemMuscleUpgrade_handleLivingUpdate_CyberwareUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at flaxbeard.cyberware.common.handler.EssentialsMissingHandler.triggerCyberwareEvent(EssentialsMissingHandler.java:78)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_362_EssentialsMissingHandler_triggerCyberwareEvent_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:531)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2005)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:296)
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:46)
	at net.minecraft.world.World.func_72866_a(World.java:1965)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1934)

-- Entity being ticked --
Details:
	Entity Type: cyberware:cyberzombie (flaxbeard.cyberware.common.entity.EntityCyberZombie)
	Entity ID: 4742
	Entity Name: Cyberzombie
	Entity's Exact location: -230.50, 22.00, -595.50
	Entity's Block location: World: (-231,22,-596), Chunk: (at 9,1,12 in -15,-38; contains blocks -240,0,-608 to -225,255,-593), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1748)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)

-- Affected level --
Details:
	Level name: new1
	All players: 1 total; [EntityPlayerMP['LocoMinerDad'/331, l='new1', x=-295.80, y=66.00, z=-548.97]]
	Chunk stats: ServerChunkCache: 801 Drop: 0
	Level seed: -4652655293470412050
	Level generator: ID 06 - atg, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-417,64,-620), Chunk: (at 15,4,4 in -27,-39; contains blocks -432,0,-624 to -417,255,-609), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Level time: 1182954 game time, 2095003 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 47969 (now: false), thunder time: 20846 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1565100848 bytes (1492 MB) / 3594518528 bytes (3428 MB) up to 4772593664 bytes (4551 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5120m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2315 60 mods loaded, 60 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2315.jar) 
	UCHIJAAAA	forge{13.20.0.2315} [Minecraft Forge] (forge-1.11.2-13.20.0.2315.jar) 
	UCHIJAAAA	backpacks16840{3.1.9} [Backpacks!] (zz-backpacks 1.11.2 - 3.1.9.jar) 
	UCHIJAAAA	anvils{1.3.1.1} [Anvil Enchantments] (AnvilEnchantments-1.11.2-1.3.1.1.jar) 
	UCHIJAAAA	atg{2} [Alternate Terrain Generation] (atg-1.11.2-2.1.4.jar) 
	UCHIJAAAA	betterthanmending{@VERSION@} [Better Than Mending] (BetterThanMending-1.1.0.jar) 
	UCHIJAAAA	ceanimals{1.3.1} [Crop-Eating Animals] (ceanimals-1.11.2-1.3.1.jar) 
	UCHIJAAAA	chameleon{1.11.2-3.1.0} [Chameleon] (Chameleon-1.11.2-3.1.0.jar) 
	UCHIJAAAA	chiselsandbits{13.10} [Chisels & Bits] (chiselsandbits-13.10.jar) 
	UCHIJAAAA	craftingcraft{5.1.1} [CraftingCraft] (CraftingCraft_1.11-5.1.1.jar) 
	UCHIJAAAA	craftingtweaks{7.1.9} [Crafting Tweaks] (CraftingTweaks_1.11.2-7.1.9.jar) 
	UCHIJAAAA	cyberware{alpha-0.2.9} [Cyberware] (cyberware-1.11.2-alpha-0.2.9.jar) 
	UCHIJAAAA	dailies{1.11.2-6} [Bailey's Dailies] (dailies-1.11.2-6.jar) 
	UCHIJAAAA	ptrmodellib{1.0.0} [ptrmodellib] (Decocraft-2.4.2_1.11.2.jar) 
	UCHIJAAAA	props{2.4.2} [Decocraft] (Decocraft-2.4.2_1.11.2.jar) 
	UCHIJAAAA	dldungeonsjdg{1.9.0} [Doomlike Dungeons] (DoomlikeDungeons-1.9.2-MC1.11.2.jar) 
	UCHIJAAAA	storagedrawers{1.11.2-4.2.9} [Storage Drawers] (StorageDrawers-1.11.2-4.2.9.jar) 
	UCHIJAAAA	bitdrawers{0.41} [Drawers & Bits] (DrawersBits-1.11.2-0.41.jar) 
	UCHIJAAAA	eleccore{1.7.421} [ElecCore] (ElecCore-1.11-1.7.421.jar) 
	UCHIJAAAA	extrautils2{1.0} [extrautils2] (extrautils2-1.11.2-1.4.4.jar) 
	UCHIJAAAA	fastleafdecay{v12} [Fast Leaf Decay] (FastLeafDecay-v12.jar) 
	UCHIJAAAA	forgelin{1.4.2} [Shadowfacts' Forgelin] (Forgelin-1.5.0.jar) 
	UCHIJAAAA	gravestone{1.7.3} [Gravestone Mod] (gravestone-1.7.3.jar) 
	UCHIJAAAA	huds{#VERSION#} [huds] (Huds-beta-1.0.2.jar) 
	UCHIJAAAA	waila{1.8.15} [Waila] (Hwyla-1.8.15-B29_1.11.jar) 
	UCHIJAAAA	llibrary{1.7.6} [LLibrary] (llibrary-1.7.6-1.11.2.jar) 
	UCHIJAAAA	iceandfire{1.1.0} [Ice and Fire] (iceandfire-1.1.0.jar) 
	UCHIJAAAA	inventorytweaks{1.62+release.90.40cf8fc} [Inventory Tweaks] (InventoryTweaks-1.62.jar) 
	UCHIJAAAA	iv{2.0.5} [Improved Villagers] (iv-2.0.5.jar) 
	UCHIJAAAA	jei{4.3.5.277} [Just Enough Items] (jei_1.11.2-4.3.5.277.jar) 
	UCHIJAAAA	journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) 
	UCHIJAAAA	jeresources{0.6.2.104} [Just Enough Resources] (JustEnoughResources-1.11.2-0.6.2.104.jar) 
	UCHIJAAAA	levelup2{${version}} [Level Up! Reloaded] (Level Up! 2-1.0.4-1.11.2.jar) 
	UCHIJAAAA	literalascension{1.11.2-1.0.2.2} [Literal Ascension] (literalascension-1.11.2-1.0.2.2.jar) 
	UCHIJAAAA	llor{1.1.3-mc1.11.2} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.3-mc1.11.2.jar) 
	UCHIJAAAA	mantle{1.11.2-1.2.0.26} [Mantle] (Mantle-1.11.2-1.2.0.26.jar) 
	UCHIJAAAA	minecolonies{1.11.2-0.8.1784} [MineColonies] (minecolonies-universal-1.11.2-0.8.1784.jar) 
	UCHIJAAAA	mobends{0.23.1} [Mo'Bends] (mobends-0.23.1_for_MC-1.11.2.jar) 
	UCHIJAAAA	shear{1.1.2} [More Shearables] (MoreShearables1.2.2-1.11.2.jar) 
	UCHIJAAAA	natura{1.11.2-4.2.0.20} [Natura] (natura-1.11.2-4.2.0.20.jar) 
	UCHIJAAAA	nmsot{1.2.0-mc1.11.2} [No Mob Spawning on Trees] (NoMobSpawningOnTrees-1.2.0-mc1.11.2.jar) 
	UCHIJAAAA	oreexcavation{1.3.95} [OreExcavation] (OreExcavation-1.3.95.jar) 
	UCHIJAAAA	roguelike{1.6.6} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2-1.6.6.jar) 
	UCHIJAAAA	sem{1.6.0b} [Steam Engines Mod] (SEM - mc1_11_2-1.6.0 beta.jar) 
	UCHIJAAAA	semmagie{1.6.0b} [Steam Engines Mod - Magie Addon] (SEM - mc1_11_2-1.6.0 beta.jar) 
	UCHIJAAAA	spartanshields{1.3} [Spartan Shields] (SpartanShields-1.11.2-1.3a.jar) 
	UCHIJAAAA	storagedrawersextra{@VERSION@} [Storage Drawers Extras] (StorageDrawersExtras-1.11.2-2.0.0.jar) 
	UCHIJAAAA	tconstruct{1.11.2-2.7.0.26} [Tinkers' Construct] (TConstruct-1.11.2-2.7.0.26.jar) 
	UCHIJAAAA	tinkertoolleveling{1.11.2-1.0.1.DEV.641b08f} [Tinkers Tool Leveling] (TinkerToolLeveling-1.11.2-1.0.1.jar) 
	UCHIJAAAA	toolbelt{1.6.1} [Tool Belt] (ToolBelt-1.11.2-1.6.1.jar) 
	UCHIJAAAA	trashslot{7.4.7} [TrashSlot] (TrashSlot_1.11.2-7.4.7.jar) 
	UCHIJAAAA	vanillamagic{1.11.2-0.21.12.0} [Vanilla Magic] (VanillaMagic-1.11.2-0.21.12.0.jar) 
	UCHIJAAAA	villagermarket{1.0} [Villager Market] (villagermarket-0.2-HF.jar) 
	UCHIJAAAA	vtt{0.6.3} [Villager Trade Tables] (VillagerTrades-1.11-0.6.3.jar) 
	UCHIJAAAA	wailaharvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.11-1.1.9.jar) 
	UCHIJAAAA	wawla{2.4.0.231} [What Are We Looking At] (Wawla-1.11.2-2.4.0.231.jar) 
	UCHIJAAAA	waystones{3.0.16} [Waystones] (Waystones_1.11.2-3.0.16.jar) 
	UCHIJAAAA	denseores{1.0} [denseores] (denseores-1.11-1.0.2.jar) 
	Loaded coremods (and transformers): 
llibrary (llibrary-1.7.6-1.11.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
ForgelinPlugin (Forgelin-1.5.0.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.62.jar)
  invtweaks.forge.asm.ContainerTransformer
literalascension (literalascension-1.11.2-1.0.2.2.jar)
  com.jamieswhiteshirt.literalascension.core.patcher.LiteralAscensionRuntimePatcher
BCModPlugin (zz-backpacks 1.11.2 - 3.1.9.jar)
  brad16840.common.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['LocoMinerDad'/331, l='new1', x=-295.80, y=66.00, z=-548.97]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Asherslab** [comment]
Looks as if it's a problem  with: 
cyberware:cyberzombie (flaxbeard.cyberware.common.entity.EntityCyberZombie)
Which is part of the Cyberware mod..
