### ISSUE TITLE
Lumberjack GUI not opening

### ISSUE THREAD

**Issue by Natrukei** [ldtteam/minecolonies#1229]
### Minecolonies version

version 1.10.2-0.8.2817

### Expected behavior

Buildable Hut and openable GUI for Lumberjack

### Actual behaviour

[12:12:57] [Server thread/ERROR] [minecolonies]: Unknown Building type 'com.minecolonies.coremod.tileentities.TileEntityColonyBuilding' or missing constructor of proper format.
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_121]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_121]
        at com.minecolonies.coremod.colony.buildings.AbstractBuilding.create(AbstractBuilding.java:382) ~[AbstractBuilding.class:?]
        at com.minecolonies.coremod.colony.Colony.addNewBuilding(Colony.java:1605) ~[Colony.class:?]
        at com.minecolonies.coremod.blocks.AbstractBlockHut.func_180633_a(AbstractBlockHut.java:262) ~[AbstractBlockHut.class:?]
        at com.minecolonies.coremod.blocks.AbstractBlockHut.onBlockPlacedByBuildTool(AbstractBlockHut.java:291) ~[AbstractBlockHut.class:?]
        at com.minecolonies.coremod.network.messages.BuildToolPlaceMessage.handleHut(BuildToolPlaceMessage.java:174) ~[BuildToolPlaceMessage.class:?]
        at com.minecolonies.coremod.network.messages.BuildToolPlaceMessage.messageOnServerThread(BuildToolPlaceMessage.java:133) ~[BuildToolPlaceMessage.class:?]
        at com.minecolonies.coremod.network.messages.BuildToolPlaceMessage.messageOnServerThread(BuildToolPlaceMessage.java:36) ~[BuildToolPlaceMessage.class:?]
        at com.minecolonies.coremod.network.messages.AbstractMessage.lambda$onMessage$0(AbstractMessage.java:24) ~[AbstractMessage.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_121]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NoSuchMethodError: net.minecraft.item.Item.func_150895_a(Lnet/minecraft/item/Item;Lnet/minecraft/creativetab/CreativeTabs;Ljava/util/List;)V
        at com.minecolonies.coremod.colony.buildings.BuildingLumberjack.calcSaplings(BuildingLumberjack.java:129) ~[BuildingLumberjack.class:?]
        at com.minecolonies.coremod.colony.buildings.BuildingLumberjack.<init>(BuildingLumberjack.java:91) ~[BuildingLumberjack.class:?]
        ... 20 more
[12:12:57] [Server thread/ERROR] [minecolonies]: Colony 1 unable to create AbstractBuilding for class com.minecolonies.coremod.blocks.BlockHutLumberjack at BlockPos{x=365, y=67, z=238}
[12:12:57] [Server thread/ERROR] [minecolonies]: BuildTool: building is null!

### Steps to reproduce the problem

1. set block (with wand)
2. try to open
3. fail
4. try not to cry
5. cry alot

**Comment by Natrukei** [comment]
After restarting the server, this error still comes up

**Comment by Wissi** [comment]
Yes it's a know issue that has been resolved in the newest Beta:  minecolonies-universal-1.10.2-0.8.2890.jar

If after installing the latest beta (minecolonies-universal-1.10.2-0.8.2890.jar) U still can't access GUI, then you have to break the hut block and place/build again. Will work again after that.
