### ISSUE TITLE
unable to interact with colony, occasional client crash

### ISSUE THREAD

**Issue by BrianEdmonds** [ldtteam/minecolonies#1257]
### Minecolonies version

minecolonies-universal-1.11.2-0.8.2786.jar
forge-1.11.2-13.20.1.2393-installer.jar

### Expected behavior

Able to interact with colonists and chests.

### Actual behaviour

Right click on colonists or chests does nothing, occasionally crashes the client. The server has not crashed, and reports nothing interesting in the log. It started when I was running minecolonies 1.11.2-0.8.1784 and forge 1.11.2-13.20.1.2388, which is where the traceback from below came from. I tried upgrading to the above versions, and interaction is still not working, but I've not seen a client crash yet.

> java.lang.NullPointerException: Unexpected error
        at com.minecolonies.coremod.colony.permissions.Permissions$View.hasPermission(Permissions.java:1077)
        at com.minecolonies.coremod.colony.permissions.Permissions$View.hasPermission(Permissions.java:1184)
        at com.minecolonies.coremod.blocks.AbstractBlockHut.func_180639_a(AbstractBlockHut.java:206)
        at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:408)
        at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1521)
        at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2179)
        at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1956)
        at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1744)
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
        at net.minecraft.client.main.Main.main(SourceFile:124)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

### Steps to reproduce the problem

Has only happened in my current underground colony, have not reproduced. No idea if it's been triggered somehow by building underground.

**Comment by BrianEdmonds** [comment]
Just got a crash clicking on my miner in the newer version:

> java.lang.NullPointerException: Unexpected error
        at com.minecolonies.coremod.colony.permissions.Permissions$View.hasPermission(Permissions.java:941)
        at com.minecolonies.coremod.colony.permissions.Permissions$View.hasPermission(Permissions.java:1048)
        at com.minecolonies.coremod.entity.EntityCitizen.func_184645_a(EntityCitizen.java:926)
        at net.minecraft.entity.EntityLiving.func_184230_a(EntityLiving.java:1213)
        at net.minecraft.entity.player.EntityPlayer.func_190775_a(EntityPlayer.java:1192)
        at net.minecraft.client.multiplayer.PlayerControllerMP.func_187097_a(PlayerControllerMP.java:534)
        at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1509)
        at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2179)
        at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1956)
        at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1744)
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
        at net.minecraft.client.main.Main.main(SourceFile:124)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by BrianEdmonds** [comment]
To leave no stone unturned, I see the same lack of interaction from the 1.11.2-0.8.2797 alpha release.

**Comment by BrianEdmonds** [comment]
I've also been seeing lots of messages like below in the logs, about one every minute and a half, which could be related:

>[09:59:17] [Server thread/WARN] [minecolonies]: EntityCitizen '564c5893-5d63-4902-803a-a58fa978b9b8' attempting to register with Colony #1 as Citizen #4, but already have a citizen ('564c5893-5d63-4902-803a-a58fa978b9b8')

**Comment by Asherslab** [comment]
Okay, so, firstly, are you the owner of this colony or an officer, second this is on a server correct? thirdly i'm guessing the first crash-log was for 1.10.2 correct?

**Comment by BrianEdmonds** [comment]
I'm the owner, and only player on the server. This world has only ever run 1.11.2.

**Comment by Asherslab** [comment]
Could you possible try /mc colony refresh <ID> 
Just to be sure =D

**Comment by BrianEdmonds** [comment]
@Asherslab, I did /mc colony refresh 1, got a "Refresh successful!"
response, and still cannot interact with colony chests or colonists. No
log messages or crashes yet; the crashes usually only seem to be after
the client has been up for a while, not on a fresh start like I just
did.

**Comment by BrianEdmonds** [comment]
@Asherslab I've been largely ignoring the colony for the past week, and playing with other mods in my pack (Mekanism and Cyberware, mainly). I checked if it worked a couple days ago when you asked for more input, and as reported it still failed then. Today I was about to shut down my client, so went to click on a colony chest as an alternate shutdown mechanism, and... it worked. I've not upgraded any mods, nor forge. Nor have I restarted the server. But it's working again, inexplicably. Unless you've had some insight, this will probably have to be put down to a head scratcher, and with any luck never seen again.

**Comment by Asherslab** [comment]
Any chance you shutdown between the time that you use /mc refresh 1 ? That might've done it, either way, glad it's fixed, I'm completely lost as to why it was happening. Hope it does come back =D

**Comment by BrianEdmonds** [comment]
Nope, no shutdown, at least on the server side. The server runs on a dedicated Xen instance that I pretty much ignore except when doing mod upgrades. I restart the client semi-regularly.

**Comment by BrianEdmonds** [comment]
And, with no warning, it's back. :( I won't be able to debug much for a couple weeks or so. We'll see how it's doing after that...

**Comment by BrianEdmonds** [comment]
I tried restarting client and server, no change. I'm already running the latest forge (1.11.2-13.20.1.2393), and upgraded minecolonies to 1.11.2-0.8.3136, still no change. The latest traceback is still a null pointer exception at line 941 of Permissions.java. Then for grins I did a "mc colony refresh 1" and restarted the server, and now it's working again. Hopefully some of this helps. :)

**Comment by Asherslab** [comment]
May I see the entire traceback?

**Comment by BrianEdmonds** [comment]
Unfortunately I'm away from my computer for a week or so.  I'll
reproduce and attach a full crash dump once I'm back.

**Comment by Raycoms** [comment]
Some issue: #1331
