### ISSUE TITLE
Supply Camp not placing

### ISSUE THREAD

**Issue by yababom** [ldtteam/minecolonies#1328]
### Minecolonies version

minecolonies-universal-1.10.2-0.8.3056

### Expected behavior

Place Supply Camp block

### Actual behaviour

No response in game, minecraft logs generate the following error upon each attempt:

[Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalAccessError: tried to access field net.minecraft.world.gen.structure.template.Template.field_186270_a from class com.minecolonies.structures.helpers.Structure
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.IllegalAccessError: tried to access field net.minecraft.world.gen.structure.template.Template.field_186270_a from class com.minecolonies.structures.helpers.Structure
	at com.minecolonies.structures.helpers.Structure.getBlockInfo(Structure.java:443) ~[Structure.class:?]
	at com.minecolonies.structures.helpers.StructureProxy.<init>(StructureProxy.java:51) ~[StructureProxy.class:?]
	at com.minecolonies.coremod.util.StructureWrapper.<init>(StructureWrapper.java:67) ~[StructureWrapper.class:?]
	at com.minecolonies.coremod.util.StructureWrapper.tryToLoadAndPlaceSupplyCampWithRotation(StructureWrapper.java:126) ~[StructureWrapper.class:?]
	at com.minecolonies.coremod.items.ItemSupplyCampDeployer.checkAndPlaceSupplyCamp(ItemSupplyCampDeployer.java:162) ~[ItemSupplyCampDeployer.class:?]
	at com.minecolonies.coremod.items.ItemSupplyCampDeployer.spawnCamp(ItemSupplyCampDeployer.java:151) ~[ItemSupplyCampDeployer.class:?]
	at com.minecolonies.coremod.items.ItemSupplyCampDeployer.func_180614_a(ItemSupplyCampDeployer.java:108) ~[ItemSupplyCampDeployer.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:780) ~[ForgeHooks.class:?]
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:145) ~[adz.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:493) ~[lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:679) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[jj.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[jj.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more

### Steps to reproduce the problem

Loaded game with MultiMC 0.5.0-945, 
lwjgl-2.9.1
Forge 12.18.3.2316

**Comment by Zygus42** [comment]
Same problem - when you click the green tick, the design goes away and nothing more happens.
Also same for supply ship, even when there's clearly more than enough space for it.

minecolonies-universal-1.12-0.8.3238
forge-1.12-14.21.1.2428-installer-win

**Comment by Raycoms** [comment]
What kind of mods did you have installed?
Did you have any coremods installed?
This does seem to be a problem with another mod.
Since our mod relies on on certain minecraft classes.
Can you try it please without any coremods and check if it works?
I will close it for now.
@Zygus42 Please open a new issue for that if still relevant.

**Comment by yababom** [comment]
@Raycoms  No other mods in my case--just Minecraft with LWJGL (2.9.1), Forge (1.10.2-12.18.3.2316), and Minecolonies as stated in the original report.

**Comment by Zygus42** [comment]
I figured out my problem with this - because I was testing in creative I gave myself the tool and the supply camp block, and the tool appears to work but doesn't place, but when you actually play in survival, you have to place the supply camp block first and that then gives you the tool in a chest which you then use from then on.  That little inconsistency appears to be causing issues for people like me who forget the start :)

**Comment by Asherslab** [comment]
Yes, sadly the build tool cannot be used to place the first supply camp. I do believe this would be something nice to change.
