### ISSUE TITLE
Players cannot log in after server restart

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#1504]
1.12 Minecolonies version

version 0.8.4118 and 0.8.4191

###  Expected behavior

Restart the server.

### Actual behaviour

Restarts, and kicks people upon login via "Internal Exception: java.io.IOException forcibly closed by remote host error" type error.

Backend looks like;
[image](https://i.imgur.com/CbnJ6GZ.png)
`[12:35:26] [User Authenticator #3/INFO]: UUID of player PotatoOrgy is 327fd2d5-b994-4223-845b-1cde6779df92
[12:35:39] [Server thread/INFO]: PotatoOrgy[/--] logged in with entity id 664 at (-1277.8143034057182, 85.0, 6.643822882801938)
[12:35:39] [Server thread/INFO]: PotatoOrgy joined the game
[12:35:39] [Server thread/WARN]: Failed to handle packet for /--
java.lang.NullPointerException: null
	at com.minecolonies.coremod.util.ServerUtils.getPlayerFromUUID(ServerUtils.java:143) ~[ServerUtils.class:?]
	at com.minecolonies.coremod.util.ServerUtils.getPlayerFromPermPlayer(ServerUtils.java:124) ~[ServerUtils.class:?]
	at com.minecolonies.coremod.util.ServerUtils.getPlayersFromPermPlayer(ServerUtils.java:103) ~[ServerUtils.class:?]
	at com.minecolonies.coremod.util.AchievementUtils.syncAchievements(AchievementUtils.java:37) ~[AchievementUtils.class:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_144]
	at com.minecolonies.coremod.colony.ColonyManager.syncAllColoniesAchievements(ColonyManager.java:231) ~[ColonyManager.class:?]
	at com.minecolonies.coremod.event.FMLEventHandler.onPlayerLogin(FMLEventHandler.java:83) ~[FMLEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_231_FMLEventHandler_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:573) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:218) ~[pl.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:256) ~[NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72) ~[NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:179) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[12:35:44] [Server thread/INFO]: PotatoOrgy lost connection: Internal server error
[12:35:44] [Server thread/INFO]: PotatoOrgy left the game`

### Steps to reproduce the problem

1. Restart the server
2. Problem
3. ...
4. Profit

**Comment by marchermans** [comment]
I will track this.

**Comment by Raycoms** [comment]
Can you check if the newest update fixes this?

**Comment by ghost** [comment]
Newest update allows us to log in! However all the minecolony items are gone (townhall/builders hut) and it's reset the towns levels. It seems to have remembered all the citizens attached to the colony but the builder fella is tearing down a level 4 town hall because he thinks it should be 1.

I assume it's because we turned the server online without the mod, so it removed all the associated items that came with it obviously, but do you guys not keep track of the placement of those items?

**Comment by Raycoms** [comment]
Yes, turning on the server without minecolonies removed all references of
it.
Only way to avoid this is rolling back the world. (You might be able to try
to rollback the minecolonies colonies.dat

2017-10-04 21:12 GMT+01:00 PotatoOrgy <notifications@github.com>:

**Comment by ghost** [comment]
This did not help.

**Comment by Raycoms** [comment]
Did you try to rollback the colonies.dat to a moment before you removed the
mod from the game?

(Its possible that it won't work because removing the mod removes all
blocks, entities and items, so it might be irreversible (the damage).

2017-10-04 22:17 GMT+01:00 PotatoOrgy <notifications@github.com>:

**Comment by ghost** [comment]
Yea I even went back a bit further in our backups. I assume it can't bring back the entities, would this be something that you guys can add to future versions of the mod?

**Comment by Raycoms** [comment]
You can recall them in the townhall

**Comment by Raycoms** [comment]
Should be fixed with the newest version
