### ISSUE TITLE
1.11.2

### ISSUE THREAD

**Issue by demon57730** [ldtteam/minecolonies#1547]
### Minecolonies version
minecolonies-universal-1.11.2-0.8.4418.jar
forge-1.11.2-13.20.1.2513-universal.jar

### Steps to reproduce the problem

 Failed to handle packet for ....
java.lang.NullPointerException
at com.minecolonies.coremod.util.ServerUtils.getPlayerFromUUID(ServerUtils.java:143) ~[ServerUtils.class:?]
at com.minecolonies.coremod.util.ServerUtils.getPlayerFromPermPlayer(ServerUtils.java:124) ~[ServerUtils.class:?]
at com.minecolonies.coremod.util.ServerUtils.getPlayersFromPermPlayer(ServerUtils.java:103) ~[ServerUtils.class:?]
at com.minecolonies.coremod.util.AchievementUtils.syncAchievements(AchievementUtils.java:37) ~[AchievementUtils.class:?]
at com.minecolonies.coremod.colony.ColonyManager$$Lambda$719/661786978.accept(Unknown Source) ~[?:?]
at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_45-internal]
at com.minecolonies.coremod.colony.ColonyManager.syncAllColoniesAchievements(ColonyManager.java:234) ~[ColonyManager.class:?]
at com.minecolonies.coremod.event.FMLEventHandler.onPlayerLogin(FMLEventHandler.java:71) ~[FMLEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_438_FMLEventHandler_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:574) ~[FMLCommonHandler.class:?]
at net.minecraft.server.m
anagement.PlayerList.initializeConnectionToPlayer(PlayerList.java:214) ~[mt.class:?]
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:262) ~[NetworkDispatcher.class:?]
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:73) ~[NetworkDispatcher.class:?]
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:211) ~[NetworkDispatcher$1.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) ~[er.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [mh.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:743) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]

**Comment by Asherslab** [comment]
Would you be okay with giving us some context? such as when this happened, what did this cause, and such please? thanks!

**Comment by demon57730** [comment]
when changing mod update version

what happens to the player can not connect even if he has no colony (if he had a colony already existing with an old version)

**Comment by demon57730** [comment]
at each restart of the server 1 move we can connect 1 shot no

I had to delete all the existing colony and thus make that the player starts again to solve the problem of the has the update
