### ISSUE TITLE
Babarians ignore Average Night Value

### ISSUE THREAD

**Issue by yotthani** [ldtteam/minecolonies#1677]
### Minecolonies version

version 1.10.2-0.8.4908

### Expected behavior

- Babarians using average Nights value to appear

### Actual behaviour

- Appearing every night

### Steps to reproduce the problem

1. set average days value to e.g. 30 Nights
2. Babarians will ignore this an appear every night

**Comment by Raycoms** [comment]
Please update to the newest alpha where this will be fixed. Sorry for the
inconvinience

2017-11-22 12:43 GMT+00:00 yotthani <notifications@github.com>:

**Comment by yotthani** [comment]
Ok thx.
got the 1.10.2-0.8.5022.jar working it fixed the issue.

FYI:
with 1.10.2-0.8.5039 i got a serverside crash:
Caused by: java.lang.NullPointerException
	at net.minecraft.item.crafting.CraftingManager.func_77596_b(SourceFile:1220)
	at net.minecraftforge.fml.common.registry.GameRegistry.addShapelessRecipe(GameRegistry.java:235)
	at com.minecolonies.coremod.util.RecipeHandler.init(RecipeHandler.java:63)
	at com.minecolonies.coremod.MineColonies.init(MineColonies.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:805)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:214)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Unknown Source)
