### ISSUE TITLE
Crash on loggin in.

### ISSUE THREAD

**Issue by bob0bob** [ldtteam/minecolonies#1714]
minecolonies-universal-
mine craft 1.12.2-
mine colonies 0.8.5290

When I log in to the server.  This is the exception that happens.

[22:44:36] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalArgumentException: The string is too long for this encoding.
        at org.apache.commons.lang3.Validate.isTrue(Validate.java:158) ~[minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.network.ByteBufUtils.writeUTF8String(ByteBufUtils.java:166) ~[ByteBufUtils.class:?]
        at com.minecolonies.coremod.colony.CitizenData.serializeViewNetworkData(CitizenData.java:709) ~[CitizenData.class:?]
        at com.minecolonies.coremod.network.messages.ColonyViewCitizenViewMessage.<init>(ColonyViewCitizenViewMessage.java:42) ~[ColonyViewCitizenViewMessage.class:?]
        at com.minecolonies.coremod.colony.Colony.lambda$sendCitizenPackets$5(Colony.java:966) ~[Colony.class:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_151]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_151]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1553) ~[?:1.8.0_151]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_151]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_151]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_151]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_151]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_151]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_151]
        at com.minecolonies.coremod.colony.Colony.sendCitizenPackets(Colony.java:966) ~[Colony.class:?]
        at com.minecolonies.coremod.colony.Colony.updateSubscribers(Colony.java:866) ~[Colony.class:?]
        at com.minecolonies.coremod.colony.Colony.onServerTick(Colony.java:787) ~[Colony.class:?]
        at com.minecolonies.coremod.colony.ColonyManager.onServerTick(ColonyManager.java:572) ~[ColonyManager.class:?]
        at com.minecolonies.coremod.event.FMLEventHandler.onServerTick(FMLEventHandler.java:35) ~[FMLEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_103_FMLEventHandler_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:264) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:710) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
[2

**Comment by bob0bob** [comment]
[crash-2017-11-27_22.44.36-server.txt](https://github.com/Minecolonies/minecolonies/files/1508437/crash-2017-11-27_22.44.36-server.txt)

**Comment by bob0bob** [comment]
I went back to the old backup save and down grade to previous alpha and it worked.    It is related to the string name.   I have "  B:enableInDevelopmentFeatures=true"  set in the config.  which shows an extra text on the text string above the citizens name.  It appears to show state.   Right before it crashed,  it was repeating the state over and over and over.

Like:

Alex [gathering][gathering][gathering][gathering][gathering][gathering][gathering]

Until it crashed and then I couldn't log back in.  The minecolonies.dat file went from 58k to 294k before it crashed.

**Comment by Raycoms** [comment]
SHould be fixed in the latest alpha
