### ISSUE TITLE
[1.10.2] Server Crash: RequestSystem

### ISSUE THREAD

**Issue by yotthani** [ldtteam/minecolonies#1786]
### Minecolonies version

version minecolonies-universal-1.10.2-0.9.5908

### Expected behavior

- Server Starting

### Actual behaviour

- Server Crashes

### Steps to reproduce the problem
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CorePlugin (MrTJPCore-1.10.2-2.0.1.20-universal.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.4.347.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.11.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.2.jar)
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.12.17-universal.jar)
  IceAndFireForgeLoading (iceandfire-1.0.1.jar)
  CreativePatchingLoader (CreativeCore v1.7.3 mc1.10.2.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  BCModPlugin (backpacks 1.10.2 - 3.4.2.jar)
  AppEngLoadingPlugin (appliedenergistics2-rv4-stable-1.jar)
  PlusTiC (plustic-5.2.1.2.jar)
  AppleCore (AppleCore-mc1.10.2-3.0.0.jar)
  TatwCore (TATW-1.10.2-1.0.0.0.jar)
  llibrary (llibrary-1.7.7-1.10.2.jar)
  ASMPlugin (VeganOption-mc1.10.2-0.2.3.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.13.133-universal.jar)
  OpenModsCorePlugin (OpenModsLib-1.10.2-0.11.2.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.308-universal.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  ModpackFix (modpackfixer-1.0.0.jar)
  MicdoodlePlugin (MicdoodleCore-1.10.2-4.0.0.118.jar)
  CTMCorePlugin (CTM-MC1.10.2-0.2.3.26.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 12/7/17 11:49 AM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at com.minecolonies.coremod.colony.requestsystem.resolvers.WarehouseRequestResolver.lambda$canResolve$1(WarehouseRequestResolver.java:57)
	at java.util.stream.MatchOps$1MatchSink.accept(Unknown Source)
	at java.util.HashMap$KeySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.anyMatch(Unknown Source)
	at com.minecolonies.coremod.colony.requestsystem.resolvers.WarehouseRequestResolver.canResolve(WarehouseRequestResolver.java:57)
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.assignRequestDefault(RequestHandler.java:153)
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.assignRequest(RequestHandler.java:92)
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.reassignRequest(RequestHandler.java:226)
	at com.minecolonies.coremod.colony.requestsystem.management.manager.StandardRequestManager.reassignRequest(StandardRequestManager.java:236)
	at com.minecolonies.coremod.colony.requestsystem.resolvers.StandardRetryingRequestResolver.lambda$update$2(StandardRetryingRequestResolver.java:165)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at com.minecolonies.coremod.colony.requestsystem.resolvers.StandardRetryingRequestResolver.func_73660_a(StandardRetryingRequestResolver.java:177)
	at com.minecolonies.coremod.colony.requestsystem.management.manager.StandardRequestManager.func_73660_a(StandardRequestManager.java:518)
	at com.minecolonies.coremod.colony.Colony.onServerTick(Colony.java:765)
	at com.minecolonies.coremod.colony.ColonyManager.onServerTick(ColonyManager.java:577)
	at com.minecolonies.coremod.event.FMLEventHandler.onServerTick(FMLEventHandler.java:31)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_810_FMLEventHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:261)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows Server 2016 (amd64) version 10.0
	Java Version: 1.8.0_151, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2495187808 bytes (2379 MB) / 4277534720 bytes (4079 MB) up to 16088694784 bytes (15343 MB)
	JVM Flags: 7 total; -Xms4G -Xmx15G -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=2 -XX:+AggressiveOpts
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.32 Powered by Forge 12.18.3.2511 149 mods loaded, 149 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar)

**Comment by Raycoms** [comment]
Will be fixed in the newest version
