### ISSUE TITLE
[1.10] Crash on Server Startup (Ore Issue)

### ISSUE THREAD

**Issue by yotthani** [ldtteam/minecolonies#1896]
### Minecolonies version

version minecolonies-universal-1.10.2-0.9.6155 & minecolonies-universal-1.10.2-0.9.6188 

### Expected behavior

- Start normal like before with minecolonies-universal-1.10.2-0.9.6077

### Actual behaviour

Surprise! Haha. Well, this is awkward.

Time: 12/22/17 9:05 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at exterminatorjeff.undergroundbiomes.common.block.UBOreSedimentary.func_180642_a(UBOreSedimentary.java:42)
	at com.minecolonies.api.compatibility.CompatabilityManager.discoverOres(CompatabilityManager.java:162)
	at com.minecolonies.api.compatibility.CompatabilityManager.discover(CompatabilityManager.java:63)
	at com.minecolonies.coremod.colony.ColonyManager.readFromNBT(ColonyManager.java:818)
	at com.minecolonies.coremod.colony.ColonyManager.onWorldLoad(ColonyManager.java:716)
	at com.minecolonies.coremod.event.EventHandler.onWorldLoad(EventHandler.java:397)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_814_EventHandler_onWorldLoad_Load.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:263)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Unknown Source)

**Comment by Raycoms** [comment]
@OrionDevelopment this shouldn't be happening:

final IBlockState state = ((ItemBlock) stack.getItem()).getBlock()
                        .getStateForPlacement(world, BlockPos.ORIGIN, EnumFacing.NORTH, 0, 0, 0, stack.getMetadata(), null);

(where null is the placer) Might have to put this in a try and catch then? =D

**Comment by marchermans** [comment]
He is probabaly querrying something from the player. You could feed him a fakeplayer? Try catching is relativly heavy on the cpu.

**Comment by Raycoms** [comment]
It's something we execute once every server start, that shouldn't be an
issue in that case

**Comment by yotthani** [comment]
in case you tried a fix it (error still exists in the new minecolonies-universal-1.10.2-0.9.6188) .. else just ignore this line ;)

**Comment by AdaraChristine** [comment]
Got same error on upgrading MP server to minecolonies-universal-1.10.2-0.9.6206.

**Comment by yotthani** [comment]
yeah seems to bee not fixed yet .. have done it my own für my server by buildung a my own version with a code fix

**Comment by yotthani** [comment]
this bug still exists in 1.10 version maybe somebody missed to include it into this branch

**Comment by AdaraChristine** [comment]
forge-1.10.2-12.18.3.2185
minecolonies-universal-1.10.2-0.9.6589

AMDescription: Exception in server tick loop java.lang.NullPointerException: Exception in server tick loop
	at exterminatorjeff.undergroundbiomes.common.block.UBOreSedimentary.func_180642_a(UBOreSedimentary.java:42)
	at com.minecolonies.api.compatibility.CompatabilityManager.discoverOres(CompatabilityManager.java:194)
	at com.minecolonies.api.compatibility.CompatabilityManager.discover(CompatabilityManager.java:69)
	at com.minecolonies.coremod.colony.ColonyManager.readFromNBT(ColonyManager.java:810)
	at com.minecolonies.coremod.colony.ColonyManager.onWorldLoad(ColonyManager.java:708)
	at com.minecolonies.coremod.event.EventHandler.onWorldLoad(EventHandler.java:397)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_725_EventHandler_onWorldLoad_Load.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:263)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266)

**Comment by Raycoms** [comment]
will fix tomorrow

2018-01-06 8:45 GMT+00:00 Adaraa <notifications@github.com>:
