### ISSUE TITLE
[1.10] Several Issues Farmer, Cook, Baker

### ISSUE THREAD

**Issue by yotthani** [ldtteam/minecolonies#1921]
### Minecolonies version

version minecolonies-universal-1.10.2-0.9.6297

### Expected behavior
Issues:
 1. Farmer: Fields automaticly assined to one farmer
 2. Cook: Restaurants get deleted after Deconstruction
 3. Baker: Consumes resources while producing

### Actual behaviour

1. Farmer: 
 fields do not get assigned or assigned to multible Farmers at the same time
 if you assign manually not all field get recognized and assignment gets deleted every Server restart

![issue_farmer](https://user-images.githubusercontent.com/26121607/34381293-f25fe7bc-eb07-11e7-8a64-f7580561089e.png)

2. Cook: 
 For each Deconstructed Restaurant "Unknown" Cook keeps calling for food 

![issue_restaurant](https://user-images.githubusercontent.com/26121607/34381294-f277447a-eb07-11e7-95aa-6336f5a2e6db.png)

3. Baker: 
    not cosumes Weat but infinitly producing Bread

### Steps to reproduce the problem
 1. Farmer: 
    Step 1: Build Farmer
    Step 2: Build Farm
 2. Cook:
    Step 1: Build Restaurant
    Step 2: Wait for Cook to get Assigned
    Step 3: Deconstruct Restaurant
 3. Baker:
    Step 1: Build Bakery
    Step 2: Wait for Baker to get Assigned
    Step 3: Put 2 Stacks of Weat into Chest
    Step 4: Wait for Inifinite Bread

**Comment by Raycoms** [comment]
about the baker, are you sure he isn't consuming weed the dman is bringing
him? I just noticed that he isn't using the wheet in his chest, but still
needs a dman to bring it.

2017-12-27 12:15 GMT+00:00 yotthani <notifications@github.com>:

**Comment by Raycoms** [comment]
About the fields, I noticed this is only a clientside representation issue,
I fixed that in the latest build, you sure they are not working correctly
at them?

2017-12-27 13:33 GMT+00:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by yotthani** [comment]
Baker: yes even if no dman is commin, the two stacks of weat stay there but bread is produced , checked that 3 days in a row and it stays the same

Fields: yes checked it with the latest build

**Comment by Raycoms** [comment]
Okay I fixed the dman, but I can't reproduce the cook problem.

**Comment by yotthani** [comment]
will try to make an video for that (but after applying "Port1.10/fix pathing (#1920)" game crashes on client side for me)

**Comment by Raycoms** [comment]
Doing some fixes on top of it, but can you send me the log?

2017-12-27 16:01 GMT+00:00 yotthani <notifications@github.com>:

**Comment by yotthani** [comment]
Log for Clientcrash "Port1.10/fix pathing (#1920)" standing near the baker while working:

I bet Cylons wouldn't have this problem.

Time: 12/27/17 3:37 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.minecolonies.coremod.entity.EntityCitizen.addExperience(EntityCitizen.java:1147)
	at com.minecolonies.coremod.entity.EntityCitizen.gatherXp(EntityCitizen.java:1051)
	at com.minecolonies.coremod.entity.EntityCitizen.func_70636_d(EntityCitizen.java:848)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:384)
	at net.minecraft.world.World.func_72866_a(World.java:1967)
	at net.minecraft.world.World.func_72870_g(World.java:1937)
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1789)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Raycoms** [comment]
okay I fixed that one and the baker, will look into the fields now

**Comment by yotthani** [comment]
number 2: still exists in the current version for 1.10
