### ISSUE TITLE
MAJOR crashing problem!

### ISSUE THREAD

**Issue by MattBeard** [ldtteam/minecolonies#1994]
### Minecolonies version

version 1.12.2.-0.8.6731

### Expected behavior

- If keeps running

### Actual behaviour

- After a while it dies and each time I re-load it dies again
- Reloading a backup and playing again eventually gets to the same problem!

### Steps to reproduce the problem

1. ?? I can send a zip of the whole world, but it's about 90MB

Here is the key section of the log that happens when this crashing state is active:

`11:38:25] [Netty Server IO #1/INFO]: Client attempting to join with 6 mods : minecraft@1.12.2,FML@8.0.99.99,forge@14.23.0.2537,minecolonies@1.12.2-0.8.6731,mcp@9.42,journeymap@1.12.2-5.5.2
[11:38:25] [Server thread/WARN]: Tried to add entity minecolonies:fishhook but it was marked as removed already
[11:38:25] [Netty Local Client IO #0/INFO]: [Netty Local Client IO #0] Client side modded connection established
[11:38:25] [Server thread/INFO]: [Server thread] Server side modded connection established
[11:38:25] [Server thread/INFO]: GettinMine[local:E:f8e0c9ca] logged in with entity id 34 at (-194.3373637453993, 63.0, -595.0240553032924)
[11:38:25] [Server thread/INFO]: GettinMine joined the game
[11:38:27] [Netty Local Client IO #0/ERROR]: SimpleChannelHandlerWrapper exception
java.lang.RuntimeException: Tried to read NBT tag that was too big; tried to allocate: 2097155bytes where max allowed: 2097152
	at net.minecraft.nbt.NBTSizeTracker.func_152450_a(NBTSizeTracker.java:25) ~[gh.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:57) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:496) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:58) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:496) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:58) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:496) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:58) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:496) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:58) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:496) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:58) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:496) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:58) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagList.func_152446_a(NBTTagList.java:63) ~[ge.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:496) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:58) ~[fy.class:?]
	at net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:133) ~[gi.class:?]
	at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:88) ~[gi.class:?]
	at net.minecraft.network.PacketBuffer.func_150793_b(PacketBuffer.java:315) ~[gy.class:?]
	at net.minecraftforge.fml.common.network.ByteBufUtils.readTag(ByteBufUtils.java:227) ~[ByteBufUtils.class:?]
	at com.minecolonies.coremod.colony.ColonyView.handleColonyViewMessage(ColonyView.java:476) ~[ColonyView.class:?]
	at com.minecolonies.coremod.colony.ColonyManager.handleColonyViewMessage(ColonyManager.java:896) ~[ColonyManager.class:?]
	at com.minecolonies.coremod.network.messages.ColonyViewMessage.onMessage(ColonyViewMessage.java:67) ~[ColonyViewMessage.class:?]
	at com.minecolonies.coremod.network.messages.ColonyViewMessage.onMessage(ColonyViewMessage.java:18) ~[ColonyViewMessage.class:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:56) ~[SimpleChannelHandlerWrapper.class:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:36) ~[SimpleChannelHandlerWrapper.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[SimpleChannelInboundHandler.class:4.1.9.Final]`

**Comment by Raycoms** [comment]
Your colony dat, can you send that to us? (its in world - minecolonies -
colonies.dat)

2018-01-10 11:43 GMT+00:00 MattBeard <notifications@github.com>:

**Comment by MattBeard** [comment]
'ere 'tiz
[colonies.zip](https://github.com/Minecolonies/minecolonies/files/1618639/colonies.zip)

**Comment by Raycoms** [comment]
Try this one:
[colonies.dat.zip](https://github.com/Minecolonies/minecolonies/files/1618649/colonies.dat.zip)

**Comment by MattBeard** [comment]
OK... that works. But it's so much smaller - what have I lost?

**Comment by Raycoms** [comment]
There was an issue a few weeks ago which created 1000 requests, I removed
those from your colonies.dat

**Comment by MattBeard** [comment]
Ahhh.... that might help.
