### ISSUE TITLE
Game crashes with a null reference

### ISSUE THREAD

**Issue by kabotnik** [ldtteam/minecolonies#2018]
### Minecolonies version

version 1.12.2-0.8.6403

### Expected behavior

- Game does not crash

### Actual behaviour

- Game crashes with the following stack trace
```
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at com.minecolonies.coremod.tileentities.ScarecrowTileEntity.func_189518_D_(ScarecrowTileEntity.java:452)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187273_a(PlayerChunkMapEntry.java:288)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:250)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:115)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.minecolonies.coremod.tileentities.ScarecrowTileEntity.func_189518_D_(ScarecrowTileEntity.java:452)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187273_a(PlayerChunkMapEntry.java:288)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:250)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:115)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
```

I assume it is related to some mechanic with the farmers and fields, but I am unsure. I have two farmers and four fields planted. I believe I may have had a scarecrow in my inventory as well, but I can't say for sure because the game crashes as soon as I start the world. This just started happening and I am unsure what caused it because I had been running with the same number of farmers and fields for several days.

### Steps to reproduce the problem

1. Load Minecraft
2. Start selected world
3. Game crashes

**Comment by Raycoms** [comment]
This is weird I'll push a fix for this tomorrow

**Comment by kabotnik** [comment]
:+1: Thanks! Looking forward to the fix. :)

**Comment by Raycoms** [comment]
can you please update to our newest alpha? This should be fixed already
