### ISSUE TITLE
[1.10.2] Server crash on Tick

### ISSUE THREAD

**Issue by yotthani** [ldtteam/minecolonies#2085]
### Minecolonies version

version 1.10.2-0.9.7104.jar

**1.**

PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at com.minecolonies.coremod.colony.CitizenData.setWorkBuilding(CitizenData.java:610)
	at com.minecolonies.coremod.colony.CitizenData.onRemoveBuilding(CitizenData.java:534)
	at com.minecolonies.coremod.colony.managers.BuildingManager.removeBuilding(BuildingManager.java:363)
	at com.minecolonies.coremod.colony.buildings.AbstractBuilding.destroy(AbstractBuilding.java:749)
	at java.util.ArrayList.forEach(Unknown Source)
	at com.minecolonies.coremod.colony.managers.BuildingManager.cleanUpBuildings(BuildingManager.java:204)
	at com.minecolonies.coremod.colony.Colony.onWorldTick(Colony.java:610)
	at com.minecolonies.coremod.colony.ColonyManager.lambda$onWorldTick$1(ColonyManager.java:695)
	at java.util.ArrayList.forEach(Unknown Source)
	at com.minecolonies.coremod.colony.ColonyManager.onWorldTick(ColonyManager.java:695)
	at com.minecolonies.coremod.event.FMLEventHandler.onWorldTick(FMLEventHandler.java:55)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_888_FMLEventHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:282)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:694)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

**2.** 
also on 1.10 there is still this issue on server startup:

Time: 12/22/17 9:05 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
at exterminatorjeff.undergroundbiomes.common.block.UBOreSedimentary.func_180642_a(UBOreSedimentary.java:42)
at com.minecolonies.api.compatibility.CompatabilityManager.discoverOres(CompatabilityManager.java:162)
at com.minecolonies.api.compatibility.CompatabilityManager.discover(CompatabilityManager.java:63)
at com.minecolonies.coremod.colony.ColonyManager.readFromNBT(ColonyManager.java:818)
at com.minecolonies.coremod.colony.ColonyManager.onWorldLoad(ColonyManager.java:716)
at com.minecolonies.coremod.event.EventHandler.onWorldLoad(EventHandler.java:397)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_814_EventHandler_onWorldLoad_Load.invoke(.dynamic)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:263)
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
at java.lang.Thread.run(Unknown Source)

**Comment by Raycoms** [comment]
Can you report this please to exterminatorjeff.undergroundbiomes.common.
block.UBOreSedimentary. since their blockState implementation has a bug
like the one of techreborn had.
https://github.com/TechReborn/TechReborn

2018-01-24 18:38 GMT+00:00 yotthani <notifications@github.com>:

**Comment by yotthani** [comment]
ok just did .. so skip number 2 👍
