### ISSUE TITLE
Constant Crashes

### ISSUE THREAD

**Issue by CoporalKritz** [ldtteam/minecolonies#2140]
4.14 Minecolonies version

Minecraft Version 1.12.2

Forge-14.23.1.2604

Expected behavior
To open and work as normal

- XXX

Actual behaviour
The game crashes before even opening the game

Currently I have no idea whats happening, as I have 8 gigs of memory, 4 gigs of video, and over a terrabyte of storage. If anyone knows how to fix this, it would be much appreciated. The same thing happened with previous versions as well. 

Here are the listed errors from the crash log

11:21:48 | game | 2018-02-02 19:21:48,072 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream   <log4j:Event logger="LaunchWrapper" timestamp="1517628108169" level="INFO" thread="main">     <log4j:Message><![CDATA[Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker]]></log4j:Message>   </log4j:Event>
-- | -- | --
11:21:48 | monitor | expected <
11:21:48 | game | 2018-02-02 19:21:48,374 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream 2018-02-02 19:21:48,389 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream   <log4j:Event logger="FML" timestamp="1517628108420" level="WARN" thread="main">     <log4j:Message><![CDATA[The coremod AppleCore (squeek.applecore.AppleCore) is not signed!]]></log4j:Message>   </log4j:Event>
11:21:48 | monitor | expected <

**Comment by Lordbaane** [comment]
I found some of the latest Forge releases have a variety of issues, did you try back tracking to 2555?

**Comment by CoporalKritz** [comment]
@Lordbaane Which Minecolonies version is that?

**Comment by CoporalKritz** [comment]
@Lordbaane I tracked back to forge version 14.23.1.2555 and once again had a crash, the error log listing a fatal error this time

**Comment by Lordbaane** [comment]
Currently I'm using 8.7281 as I'm waiting for some updates regarding some other issues. I have over 50 other mods running and it is stable.

**Comment by Lordbaane** [comment]
_"Alright, I think I've got it.

Try disabling the forge loading screen.

In some folder somewhere there should be something called splash.properties with an options that says enabled=true or something similar. Change it to enabled=false.

If that doesn't work it could be some of the weird JVM arguments you have for whatever reason, but try the config thing first._"

I think I ran into the same problem a few versions back. Try this if you can, I found it on another site.

**Comment by marchermans** [comment]
@CoporalKritz are you running a Mac or Unix variant?

**Comment by CoporalKritz** [comment]
@OrionDevelopment I run windows 10 with a dell HP

**Comment by CoporalKritz** [comment]
@Lordbaane I found the folder, set it to false, saved it, and it's still the same

**Comment by Lordbaane** [comment]
What version of Java are you using? Also, are there any driver updates for your system? It sounds to me it is more of a Forge/Driver issue than the file. 
Another thought is how many mods are your running? Was there a stable startup? If so, what was running? Lastly if you have some setup that runs fine, add one mod at a time to see what happens.

**Comment by Lordbaane** [comment]
I still have an issue with the gravestones extended mod where is causes it not to start. I'm waiting for an update to see if that helps.

**Comment by marchermans** [comment]
@CoporalKritz Send me the entire log in a gist or pastebin.

**Comment by CoporalKritz** [comment]
@OrionDevelopment [11:18:55] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[11:18:55] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[11:18:55] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[11:18:55] [main/INFO]: Forge Mod Loader version 14.23.1.2604 for Minecraft 1.12.2 loading
[11:18:55] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 10:amd64:10.0, installed at C:\Users\ardel\OneDrive\Documents\Curse\Minecraft\Install\runtime\jre-x64\1.8.0_25
[11:18:56] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in AppleCore-mc1.12.2-3.1.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[11:18:56] [main/WARN]: The coremod AppleCore (squeek.applecore.AppleCore) is not signed!
[11:18:56] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in backpacks 1.12.2 - 3.4.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[11:18:56] [main/WARN]: The coremod BCModPlugin (brad16840.core.BCModPlugin) is not signed!
[11:18:56] [main/INFO]: Loading tweaker guichaguri.betterfps.tweaker.BetterFpsTweaker from BetterFps-1.4.8.jar
[11:18:56] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in ColorUtility-universal-1.0.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[11:18:56] [main/WARN]: The coremod com.Axeryok.ColorUtility.ColorUtilityCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[11:18:56] [main/WARN]: The coremod ColorUtilityCorePlugin (com.Axeryok.ColorUtility.ColorUtilityCorePlugin) is not signed!
[11:18:56] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in comforts-1.12.2-1.1.0.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[11:18:56] [main/WARN]: The coremod c4.comforts.asm.ComfortsCoreLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[11:18:56] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in CTM-MC1.12-0.2.3.12.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[11:18:56] [main/WARN]: The coremod team.chisel.ctm.client.asm.CTMCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[11:18:56] [main/WARN]: The coremod CTMCorePlugin (team.chisel.ctm.client.asm.CTMCorePlugin) is not signed!
[11:18:56] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in DynamicLights-1.12.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[11:18:56] [main/WARN]: The coremod atomicstryker.dynamiclights.common.DLFMLCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[11:18:56] [main/WARN]: The coremod DLFMLCorePlugin (atomicstryker.dynamiclights.common.DLFMLCorePlugin) is not signed!
[11:18:56] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in DynamicSurroundings-1.12.2-3.4.9.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[11:18:56] [main/WARN]: The coremod org.blockartistry.DynSurround.asm.TransformLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[11:18:56] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Forgelin-1.6.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[11:18:56] [main/WARN]: The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[11:18:56] [main/WARN]: The coremod ForgelinPlugin (net.shadowfacts.forgelin.preloader.ForgelinPlugin) is not signed!
[11:18:56] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in InventoryTweaks-1.63.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[11:18:56] [main/WARN]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[11:18:56] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from LagGoggles-FORGE-1.12.2-3.0.jar
[11:18:56] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from malisiscore-1.12.2-6.3.2.jar
[11:18:56] [main/WARN]: The coremod openeye.CorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[11:18:56] [main/WARN]: The coremod OpenEyePlugin (openeye.CorePlugin) is not signed!
[11:18:56] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in Quark-r1.4-122.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[11:18:56] [main/WARN]: The coremod vazkii.quark.base.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[11:18:56] [main/WARN]: The coremod LoadingPlugin (vazkii.quark.base.asm.LoadingPlugin) is not signed!
[11:18:56] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in redstonepaste-mc1.12-1.7.5.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[11:18:56] [main/WARN]: The coremod net.fybertech.nwr.NWRTweak does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[11:18:56] [main/WARN]: The coremod NWRTweak (net.fybertech.nwr.NWRTweak) is not signed!
[11:18:56] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in ResourceLoader-MC1.12.1-1.5.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[11:18:56] [main/WARN]: The coremod lumien.resourceloader.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[11:18:56] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in shetiphiancore-1.12.0-3.5.6.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[11:18:56] [main/WARN]: The coremod shetiphian.asm.TweakPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[11:18:56] [main/WARN]: The coremod ShetiPhian-ASM (shetiphian.asm.TweakPlugin) is not signed!
[11:18:56] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[11:18:56] [main/INFO]: Loading tweak class name guichaguri.betterfps.tweaker.BetterFpsTweaker
[11:18:56] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[11:18:56] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.5 Source=file:/C:/Users/ardel/OneDrive/Documents/Curse/Minecraft/Instances/MineColonies%20Official%20(1)/mods/LagGoggles-FORGE-1.12.2-3.0.jar Service=LaunchWrapper Env=CLIENT
[11:18:56] [main/WARN]: The coremod net.malisis.core.asm.MalisisCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[11:18:56] [main/WARN]: The coremod MalisisCorePlugin (net.malisis.core.asm.MalisisCorePlugin) is not signed!
[11:18:56] [main/INFO]: Compatibility level set to JAVA_8
[11:18:56] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[11:18:56] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[11:18:56] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[11:18:56] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[11:18:56] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[11:18:57] [main/FATAL]: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty.
[11:18:57] [main/ERROR]: Unable to launch
java.lang.RuntimeException: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty, your vanilla jar may be corrupt.
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:170) ~[forge-1.12.2-14.23.1.2604.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty, your vanilla jar may be corrupt.
	at net.minecraftforge.fml.common.patcher.ClassPatchManager.applyPatch(ClassPatchManager.java:113) ~[forge-1.12.2-14.23.1.2604.jar:?]
	at net.minecraftforge.fml.common.patcher.ClassPatchManager.getPatchedResource(ClassPatchManager.java:76) ~[forge-1.12.2-14.23.1.2604.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.getFieldType(FMLDeobfuscatingRemapper.java:219) ~[forge-1.12.2-14.23.1.2604.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.parseField(FMLDeobfuscatingRemapper.java:192) ~[forge-1.12.2-14.23.1.2604.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.setup(FMLDeobfuscatingRemapper.java:161) ~[forge-1.12.2-14.23.1.2604.jar:?]
	at net.minecraftforge.fml.common.asm.FMLSanityChecker.injectData(FMLSanityChecker.java:188) ~[forge-1.12.2-14.23.1.2604.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:165) ~[forge-1.12.2-14.23.1.2604.jar:?]
	... 2 more
[11:18:57] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[11:18:57] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[11:18:57] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[11:18:57] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[11:18:57] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:968)
[11:18:57] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[11:18:57] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
 I'm sorry that this is long but this is the entire latest log that I got from last time I launched the modpack

**Comment by CoporalKritz** [comment]
@Lordbaane I'm using the mod in the standard modpack with no extra mods other than what it came with, and there are no driver updates nor am I experiencing any issues with my computer starting up

**Comment by Lordbaane** [comment]
Have you allocated more memory to MC?

**Comment by Lordbaane** [comment]
I have 16gb for my comp, but I allocate 12g to the game as I sometime lan with my kids.

**Comment by copperwarrior** [comment]
It may seem an obvious fix, but have you attempted to reinstall the modpack? Crash log reports that the vanilla game is corrupt.

**Comment by CoporalKritz** [comment]
@copperwarrior I have transferred new updates to new folders, but I have not tried actually deleting it entirely and reinstalling it.

**Comment by CoporalKritz** [comment]
@Lordbaane I have not as I have no real clue as how too

**Comment by copperwarrior** [comment]
@CoporalKritz It's not an out of memory error, those are almost always explicitly stated in the crash report. Attempt to reinstall the modpack, backup your saves ofc, and try and run it then.

**Comment by CoporalKritz** [comment]
@copperwarrior alright then, I'm reinstalling it right now to see if it works

**Comment by CoporalKritz** [comment]
@copperwarrior still doesn't work, I tried making a new profile to see if it was a forge issue, and by starting said new profile it is indeed a forge issue as stated by the crash report


07:43:48 | game |   | error | 2018-02-03 15:43:47,935 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream   <log4j:Event logger="LaunchWrapper" timestamp="1517701428029" level="INFO" thread="main">     <log4j:Message><![CDATA[Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker]]></log4j:Message>   </log4j:Event>
-- | -- | -- | -- | --
07:43:48 | monitor | Process Monitor | error | expected <

**Comment by copperwarrior** [comment]
@CoporalKritz can you send the log? this crash report doesn't tell much

**Comment by CoporalKritz** [comment]
@copperwarrior it'll be long so be prepared

[15:43:48] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[15:43:48] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[15:43:48] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[15:43:48] [main/INFO]: Forge Mod Loader version 14.23.2.2611 for Minecraft 1.12.2 loading
[15:43:48] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 10:amd64:10.0, installed at C:\Users\ardel\OneDrive\Documents\Curse\Minecraft\Install\runtime\jre-x64\1.8.0_25
[15:43:48] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in InventoryTweaks-1.63.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[15:43:48] [main/WARN]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[15:43:48] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:43:48] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[15:43:48] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:43:48] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[15:43:48] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[15:43:49] [main/FATAL]: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty.
[15:43:49] [main/ERROR]: Unable to launch
java.lang.RuntimeException: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty, your vanilla jar may be corrupt.
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:170) ~[forge-1.12.2-14.23.2.2611.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.crash.CrashReport$1, but received empty, your vanilla jar may be corrupt.
	at net.minecraftforge.fml.common.patcher.ClassPatchManager.applyPatch(ClassPatchManager.java:113) ~[forge-1.12.2-14.23.2.2611.jar:?]
	at net.minecraftforge.fml.common.patcher.ClassPatchManager.getPatchedResource(ClassPatchManager.java:76) ~[forge-1.12.2-14.23.2.2611.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.getFieldType(FMLDeobfuscatingRemapper.java:219) ~[forge-1.12.2-14.23.2.2611.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.parseField(FMLDeobfuscatingRemapper.java:192) ~[forge-1.12.2-14.23.2.2611.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.setup(FMLDeobfuscatingRemapper.java:161) ~[forge-1.12.2-14.23.2.2611.jar:?]
	at net.minecraftforge.fml.common.asm.FMLSanityChecker.injectData(FMLSanityChecker.java:188) ~[forge-1.12.2-14.23.2.2611.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:165) ~[forge-1.12.2-14.23.2.2611.jar:?]
	... 2 more
[15:43:49] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[15:43:49] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[15:43:49] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[15:43:49] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[15:43:49] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:968)
[15:43:49] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[15:43:49] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by CoporalKritz** [comment]
@copperwarrior mainly it keeps talking about "class tweaks" and forge, which I get nothing about as I barely know anything about coding, much less modding

**Comment by copperwarrior** [comment]
@CoporalKritz That's the same issue as before, try installing forge 2555, the recommended version

**Comment by CoporalKritz** [comment]
@copperwarrior just did, I even tried launching without the minecolonies mod itself, and still I get crash reports upon crash reports

**Comment by copperwarrior** [comment]
@CoporalKritz How are you launching the modpack? Upon closer inspection, it may be a memory issue, but it still seems unlikely.

**Comment by CoporalKritz** [comment]
@copperwarrior I do nothing special when I launch it, as I don't mess with the code or technical stuff out of fear of screwing it up even more, but mostly I just press "play", open the launcher, and press the button that would open the minecolonies modpack, but i just crash after that without the game even opening

**Comment by copperwarrior** [comment]
@CoporalKritz What I mean is do you use the twitch, technic, or normal minecraft launcher?

**Comment by CoporalKritz** [comment]
@copperwarrior mainly twitch for the easy curse use

**Comment by copperwarrior** [comment]
@CoporalKritz View the minecolonies profile. Click on the three dots in the corner to get to the profile options. Change the memory settings to use something in the recommended range that your system can handle. I recommend about 4gb, or 4096 mb. Then save and attempt to run the game.

**Comment by CoporalKritz** [comment]
@copperwarrior I still keep getting crashes, once again even without the minecolonies mod.

**Comment by copperwarrior** [comment]
@CoporalKritz I am unsure as to what is causing your crashes at this point. In the same menu where you found the profile options, can you attempt to repair minecraft?

**Comment by CoporalKritz** [comment]
@copperwarrior I just pressed the button to do so, so I hope to god this works

**Comment by CoporalKritz** [comment]
@copperwarrior still crashing, did you tweak anything in the files before starting up your game? Or are you on an earlier version other than 1.12.2?

**Comment by copperwarrior** [comment]
@CoporalKritz I've been following along with your reports under the assumption that you are using our official modpack in the 1.12.2 version. In the same place where you find the logs, there should be a folder labelled crash-reports. Can you send the most recent one of those? They tend to provide useful information on their own.

**Comment by CoporalKritz** [comment]
@copperwarrior Is there a way to enable crash reports? I can't find any file labeled as such when I look through the log file. Either that or I'm doing it incorrectly, as I just press the three dots in the corner, press open file, and look in the folder labeled "logs"

**Comment by copperwarrior** [comment]
@CoporalKritz Actually, I just realized you wouldn't find crash reports due to the error reported in the log. Essentially the fatal error which triggers the crash is saying that it cannot find the piece of code in the Minecraft jar which reports errors, so we really don't have any good way to figure out what's actually happening. I'll try and figure out some solution to this.

**Comment by CoporalKritz** [comment]
@copperwarrior thank you for helping me this far, I hope there's a solution to this as I've been following the mod since 1.7.10 and I don't wanna stop playing this anytime soon.

**Comment by copperwarrior** [comment]
@CoporalKritz I doubt it will help but can you double check to make sure you are on the latest modpack version? I'm trying to recreate the issue and I just want to make sure everything is the same on both ends.

**Comment by CoporalKritz** [comment]
@copperwarrior I am on the most recent version that's listed which is 4.15 , although the same thing happened with previous versions as well

**Comment by copperwarrior** [comment]
@CoporalKritz Does any other version of minecraft run?

**Comment by CoporalKritz** [comment]
@copperwarrior I haven't tried previous versions yet, but I'll try that now

**Comment by copperwarrior** [comment]
@CoporalKritz I mean other modpacks, or vanilla minecraft

**Comment by CoporalKritz** [comment]
@copperwarrior I'll try that as well, and vanilla works fine from my experience as it doesn't crash

**Comment by CoporalKritz** [comment]
@copperwarrior other modpacks work, as I just started up a FTD modpack, and it starts up very nicely

**Comment by copperwarrior** [comment]
@CoporalKritz Try this. In the twitch launcher, in the very top left corner, there is a menu. Click on that menu, go to File>Settings>Minecraft and then find and click the "Jar Launcher" option.

**Comment by CoporalKritz** [comment]
@copperwarrior just did, I hope this works

**Comment by CoporalKritz** [comment]
@copperwarrior Hallelujah it works

**Comment by CoporalKritz** [comment]
@copperwarrior well, the launcher, I still have to open the modpack using it

**Comment by copperwarrior** [comment]
@CoporalKritz Make sure you can actually run the game, of course.

**Comment by CoporalKritz** [comment]
@copperwarrior It's actually loading so it's a good sign, I'm just waiting for it to lead me to the menu

**Comment by CoporalKritz** [comment]
@copperwarrior It works, thank you so much for helping me

**Comment by copperwarrior** [comment]
@CoporalKritz No problem
