### ISSUE TITLE
Undergroundbiomes ore error

### ISSUE THREAD

**Issue by AdaraChristine** [ldtteam/minecolonies#2170]
### Minecolonies version
minecolonies-universal-1.10.2-0.9.6974
UndergroundBiomesConstructs-1.10-1.0.v.19
forge-1.10.2-12.18.3.2511

### Expected behavior
Server start

### Actual behavior
Server crash

Description: Exception in server tick loop
java.lang.NullPointerException: Exception in server tick loop
	at exterminatorjeff.undergroundbiomes.common.block.UBOreSedimentary.func_180642_a(UBOreSedimentary.java:42)
	at com.minecolonies.api.compatibility.CompatabilityManager.discoverOres(CompatabilityManager.java:198)
	at com.minecolonies.api.compatibility.CompatabilityManager.discover(CompatabilityManager.java:69)
	at com.minecolonies.coremod.colony.ColonyManager.readFromNBT(ColonyManager.java:871)
	at com.minecolonies.coremod.colony.ColonyManager.onWorldLoad(ColonyManager.java:723)
	at com.minecolonies.coremod.event.EventHandler.onWorldLoad(EventHandler.java:398)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_788_EventHandler_onWorldLoad_Load.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:263)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Unknown Source)

**Comment by marchermans** [comment]
Update both Minecolonies as well as Underground biomes. There ore blocks are broken, but should have been fixed by now. @Raycoms.

**Comment by AdaraChristine** [comment]
Will this be fixed in the 1.10.2 version?

**Comment by Raycoms** [comment]
Yeah, might need a bit since we need to port a lot of changes to 1.10

2018-02-12 22:25 GMT+00:00 AdaraChristine <notifications@github.com>:

**Comment by AdaraChristine** [comment]
Just checking. Thank you for your work!

**Comment by AdaraChristine** [comment]
Was this fixed in the 1.10. version? Im still getting this error on server start up with the minecolonies-universal-1.10.2-0.9.7587 version.

**Comment by Sandriell** [comment]
They haven't pushed a new 1.10 version yet.

Raycoms said in another issue earlier today:

> we are really behind on the 1.10 branch, in 1.12 it is fixed
already, 1.10 will need a while still, we don't have much time, and porting
takes ages.

**Comment by AdaraChristine** [comment]
Ah OK thanks!
