### ISSUE TITLE
1.12.2-0.8.7582 Server crashes when updating to newer version

### ISSUE THREAD

**Issue by alanman** [ldtteam/minecolonies#2301]
### Minecolonies version

version 0.8.7582, and updating to any newer version from curseforge

### Expected behavior

- loads server

### Actual behaviour

- First, complains about missing block, blocktimberframe.  If I confirm the deletion, the server will crash with a MethodNotFound Exception:
```
Encountered an unexpected exception
java.lang.NoSuchMethodError: net.minecraft.world.chunk.Chunk.getCapability(Lnet/minecraftforge/common/capabilities/Capability;Lnet/minecraft/util/EnumFacing;)Ljava/lang/Object;
	at com.minecolonies.coremod.colony.ColonyManager.notifyChunksInRange(ColonyManager.java:215) ~[ColonyManager.class:?]
	at com.minecolonies.coremod.colony.ColonyManager.onWorldLoad(ColonyManager.java:960) ~[ColonyManager.class:?]
	at com.minecolonies.coremod.event.EventHandler.onWorldLoad(EventHandler.java:511) ~[EventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_12_EventHandler_onWorldLoad_Load.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:309) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
```
Here's the full log.
[crash-2018-03-09_22.09.22-server.txt](https://github.com/Minecolonies/minecolonies/files/1799121/crash-2018-03-09_22.09.22-server.txt)

### Steps to reproduce the problem

1. Play on 7582 version
2. Update to any later version
3. ...
4. (lose your) Profit

**Comment by marchermans** [comment]
Update Forge.

**Comment by alanman** [comment]
Oh! Haha. Totally forgot about that as an option.  My version came out back in September!  Updating resolved the issue. Thanks!
