### ISSUE TITLE
Fatal Crash

### ISSUE THREAD

**Issue by SulpherStaer** [ldtteam/minecolonies#2317]
### Minecolonies version

version minecolonies-universal-1.12.2-0.8.7737 **ALPHA**

### Expected behavior

- Doesn't crash

### Actual behaviour

- Crashed to desktop

### Steps to reproduce the problem

1. Builder knows recipe to make crafting table
2. Lumberjack knows recipe to make planks
3. Builder requires crafting table
4. Builder waits for lumberjack to make planks
5. Fatal crash

```
Exception in server tick loop

java.lang.StackOverflowError: Exception in server tick loop
	at java.lang.String.valueOf(String.java:2981)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at com.minecolonies.api.colony.requestsystem.token.StandardToken.toString(StandardToken.java:72)
	at java.lang.String.valueOf(String.java:2981)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.getRequestOrNull(RequestHandler.java:520)
	at com.minecolonies.coremod.colony.requestsystem.management.manager.StandardRequestManager.getRequestForToken(StandardRequestManager.java:211)
	at com.minecolonies.coremod.colony.requestsystem.resolvers.PrivateWorkerCraftingRequestResolver.getBuilding(PrivateWorkerCraftingRequestResolver.java:42)
	at com.minecolonies.coremod.colony.requestsystem.resolvers.PrivateWorkerCraftingRequestResolver.getBuilding(PrivateWorkerCraftingRequestResolver.java:59)
	at com.minecolonies.coremod.colony.requestsystem.resolvers.PrivateWorkerCraftingRequestResolver.getBuilding(PrivateWorkerCraftingRequestResolver.java:59)
	at com.minecolonies.coremod.colony.requestsystem.resolvers.PrivateWorkerCraftingRequestResolver.getBuilding(PrivateWorkerCraftingRequestResolver.java:59)
```

**Comment by PoroUsedSnax** [comment]
I couldn't tell you why the crash happens, but thought I would add that currently the Lumberjack will **not** craft planks, as they are not a requirement for them to craft, you'd need to teach the builder to also craft planks.

**Comment by Raycoms** [comment]
@OrionDevelopment

**Comment by Wissi** [comment]
@sylcai Please update to the latest Alpha.
Can you confirm you still have this issue?
Else the issue will be closed.
Thanks.

**Comment by marchermans** [comment]
No idea

**Comment by marchermans** [comment]
Will de fixed with the rs rewrite though

**Comment by Raycoms** [comment]
Should be fixed with RS changes soon (closed in favor of the general RS related issues)
