### ISSUE TITLE
Error on startup about sounds.

### ISSUE THREAD

**Issue by ProsperCraft** [ldtteam/minecolonies#2325]
### Minecolonies version

minecolonies-universal-1.12.2-0.8.7855

### Actual behavior

[11:28:30] [main/INFO] [mxtune]: Sound Setup Event net.minecraftforge.client.event.sound.SoundSetupEvent@4c9bc82e
[11:28:30] [main/INFO] [mxtune]: Sound channels: 176 normal, 16 streaming (total avail: 192)
[11:28:30] [main/WARN] [net.minecraft.client.audio.SoundHandler]: Invalid sounds.json
com.google.gson.JsonParseException: java.io.EOFException: End of input at line 1 column 1 path $
	at net.minecraft.util.JsonUtils.func_193838_a(SourceFile:506) ~[rc.class:?]
	at net.minecraft.util.JsonUtils.func_193841_a(SourceFile:522) ~[rc.class:?]
	at net.minecraft.client.audio.SoundHandler.func_175085_a(SoundHandler.java:145) ~[cho.class:?]
	at net.minecraft.client.audio.SoundHandler.func_110549_a(SoundHandler.java:79) [cho.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121) [cev.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:473) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.io.EOFException: End of input at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1393) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:549) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425) ~[JsonReader.class:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:161) ~[MapTypeAdapterFactory$Adapter.class:?]
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145) ~[MapTypeAdapterFactory$Adapter.class:?]
	at net.minecraft.util.JsonUtils.func_193838_a(SourceFile:504) ~[rc.class:?]
	... 13 more
[11:28:39] [main/WARN] [net.minecraft.client.audio.SoundHandler]: File minecolonies:sounds/mob/deliveryman/female/inhaleexhale1.ogg does not exist, cannot add it to event minecolonies:mob.deliveryman.female.noise
[11:28:39] [main/WARN] [net.minecraft.client.audio.SoundHandler]: File minecolonies:sounds/mob/builder/female/whatisit.ogg does not exist, cannot add it to event minecolonies:mob.builder.female.interaction
[11:28:39] [main/WARN] [net.minecraft.client.audio.SoundManager]: Missing sound for event: minecolonies:mob.guard.archer.female.badhousing
[11:28:39] [main/WARN] [net.minecraft.client.audio.SoundManager]: Missing sound for event: techguns:guns.cyberdemonblasterreload
[11:28:39] [main/WARN] [net.minecraft.client.audio.SoundManager]: Missing sound for event: techguns:jetpack.end
[11:28:39] [Sound Library Loader/INFO] [net.minecraft.client.audio.SoundManager]: Starting up SoundSystem...

**Comment by Fireruner** [comment]
Did you tried to redownload the mod? Looks like there´s something wrong with your local files, as Forge couldn´t load some of the resources of the mod. 

Try redownloading and reinstalling the mod and see if it works

**Comment by marchermans** [comment]
That Crash does not indicate that minecolonies is to blame. One of your mods has a wrongly formatted sounds.json file.

As far as I can see however ours is okey. Except for some additionally defined sounds which are not in the jar (the warnings) Minecolonies is not causing this exception.
