### ISSUE TITLE
Sawmill Crash

### ISSUE THREAD

**Issue by matthewm2148** [ldtteam/minecolonies#2344]
### Minecolonies version

version X.X.XXXX or curse X.X.XX

### Expected behavior
opening sawmill UI
- XXX

### Actual behaviour
crash
at com.minecolonies.coremod.client.gui.WindowHutLumberjack$1.updateElement(WindowHutLumberjack.java:122)
	at com.minecolonies.blockout.views.ScrollingListContainer.refreshElementPanes(ScrollingListContainer.java:52)
	at com.minecolonies.blockout.views.ScrollingList.refreshElementPanes(ScrollingList.java:69)
	at com.minecolonies.blockout.views.ScrollingList.setDataProvider(ScrollingList.java:61)
	at com.minecolonies.coremod.client.gui.WindowHutLumberjack.onOpened(WindowHutLumberjack.java:105)
	at com.minecolonies.blockout.Screen.func_73866_w_(Screen.java:119)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:478)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1016)
	at net.minecraftforge.fml.client.FMLClientHandler.showGuiScreen(FMLClientHandler.java:534)
	at net.minecraftforge.fml.common.FMLCommonHandler.showGuiScreen(FMLCommonHandler.java:321)
	at com.minecolonies.blockout.views.Window.open(Window.java:168)
	at com.minecolonies.coremod.colony.buildings.views.AbstractBuildingView.openGui(AbstractBuildingView.java:247)
	at com.minecolonies.coremod.blocks.AbstractBlockHut.func_180639_a(AbstractBlockHut.java:213)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:423)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1577)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2252)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2018)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1806)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

- YYY

### Steps to reproduce the problem

1. right-click sawmill chest
2. crasjh
3. ...
4. Profit

**Comment by snoopydude48** [comment]
I had this same thing happen to me on in my world with lots of time spent.  I decided to start a new world to see if it would do it again and it didn't.  All is good on the new world.

**Comment by Raycoms** [comment]
Could we have the complete log?

2018-04-04 17:16 GMT+01:00 snoopydude48 <notifications@github.com>:

**Comment by Raycoms** [comment]
Fixed
