### ISSUE TITLE
Supply Ship not being crafted

### ISSUE THREAD

**Issue by theoneandonlydonnie** [ldtteam/minecolonies#2515]
Minecolonies version
version 0.8.7582 

Expected behavior
When placing five boats, I expect the supply ship to be in the output box
Actual behaviour
I place five boats in the crafting table in the formation as stated in the wiki recipes and no supply ship shows in the output
Steps to reproduce the problem
craft five boats
place them in the crafting table
I am wanting to test the mod out so I only have Minecraft Coder Pack 9.42, Forge Mod Loader 8.0.99.99, Minecraft Forge 14.23.3.2655 and Minecolonies loaded. I tried it with and without my resource pack and the issue remains

The last post was closed without verifying that the solution worked. They said to upgrade to the latest version and immediately closed it.

The version I am posting about now is the latest version that I could find and doing so did not resolve the issue

**Comment by Asherslab** [comment]
1st. Forge version?
2nd. that version is almost 4 months old
3rd. Please calm down, he was correct. you're on an ancient version
4th. I just confirmed that it is most certainly in the most recent version

**Comment by Asherslab** [comment]
Sorry, just saw your forge version. But non-the-less you're on a very old version

**Comment by theoneandonlydonnie** [comment]
I apologize. I work with trouble tickets as well.

Is the Minecolonies or the Forge too old? If so, what are the recommended versions?

**Comment by Asherslab** [comment]
MineColonies version is too old, Where did you get it from?
Curseforge?
Alpha's are our go-to for versions sadly. the Release is extremely out-dated (Think we can get another one soon @Raycoms ?)

**Comment by theoneandonlydonnie** [comment]
Yes, from Curseforge. Where can I get the newest version?

**Comment by Asherslab** [comment]
Curseforge =D you'll want an Alpha though

**Comment by Asherslab** [comment]
newest: https://minecraft.curseforge.com/projects/minecolonies/files/2570694

**Comment by Asherslab** [comment]
we release new Alpha's almost daily, so you'll want to keep tabs on there.
We *should* release a new "realease" version soon. Just depends on how many bugs and etc we need to squish before we're comfortable doing so

**Comment by theoneandonlydonnie** [comment]
I can definitely understand that.
I just tried the newest version that was released 17 hours ago. The issue still remains.
I used creative mode to get the boats and crafting table. Still no supply ship when the boats are placed. Does it all have to be done solely in survival mode? Do I need the tool? All I did was place the five boats on the crafting table

**Comment by theoneandonlydonnie** [comment]
I also grabbed the supply ship in creative and then the game crashed.

Here is the crash report
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 6/9/18 6:37 AM
Description: Updating screen events

java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at com.minecolonies.coremod.client.gui.WindowBuildTool.confirmClicked(WindowBuildTool.java:909)
	at com.minecolonies.coremod.client.gui.WindowBuildTool$$Lambda$183/108202798.run(Unknown Source)
	at com.minecolonies.coremod.client.gui.AbstractWindowSkeleton.lambda$registerButton$0(AbstractWindowSkeleton.java:40)
	at com.minecolonies.coremod.client.gui.AbstractWindowSkeleton$$Lambda$174/1351886228.accept(Unknown Source)
	at com.minecolonies.coremod.client.gui.AbstractWindowSkeleton.onButtonClicked(AbstractWindowSkeleton.java:67)
	at com.minecolonies.blockout.controls.Button.handleClick(Button.java:95)
	at com.minecolonies.blockout.Pane.click(Pane.java:454)
	at com.minecolonies.blockout.views.View.click(View.java:153)
	at com.minecolonies.blockout.views.View.click(View.java:153)
	at com.minecolonies.blockout.Screen.func_73864_a(Screen.java:77)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at com.minecolonies.blockout.Screen.func_146274_d(Screen.java:88)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at com.minecolonies.coremod.client.gui.WindowBuildTool.confirmClicked(WindowBuildTool.java:909)
	at com.minecolonies.coremod.client.gui.WindowBuildTool$$Lambda$183/108202798.run(Unknown Source)
	at com.minecolonies.coremod.client.gui.AbstractWindowSkeleton.lambda$registerButton$0(AbstractWindowSkeleton.java:40)
	at com.minecolonies.coremod.client.gui.AbstractWindowSkeleton$$Lambda$174/1351886228.accept(Unknown Source)
	at com.minecolonies.coremod.client.gui.AbstractWindowSkeleton.onButtonClicked(AbstractWindowSkeleton.java:67)
	at com.minecolonies.blockout.controls.Button.handleClick(Button.java:95)
	at com.minecolonies.blockout.Pane.click(Pane.java:454)
	at com.minecolonies.blockout.views.View.click(View.java:153)
	at com.minecolonies.blockout.views.View.click(View.java:153)
	at com.minecolonies.blockout.Screen.func_73864_a(Screen.java:77)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at com.minecolonies.blockout.Screen.func_146274_d(Screen.java:88)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: com.minecolonies.blockout.Screen

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['thedonnie'/1687, l='MpServer', x=-55.32, y=63.00, z=233.94]]
	Chunk stats: MultiplayerChunkCache: 426, 426
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-63,64,249), Chunk: (at 1,4,9 in -4,15; contains blocks -64,0,240 to -49,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 6669 game time, 6669 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 71 total; [EntityPlayerSP['thedonnie'/1687, l='MpServer', x=-55.32, y=63.00, z=233.94], EntityZombie['Zombie'/5640, l='MpServer', x=-111.24, y=51.00, z=178.49], EntitySkeleton['Skeleton'/4621, l='MpServer', x=-89.50, y=26.00, z=244.50], EntityCreeper['Creeper'/5648, l='MpServer', x=-29.50, y=32.00, z=177.50], EntityCreeper['Creeper'/5649, l='MpServer', x=-27.50, y=32.00, z=176.50], EntityBat['Bat'/5139, l='MpServer', x=-87.90, y=14.35, z=218.93], EntityBat['Bat'/5144, l='MpServer', x=10.88, y=31.68, z=167.80], EntityZombie['Zombie'/4896, l='MpServer', x=-24.50, y=34.00, z=173.70], EntityZombie['Zombie'/4897, l='MpServer', x=-24.50, y=34.00, z=172.95], EntitySkeleton['Skeleton'/5430, l='MpServer', x=-96.50, y=18.00, z=236.50], EntityCreeper['Creeper'/5687, l='MpServer', x=-109.50, y=24.00, z=200.50], EntitySkeleton['Skeleton'/5432, l='MpServer', x=-96.68, y=18.00, z=234.54], EntityCreeper['Creeper'/5688, l='MpServer', x=-110.50, y=24.00, z=199.50], EntityZombie['Zombie'/5689, l='MpServer', x=-53.19, y=16.00, z=168.45], EntityZombie['Zombie'/3130, l='MpServer', x=2.50, y=36.00, z=170.50], EntityZombie['Zombie'/5690, l='MpServer', x=-51.50, y=16.00, z=167.50], EntityCreeper['Creeper'/5452, l='MpServer', x=-24.50, y=20.00, z=200.50], EntityCreeper['Creeper'/5453, l='MpServer', x=-27.69, y=19.00, z=198.49], EntityCreeper['Creeper'/5454, l='MpServer', x=-24.50, y=20.00, z=200.50], EntityCreeper['Creeper'/5455, l='MpServer', x=-25.50, y=20.00, z=200.50], EntitySkeleton['Skeleton'/5713, l='MpServer', x=-92.35, y=26.00, z=248.34], EntitySpider['Spider'/5714, l='MpServer', x=-91.20, y=28.00, z=242.40], EntityZombie['Zombie'/5717, l='MpServer', x=-95.39, y=27.00, z=247.18], EntityBat['Bat'/5723, l='MpServer', x=-127.29, y=59.14, z=170.51], EntityCreeper['Creeper'/5725, l='MpServer', x=-6.81, y=49.00, z=195.44], EntitySheep['Sheep'/97, l='MpServer', x=-81.19, y=68.00, z=157.34], EntityBat['Bat'/4707, l='MpServer', x=-41.27, y=27.09, z=240.66], EntityPig['Pig'/101, l='MpServer', x=-85.50, y=68.00, z=302.50], EntityPig['Pig'/102, l='MpServer', x=-85.50, y=69.00, z=303.50], EntityWitch['Witch'/5734, l='MpServer', x=-107.38, y=17.00, z=213.76], EntityPig['Pig'/103, l='MpServer', x=-86.50, y=64.00, z=300.50], EntityPig['Pig'/104, l='MpServer', x=-85.50, y=64.00, z=298.50], EntitySquid['Squid'/4726, l='MpServer', x=-47.90, y=59.30, z=176.93], EntitySpider['Spider'/4989, l='MpServer', x=-121.50, y=13.00, z=205.50], EntitySkeleton['Skeleton'/5252, l='MpServer', x=-32.50, y=23.00, z=243.50], EntityCreeper['Creeper'/5509, l='MpServer', x=-69.50, y=24.00, z=239.50], EntityZombie['Zombie'/5510, l='MpServer', x=-76.27, y=24.00, z=235.52], EntityZombie['Zombie'/5511, l='MpServer', x=-81.22, y=23.00, z=247.63], EntityCreeper['Creeper'/5003, l='MpServer', x=-16.23, y=19.00, z=189.43], EntitySkeleton['Skeleton'/5771, l='MpServer', x=-128.50, y=16.00, z=155.50], EntitySkeleton['Skeleton'/5772, l='MpServer', x=-127.50, y=16.00, z=158.50], EntityBat['Bat'/5773, l='MpServer', x=1.40, y=19.06, z=213.75], EntitySkeleton['Skeleton'/5006, l='MpServer', x=-4.79, y=22.00, z=169.63], EntityZombie['Zombie'/5523, l='MpServer', x=-97.45, y=18.00, z=261.78], EntitySquid['Squid'/4763, l='MpServer', x=-0.29, y=60.99, z=245.69], EntityCow['Cow'/157, l='MpServer', x=-3.50, y=64.00, z=286.50], EntityCow['Cow'/158, l='MpServer', x=-4.50, y=64.00, z=285.50], EntityBat['Bat'/5790, l='MpServer', x=-73.60, y=24.66, z=250.52], EntityCow['Cow'/159, l='MpServer', x=-4.50, y=64.00, z=285.50], EntitySquid['Squid'/4767, l='MpServer', x=-60.18, y=62.29, z=234.73], EntityCow['Cow'/160, l='MpServer', x=-4.50, y=64.00, z=286.50], EntitySquid['Squid'/4769, l='MpServer', x=5.51, y=52.39, z=244.69], EntitySquid['Squid'/4770, l='MpServer', x=4.28, y=53.06, z=244.38], EntitySquid['Squid'/4789, l='MpServer', x=-22.89, y=47.32, z=239.07], EntitySquid['Squid'/4790, l='MpServer', x=-21.05, y=52.48, z=249.96], EntitySquid['Squid'/4791, l='MpServer', x=-18.99, y=52.77, z=245.81], EntityCreeper['Creeper'/5305, l='MpServer', x=-86.50, y=27.00, z=242.50], EntitySkeleton['Skeleton'/5819, l='MpServer', x=-127.82, y=52.00, z=168.44], EntitySquid['Squid'/4796, l='MpServer', x=-13.55, y=50.70, z=243.00], EntitySkeleton['Skeleton'/5820, l='MpServer', x=-126.50, y=52.00, z=166.50], EntitySpider['Spider'/5822, l='MpServer', x=-126.17, y=54.00, z=170.57], EntitySquid['Squid'/4800, l='MpServer', x=-3.19, y=55.96, z=261.67], EntityCreeper['Creeper'/5578, l='MpServer', x=-114.85, y=23.00, z=215.40], EntityZombie['Zombie'/5579, l='MpServer', x=-110.50, y=25.00, z=207.50], EntityCreeper['Creeper'/5586, l='MpServer', x=-16.50, y=31.00, z=163.50], EntitySquid['Squid'/4822, l='MpServer', x=6.14, y=53.67, z=267.28], EntityCreeper['Creeper'/5852, l='MpServer', x=-111.50, y=26.00, z=278.50], EntityZombie['Zombie'/4326, l='MpServer', x=-120.53, y=23.00, z=216.72], EntitySkeleton['Skeleton'/5615, l='MpServer', x=-122.50, y=23.00, z=214.75], EntitySkeleton['Skeleton'/5627, l='MpServer', x=-104.50, y=16.00, z=196.50], EntitySkeleton['Skeleton'/5118, l='MpServer', x=-21.50, y=19.00, z=171.50]]
	Retry entities: 0 total; []
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2737)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 581335976 bytes (554 MB) / 1006632960 bytes (960 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.3.2655 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID           | Version         | Source                                     | Signature                                |
	|:------ |:------------ |:--------------- |:------------------------------------------ |:---------------------------------------- |
	| UCHIJA | minecraft    | 1.12.2          | minecraft.jar                              | None                                     |
	| UCHIJA | mcp          | 9.42            | minecraft.jar                              | None                                     |
	| UCHIJA | FML          | 8.0.99.99       | forge-1.12.2-14.23.3.2655.jar              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge        | 14.23.3.2655    | forge-1.12.2-14.23.3.2655.jar              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | minecolonies | 1.12.2-0.8.8586 | minecolonies-universal-1.12.2-0.8.8586.jar | None                                     |

	Loaded coremods (and transformers): 
	Launched Version: 1.12.2-forge1.12.2-14.23.3.2655
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 630 GL version 4.4.0 - Build 21.20.16.4526, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz

**Comment by Asherslab** [comment]
oh shoot.. you might have to "learn" the recipe? i know minecraft added a stupid recipe learning system.
Try crafting the boat first?

**Comment by theoneandonlydonnie** [comment]
I did craft the boat. I then tried to craft the supply ship. It did not allow me.  It also does not show up as a potential recipe when I have boats and the crafting table.

Also, I tried to use creative to just grab a supply camp or supply ship and the game crashes each time I place them. The crash reports resemble the one I placed in the above update

**Comment by Raycoms** [comment]
Are you on a server? Does the server have the right version?

**Comment by theoneandonlydonnie** [comment]
I am on my own server.

**Comment by Raycoms** [comment]
Its weird, some people had this problem already once, but it seemed it has
been due to an issue with forge rather than an issue with us.

2018-06-09 10:03 GMT-03:00 theoneandonlydonnie <notifications@github.com>:

**Comment by theoneandonlydonnie** [comment]
What was that solution? I have gone ahead and even re-installed my entire server using a newer version of Forge. The Forge version is 14.23.4.2707

I have been wanting to install and play with this mod for a very long time now so I apologize if I am over eager as I really want to have it.

**Comment by Raycoms** [comment]
Might also be one of these two here interfering:  Minecraft Coder Pack
9.42, Forge Mod Loader 8.0.99.99

Like, to me it seems like the mod is not loading at all on the server

2018-06-09 10:12 GMT-03:00 theoneandonlydonnie <notifications@github.com>:

**Comment by theoneandonlydonnie** [comment]
Those were loaded by Forge. All I did was to get Forge loaded up and then put the latest version of minecolonies into the mods folder at .minefract/mods.

I can see where you are coming from, though. I am not sure what to do about the Minecraft Coder Pack or Forge Mod Loader versions, though as those come from Forge itself. If you have any information, then please let me know and I will go that route.

**Comment by Raycoms** [comment]
Can you send us your startup log? of the server?

2018-06-09 10:42 GMT-03:00 theoneandonlydonnie <notifications@github.com>:

**Comment by theoneandonlydonnie** [comment]
[08:54:25 INFO]: Starting minecraft server version 1.12.2
[08:54:25 INFO]: Loading properties
[08:54:25 ERROR]: Exception handling console input
java.io.IOException: The handle is invalid
	at java.io.FileInputStream.readBytes(Native Method) ~[?:?]
	at java.io.FileInputStream.read(Unknown Source) ~[?:?]
	at java.io.BufferedInputStream.read1(Unknown Source) ~[?:?]
	at java.io.BufferedInputStream.read(Unknown Source) ~[?:?]
	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source) ~[?:?]
	at sun.nio.cs.StreamDecoder.implRead(Unknown Source) ~[?:?]
	at sun.nio.cs.StreamDecoder.read(Unknown Source) ~[?:?]
	at java.io.InputStreamReader.read(Unknown Source) ~[?:?]
	at java.io.BufferedReader.fill(Unknown Source) ~[?:?]
	at java.io.BufferedReader.readLine(Unknown Source) ~[?:?]
	at java.io.BufferedReader.readLine(Unknown Source) ~[?:?]
	at nz$2.run(SourceFile:100) [minecraft_server.1.12.2.jar:?]
[08:54:25 INFO]: Default game type: SURVIVAL
[08:54:25 INFO]: Generating keypair
[08:54:25 INFO]: Starting Minecraft server on *:25565
[08:54:25 INFO]: Using default channel type
[08:54:25 INFO]: Preparing level "world"
[08:54:26 INFO]: Loaded 488 advancements
[08:54:26 INFO]: Preparing start region for level 0
[08:54:27 INFO]: Preparing spawn area: 10%
[08:54:28 INFO]: Preparing spawn area: 16%
[08:54:29 INFO]: Preparing spawn area: 28%
[08:54:30 INFO]: Preparing spawn area: 39%
[08:54:31 INFO]: Preparing spawn area: 45%
[08:54:32 INFO]: Preparing spawn area: 53%
[08:54:33 INFO]: Preparing spawn area: 65%
[08:54:34 INFO]: Preparing spawn area: 77%
[08:54:35 INFO]: Preparing spawn area: 89%
[08:54:36 INFO]: Done (10.648s)! For help, type "help" or "?"

**Comment by Raycoms** [comment]
isn't there more to that?

But it definitely looks like minecolonies isn't loading server-side

2018-06-09 10:55 GMT-03:00 theoneandonlydonnie <notifications@github.com>:

**Comment by theoneandonlydonnie** [comment]
That is all that showed up when I started the server.

What needs to be done to get this mod to load server-side?

**Comment by Raycoms** [comment]
Do you have a correct forge server install?

2018-06-09 11:01 GMT-03:00 theoneandonlydonnie <notifications@github.com>:

**Comment by marchermans** [comment]
@theoneandonlydonnie your server is not running forge.
Please consult forge support on how to start a Forge server.

Or download an FTB Server and clear its mod folder.
