### ISSUE TITLE
CTD when first villager tries to spawn after setting down townhall

### ISSUE THREAD

**Issue by JonnaJudin** [ldtteam/minecolonies#2556]
### Minecolonies version

version minecolonies-universal-1.12.2-0.8.9540.jar

### Expected behavior

- Set down town hall, see villagers appear, keep playing minecraft

### Actual behaviour

- Set down town hall (tried with mesa and desert), wait second or two, crash to desktop

[crash-2018-06-24_13.57.58-server.txt](https://github.com/ldtteam/minecolonies/files/2130810/crash-2018-06-24_13.57.58-server.txt)

### Steps to reproduce the problem

1. Install Craft to the future modpack, v.  1.23 (or 1.22 I think it worked in 1.17 or 1.18 version with whatever was the newest minecolonies early june)

https://minecraft.curseforge.com/projects/craft-to-the-future-cott-ii/files/2575751

2. Add mod minecolonies-universal-1.12.2-0.8.9540.jar

3. Probably not relevant but what I did: (turn mobs neutral = true in epic siege mod and disable ambience mod)

4. Start game, go to creative, get wand and townhall an place them.

5. Crash

callstack:
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at com.minecolonies.coremod.entity.EntityCitizen.hashCode(EntityCitizen.java:881)
	at java.util.HashMap.hash(Unknown Source)
	at java.util.HashMap.remove(Unknown Source)
	at net.ilexiconn.llibrary.server.capability.EntityDataHandler.putQueuedData(EntityDataHandler.java:74)
	at net.ilexiconn.llibrary.server.ServerEventHandler.onFinishAttachCapabilities(ServerEventHandler.java:56)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1102_ServerEventHandler_onFinishAttachCapabilities_AttachCapabilitiesEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:658)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:628)
	at net.minecraft.entity.Entity.<init>(Entity.java:219)
	at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:163)
	at net.minecraft.entity.EntityLiving.<init>(EntityLiving.java:120)
	at net.minecraft.entity.EntityCreature.<init>(SourceFile:21)
	at net.minecraft.entity.EntityAgeable.<init>(EntityAgeable.java:27)
	at com.minecolonies.coremod.entity.AbstractEntityCitizen.<init>(AbstractEntityCitizen.java:81)
	at com.minecolonies.coremod.entity.EntityCitizen.<init>(EntityCitizen.java:154)
	at com.minecolonies.coremod.colony.managers.CitizenManager.spawnCitizen(CitizenManager.java:171)
	at com.minecolonies.coremod.colony.managers.CitizenManager.spawnCitizen(CitizenManager.java:294)
	at com.minecolonies.coremod.colony.managers.CitizenManager.onWorldTick(CitizenManager.java:443)
	at com.minecolonies.coremod.colony.Colony.onWorldTick(Colony.java:648)
	at com.minecolonies.coremod.colony.ColonyManager.lambda$onWorldTick$2(ColonyManager.java:945)
	at java.util.ArrayList.forEach(Unknown Source)
	at com.minecolonies.coremod.colony.ColonyManager.onWorldTick(ColonyManager.java:945)
	at com.minecolonies.coremod.event.FMLEventHandler.onWorldTick(FMLEventHandler.java:58)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_298_FMLEventHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)

**Comment by JonnaJudin** [comment]
I tried to find more information and noticed this:
https://github.com/iLexiconn/LLibrary/issues/83

I suppose this is the same issue, should I close this one?

**Comment by Crowfooted** [comment]
The crash log posted in that thread is reporting different things from the one in this thread, so it's probably not the same issue, no.

But I am experiencing the same crash you are, only I am running a local server so the crash was a server crash. Placing the townhall is causing the crash. No NPCs have a chance to appear before the crash happens.

Paste here: https://pastebin.com/HjyuyvRi

**Comment by Raycoms** [comment]
On which version are you?

2018-06-28 9:07 GMT-03:00 Corvid <notifications@github.com>:

**Comment by Crowfooted** [comment]
I am on MineColonies version 1.12.2-0.8.8618.

**Comment by Raycoms** [comment]
Please upgrade to the newest alpha

2018-06-28 9:42 GMT-03:00 Corvid <notifications@github.com>:

**Comment by Crowfooted** [comment]
Thanks, fixed.
