### ISSUE TITLE
Guard giving java.lang.NullPointerException: null server console spam.

### ISSUE THREAD

**Issue by QueenBonnydust** [ldtteam/minecolonies#2685]
### Minecolonies version

minecolonies-1.12.2-0.9.1-RELEASE-universal.jar

### Expected behavior

Make guard tower, employed guard will act as normal.

### Actual behaviour

Spamming server console error message, please see console log it was too long and looked terrible pasted here.

### Steps to reproduce the problem

1. Put minecolonies on a server.
2. Build a guard tower in your colony.
3. Issue begins to spam the log, changing whether guard is automatically or manually assigned, fulfilling any request and changing from knight to ranger does not solve the issue.

[Console_Log.log](https://github.com/ldtteam/minecolonies/files/2225413/Console_Log.log)

**Comment by Nightenom** [comment]
Can you try the latest alpha please?

Extracted error:
```
[19:20:23] [Server thread/WARN] [minecolonies]: Action for target com.minecolonies.coremod.entity.ai.util.AITarget@68f4548e threw an exception:
java.lang.NullPointerException: null
	at com.minecolonies.coremod.entity.ai.citizen.guard.AbstractEntityAIGuard.getTarget(AbstractEntityAIGuard.java:294) ~[AbstractEntityAIGuard.class:?]
	at com.minecolonies.coremod.entity.ai.citizen.guard.AbstractEntityAIGuard.decide(AbstractEntityAIGuard.java:231) ~[AbstractEntityAIGuard.class:?]
	at com.minecolonies.coremod.entity.ai.citizen.guard.EntityAIKnight.decide(EntityAIKnight.java:69) ~[EntityAIKnight.class:?]
	at com.minecolonies.coremod.entity.ai.util.AITarget.apply(AITarget.java:125) ~[AITarget.class:?]
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.applyTarget(AbstractAISkeleton.java:208) ~[AbstractAISkeleton.class:?]
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.checkOnTarget(AbstractAISkeleton.java:182) ~[AbstractAISkeleton.class:?]
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) [?:1.8.0_171]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359) [?:1.8.0_171]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) [?:1.8.0_171]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) [?:1.8.0_171]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) [?:1.8.0_171]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) [?:1.8.0_171]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) [?:1.8.0_171]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) [?:1.8.0_171]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:1.8.0_171]
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449) [?:1.8.0_171]
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:135) [AbstractAISkeleton.class:?]
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129) [xf.class:?]
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763) [vq.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2350) [vp.class:?]
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577) [vq.class:?]
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178) [vd.class:?]
	at com.minecolonies.coremod.entity.EntityCitizen.func_70636_d(EntityCitizen.java:550) [EntityCitizen.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170) [vp.class:?]
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) [vq.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1990) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) [oo.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1952) [amu.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1756) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Comment by QueenBonnydust** [comment]
Updated to minecolonies-1.12.2-0.9.86-ALPHA-universal.jar a couple of days ago and no longer experiencing this issue. We are however experiencing barbarians that are invisible at times, I will just attempt to replicate this issue again today and post a new issue for it.
