### ISSUE TITLE
Build tool bug

### ISSUE THREAD

**Issue by arepsz** [ldtteam/minecolonies#2776]
### Minecolonies version

version 1.10.2-0.8.4063  installed in Sprout modpack

### Expected behavior

- Able to do anything with build tool

### Actual behaviour

- Can't select the building, the look of it, or anything else, and when I click on the green tick, the game automatically crashes

### Steps to reproduce the problem

1. Open Sprout
2. Open any world
3. Click with the Build tool, then click on the green tick
4. Instant  **crash**

**Comment by marchermans** [comment]
Crashlogs please.

**Comment by arepsz** [comment]
[crash-2018-08-12_12.55.37-client.txt](https://github.com/ldtteam/minecolonies/files/2280909/crash-2018-08-12_12.55.37-client.txt)

**Comment by arepsz** [comment]
I didn't mentoin it but i reinstalled the pack 2 days ago, so this is they only crash log avaible since then

**Comment by Nightenom** [comment]
Version minecolonies-universal-1.10.2-0.8.4063.jar, 1.10 is no longer in development, please try latest version for 1.10 on your own or switch to 1.12.2 to get latest features
Exported:
```

java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at com.minecolonies.coremod.client.gui.WindowBuildTool.confirmClicked(WindowBuildTool.java:802)
	at com.minecolonies.coremod.client.gui.WindowBuildTool$$Lambda$2054/369853758.run(Unknown Source)
	at com.minecolonies.coremod.client.gui.AbstractWindowSkeleton.lambda$registerButton$0(AbstractWindowSkeleton.java:40)
	at com.minecolonies.coremod.client.gui.AbstractWindowSkeleton$$Lambda$2045/1272044226.accept(Unknown Source)
	at com.minecolonies.coremod.client.gui.AbstractWindowSkeleton.onButtonClicked(AbstractWindowSkeleton.java:67)
	at com.minecolonies.blockout.controls.Button.handleClick(Button.java:95)
	at com.minecolonies.blockout.Pane.click(Pane.java:452)
	at com.minecolonies.blockout.views.View.click(View.java:124)
	at com.minecolonies.blockout.views.View.click(View.java:124)
	at com.minecolonies.blockout.Screen.func_73864_a(Screen.java:70)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
