### ISSUE TITLE
Miner stuck with long timeouts

### ISSUE THREAD

**Issue by martinmeneval** [ldtteam/minecolonies#2831]
### Minecolonies version

version 1.12.2-0.8.9646 
Sorry, don't know how old it is, maybe the issue is on my side and/or has been fixed, but it still is the one in the current version of the All the Mods 3 pack (5.9.8d)

### Expected behavior

- Miner does his job, and doesn't stand around despite not being hungry or having any requests

### Actual behaviour

- Miner stays at his bed, or just stands around not doing anything.

### Steps to reproduce the problem

1. Have a level 3 miner who dug all the way to bedrock 
2. Ask him to do literally anything
3. ...
4. Profit

At the bottom is a log of the error, showing a timeout of 819200 seconds, or around 9 and a half days. I took the liberty of removing the timestamp from every line, it all happened at [2018-08-30 11:25:25]

It's not the first time it happens, because it's been a few days that I've been trying to get him to mine at various heights in his mineshaft. Restarting the server or running `/mc colonies rsresetall` doesn't really fix it. I've had various problems with the colony in general, like having the builder non-stop digging down instead of building a house, or having the deliveryman not deliver anything, but this is the first one I can't wrap my head around...
Thank you very much for your help, and your work on this mod

```log
[Server thread/WARN] [minecolonies]: Action for target com.minecolonies.coremod.entity.ai.util.AITarget@49168bfc threw an exception:
java.lang.NullPointerException: null
at com.minecolonies.coremod.entity.ai.citizen.miner.EntityAIStructureMiner.searchANodeToMine(EntityAIStructureMiner.java:585) ~[EntityAIStructureMiner.class:?]
at com.minecolonies.coremod.entity.ai.citizen.miner.EntityAIStructureMiner.executeNodeMining(EntityAIStructureMiner.java:545) ~[EntityAIStructureMiner.class:?]
at com.minecolonies.coremod.entity.ai.util.AITarget.apply(AITarget.java:125) ~[AITarget.class:?]
at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.applyTarget(AbstractAISkeleton.java:208) ~[AbstractAISkeleton.class:?]
at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.checkOnTarget(AbstractAISkeleton.java:182) ~[AbstractAISkeleton.class:?]
at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) [?:1.8.0_181]
at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359) [?:1.8.0_181]
at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) [?:1.8.0_181]
at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) [?:1.8.0_181]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) [?:1.8.0_181]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) [?:1.8.0_181]
at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) [?:1.8.0_181]
at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) [?:1.8.0_181]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:1.8.0_181]
at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449) [?:1.8.0_181]
at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:135) [AbstractAISkeleton.class:?]
at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129) [xf.class:?]
at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763) [vq.class:?]
at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2350) [vp.class:?]
at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577) [vq.class:?]
at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178) [vd.class:?]
at com.minecolonies.coremod.entity.EntityCitizen.func_70636_d(EntityCitizen.java:518) [EntityCitizen.class:?]
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170) [vp.class:?]
at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) [vq.class:?]
at net.minecraft.world.World.func_72866_a(World.java:1990) [amu.class:?]
at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) [oo.class:?]
at net.minecraft.world.World.func_72870_g(World.java:1952) [amu.class:?]
at net.minecraft.world.World.func_72939_s(World.java:1756) [amu.class:?]
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) [oo.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[Server thread/ERROR] [minecolonies]: Pausing Entity Leo V. Greenway (com.minecolonies.coremod.job.Miner) at BlockPos{x=-261, y=69, z=619} for 819200 Seconds because of error:
[Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:271]: java.lang.NullPointerException
[Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:271]: at com.minecolonies.coremod.entity.ai.citizen.miner.EntityAIStructureMiner.searchANodeToMine(EntityAIStructureMiner.java:585)
[Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:271]: at com.minecolonies.coremod.entity.ai.citizen.miner.EntityAIStructureMiner.executeNodeMining(EntityAIStructureMiner.java:545)
[Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:271]: at com.minecolonies.coremod.entity.ai.util.AITarget.apply(AITarget.java:125)
[Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:271]: at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.applyTarget(AbstractAISkeleton.java:208)
[Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:271]: at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.checkOnTarget(AbstractAISkeleton.java:182)
[Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:271]: at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
[Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:271]: at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
[Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:271]: at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
[Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:271]: at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
[Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:271]: at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
[Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:271]: at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
[Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:271]: at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
[Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:271]: at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
[Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:271]: at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:271]: at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
[Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:271]: at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:135)
[Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:271]: at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
[Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:271]: at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
[Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:271]: at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2350)
[Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:271]: at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
[Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:271]: at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
[Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:271]: at com.minecolonies.coremod.entity.EntityCitizen.func_70636_d(EntityCitizen.java:518)
[Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:271]: at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
[Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:271]: at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
[Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:271]: at net.minecraft.world.World.func_72866_a(World.java:1990)
[Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:271]: at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
[Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:271]: at net.minecraft.world.World.func_72870_g(World.java:1952)
[Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:271]: at net.minecraft.world.World.func_72939_s(World.java:1756)
[Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:271]: at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
[Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:271]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
[Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:271]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
[Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:271]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:271]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[Server thread/INFO] [STDERR]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:271]: at java.lang.Thread.run(Thread.java:748)
```

**Comment by Raycoms** [comment]
Please update to the newest version, ATM3 are too lazy to update our mod
for months and complain it has bugs.

Am Do., 30. Aug. 2018 um 12:32 Uhr schrieb ONE-Martin <
notifications@github.com>:

**Comment by martinmeneval** [comment]
Thank you for your answer. I think I'll end up doing that. It'll be a bit hard convincing the others users on my little server to do the same, but I'm the admin.
Best regards and good luck
