### ISSUE TITLE
Entire town stuck in beds

### ISSUE THREAD

**Issue by asphaltbuffet** [ldtteam/minecolonies#2895]
### Minecolonies version

Version: 1.12.2-0.9.86-ALPHA-universal

### Expected behavior

Townspeople do their jobs and get out of beds during the day.

### Actual behaviour
Barbarians attacked and unknown if it created this issue. Two townspeople were killed. Next day, all townspeople still laying in beds. If I walk near them, they play normal audio. Can interact with them as normal. Firing them from home does not prevent them from staying in bed. If i break bed, stay laying down hovering in air.

Anyone not assigned to a house is stuck in townhall. Firing and hiring jobs does nothing if in a house. If they are in town hall, they will walk to and from front door of townhall ad nauseum.

Recalling all citizens to town hall does nothing but provides the following in the logs:

```
[20:58:38] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:torch, properties=[facing]}
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_172]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_172]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:torch, properties=[facing]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201) ~[awu$a.class:?]
	at net.minecraft.block.BlockBed.func_176468_a(BlockBed.java:234) ~[aou.class:?]
	at com.minecolonies.coremod.entity.citizenhandlers.CitizenSleepHandler.onWakeUp(CitizenSleepHandler.java:159) ~[CitizenSleepHandler.class:?]
	at com.minecolonies.coremod.util.TeleportHelper.teleportCitizen(TeleportHelper.java:38) ~[TeleportHelper.class:?]
	at com.minecolonies.coremod.network.messages.RecallTownhallMessage.messageOnServerThread(RecallTownhallMessage.java:87) ~[RecallTownhallMessage.class:?]
	at com.minecolonies.coremod.network.messages.RecallTownhallMessage.messageOnServerThread(RecallTownhallMessage.java:25) ~[RecallTownhallMessage.class:?]
	at com.minecolonies.coremod.network.messages.AbstractMessage.lambda$onMessage$0(AbstractMessage.java:27) ~[AbstractMessage.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_172]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_172]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
```

### Steps to reproduce the problem

Unknown what causes this.

**Comment by blaster56745** [comment]
did you kill all the barbarians?
im having a similar issue but the barbarians arnt even loading in for me, so i cant do anything about it
but yeah, killing barbarians is supposed to do it

**Comment by PoroUsedSnax** [comment]
Please try updating and see if this continues to happen, .86 is roughly a month and a half old and we update at least every couple of days, current is .133, if it can be reproduced feel free to re-open this

**Comment by Raycoms** [comment]
Please go to a newer version, it's fixed there

Am Mi., 19. Sep. 2018 um 22:13 Uhr schrieb Ben Lechlitner <
notifications@github.com>:

**Comment by asphaltbuffet** [comment]
UPDATE: Resolved, I edited the colony1.dat file to change a colonist to not sleeping (he seemed to be stuck.

~~So, I updated, and now it hard crashes server when I log in. Looks like there's a problem with a citizen. Is there a way to remove him and let rest of colony just mourn and move on?~~

~~[crash-2018-09-19_23.04.56-server.txt](https://github.com/ldtteam/minecolonies/files/2399468/crash-2018-09-19_23.04.56-server.txt)~~
