### ISSUE TITLE
Game crashes whenever I load up my world after placing my Town Hall

### ISSUE THREAD

**Issue by BugmanBugman** [ldtteam/minecolonies#2974]
---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 2018-10-14 13:36:30 CDT
Description: Exception in server tick loop

java.lang.IllegalArgumentException: Already a colony registered to id=1, colony=Velocihater's Colony, not changing to colony=Velocihater's Colony
    at com.minecolonies.coremod.colony.ColonyList.add(ColonyList.java:94)
    at com.minecolonies.coremod.colony.IColonyManagerCapability$Impl.addColony(IColonyManagerCapability.java:121)
    at com.minecolonies.coremod.colony.ColonyManager.readFromNBT(ColonyManager.java:764)
    at com.minecolonies.coremod.colony.ColonyManager.onWorldLoad(ColonyManager.java:844)
    at com.minecolonies.coremod.event.EventHandler.onWorldLoad(EventHandler.java:612)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_626_EventHandler_onWorldLoad_Load.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.optifine.reflect.Reflector.call(Reflector.java:961)
    at net.optifine.reflect.Reflector.postForgeBusEvent(Reflector.java:1188)
    at net.optifine.reflect.Reflector.postForgeBusEvent(Reflector.java:1174)
    at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:113)
    at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:209)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Unknown Source)

**Comment by Nightenom** [comment]
Rename colony1.dat in your world folder to colony1.dat.backup
