### ISSUE TITLE
Builder Refuses to Build the Guard Tower, Little Tiles Conflict

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#3067]
### Forge Version
Version: 14.23.5.2772-1.12.2
### Little Tiles Version
Version: 1.5.0-pre122
### Creative Core Version
Version: 1.9.35
### Minecolonies Version
Version: 0.10.43-Alpha

### Expected behavior
- I expected to see the builder to start building the guard tower.

### Actual behaviour
- The builder instead stood in one spot and did nothing. The guard tower seems to be the only building the builder wouldn't build. All the guard tower variants seem to be afftected, although I only tested the wooden, medieval oak, and the sandstone guard tower types. The was an error in the logs that seems to be related to the Little Tiles Mod, although there were no Little Tiles blocks in the spot the builder was supposed to build.

- **Error Log** (This repeats until the build is canceled):
`
[08:37:20] [pool-13-thread-1/WARN]: Pathfinding Exception
java.lang.NullPointerException: null
	at com.creativemd.littletiles.common.blocks.BlockTile.isLadder(BlockTile.java:280) ~[BlockTile.class:?]
	at com.minecolonies.coremod.entity.pathfinding.AbstractPathJob.isLadder(AbstractPathJob.java:1015) ~[AbstractPathJob.class:?]
	at com.minecolonies.coremod.entity.pathfinding.AbstractPathJob.isLadder(AbstractPathJob.java:1020) ~[AbstractPathJob.class:?]
	at com.minecolonies.coremod.entity.pathfinding.AbstractPathJob.onLadderGoingDown(AbstractPathJob.java:510) ~[AbstractPathJob.class:?]
	at com.minecolonies.coremod.entity.pathfinding.AbstractPathJob.walkCurrentNode(AbstractPathJob.java:478) ~[AbstractPathJob.class:?]
	at com.minecolonies.coremod.entity.pathfinding.AbstractPathJob.search(AbstractPathJob.java:424) ~[AbstractPathJob.class:?]
	at com.minecolonies.coremod.entity.pathfinding.AbstractPathJob.call(AbstractPathJob.java:364) ~[AbstractPathJob.class:?]
	at com.minecolonies.coremod.entity.pathfinding.AbstractPathJob.call(AbstractPathJob.java:33) ~[AbstractPathJob.class:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
`

### Steps to reproduce the problem

1.  Place a guard tower
2.  Click the build buttons
3.  Provide the builder with all materials
4. ... Profit, and the builder doesn't do anything.

**Comment by Raycoms** [comment]
Can you please report this to the Littletiles mod?

Our worker is just calling the isLadder function of their block which crashes.

com.creativemd.littletiles.common.blocks.BlockTile.isLadder(BlockTile.java:280)

Might be a compatibility issue with pathfinding and their block.
