### ISSUE TITLE
Exception when the Lumberjack tries to chop down a Dynamic Tree

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#3189]
### Minecolonies Version

Version: v0.10.87-BETA
### Dynanic Trees Version

Version: v0.9.1d

### Expected behavior

-  For the lumberjack to cut down and plant dynamic trees.

### Actual behaviour

-  When the lumberjack tries to cut down a tree from dynamic trees, an exception is thrown in the log and the tree isn't cut down. The builder is then paused.

[Exception Log](https://gist.github.com/WenXin20/9440fbc9224932f90c0174fcfffca576)

### Steps to reproduce the problem

1.  Plant dynamic trees
2.  Wait for the lumberjack to try to chop it down
3. Check the Minecraft logs
4. ... Profit

**Comment by someaddons** [comment]
should be working in the current version

**Comment by WenXin20** [comment]
I had the same thing happened again with Minecolonies v0.10.304-Alpha. I also have Dynamic Trees for BOP, Traverse, and Climatic Biomes. The lumberjack seems to be trying to plant a Spruce seed.
```
[16:52:03] [Server thread/ERROR]: Pausing Entity Alexander X. Good (com.minecolonies.coremod.job.Lumberjack) at BlockPos{x=-1419, y=64, z=-1044} for 12800 Seconds because of error:
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: java.lang.ClassCastException: com.ferreusveritas.dynamictrees.items.Seed cannot be cast to net.minecraft.item.ItemBlock
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at com.minecolonies.coremod.entity.ai.citizen.lumberjack.EntityAIWorkLumberjack.plantSapling(EntityAIWorkLumberjack.java:593)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at com.minecolonies.coremod.entity.ai.citizen.lumberjack.EntityAIWorkLumberjack.plantSapling(EntityAIWorkLumberjack.java:514)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at com.minecolonies.coremod.entity.ai.citizen.lumberjack.EntityAIWorkLumberjack.chopTree(EntityAIWorkLumberjack.java:389)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at com.minecolonies.coremod.entity.ai.citizen.lumberjack.EntityAIWorkLumberjack.chopWood(EntityAIWorkLumberjack.java:353)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at com.minecolonies.coremod.entity.ai.citizen.lumberjack.EntityAIWorkLumberjack$$Lambda$4909/1876054845.get(Unknown Source)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at com.minecolonies.coremod.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:77)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at com.minecolonies.coremod.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:148)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at com.minecolonies.coremod.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:131)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at com.minecolonies.coremod.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:80)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at com.minecolonies.coremod.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine$$Lambda$5103/1420683285.test(Unknown Source)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at com.minecolonies.coremod.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:62)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.updateTask(AbstractAISkeleton.java:150)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at net.minecraft.entity.ai.EntityAITasks.onUpdateTasks(SourceFile:129)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at net.minecraft.entity.EntityLiving.updateEntityActionState(EntityLiving.java:888)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at net.minecraft.entity.EntityLivingBase.onLivingUpdate(EntityLivingBase.java:2359)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at net.minecraft.entity.EntityLiving.onLivingUpdate(EntityLiving.java:678)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at net.minecraft.entity.EntityAgeable.onLivingUpdate(EntityAgeable.java:178)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at com.minecolonies.coremod.entity.EntityCitizen.onLivingUpdate(EntityCitizen.java:597)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2179)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:377)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1993)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at net.minecraft.world.World.updateEntity(World.java:1955)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at net.minecraft.world.World.redirect$updateEntity$zci000(World.java:5118)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at net.minecraft.world.World.updateEntities(World.java:1759)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[16:52:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:332]: 	at java.lang.Thread.run(Thread.java:745)
```
