### ISSUE TITLE
[BUG] Builder stopped building

### ISSUE THREAD

**Issue by nick-johnson** [ldtteam/minecolonies#3281]
Error showed up in server log and builder no longer builds, but still returns home at night.

minecolonies-1.12.2-0.10.137-ALPHA-universal

15.01 13:01:32 [Server] Server thread/INFO [minecraft/DedicatedServer]: [fujcycle13: Set the time to 0] 15.01 13:02:59 [Server] Server thread/WARN [minecolonies]: Statemachine for transition com.minecolonies.coremod.entity.ai.statemachine.AITarget@75c6da5b threw an exception: 15.01 13:02:59 [Server] INFO java.lang.NullPointerException: null 15.01 13:02:59 [Server] INFO at com.minecolonies.coremod.entity.ai.citizen.builder.EntityAIStructureBuilder.pickUpMaterial(EntityAIStructureBuilder.java:152) ~[EntityAIStructureBuilder.class:?] 15.01 13:02:59 [Server] INFO at com.minecolonies.coremod.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:77) ~[BasicTransition.class:?] 15.01 13:02:59 [Server] INFO at com.minecolonies.coremod.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:148) ~[BasicStateMachine.class:?] 15.01 13:02:59 [Server] INFO at com.minecolonies.coremod.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:131) ~[BasicStateMachine.class:?] 15.01 13:02:59 [Server] INFO at com.minecolonies.coremod.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:72) ~[TickRateStateMachine.class:?] 15.01 13:02:59 [Server] INFO at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) [?:1.8.0_191] 15.01 13:02:59 [Server] INFO at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359) [?:1.8.0_191] 15.01 13:02:59 [Server] INFO at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) [?:1.8.0_191] 15.01 13:02:59 [Server] INFO at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) [?:1.8.0_191] 15.01 13:02:59 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) [?:1.8.0_191] 15.01 13:02:59 [Server] INFO at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) [?:1.8.0_191] 15.01 13:02:59 [Server] INFO at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) [?:1.8.0_191] 15.01 13:02:59 [Server] INFO at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) [?:1.8.0_191] 15.01 13:02:59 [Server] INFO at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:1.8.0_191] 15.01 13:02:59 [Server] INFO at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449) [?:1.8.0_191] 15.01 13:02:59 [Server] INFO at com.minecolonies.coremod.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:54) [TickRateStateMachine.class:?] 15.01 13:02:59 [Server] INFO at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:150) [AbstractAISkeleton.class:?] 15.01 13:02:59 [Server] INFO at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129) [xf.class:?] 15.01 13:02:59 [Server] INFO at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763) [vq.class:?] 15.01 13:02:59 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359) [vp.class:?] 15.01 13:02:59 [Server] INFO at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577) [vq.class:?] 15.01 13:02:59 [Server] INFO at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178) [vd.class:?] 15.01 13:02:59 [Server] INFO at com.minecolonies.coremod.entity.EntityCitizen.func_70636_d(EntityCitizen.java:572) [EntityCitizen.class:?] 15.01 13:02:59 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179) [vp.class:?] 15.01 13:02:59 [Server] INFO at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) [vq.class:?] 15.01 13:02:59 [Server] INFO at net.minecraft.world.World.func_72866_a(World.java:1993) [amu.class:?] 15.01 13:02:59 [Server] INFO at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) [oo.class:?] 15.01 13:02:59 [Server] INFO at net.minecraft.world.World.func_72870_g(World.java:1955) [amu.class:?]

**Comment by Raghalin** [comment]
I also got this.  Using minecolonies-1.12.2-0.10.109-RELEASE-universal.jar
Builder built builders hut / town hall / deliveryman hut / started warehouse.
2 different npc used as builders just stand at the builders hut with a chest in hand but no qued item.  
[debug.log](https://github.com/ldtteam/minecolonies/files/2765249/debug.log)
[latest.log](https://github.com/ldtteam/minecolonies/files/2765250/latest.log)

**Comment by SulpherStaer** [comment]
I've noticed the builder stopping more often too in the latest alpha build. Supplying all building materials and then restarting seems to fix it. I think it has to do with the new tick implementation, and that it hampers communication to the request system. My builder stopped working when he needed more fences, and the wood crafter never got the request to make em.

**Comment by Raycoms** [comment]
I fixed the crash above.
I will check th ereport of @sylcai as well.

**Comment by Raycoms** [comment]
The tick implementation should not matter in this case, but I can investigate it

**Comment by SulpherStaer** [comment]
Nah - don't spent effort to investigate this random event. I can't replicate it solidly myself. I'll just wait for the patch for this crash-fix, and it might have fixed the builders themselves too.

edit: Found it, the builders don't know how to destroy / replace double tall grass anymore.
The mod Desire Paths increases their growth in my world - so I ran into this issue quicker,

**Comment by Raycoms** [comment]
he doesn't replace/destroy double grass?

**Comment by Raycoms** [comment]
Is there any log output to this?

**Comment by SulpherStaer** [comment]
How do I get that? Because he just stands there and says nothing. And when I destroy the double tall grass, he continues upgrading the building, till he gets to another double tallgrass.

**Comment by Raycoms** [comment]
latest.log in your log folder

Am Do., 17. Jan. 2019 um 16:09 Uhr schrieb Silvester <
notifications@github.com>:

**Comment by SulpherStaer** [comment]
There's nothing in the log there, also, the builder completed the build without stopping this time... As I said, I can't reliably recreate the issue. I think it is a very spesific case when a fence post needs to go where there's a double tall grass. I'll see if I can find a building that I want build in my colony that has a fence post at ground level.

```[19:29:20] [Client thread/INFO]: DimensionInfo{id=0, name=overworld, seaLevel=63, cloudHeight=128, skyHeight=256, haze=true, aurora=true, weather=true, fog=true}
[19:29:31] [Server thread/INFO]: [sylcai] The world has just loaded.
[19:29:31] [Client thread/INFO]: [CHAT] [sylcai] The world has just loaded.
[19:29:56] [Server thread/INFO]: [sylcai] I will now build a baracks tower, that is surrounded by double tall grass.
[19:29:56] [Client thread/INFO]: [CHAT] [sylcai] I will now build a baracks tower, that is surrounded by double tall grass.
[19:30:01] [Client thread/INFO]: isCorrectMD5: md5:7AA0E0D2ED75D789FBBFEC92CD4D49E1 other:7AA0E0D2ED75D789FBBFEC92CD4D49E1
[19:30:01] [Client thread/WARN]: Skipping BlockEntity with id minecraft:minecolonies.colonybuilding
[19:30:01] [Client thread/WARN]: Skipping BlockEntity with id minecraft:minecolonies.colonybuilding
[19:30:01] [Client thread/INFO]: isCorrectMD5: md5:7AA0E0D2ED75D789FBBFEC92CD4D49E1 other:7AA0E0D2ED75D789FBBFEC92CD4D49E1
[19:30:01] [Client thread/WARN]: Skipping BlockEntity with id minecraft:minecolonies.colonybuilding
[19:30:01] [Client thread/WARN]: Skipping BlockEntity with id minecraft:minecolonies.colonybuilding
[19:30:01] [Server thread/INFO]: Saving and pausing game...
[19:30:01] [Server thread/INFO]: Saving chunks for level '6283185307179586476'/overworld
[19:30:04] [Server thread/INFO]: WorkOrderBuild at location BlockPos{x=-316, y=69, z=237} is using schematics/Medieval Oak/BarracksTower1 instead of schematics/Medieval Oak/BarracksTower1
[19:30:04] [Client thread/INFO]: [CHAT] Build Request Created!
[19:30:04] [Server thread/WARN]: Skipping BlockEntity with id minecraft:minecolonies.colonybuilding
[19:30:05] [Client thread/INFO]: [CHAT] Builder Jonathan Bathurst (WORKING)[START_WORKING]: Started building schematics/Medieval Oak/BarracksTower1
[19:31:02] [Client thread/INFO]: [CHAT] Builder Jonathan Bathurst (WORKING)[INVENTORY_FULL]: Please make space in my building chest. I am not able to dump my inventory.
[19:31:42] [Client thread/WARN]: Received passengers for unknown entity
[19:32:06] [Client thread/INFO]: [CHAT] Builder Jonathan Bathurst (WORKING)[INVENTORY_FULL]: Please make space in my building chest. I am not able to dump my inventory.
[19:32:18] [Server thread/INFO]: [sylcai: Cleared the inventory of sylcai, removing 322 items]
[19:32:18] [Client thread/INFO]: [CHAT] Cleared the inventory of sylcai, removing 322 items
[19:32:19] [Server thread/INFO]: [sylcai: Set the time to 0]
[19:32:19] [Client thread/INFO]: [CHAT] Set the time to 0
[19:34:54] [Server thread/INFO]: WorkOrderBuild at location BlockPos{x=-316, y=69, z=237} is using schematics/Medieval Oak/BarracksTower1 instead of schematics/Medieval Oak/BarracksTower1
[19:34:54] [Server thread/WARN]: Skipping BlockEntity with id minecraft:minecolonies.colonybuilding
[19:34:54] [Client thread/INFO]: [CHAT] Builder Jonathan Bathurst (WORKING)[COMPLETE_BUILD]: Finished building schematics/Medieval Oak/BarracksTower1
[19:35:11] [Server thread/INFO]: Saving and pausing game...
[19:35:12] [Server thread/INFO]: Saving chunks for level '6283185307179586476'/overworld
[19:35:13] [Server thread/INFO]: Stopping server
[19:35:13] [Server thread/INFO]: Saving players
[19:35:13] [Server thread/INFO]: sylcai lost connection: Disconnected
[19:35:13] [Server thread/INFO]: sylcai left the game
[19:35:13] [Server thread/INFO]: Stopping singleplayer server as player logged out
[19:35:13] [Server thread/INFO]: Saving worlds
[19:35:13] [Server thread/INFO]: Saving chunks for level '6283185307179586476'/overworld
[19:35:14] [Server thread/INFO]: Unloading dimension 0```

**Comment by SulpherStaer** [comment]
Got a log where the builder appeared stuck, and indeed the log shows that something is going on.
[latest.log](https://github.com/ldtteam/minecolonies/files/2770506/latest.log)
```[com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:331]: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=half, clazz=class net.minecraft.block.BlockDoublePlant$EnumBlockHalf, values=[upper, lower]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}```

And as I thought, it is because of the double plant.

**Comment by Raycoms** [comment]
fixed this

**Comment by JPowerX2** [comment]
I am having the same issue with trying to upgrade to a lvl 2 swine herder Medieval Oak Style. There is no double grass anywhere near the site though. The builder wont even be assigned by the townhall.
