### ISSUE TITLE
Crash when Selecting Medieval Spruce Warehouse

### ISSUE THREAD

**Issue by raistlain** [ldtteam/minecolonies#3308]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.150-ALPHA-universal.jar and structurize-1.12.2-0.10.44-ALPHA.jar

### Expected behavior
Display Medieval Spruce Warehouse correctly

### Actual behaviour
Delay when selecting Medieval Spruce then crashes.

### Steps to reproduce the problem

1. Click with building tool
2. Select Warehouse
3. Switch to Medieval Spruce
4. Crash

**Comment by lunadragnstar** [comment]
What level is it on when you try to view it?

**Comment by lunadragnstar** [comment]
I was able to open and view it with 150, with the official mod pack, So it isn't a schematics issue

**Comment by Raycoms** [comment]
Can you send us the log?



On Jan 28, 2019 1:53 AM, "lunadragnstar" <notifications@github.com> wrote:

I was able to open and view it with 150, with the official mod pack, So it
isn't a schematics issue

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ldtteam/minecolonies/issues/3308#issuecomment-457991797>,
or mute the thread

**Comment by jollejonas** [comment]
I've had some crashes too, when i tried to open the infrastructure tabs.
Here is the crashlog
[crash-2019-01-28_13.10.25-client.txt](https://github.com/ldtteam/minecolonies/files/2802874/crash-2019-01-28_13.10.25-client.txt)

**Comment by raistlain** [comment]
[2019-01-27-4.log](https://github.com/ldtteam/minecolonies/files/2805320/2019-01-27-4.log)

Seems to be an issue with structurize: 

```[21:48:14] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Updating screen events
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1772) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at com.structurize.structures.blueprints.v1.BlueprintUtil.toTemplate(BlueprintUtil.java:466) ~[BlueprintUtil.class:?]
	at com.structurize.structures.helpers.Structure.<init>(Structure.java:145) ~[Structure.class:?]
	at com.structurize.coremod.client.gui.WindowBuildTool.changeSchematic(WindowBuildTool.java:789) ~[WindowBuildTool.class:?]
	at com.structurize.coremod.client.gui.WindowBuildTool.onDropDownListChanged(WindowBuildTool.java:643) ~[WindowBuildTool.class:?]
	at com.structurize.coremod.client.gui.WindowBuildTool$$Lambda$4144/190106605.accept(Unknown Source) ~[?:?]
	at com.structurize.blockout.views.DropDownList.setSelectedIndex(DropDownList.java:202) ~[DropDownList.class:?]
	at com.structurize.coremod.client.gui.WindowBuildTool.updateSchematics(WindowBuildTool.java:610) ~[WindowBuildTool.class:?]
	at com.structurize.coremod.client.gui.WindowBuildTool.onDropDownListChanged(WindowBuildTool.java:639) ~[WindowBuildTool.class:?]
	at com.structurize.coremod.client.gui.WindowBuildTool$$Lambda$4141/1323144675.accept(Unknown Source) ~[?:?]
	at com.structurize.blockout.views.DropDownList.setSelectedIndex(DropDownList.java:202) ~[DropDownList.class:?]
	at com.structurize.coremod.client.gui.WindowBuildTool.updateStyles(WindowBuildTool.java:535) ~[WindowBuildTool.class:?]
	at com.structurize.coremod.client.gui.WindowBuildTool.onDropDownListChanged(WindowBuildTool.java:635) ~[WindowBuildTool.class:?]
	at com.structurize.coremod.client.gui.WindowBuildTool$$Lambda$4138/9387624.accept(Unknown Source) ~[?:?]
	at com.structurize.blockout.views.DropDownList.setSelectedIndex(DropDownList.java:202) ~[DropDownList.class:?]
	at com.structurize.blockout.views.DropDownList.onButtonClickedFromList(DropDownList.java:155) ~[DropDownList.class:?]
	at com.structurize.blockout.views.DropDownList.onButtonClicked(DropDownList.java:122) ~[DropDownList.class:?]
	at com.structurize.blockout.controls.Button.handleClick(Button.java:95) ~[Button.class:?]
	at com.structurize.blockout.Pane.click(Pane.java:454) ~[Pane.class:?]
	at com.structurize.blockout.views.View.click(View.java:153) ~[View.class:?]
	at com.structurize.blockout.views.View.click(View.java:153) ~[View.class:?]
	at com.structurize.blockout.views.ScrollingContainer.click(ScrollingContainer.java:72) ~[ScrollingContainer.class:?]
	at com.structurize.blockout.views.View.click(View.java:153) ~[View.class:?]
	at com.structurize.blockout.views.OverlayView.click(OverlayView.java:42) ~[OverlayView.class:?]
	at com.structurize.blockout.views.View.click(View.java:153) ~[View.class:?]
	at com.structurize.blockout.Screen.func_73864_a(Screen.java:77) ~[Screen.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533) ~[blk.class:?]
	at com.structurize.blockout.Screen.func_146274_d(Screen.java:88) ~[Screen.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501) ~[blk.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759) ~[bib.class:?]
	... 9 more
[21:48:15] [Client thread/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----```

**Comment by raistlain** [comment]
Was able to correct the issue by deleting the structurize schematics folder and allowing only the jar blueprints to be used. Seems like the .nbt schematics are not always liked once upgrading to the new structurize

**Comment by Nightenom** [comment]
Looking into the code, nbt shouldn't be loaded through blueprints if the extension is correct
