### ISSUE TITLE
Log spam of NBT Tag being too big

### ISSUE THREAD

**Issue by Fatmice** [ldtteam/minecolonies#3365]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.154-BETA-universal

### Expected behavior

- A lot of log spam about NBT Tag being too big.

### Actual behaviour

- [19:49:00] [main/FATAL] [minecraft/Minecraft]: Error executing task
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Tried to read NBT tag that was too big; tried to allocate: 2097158bytes where max allowed: 2097152
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_201]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.util.Util.func_181617_a(Util.java:48) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1087) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: Tried to read NBT tag that was too big; tried to allocate: 2097158bytes where max allowed: 2097152
	at net.minecraft.nbt.NBTSizeTracker.func_152450_a(NBTSizeTracker.java:25) ~[gh.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:57) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:496) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:58) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:496) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:58) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:496) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:58) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:496) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:58) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagList.func_152446_a(NBTTagList.java:63) ~[ge.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:496) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:58) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:496) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:58) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:496) ~[fy.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:58) ~[fy.class:?]
	at net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:133) ~[gi.class:?]
	at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:88) ~[gi.class:?]
	at net.minecraft.network.PacketBuffer.func_150793_b(PacketBuffer.java:315) ~[gy.class:?]
	at net.minecraftforge.fml.common.network.ByteBufUtils.readTag(ByteBufUtils.java:227) ~[ByteBufUtils.class:?]
	at com.minecolonies.coremod.colony.ColonyView.handleColonyViewMessage(ColonyView.java:520) ~[ColonyView.class:?]
	at com.minecolonies.coremod.colony.ColonyManager.handleColonyViewMessage(ColonyManager.java:926) ~[ColonyManager.class:?]
	at com.minecolonies.coremod.network.messages.ColonyViewMessage.messageOnClientThread(ColonyViewMessage.java:66) ~[ColonyViewMessage.class:?]
	at com.minecolonies.coremod.network.messages.ColonyViewMessage.messageOnClientThread(ColonyViewMessage.java:16) ~[ColonyViewMessage.class:?]
	at com.minecolonies.coremod.network.messages.AbstractMessage.lambda$onMessage$1(AbstractMessage.java:31) ~[AbstractMessage.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_201]
	at net.minecraft.util.Util.func_181617_a(Util.java:47) ~[h.class:?]
	... 17 more

### Steps to reproduce the problem

1. 
2. 
3. 
4. ... Profit
[debug.log](https://github.com/ldtteam/minecolonies/files/2853765/debug.log)
[latest.log](https://github.com/ldtteam/minecolonies/files/2853767/latest.log)

**Comment by Fatmice** [comment]
It appears that pausing the deliveryboy stopped the spam

**Comment by Raycoms** [comment]
./mc colonies rs resetAll should fix this

**Comment by ht02** [comment]
Getting the same issue.

https://paste.dimdev.org/arezizunes.mccrash

Pausing the Delivery boys doesn't help me
