### ISSUE TITLE
Crashing when placing Builder's Hut; Cannot place Supply Ship

### ISSUE THREAD

**Issue by spoopyghostramses** [ldtteam/minecolonies#338]
### Minecolonies version

Version: 1.11-0.6.1994

- Crashes when placing builder's hut. Cannot place supply ship, simply won't let me anywhere. I tried many bodies of water.

[crash-2016-12-11_09.56.38-server.txt](https://github.com/Minecolonies/minecolonies/files/644508/crash-2016-12-11_09.56.38-server.txt)

**Comment by Raycoms** [comment]
Working on it.
I think I got the fix already.
Will test it fast and then return.

2016-12-11 13:00 GMT-02:00 spoopyghostramses <notifications@github.com>:

**Comment by spoopyghostramses** [comment]
Thanks haha, I hope I'm not being annoying with these issue reports.

**Comment by Raycoms** [comment]
We need these reports in order to fix the problems.

2016-12-11 13:14 GMT-02:00 spoopyghostramses <notifications@github.com>:

**Comment by Raycoms** [comment]
Can you check if the newest one works now?

2016-12-11 13:15 GMT-02:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by spoopyghostramses** [comment]
I can place supply ship no problem, I still get a "ticking player" crash when placing multiple buildings. Specifically I placed down 3 fields and it crashed.

[crash-2016-12-11_12.39.27-server.txt](https://github.com/Minecolonies/minecolonies/files/644637/crash-2016-12-11_12.39.27-server.txt)

**Comment by Raycoms** [comment]
Very strange can't find anything mod related in the crashlog. Did you try
it without other mods?

2016-12-11 15:42 GMT-02:00 spoopyghostramses <notifications@github.com>:

**Comment by spoopyghostramses** [comment]
Whoops, for some reason that crash log doesn't have the blurb about minecolonies in it. The crash (seemingly) randomly happens when placing a field.

`java.util.concurrent.ExecutionException: java.lang.NullPointerException: The validated object is null
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240) [cce.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]
Caused by: java.lang.NullPointerException: The validated object is null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:222) ~[commons-lang3-3.3.2.jar:3.3.2]
	at org.apache.commons.lang3.Validate.notNull(Validate.java:203) ~[commons-lang3-3.3.2.jar:3.3.2]
	at net.minecraft.util.NonNullList.add(SourceFile:52) ~[dd.class:?]
	at java.util.AbstractList.add(AbstractList.java:108) ~[?:1.8.0_25]
	at net.minecraft.inventory.Container.func_75138_a(Container.java:59) ~[ack.class:?]
	at net.minecraft.inventory.Container.func_75132_a(Container.java:48) ~[ack.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:100) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2490) ~[aax.class:?]
	at com.minecolonies.coremod.blocks.BlockHutField.func_180639_a(BlockHutField.java:181) ~[BlockHutField.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:448) ~[lz.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:674) ~[mi.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[jm.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[jm.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fo$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_25]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_25]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more`

**Comment by Raycoms** [comment]
Seems to be a bigger issue. I suggest not using the farmer yet.

2016-12-11 16:04 GMT-02:00 spoopyghostramses <notifications@github.com>:

**Comment by Raycoms** [comment]
Solved in the newest version.
