### ISSUE TITLE
Minecolonies Warehouse, Forge, Quarry and Bakery do not exist for some reason.

### ISSUE THREAD

**Issue by Moonlightneo** [ldtteam/minecolonies#343]
### Minecolonies version
Curse v0.5 v18

### Expected behavior

- Can build and preview Warehouse

### Actual behaviour

- Warehouse doesn't exist?

### Steps to reproduce the problem

1. Cant make warehouse, proceed to cheat in block with creative.
2. Cant preview warehouse, but is placeable and interactable.
3. Builder wont build warehouse because it doesn't exist?

Also happens to Forge, Quarry and Bakery

This is a pack that's pretty heavily modded and currently running on a personal server, so i haven't quite had the time to update to the v19 release, but judging by changelogs it won't solve the problem i specifically am having, if necessary i can attempt to though, as i was planning to update anyways.

Normally i'd share via pastebin but logs are a tad big.
Here's a snip of the server log and the full log file
`[Server thread/WARN] [Minecolonies:blockout/]: Couldn't find any structure with this name anywhere
java.io.FileNotFoundException: .\minecolonies\default\Warehouse1.nbt (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method) ~[?:1.8.0_111]
	at java.io.FileInputStream.open(Unknown Source) ~[?:1.8.0_111]
	at java.io.FileInputStream.<init>(Unknown Source) ~[?:1.8.0_111]
	at java.io.FileInputStream.<init>(Unknown Source) ~[?:1.8.0_111]
	at com.structures.helpers.Structure.<init>(Structure.java:98) ~[Structure.class:?]
	at com.structures.helpers.StructureProxy.<init>(StructureProxy.java:42) ~[StructureProxy.class:?]
	at com.minecolonies.util.StructureWrapper.<init>(StructureWrapper.java:68) ~[StructureWrapper.class:?]
	at com.minecolonies.entity.ai.citizen.builder.EntityAIStructureBuilder.loadStructure(EntityAIStructureBuilder.java:226) ~[EntityAIStructureBuilder.class:?]
	at com.minecolonies.entity.ai.citizen.builder.EntityAIStructureBuilder.initiate(EntityAIStructureBuilder.java:165) ~[EntityAIStructureBuilder.class:?]
	at com.minecolonies.entity.ai.citizen.builder.EntityAIStructureBuilder.checkIfExecute(EntityAIStructureBuilder.java:154) ~[EntityAIStructureBuilder.class:?]
	at com.minecolonies.entity.ai.util.AITarget.test(AITarget.java:114) ~[AITarget.class:?]
	at com.minecolonies.entity.ai.basic.AbstractAISkeleton.checkOnTarget(AbstractAISkeleton.java:165) ~[AbstractAISkeleton.class:?]
	at java.util.stream.MatchOps$1MatchSink.accept(Unknown Source) [?:1.8.0_111]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source) [?:1.8.0_111]
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) [?:1.8.0_111]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) [?:1.8.0_111]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) [?:1.8.0_111]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) [?:1.8.0_111]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source) [?:1.8.0_111]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source) [?:1.8.0_111]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) [?:1.8.0_111]
	at java.util.stream.ReferencePipeline.anyMatch(Unknown Source) [?:1.8.0_111]
	at com.minecolonies.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:129) [AbstractAISkeleton.class:?]
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129) [tr.class:?]
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:773) [sg.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2183) [sf.class:?]
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577) [sg.class:?]
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:155) [rt.class:?]
	at com.minecolonies.entity.EntityCitizen.func_70636_d(EntityCitizen.java:777) [EntityCitizen.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013) [sf.class:?]
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) [sg.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1964) [aid.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839) [ls.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1934) [aid.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1750) [aid.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620) [ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
[03:43:46] [Server thread/WARN] [minecolonies/]: StructureProxy: (default/Warehouse1) does not exist - removing build request
java.lang.NullPointerException
	at com.structures.helpers.Structure.getSize(Structure.java:187) ~[Structure.class:?]
	at com.structures.helpers.StructureProxy.<init>(StructureProxy.java:43) ~[StructureProxy.class:?]
	at com.minecolonies.util.StructureWrapper.<init>(StructureWrapper.java:68) ~[StructureWrapper.class:?]
	at com.minecolonies.entity.ai.citizen.builder.EntityAIStructureBuilder.loadStructure(EntityAIStructureBuilder.java:226) ~[EntityAIStructureBuilder.class:?]
	at com.minecolonies.entity.ai.citizen.builder.EntityAIStructureBuilder.initiate(EntityAIStructureBuilder.java:165) ~[EntityAIStructureBuilder.class:?]
	at com.minecolonies.entity.ai.citizen.builder.EntityAIStructureBuilder.checkIfExecute(EntityAIStructureBuilder.java:154) ~[EntityAIStructureBuilder.class:?]
	at com.minecolonies.entity.ai.util.AITarget.test(AITarget.java:114) ~[AITarget.class:?]
	at com.minecolonies.entity.ai.basic.AbstractAISkeleton.checkOnTarget(AbstractAISkeleton.java:165) ~[AbstractAISkeleton.class:?]
	at java.util.stream.MatchOps$1MatchSink.accept(Unknown Source) [?:1.8.0_111]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source) [?:1.8.0_111]
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) [?:1.8.0_111]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) [?:1.8.0_111]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) [?:1.8.0_111]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) [?:1.8.0_111]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source) [?:1.8.0_111]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source) [?:1.8.0_111]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) [?:1.8.0_111]
	at java.util.stream.ReferencePipeline.anyMatch(Unknown Source) [?:1.8.0_111]
	at com.minecolonies.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:129) [AbstractAISkeleton.class:?]
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129) [tr.class:?]
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:773) [sg.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2183) [sf.class:?]
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577) [sg.class:?]
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:155) [rt.class:?]
	at com.minecolonies.entity.EntityCitizen.func_70636_d(EntityCitizen.java:777) [EntityCitizen.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013) [sf.class:?]
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) [sg.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1964) [aid.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839) [ls.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1934) [aid.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1750) [aid.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620) [ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
[03:43:46] [Server thread/WARN] [minecolonies/]: Condition check for target com.minecolonies.entity.ai.util.AITarget@6cd3047e threw an exception:
java.lang.NullPointerException
	at com.minecolonies.entity.ai.citizen.builder.EntityAIStructureBuilder.initiate(EntityAIStructureBuilder.java:196) ~[EntityAIStructureBuilder.class:?]
	at com.minecolonies.entity.ai.citizen.builder.EntityAIStructureBuilder.checkIfExecute(EntityAIStructureBuilder.java:154) ~[EntityAIStructureBuilder.class:?]
	at com.minecolonies.entity.ai.util.AITarget.test(AITarget.java:114) ~[AITarget.class:?]
	at com.minecolonies.entity.ai.basic.AbstractAISkeleton.checkOnTarget(AbstractAISkeleton.java:165) ~[AbstractAISkeleton.class:?]
	at java.util.stream.MatchOps$1MatchSink.accept(Unknown Source) [?:1.8.0_111]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source) [?:1.8.0_111]
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) [?:1.8.0_111]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) [?:1.8.0_111]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) [?:1.8.0_111]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) [?:1.8.0_111]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source) [?:1.8.0_111]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source) [?:1.8.0_111]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) [?:1.8.0_111]
	at java.util.stream.ReferencePipeline.anyMatch(Unknown Source) [?:1.8.0_111]
	at com.minecolonies.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:129) [AbstractAISkeleton.class:?]
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129) [tr.class:?]
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:773) [sg.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2183) [sf.class:?]
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577) [sg.class:?]
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:155) [rt.class:?]
	at com.minecolonies.entity.EntityCitizen.func_70636_d(EntityCitizen.java:777) [EntityCitizen.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013) [sf.class:?]
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) [sg.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1964) [aid.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839) [ls.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1934) [aid.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1750) [aid.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620) [ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]`

Heres the full log
[fml-server-latest - Copy.txt](https://github.com/Minecolonies/minecolonies/files/645069/fml-server-latest.-.Copy.txt)

**Comment by marvin-bitterlich** [comment]
They are not implemented
