### ISSUE TITLE
[1.12.2] Server Crash on Start

### ISSUE THREAD

**Issue by ipradasgomez** [ldtteam/minecolonies#3523]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.202-RELEASE-universal

### Expected behavior
- Server starts normally the first time (With no world generated)

### Actual behaviour
- Server crashed and marks minecolonies as errored.

### Steps to reproduce the problem
1. Run server

###Crash Report

> ---- Minecraft Crash Report ----

WARNING: coremods are present:
  SecretRoomsMod-Core (SecretRooms-5.6.4.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.15.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  CreativePatchingLoader (CreativeCore_v1.9.41_mc1.12.2.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.15-universal.jar)
  Wizardry Plugin (wizardry-0.9.9.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  ItemPatchingLoader (ItemPhysic_Full_1.4.19_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 3/28/19 7:03 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Structurize (structurize)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiScreen
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.ldtteam.structurize.compat.optifine.OptifineCompat.setupReflectedMethodReferences(OptifineCompat.java:86)
	at com.ldtteam.structurize.compat.optifine.OptifineCompat.intialize(OptifineCompat.java:55)
	at com.ldtteam.structurize.Structurize.init(Structurize.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.gui.GuiScreen
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 40 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@1ec7d8b3 from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 42 more
Caused by: java.lang.RuntimeException: Attempted to load class blk for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.15.18-9-pve
	Java Version: 1.8.0_191, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2825205600 bytes (2694 MB) / 3083862016 bytes (2941 MB) up to 3083862016 bytes (2941 MB)
	JVM Flags: 2 total; -Xms3072M -Xmx3072M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2823 43 mods loaded, 43 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                 | Version                 | Source                                             | Signature                                |
	|:----- |:------------------ |:----------------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft          | 1.12.2                  | minecraft.jar                                      | None                                     |
	| LCHI  | mcp                | 9.42                    | minecraft.jar                                      | None                                     |
	| LCHI  | FML                | 8.0.99.99               | forge-1.12.2-14.23.5.2823-universal.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge              | 14.23.5.2823            | forge-1.12.2-14.23.5.2823-universal.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | creativecoredummy  | 1.0.0                   | minecraft.jar                                      | None                                     |
	| LCHI  | itemphysic         | 1.4.0                   | minecraft.jar                                      | None                                     |
	| LCHI  | foamfixcore        | 7.7.4                   | minecraft.jar                                      | None                                     |
	| LCHI  | srm-hooks          | 1.12.2-1.0.0            | minecraft.jar                                      | None                                     |
	| LCHI  | dsurroundcore      | 3.5.4.3                 | minecraft.jar                                      | None                                     |
	| LCHI  | aiimprovements     | 0.0.1.3                 | AIImprovements-1.12-0.0.1b3.jar                    | None                                     |
	| LCHI  | aquaculture        | 1.6.8                   | Aquaculture-1.12.2-1.6.8.jar                       | None                                     |
	| LCHI  | architecturecraft  | @VERSION@               | Architecturecraft-1.20.jar                         | None                                     |
	| LCHI  | biomesoplenty      | 7.0.1.2425              | BiomesOPlenty-1.12.2-7.0.1.2425-universal.jar      | None                                     |
	| LCHI  | birdsnests         | 2.1.0                   | BirdsNests-2.1.0.jar                               | None                                     |
	| LCHI  | bullseye           | 3.0.7                   | Bullseye-1.12.2-3.0.7.jar                          | None                                     |
	| LCHI  | carryon            | 1.12.1                  | CarryOn+MC1.12.2+v1.12.1.jar                       | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| LCHI  | creativecore       | 1.9.9                   | CreativeCore_v1.9.41_mc1.12.2.jar                  | None                                     |
	| LCHI  | nhc                | 4.0.3                   | NHCore-1.12-4.0.3 For DeepSea.jar                  | None                                     |
	| LCHI  | dse                | A6                      | DeepSeaExpansion-1.12.2-Preview-A6.jar             | None                                     |
	| LCHI  | dynamictrees       | 1.12.2-0.9.4            | DynamicTrees-1.12.2-0.9.4.jar                      | None                                     |
	| LCHI  | fastleafdecay      | v14                     | FastLeafDecay-14.0.jar                             | None                                     |
	| LCHI  | fencejumper        | 1.0.5                   | FenceJumper-1.0.5.jar                              | None                                     |
	| LCHI  | foamfix            | 0.10.3-1.12.2           | foamfix-0.10.3-1.12.2.jar                          | None                                     |
	| LCHI  | forgelin           | 1.8.2                   | Forgelin-1.8.2.jar                                 | None                                     |
	| LCHI  | waila              | 1.8.26                  | Hwyla-1.8.26-B41.jar                               | None                                     |
	| LCHI  | inventorytweaks    | 1.64+dev.146.2180b27    | InventoryTweaks-1.64+dev.146.jar                   | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHI  | jei                | 4.15.0.271              | jei_1.12.2-4.15.0.271.jar                          | None                                     |
	| LCHI  | lex                | 1.0.8                   | LibExCore-1.0.8.jar                                | None                                     |
	| LCHI  | librarianlib       | 4.15                    | librarianlib-1.12.2-4.15.jar                       | None                                     |
	| LCHI  | mobends            | 0.24                    | MoBends-0.24.jar                                   | None                                     |
	| LCHI  | movinglightsource  | 1.0.15                  | MovingLightSource-1.0.15.jar                       | None                                     |
	| LCHI  | naturalbabyanimals | 1.2.0                   | naturalbabyanimals-1.2.0-mc1.12.x.jar              | None                                     |
	| LCHI  | nex                | 2.0.8                   | NetherEx-2.0.8.jar                                 | None                                     |
	| LCHI  | secretroomsmod     | 5.6.4                   | SecretRooms-5.6.4.jar                              | None                                     |
	| LCHI  | sereneseasons      | 1.2.15                  | SereneSeasons-1.12.2-1.2.15-universal.jar          | None                                     |
	| LCHI  | timberjack         | 1.6                     | Timberjack_1.12.2-1.6.jar                          | None                                     |
	| LCHI  | wizardry           | 0.9.9                   | wizardry-0.9.9.jar                                 | None                                     |
	| LCHI  | worleycaves        | 1.3.0                   | WorleyCaves-1.3.0.jar                              | None                                     |
	| LCHE  | structurize        | 1.12.2-0.10.63-ALPHA    | structurize-1.12.2-0.10.63-ALPHA.jar               | None                                     |
	| LCH   | minecolonies       | 1.12.2-0.10.202-RELEASE | minecolonies-1.12.2-0.10.202-RELEASE-universal.jar | None                                     |
	| LCH   | orelib             | 3.5.2.2                 | OreLib-1.12.2-3.5.2.2 For Dynamic.jar              | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | dsurround          | 3.5.4.3                 | DynamicSurroundings-1.12.2-3.5.4.3.jar             | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LCH   | librarianliblate   | 4.15                    | librarianlib-1.12.2-4.15.jar                       | None                                     |

	Loaded coremods (and transformers):
SecretRoomsMod-Core (SecretRooms-5.6.4.jar)
  com.wynprice.secretroomsmod.core.SecretRoomsTransformer
LibrarianLib Plugin (librarianlib-1.12.2-4.15.jar)
  com.teamwizardry.librarianlib.asm.LibLibTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  invtweaks.forge.asm.ContainerTransformer
BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
CreativePatchingLoader (CreativeCore_v1.9.41_mc1.12.2.jar)
  
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.15-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
Wizardry Plugin (wizardry-0.9.9.jar)
  com.teamwizardry.wizardry.asm.WizardryTransformer
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
  org.orecruncher.dsurround.asm.Transformer
ForgelinPlugin (Forgelin-1.8.2.jar)
  
ItemPatchingLoader (ItemPhysic_Full_1.4.19_mc1.12.2.jar)
  com.creativemd.itemphysic.ItemTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

##LOG
 This crash report has been saved to: /home/msserver/./crash-reports/crash-2019-03-28_19.03.40-server.txt
[19:03:40] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[19:03:40] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds
[19:03:40] [Server thread/ERROR] [FML]: Skipping event FMLServerStoppedEvent and marking errored mod minecolonies since required dependency structurize has errored
[19:03:40] [Server thread/INFO] [FML]: The state engine was in incorrect state POSTINITIALIZATION and forced into state SERVER_STOPPED. Errors may have been discarded.

**Comment by Nightenom** [comment]
I think Optifine compat should be only called in client proxy to avoid server related things

**Comment by ipradasgomez** [comment]
> I think Optifine compat should be only called in client proxy to avoid server related things

So... Is there something I could do to fix this? Is it an internal mod bug?...

**Comment by Nightenom** [comment]
Nah, just internal talking

**Comment by someaddons** [comment]
you could remove optifine from the servers mods

**Comment by GanthorPrime** [comment]
I dont have optifine in the server mods folder and didnt have this problem. (i use optifine in client)
