### ISSUE TITLE
Crash from Server Startup (Dedicated)

### ISSUE THREAD

**Issue by joelou1** [ldtteam/minecolonies#355]
### Minecolonies version

version 0.6.2038

### Expected behavior

- Server would start normally after the loading.

### Actual behaviour

- Crashes after server start. (See Crash Log)

java.lang.NullPointerException: Exception in server tick loop
	at com.minecolonies.coremod.colony.buildings.BuildingFarmer.onDestroyed(BuildingFarmer.java:263)
	at com.minecolonies.coremod.colony.buildings.AbstractBuilding.destroy(AbstractBuilding.java:455)
	at java.util.ArrayList.forEach(Unknown Source)
	at com.minecolonies.coremod.colony.Colony.cleanUpBuildings(Colony.java:897)
	at com.minecolonies.coremod.colony.Colony.onWorldTick(Colony.java:822)
	at com.minecolonies.coremod.colony.ColonyManager.lambda$onWorldTick$49(ColonyManager.java:617)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.util.HashMap$ValueSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at com.minecolonies.coremod.colony.ColonyManager.onWorldTick(ColonyManager.java:617)
	at com.minecolonies.coremod.event.FMLEventHandler.onWorldTick(FMLEventHandler.java:50)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_183_FMLEventHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:282)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:694)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

### Steps to reproduce the problem

(Extra Info: It is working just fine on another machine. I got a friend's server files to host the server, and I got this crash, I tried downgrading, nothing would do.)

1. Getting working server files and configs from .ZIP
2. Unpacked .ZIP and configure ports
3. Start the server
4. Wait for it to properly open.
5. Crash after "Done"

[crash-2016-12-17_12.27.09-server.txt](https://github.com/Minecolonies/minecolonies/files/658962/crash-2016-12-17_12.27.09-server.txt)

**Comment by carbonrobin** [comment]
We get a tick related error with the same version of Minecolonies. Cause the server to restart.

java.lang.IllegalStateException: Colony's world does not match the event.
	at com.minecolonies.coremod.colony.Colony.onWorldTick(Colony.java:791)
	at com.minecolonies.coremod.colony.ColonyManager.lambda$onWorldTick$49(ColonyManager.java:617)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1620)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.minecolonies.coremod.colony.ColonyManager.onWorldTick(ColonyManager.java:617)
	at com.minecolonies.coremod.event.FMLEventHandler.onWorldTick(FMLEventHandler.java:50)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_702_FMLEventHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:269)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:718)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

[crash-2016-12-20_05.24.57-server.txt](https://github.com/Minecolonies/minecolonies/files/662763/crash-2016-12-20_05.24.57-server.txt)

**Comment by Raycoms** [comment]
@kostronor can you take a look at it?
I'm without Internet atm

Am Dienstag, 20. Dezember 2016 schrieb Doug :

**Comment by joelou1** [comment]
> We get a tick related error with the same version of Minecolonies. Cause the server to restart.

Erm, sorry, who are you? This is not related to my crash. Would you be kind enough to make a separate issue? I'm sure those gentlemen will be taking care of it aswell?

Also, thanks for quick response, Raycoms, I'll be waiting.

**Comment by Raycoms** [comment]
I created a fix joelou.  I might be able to upload it within the next few
days.
@doug it seems like one of your players placed his colony in the nether or
the end. Can you please confirm that?

Am Mittwoch, 21. Dezember 2016 schrieb joelou1 :
