### ISSUE TITLE
Pathfinding Issue with Dynamic Trees' Cactus Branch

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#3672]
### Minecolonies Version
Version: 0.10.297-ALPHA

### Dynamic Trees Version
Version: 0.9.5

### Expected behavior
- For the Lumberjack to be able to cut down Dynamic Cactus successfully.

### Actual behaviour

-  The log seems to print an error with the Lumberjack's pathfinding. There is also a dynamic cactus planted near the Lumberjack. It seems to spam this in the log several times before stopping:

```
[08:35:41] [pool-12-thread-1/WARN]: Pathfinding Exception
java.lang.IllegalArgumentException: Cannot get property null as it does not exist in ExtendedBlockState{block=dynamictrees:cactusbranch, properties=[origin, trunk]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.getValue(BlockStateContainer.java:209) ~[awu$a.class:?]
	at com.minecolonies.coremod.entity.ai.citizen.lumberjack.Tree.checkTree(Tree.java:320) ~[Tree.class:?]
	at com.minecolonies.coremod.entity.pathfinding.PathJobFindTree.isTree(PathJobFindTree.java:118) ~[PathJobFindTree.class:?]
	at com.minecolonies.coremod.entity.pathfinding.PathJobFindTree.isNearTree(PathJobFindTree.java:107) ~[PathJobFindTree.class:?]
	at com.minecolonies.coremod.entity.pathfinding.PathJobFindTree.isAtDestination(PathJobFindTree.java:99) ~[PathJobFindTree.class:?]
	at com.minecolonies.coremod.entity.pathfinding.AbstractPathJob.search(AbstractPathJob.java:417) ~[AbstractPathJob.class:?]
	at com.minecolonies.coremod.entity.pathfinding.AbstractPathJob.call(AbstractPathJob.java:374) [AbstractPathJob.class:?]
	at com.minecolonies.coremod.entity.pathfinding.AbstractPathJob.call(AbstractPathJob.java:35) [AbstractPathJob.class:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
```
### Steps to reproduce the problem

1. Place and hire a Lumberjack
2.  Plant a Dynamic Cactus nearby
4. ... Profit

**Comment by someaddons** [comment]
the lumberjack isnt intended to cut down cactus at all, but the log you posted is a bug
