### ISSUE TITLE
Scanning tool causes game to crash

### ISSUE THREAD

**Issue by kooky112** [ldtteam/minecolonies#3674]
### Minecolonies version

Version: 	minecolonies-1.12.2-0.10.297-ALPHA

### Expected behavior

Scanning tool

To be used as intended, selecting an area and making a schematic to be used.

### Actual behaviour

Upon selecting an area, the game crashes instead.

### Steps to reproduce the problem

1. Use the scanning tool to select an area
2. Try and name it or view the rescources
3. pray it works
4. game crashes completely
[latest.log](https://github.com/ldtteam/minecolonies/files/3293847/latest.log)

**Comment by Nightenom** [comment]
Might not be our fault but don't know
```
[01:14:34] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Updating screen events
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1772) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098) ~[bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.shadowmage.ancientwarfare.structure.tile.TileAdvancedLootChest.func_70301_a(TileAdvancedLootChest.java:76) ~[TileAdvancedLootChest.class:?]
	at com.ldtteam.structurize.api.util.ItemStackUtils.getItemStacksOfTileEntity(ItemStackUtils.java:54) ~[ItemStackUtils.class:?]
	at com.ldtteam.structurize.client.gui.WindowScan.updateResources(WindowScan.java:335) ~[WindowScan.class:?]
	at com.ldtteam.structurize.client.gui.WindowScan.onKeyTyped(WindowScan.java:274) ~[WindowScan.class:?]
	at com.ldtteam.blockout.Screen.func_73869_a(Screen.java:68) ~[Screen.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558) ~[blk.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512) ~[blk.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759) ~[bib.class:?]
	... 9 more
[01:14:34] [Client thread/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.57-core.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  Wizardry Plugin (wizardry-0.10.7.jar)
  AstralCore (astralsorcery-1.12.2-1.10.19.jar)
  Quark Plugin (Quark-r1.5-159.jar)
  MekanismCoremod (Mekanism-1.12.2-9.7.8.379.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.19.1-release.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 6/16/19 1:14 AM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at net.shadowmage.ancientwarfare.structure.tile.TileAdvancedLootChest.func_70301_a(TileAdvancedLootChest.java:76)
	at com.ldtteam.structurize.api.util.ItemStackUtils.getItemStacksOfTileEntity(ItemStackUtils.java:54)
	at com.ldtteam.structurize.client.gui.WindowScan.updateResources(WindowScan.java:335)
	at com.ldtteam.structurize.client.gui.WindowScan.onKeyTyped(WindowScan.java:274)
	at com.ldtteam.blockout.Screen.func_73869_a(Screen.java:68)
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.shadowmage.ancientwarfare.structure.tile.TileAdvancedLootChest.func_70301_a(TileAdvancedLootChest.java:76)
	at com.ldtteam.structurize.api.util.ItemStackUtils.getItemStacksOfTileEntity(ItemStackUtils.java:54)
	at com.ldtteam.structurize.client.gui.WindowScan.updateResources(WindowScan.java:335)
	at com.ldtteam.structurize.client.gui.WindowScan.onKeyTyped(WindowScan.java:274)
	at com.ldtteam.blockout.Screen.func_73869_a(Screen.java:68)
	at net.minecraft.client.gui.GuiScreen.func_146282_l(GuiScreen.java:558)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)

-- Affected screen --
Details:
	Screen name: com.ldtteam.blockout.Screen

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Kooky117'/10136, l='MpServer', x=2.06, y=104.91, z=2106.08]]
	Chunk stats: MultiplayerChunkCache: 167, 167
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (4,64,220), Chunk: (at 4,4,12 in 0,13; contains blocks 0,0,208 to 15,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 5154955 game time, 5368608 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 72 total; [EntityPig['Pig'/10497, l='MpServer', x=67.22, y=67.00, z=2097.39], EntityZombie['Zombie'/10247, l='MpServer', x=-51.50, y=67.00, z=2053.50], EntityPig['Pig'/10252, l='MpServer', x=-18.70, y=68.00, z=2043.77], EntityMinecartChest['Minecart with Chest'/10508, l='MpServer', x=79.50, y=45.06, z=2161.50], EntityPig['Pig'/10386, l='MpServer', x=7.76, y=72.00, z=2181.50], EntityPig['Pig'/10387, l='MpServer', x=10.50, y=71.00, z=2177.50], EntityPig['Pig'/10388, l='MpServer', x=13.50, y=71.00, z=2176.50], EntityPig['Pig'/10262, l='MpServer', x=-29.82, y=69.00, z=2125.22], EntityPig['Pig'/10390, l='MpServer', x=7.61, y=65.49, z=2136.14], EntitySheep['Sheep'/10263, l='MpServer', x=-25.55, y=69.00, z=2101.23], EntityPig['Pig'/10391, l='MpServer', x=9.78, y=66.00, z=2132.49], item.vehicleSpawner.5::10137 @ 7.50, 95.00, 2105.50  -- y:-181.70 p:0.00 -- m: 0.00, 0.00, 0.00, item.vehicleSpawner.5::10270 @ 1.50, 79.00, 2091.50  -- y:-282.05 p:0.00 -- m: 0.00, 0.00, 0.00, item.vehicleSpawner.5::10271 @ 1.50, 79.00, 2095.50  -- y:-273.80 p:0.00 -- m: 0.00, 0.00, 0.00, EntityGate['Gate'/10272, l='MpServer', x=15.50, y=65.00, z=2093.50], item.vehicleSpawner.5::10273 @ 7.50, 91.00, 2082.50  -- y:-9.35 p:0.00 -- m: 0.00, 0.00, 0.00, EntityPegasus['Pegasus'/10412, l='MpServer', x=27.56, y=70.00, z=2164.63], EntityBouncyCreeper['Bouncy Creeper'/10413, l='MpServer', x=33.70, y=46.00, z=2142.07], EntityPig['Pig'/10414, l='MpServer', x=17.70, y=66.00, z=2127.13], EntityPlayerSP['Kooky117'/10136, l='MpServer', x=2.06, y=104.91, z=2106.08], item.vehicleSpawner.5::10415 @ 23.50, 81.00, 2100.50  -- y:-88.25 p:0.00 -- m: 0.00, 0.00, 0.00, EntitySheep['Sheep'/10169, l='MpServer', x=-56.77, y=66.00, z=2077.78], EntityPig['Pig'/10170, l='MpServer', x=-57.71, y=66.00, z=2086.79], EntityGate['Gate'/10426, l='MpServer', x=19.50, y=66.00, z=2093.50], item.vehicleSpawner.5::10427 @ 23.50, 81.00, 2086.50  -- y:-96.65 p:0.00 -- m: 0.00, 0.00, 0.00, EntityPig['Pig'/10182, l='MpServer', x=-73.79, y=65.00, z=2087.18], EntityPig['Pig'/10183, l='MpServer', x=-69.81, y=65.00, z=2086.77], EntityItem['item.item.minecraft:chicken'/10185, l='MpServer', x=-59.03, y=68.00, z=2045.36], EntityItem['item.item.feather'/10186, l='MpServer', x=-58.53, y=67.00, z=2045.44], EntityFireDragon['Fire Dragon'/10315, l='MpServer', x=-3.33, y=27.38, z=2157.73], EntitySpider['Spider'/10190, l='MpServer', x=-63.50, y=69.00, z=2184.50], EntityPig['Pig'/10446, l='MpServer', x=39.51, y=66.00, z=2059.25], EntityBat['Bat'/10448, l='MpServer', x=24.75, y=19.10, z=2178.25], EntitySkeleton['Skeleton'/10204, l='MpServer', x=-66.50, y=69.00, z=2184.50], EntityPig['Pig'/10336, l='MpServer', x=-0.43, y=67.00, z=2130.21], EntityMinecartChest['Minecart with Chest'/10464, l='MpServer', x=42.50, y=39.06, z=2137.50], EntityPig['Pig'/10337, l='MpServer', x=-10.41, y=68.00, z=2136.29], EntityItem['item.item.egg'/10465, l='MpServer', x=58.06, y=67.00, z=2096.41], EntityPig['Pig'/10338, l='MpServer', x=-1.54, y=67.00, z=2132.27], EntitySkeleton['Skeleton'/10466, l='MpServer', x=36.50, y=30.00, z=2113.50], EntityPig['Pig'/10339, l='MpServer', x=5.31, y=67.00, z=2125.54], EntityChicken['Chicken'/10467, l='MpServer', x=45.90, y=66.00, z=2096.11], EntityPig['Pig'/10340, l='MpServer', x=-3.27, y=67.00, z=2121.77], EntityChicken['Chicken'/10468, l='MpServer', x=57.16, y=67.00, z=2095.49], EntityChicken['Chicken'/10469, l='MpServer', x=51.11, y=67.00, z=2080.20], EntityBat['Bat'/10214, l='MpServer', x=-29.25, y=35.81, z=2144.75], EntityItem['item.item.egg'/10471, l='MpServer', x=50.62, y=66.00, z=2090.79], EntityItem['item.item.feather'/10472, l='MpServer', x=56.44, y=67.00, z=2095.49], EntityPig['Pig'/10473, l='MpServer', x=70.49, y=67.00, z=2078.44], EntityItem['item.item.egg'/10474, l='MpServer', x=46.56, y=67.00, z=2081.10], EntityPig['Pig'/10475, l='MpServer', x=39.27, y=66.00, z=2094.46], EntityPig['Pig'/10220, l='MpServer', x=-32.25, y=68.00, z=2137.36], EntityBat['Bat'/10476, l='MpServer', x=48.19, y=22.36, z=2180.86], EntityBouncyCreeper['Bouncy Creeper'/10221, l='MpServer', x=-54.68, y=15.71, z=2156.91], EntitySkeleton['Skeleton'/10477, l='MpServer', x=48.50, y=34.00, z=2178.50], EntityBouncyCreeper['Bouncy Creeper'/10222, l='MpServer', x=-67.50, y=15.00, z=2174.50], EntityCow['Cow'/10478, l='MpServer', x=51.50, y=70.00, z=2183.50], EntityPig['Pig'/10223, l='MpServer', x=-44.50, y=67.00, z=2123.75], EntityCow['Cow'/10479, l='MpServer', x=51.50, y=70.00, z=2182.50], EntityPig['Pig'/10224, l='MpServer', x=-41.22, y=67.00, z=2117.40], EntityCow['Cow'/10480, l='MpServer', x=50.50, y=70.00, z=2183.50], EntityCow['Cow'/10481, l='MpServer', x=52.50, y=70.00, z=2182.50], EntityBouncyCreeper['Bouncy Creeper'/10230, l='MpServer', x=-59.30, y=21.00, z=2127.30], EntityChicken['Chicken'/10486, l='MpServer', x=34.82, y=66.00, z=2073.51], EntityBouncyCreeper['Bouncy Creeper'/10231, l='MpServer', x=-56.22, y=23.00, z=2120.88], EntityBouncyCreeper['Bouncy Creeper'/10487, l='MpServer', x=42.07, y=16.50, z=2178.70], EntityCreeper['Creeper'/10489, l='MpServer', x=35.48, y=35.85, z=2177.44], EntityCreeper['Creeper'/10490, l='MpServer', x=40.03, y=37.00, z=2179.44], EntityCreeper['Creeper'/10491, l='MpServer', x=40.00, y=71.00, z=2182.81], EntityMinecartChest['Minecart with Chest'/10492, l='MpServer', x=74.50, y=40.06, z=2159.50], EntityMinecartChest['Minecart with Chest'/10493, l='MpServer', x=55.50, y=39.06, z=2165.50], EntityBouncyCreeper['Bouncy Creeper'/10494, l='MpServer', x=66.05, y=68.50, z=2176.10]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by kooky112** [comment]
I tried with just mine colonies and core mods needed for it as well and
still got the same issue.

Ashley Hampton
23810 S Keystone Way
Clinton twp. MI 48036

**Comment by OCDCleric** [comment]
@kooky112 can you show the log from that attempt as well?

**Comment by kooky112** [comment]
[image: Screenshot_2.png]
No crashes this time but it did keep giving me this error, meanwhile on my
modded dedicated server, my game crashed. I've included both logs as well.
Not sure if it's a config thing or not.

**Comment by OCDCleric** [comment]
@kooky112 i think you goofed on the links. You need to retry cause i cant see em.

**Comment by Raycoms** [comment]
@kooky112 we still need the altered log

**Comment by kooky112** [comment]
Try this google drive link, I zipped both logs plus the screenshot of what
the game told me when trying to save a schematic as well. Sorry it took a
bit, between work and helping my sister move it's been a bit hectic.

https://drive.google.com/file/d/1lzodqwhvffRejEKnlhrf8stVXHmjL1Mh/view?usp=sharing

**Comment by OCDCleric** [comment]
@kooky112 ok... So the scan tool doesn't like ancient warfare 2's loot chest. As for when you did minecolonies only... I'd say find your schematic folder in Roaming/.minecraft and try emptying it out. Not sure how many schematics you jave or if theres a corrupt schematic though.

**Comment by Raycoms** [comment]
Yeah it's the loot chest of the ancient warfare mod, this is not our fault. I reported it to them and I am waiting for their response to either give me a return on a workaround or fix their chest.
