### ISSUE TITLE
Minecolonies crash on start

### ISSUE THREAD

**Issue by snoopyowen** [ldtteam/minecolonies#3719]
### Minecolonies version
0.9.2 release 1.12.2

### Expected behavior
Not crashing instantly as soon as I open a world
### Actual behaviour

 After buying a new computer everytime I open minecraft with this mod I get a crash and this

Time: 7/6/19 2:47 PM

Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MineColonies (minecolonies)

Caused by: java.lang.NoClassDefFoundError: com/minecolonies/coremod/blocks/huts/BlockHutBaker

at java.lang.Class.forName0(Native Method)

at java.lang.Class.forName([Class.java:348](https://Class.java:348))

at net.minecraftforge.fml.common.ProxyInjector.inject([ProxyInjector.java:85](https://ProxyInjector.java:85))

at net.minecraftforge.fml.common.FMLModContainer.constructMod([FMLModContainer.java:583](https://FMLModContainer.java:583))

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke([NativeMethodAccessorImpl.java:62](https://NativeMethodAccessorImpl.java:62))

at sun.reflect.DelegatingMethodAccessorImpl.invoke([DelegatingMethodAccessorImpl.java:43](https://DelegatingMethodAccessorImpl.java:43))

at java.lang.reflect.Method.invoke([Method.java:497](https://Method.java:497))

at com.google.common.eventbus.Subscriber.invokeSubscriberMethod([Subscriber.java:91](https://Subscriber.java:91))

at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod([Subscriber.java:150](https://Subscriber.java:150))

at [com.google.common.eventbus.Subscriber$1.run](https://com.google.common.eventbus.Subscriber$1.run)([Subscriber.java:76](https://Subscriber.java:76))

at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute([MoreExecutors.java:399](https://MoreExecutors.java:399))

at com.google.common.eventbus.Subscriber.dispatchEvent([Subscriber.java:71](https://Subscriber.java:71))

at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch([Dispatcher.java:116](https://Dispatcher.java:116))

at [com.google.common.eventbus.EventBus.post](https://com.google.common.eventbus.EventBus.post)([EventBus.java:217](https://EventBus.java:217))

at net.minecraftforge.fml.common.LoadController.sendEventToModContainer([LoadController.java:253](https://LoadController.java:253))

at net.minecraftforge.fml.common.LoadController.propogateStateMessage([LoadController.java:231](https://LoadController.java:231))

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke([NativeMethodAccessorImpl.java:62](https://NativeMethodAccessorImpl.java:62))

at sun.reflect.DelegatingMethodAccessorImpl.invoke([DelegatingMethodAccessorImpl.java:43](https://DelegatingMethodAccessorImpl.java:43))

at java.lang.reflect.Method.invoke([Method.java:497](https://Method.java:497))

at com.google.common.eventbus.Subscriber.invokeSubscriberMethod([Subscriber.java:91](https://Subscriber.java:91))

at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod([Subscriber.java:150](https://Subscriber.java:150))

at [com.google.common.eventbus.Subscriber$1.run](https://com.google.common.eventbus.Subscriber$1.run)([Subscriber.java:76](https://Subscriber.java:76))

at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute([MoreExecutors.java:399](https://MoreExecutors.java:399))

at com.google.common.eventbus.Subscriber.dispatchEvent([Subscriber.java:71](https://Subscriber.java:71))

at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch([Dispatcher.java:116](https://Dispatcher.java:116))

at [com.google.common.eventbus.EventBus.post](https://com.google.common.eventbus.EventBus.post)([EventBus.java:217](https://EventBus.java:217))

at net.minecraftforge.fml.common.LoadController.distributeStateMessage([LoadController.java:148](https://LoadController.java:148))

at net.minecraftforge.fml.common.Loader.loadMods([Loader.java:568](https://Loader.java:568))

at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading([FMLClientHandler.java:231](https://FMLClientHandler.java:231))

at net.minecraft.client.Minecraft.func\_71384\_a([Minecraft.java:466](https://Minecraft.java:466))

at net.minecraft.client.Minecraft.func\_99999\_d([Minecraft.java:377](https://Minecraft.java:377))

at net.minecraft.client.main.Main.main(SourceFile:123)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke([NativeMethodAccessorImpl.java:62](https://NativeMethodAccessorImpl.java:62))

at sun.reflect.DelegatingMethodAccessorImpl.invoke([DelegatingMethodAccessorImpl.java:43](https://DelegatingMethodAccessorImpl.java:43))

at java.lang.reflect.Method.invoke([Method.java:497](https://Method.java:497))

at net.minecraft.launchwrapper.Launch.launch([Launch.java:135](https://Launch.java:135))

at net.minecraft.launchwrapper.Launch.main([Launch.java:28](https://Launch.java:28))
Caused by: java.lang.ClassNotFoundException: com.minecolonies.coremod.blocks.huts.BlockHutBaker

at net.minecraft.launchwrapper.LaunchClassLoader.findClass([LaunchClassLoader.java:191](https://LaunchClassLoader.java:191))

at java.lang.ClassLoader.loadClass([ClassLoader.java:424](https://ClassLoader.java:424))

at java.lang.ClassLoader.loadClass([ClassLoader.java:357](https://ClassLoader.java:357))

... 40 more
Caused by: java.lang.NoClassDefFoundError: com/minecolonies/coremod/blocks/AbstractBlockHut

at java.lang.ClassLoader.defineClass1(Native Method)

at java.lang.ClassLoader.defineClass([ClassLoader.java:760](https://ClassLoader.java:760))

at java.security.SecureClassLoader.defineClass([SecureClassLoader.java:142](https://SecureClassLoader.java:142))

at net.minecraft.launchwrapper.LaunchClassLoader.findClass([LaunchClassLoader.java:182](https://LaunchClassLoader.java:182))

... 42 more
Caused by: java.lang.ClassNotFoundException: com.minecolonies.coremod.blocks.AbstractBlockHut

at net.minecraft.launchwrapper.LaunchClassLoader.findClass([LaunchClassLoader.java:101](https://LaunchClassLoader.java:101))

at java.lang.ClassLoader.loadClass([ClassLoader.java:424](https://ClassLoader.java:424))

at java.lang.ClassLoader.loadClass([ClassLoader.java:357](https://ClassLoader.java:357))

... 46 more

A detailed walkthrough of the error, its code path and all known details is as follows:

---------------------------------------------------------------------------------------

-- System Details --

Details:

Minecraft Version: 1.12.2

Operating System: Windows 10 (amd64) version 10.0

Java Version: 1.8.0\_51, Oracle Corporation

Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation

Memory: 495283856 bytes (472 MB) / 872415232 bytes (832 MB) up to 2147483648 bytes (2048 MB)

JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance\_javaw.exe\_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0

FML: MCP 9.42 Powered by Forge 14.23.0.2529 7 mods loaded, 7 mods active

States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

| State | ID                | Version                 | Source                                             | Signature                                |

|:----- |:----------------- |:----------------------- |:-------------------------------------------------- |:---------------------------------------- |

| UC    | minecraft         | 1.12.2                  | minecraft.jar                                      | None                                     |

| UC    | mcp               | 9.42                    | minecraft.jar                                      | None                                     |

| UC    | FML               | [8.0.99.99](https://8.0.99.99)| forge-1.12.2-14.23.0.2529.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |

| UC    | forge             | 14.23.0.2529            | forge-1.12.2-14.23.0.2529.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |

| UC    | mercurius\_updater | 1.0                     | MercuriusUpdater-1.12.2.jar                        | None                                     |

| UC    | structurize       | 1.12.2-0.10.7-ALPHA     | structurize-1.12.2-0.10.7-ALPHA-universal.jar      | None                                     |

| UE    | minecolonies      | 1.12.2-0.10.259-RELEASE | minecolonies-1.12.2-0.10.259-RELEASE-universal.jar | None                                     |

Loaded coremods (and transformers): 

GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 419.17' Renderer: 'GeForce RTX 2070/PCIe/SSE2'

### Steps to reproduce the problem
1. not using multi mc dowload the latest java for 1.12.2
2.download minecolonies and the building mod that goes with it
3 press play
4 crash

**Comment by lunadragnstar** [comment]
Update to the newest forge, and make sure you have the updated java too.

**Comment by snoopyowen** [comment]
I did that no change

**Comment by snoopyowen** [comment]
still crashes on opening

**Comment by Raycoms** [comment]
Redownload the jar

**Comment by snoopyowen** [comment]
That didnt work either to update forge you just deleat it and dowload the new one right?

**Comment by snoopyowen** [comment]
only minecolonies crashes it btw other mods are fine

**Comment by Raycoms** [comment]
I mean, did you try to redownload minecolonies?

Am Sa., 6. Juli 2019 um 21:29 Uhr schrieb snoopyowen <
notifications@github.com>:

**Comment by snoopyowen** [comment]
yes

**Comment by Talyda** [comment]
You're using a quite old version of minecolonies (minecolonies-1.12.2-0.10.259-RELEASE) - would be worth downloading the latest alpha and trying that!

**Comment by snoopyowen** [comment]
ok

**Comment by snoopyowen** [comment]
were can I find the latest one?

**Comment by Talyda** [comment]
Stupid new design of the curseforge page!

https://www.curseforge.com/minecraft/mc-mods/minecolonies
Go to "files"
Scroll down to "recent files" to the right is a button with "view all"
That should open a new page, and "minecolonies-1.12.2-0.10.304-ALPHA-universal.jar" should show as the most recent =)

**Comment by snoopyowen** [comment]
ok

**Comment by snoopyowen** [comment]
negative on that one command

**Comment by snoopyowen** [comment]
crash and burn

**Comment by snoopyowen** [comment]
any idea what is causing the crash?

**Comment by snoopyowen** [comment]
Did the crash report say anything other than its a coreblock error?

**Comment by someaddons** [comment]
you're using a really old forge version, probably just need to update that to get it to work
oh and your java is too old aswell

**Comment by snoopyowen** [comment]
it won't update

**Comment by snoopyowen** [comment]
I updated forge though

**Comment by snoopyowen** [comment]
That worked though

**Comment by snoopyowen** [comment]
RESOLVED YAY
