### ISSUE TITLE
Critical error when loading the world

### ISSUE THREAD

**Issue by kellixon** [ldtteam/minecolonies#3780]
[14:45:20] [Server thread/INFO] [structurize]: Load huts or decorations from jar
[14:45:20] [Server thread/WARN] [structurize]: loadSchematicsForPrefix: Could not load schematics from /assets/structurize/schematics
java.nio.file.NoSuchFileException: /assets/structurize/schematics
	at com.sun.nio.zipfs.ZipPath.getAttributes(ZipPath.java:666) ~[zipfs.jar:1.8.0_221]
	at com.sun.nio.zipfs.ZipFileSystemProvider.readAttributes(ZipFileSystemProvider.java:294) ~[zipfs.jar:1.8.0_221]
	at java.nio.file.Files.readAttributes(Unknown Source) ~[?:1.8.0_221]
	at java.nio.file.FileTreeWalker.getAttributes(Unknown Source) ~[?:1.8.0_221]
	at java.nio.file.FileTreeWalker.visit(Unknown Source) ~[?:1.8.0_221]
	at java.nio.file.FileTreeWalker.walk(Unknown Source) ~[?:1.8.0_221]
	at java.nio.file.FileTreeIterator.<init>(Unknown Source) ~[?:1.8.0_221]
	at java.nio.file.Files.walk(Unknown Source) ~[?:1.8.0_221]
	at java.nio.file.Files.walk(Unknown Source) ~[?:1.8.0_221]
	at com.ldtteam.structurize.management.Structures.loadSchematicsForPrefix(Structures.java:274) [Structures.class:?]
	at com.ldtteam.structurize.management.Structures.loadStyleMapsJar(Structures.java:213) [Structures.class:?]
	at com.ldtteam.structurize.management.Structures.loadStyleMaps(Structures.java:152) [Structures.class:?]
	at com.ldtteam.structurize.management.Structures.init(Structures.java:139) [Structures.class:?]
	at com.ldtteam.structurize.Structurize.serverAboutLoad(Structurize.java:160) [Structurize.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.serverAboutToStart(Loader.java:854) [Loader.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:292) [FMLCommonHandler.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_221]
	at net.optifine.reflect.Reflector.callBoolean(Reflector.java:848) [Reflector.class:?]
	at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:210) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]

**Comment by Raycoms** [comment]
Does it crash?

Am Do., 8. Aug. 2019 um 13:09 Uhr schrieb Konstantin <
notifications@github.com>:

**Comment by marchermans** [comment]
This is normal the directory does not exist
We should check if it exists in structurize transfering issue.
