### ISSUE TITLE
Minecolonies keeps crashing

### ISSUE THREAD

**Issue by Rizzolli** [ldtteam/minecolonies#3798]
### Minecolonies version

Version:  minecolonies-1.12.2-0.10.259-RELEASE-universal

### Expected behavior

-  Game doesn't crash

### Actual behaviour

-  
When I load into the game it crashes almost immediately and get this error message:

     The game crashed whilst exception in server tick loop
     Error: java.lang.IllegalArgumentException: ChunkNibbleArrays should be 2048 bytes not: 0

I'm not certain that it is because of minecolonies but I'm pretty sure it is. I started a new world after removing my other world from my minecraft folder and the new world was literally the same world and had all my building in it but as soon as I loaded the chunks my colony was in the game crashes and gives the same error,

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 8/18/19 1:19 PM
Description: Exception in server tick loop

java.lang.IllegalArgumentException: ChunkNibbleArrays should be 2048 bytes not: 0
	at net.minecraft.world.chunk.NibbleArray.<init>(SourceFile:16)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75823_a(AnvilChunkLoader.java:449)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.checkedReadChunkFromNBT__Async(AnvilChunkLoader.java:128)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:92)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.run(ChunkIOProvider.java:70)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:92)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89)
	at net.minecraft.server.management.PlayerChunkMapEntry$1.run(PlayerChunkMapEntry.java:39)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.runCallbacks(ChunkIOProvider.java:134)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:96)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89)
	at net.minecraft.server.management.PlayerChunkMapEntry$1.run(PlayerChunkMapEntry.java:39)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.runCallbacks(ChunkIOProvider.java:134)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:96)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:728)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 535571368 bytes (510 MB) / 1073741824 bytes (1024 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E3 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID            | Version                 | Source                                             | Signature                                |
	|:--------- |:------------- |:----------------------- |:-------------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft     | 1.12.2                  | minecraft.jar                                      | None                                     |
	| UCHIJAAAA | mcp           | 9.42                    | minecraft.jar                                      | None                                     |
	| UCHIJAAAA | FML           | 8.0.99.99               | forge-1.12.2-14.23.5.2768.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge         | 14.23.5.2768            | forge-1.12.2-14.23.5.2768.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | bspkrscore    | at_0.9                  | TreeCapitator-Mod-1.12.jar                         | None                                     |
	| UCHIJAAAA | treecapitator | at_0.9                  | TreeCapitator-Mod-1.12.jar                         | None                                     |
	| UCHIJAAAA | xaerominimap  | 1.17.4                  | Xaeros-Minimap-Mod-1.12.2.jar                      | None                                     |
	| UCHIJAAAA | structurize   | 1.12.2-0.10.79-ALPHA    | structurize-1.12.2-0.10.79-ALPHA.jar               | None                                     |
	| UCHIJAAAA | minecolonies  | 1.12.2-0.10.259-RELEASE | minecolonies-1.12.2-0.10.259-RELEASE-universal.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['xtremeelf'/1015, l='New World', x=29.72, y=65.00, z=553.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 418.81
	OpenGlRenderer: GeForce GTX 1080/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

### Steps to reproduce the problem

My game was running fine, I had 6 colonists, 5 with jobs, and all of a sudden my power went out. When I was able to load up the game again I started getting this problem. The newest change to my colony was adding 2 new colonists but my game was fine for at least an hour after that. I had a different error a couple times as well that mentioned one of the colonists names but I couldnt figure out how to delete just that colonist. Here is that crash log:

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 8/17/19 12:10 PM
Description: Ticking entity

java.lang.IllegalArgumentException: ChunkNibbleArrays should be 2048 bytes not: 0
	at net.minecraft.world.chunk.NibbleArray.<init>(SourceFile:16)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75823_a(AnvilChunkLoader.java:449)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.checkedReadChunkFromNBT__Async(AnvilChunkLoader.java:128)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:92)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.run(ChunkIOProvider.java:70)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:92)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
	at net.minecraft.world.World.func_72964_e(World.java:310)
	at net.minecraft.world.ChunkCache.<init>(ChunkCache.java:37)
	at com.minecolonies.coremod.entity.pathfinding.AbstractPathJob.<init>(AbstractPathJob.java:162)
	at com.minecolonies.coremod.entity.pathfinding.AbstractPathJob.<init>(AbstractPathJob.java:141)
	at com.minecolonies.coremod.entity.pathfinding.PathJobMoveToLocation.<init>(PathJobMoveToLocation.java:37)
	at com.minecolonies.coremod.entity.pathfinding.PathNavigate.moveToXYZ(PathNavigate.java:183)
	at com.minecolonies.coremod.entity.pathfinding.PathNavigate.func_75492_a(PathNavigate.java:142)
	at com.minecolonies.coremod.entity.ai.minimal.EntityAICitizenWander.func_75249_e(EntityAICitizenWander.java:103)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:102)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:888)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2352)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at com.minecolonies.coremod.entity.EntityCitizen.func_70636_d(EntityCitizen.java:596)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2172)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.chunk.NibbleArray.<init>(SourceFile:16)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75823_a(AnvilChunkLoader.java:449)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.checkedReadChunkFromNBT__Async(AnvilChunkLoader.java:128)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:92)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.run(ChunkIOProvider.java:70)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:92)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
	at net.minecraft.world.World.func_72964_e(World.java:310)
	at net.minecraft.world.ChunkCache.<init>(ChunkCache.java:37)
	at com.minecolonies.coremod.entity.pathfinding.AbstractPathJob.<init>(AbstractPathJob.java:162)
	at com.minecolonies.coremod.entity.pathfinding.AbstractPathJob.<init>(AbstractPathJob.java:141)
	at com.minecolonies.coremod.entity.pathfinding.PathJobMoveToLocation.<init>(PathJobMoveToLocation.java:37)
	at com.minecolonies.coremod.entity.pathfinding.PathNavigate.moveToXYZ(PathNavigate.java:183)
	at com.minecolonies.coremod.entity.pathfinding.PathNavigate.func_75492_a(PathNavigate.java:142)
	at com.minecolonies.coremod.entity.ai.minimal.EntityAICitizenWander.func_75249_e(EntityAICitizenWander.java:103)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:102)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:888)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2352)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at com.minecolonies.coremod.entity.EntityCitizen.func_70636_d(EntityCitizen.java:596)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2172)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: minecolonies:citizen (com.minecolonies.coremod.entity.EntityCitizen)
	Entity ID: 191
	Entity Name: Susanna R. Crickett
	Entity's Exact location: 14.18, 66.00, 584.47
	Entity's Block location: World: (14,66,584), Chunk: (at 14,4,8 in 0,36; contains blocks 0,0,576 to 15,255,591), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['xtremeelf'/121, l='New World', x=27.41, y=71.00, z=637.52]]
	Chunk stats: ServerChunkCache: 894 Drop: 0
	Level seed: -8169068500603287714
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-220,64,248), Chunk: (at 4,4,8 in -14,15; contains blocks -224,0,240 to -209,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 713737 game time, 1133816 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 160557 (now: false), thunder time: 61583 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 443161704 bytes (422 MB) / 1040187392 bytes (992 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E3 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID            | Version                 | Source                                             | Signature                                |
	|:--------- |:------------- |:----------------------- |:-------------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft     | 1.12.2                  | minecraft.jar                                      | None                                     |
	| UCHIJAAAA | mcp           | 9.42                    | minecraft.jar                                      | None                                     |
	| UCHIJAAAA | FML           | 8.0.99.99               | forge-1.12.2-14.23.5.2768.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge         | 14.23.5.2768            | forge-1.12.2-14.23.5.2768.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | bspkrscore    | at_0.9                  | TreeCapitator-Mod-1.12.jar                         | None                                     |
	| UCHIJAAAA | treecapitator | at_0.9                  | TreeCapitator-Mod-1.12.jar                         | None                                     |
	| UCHIJAAAA | xaerominimap  | 1.17.4                  | Xaeros-Minimap-Mod-1.12.2.jar                      | None                                     |
	| UCHIJAAAA | structurize   | 1.12.2-0.10.79-ALPHA    | structurize-1.12.2-0.10.79-ALPHA.jar               | None                                     |
	| UCHIJAAAA | minecolonies  | 1.12.2-0.10.259-RELEASE | minecolonies-1.12.2-0.10.259-RELEASE-universal.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['xtremeelf'/121, l='New World', x=27.41, y=71.00, z=637.52]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 418.81
	OpenGlRenderer: GeForce GTX 1080/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by Raycoms** [comment]
This seems like a corrupted world

**Comment by Raycoms** [comment]
Yeah chcked into this again, something seems to have corrupted the chunk the citizen is in. And when loading it in the pathfinder it crashes.
