### ISSUE TITLE
Postbox issue on heavy modded server

### ISSUE THREAD

**Issue by TMarc** [ldtteam/minecolonies#3829]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.357-ALPHA

### Expected behavior

- Lag/Crash with the block Postbox on server with a lot of mods, perhaps reduce the list of contents to the warehouse and crafting items if possible.

### Actual behaviour

- Accessing the Postbox is very slow because it list all the items on a heavy modded server.

### Steps to reproduce the problem

1. On a heavy modpack (for example : All the mods 3)
2. Put a Postbox in the world
3. Access it...
4. ... Profit

### Log Error:
[14:56:42] [Client thread/ERROR]: Exception when parsing XML for pane type buttonimage
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedConstructorAccessor512.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
	at com.minecolonies.blockout.Loader.createFromPaneParams(Loader.java:107) [Loader.class:?]
	at com.minecolonies.blockout.Loader.createFromPaneParams(Loader.java:141) [Loader.class:?]
	at com.minecolonies.blockout.views.View.parseChildren(View.java:60) [View.class:?]
	at com.minecolonies.blockout.Loader.createFromPaneParams(Loader.java:146) [Loader.class:?]
	at com.minecolonies.blockout.views.ScrollingListContainer.refreshElementPanes(ScrollingListContainer.java:39) [ScrollingListContainer.class:?]
	at com.minecolonies.blockout.views.ScrollingList.refreshElementPanes(ScrollingList.java:69) [ScrollingList.class:?]
	at com.minecolonies.blockout.views.ScrollingList.setDataProvider(ScrollingList.java:61) [ScrollingList.class:?]
	at com.minecolonies.coremod.client.gui.WindowPostBox.updateResourceList(WindowPostBox.java:146) [WindowPostBox.class:?]
	at com.minecolonies.coremod.client.gui.WindowPostBox.updateResources(WindowPostBox.java:110) [WindowPostBox.class:?]
	at com.minecolonies.coremod.client.gui.WindowPostBox.onOpened(WindowPostBox.java:97) [WindowPostBox.class:?]
	at com.minecolonies.blockout.Screen.func_73866_w_(Screen.java:122) [Screen.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:478) [blk.class:?]
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1018) [bib.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.showGuiScreen(FMLClientHandler.java:501) [FMLClientHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.showGuiScreen(FMLCommonHandler.java:322) [FMLCommonHandler.class:?]
	at com.minecolonies.blockout.views.Window.open(Window.java:168) [Window.class:?]
	at com.minecolonies.coremod.colony.buildings.views.AbstractBuildingView.openGui(AbstractBuildingView.java:322) [AbstractBuildingView.class:?]
	at com.minecolonies.api.blocks.AbstractBlockHut.func_180639_a(AbstractBlockHut.java:240) [AbstractBlockHut.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:423) [bsa.class:?]
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1579) [bib.class:?]
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254) [bib.class:?]
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020) [bib.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808) [bib.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.OutOfMemoryError
	at java.util.zip.Inflater.inflateBytes(Native Method) ~[?:1.8.0_51]
	at java.util.zip.Inflater.inflate(Inflater.java:259) ~[?:1.8.0_51]
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:152) ~[?:1.8.0_51]
	at javax.imageio.stream.MemoryCache.loadFromStream(MemoryCache.java:113) ~[?:1.8.0_51]
	at javax.imageio.stream.MemoryCacheImageInputStream.read(MemoryCacheImageInputStream.java:110) ~[?:1.8.0_51]
	at javax.imageio.stream.ImageInputStreamImpl.readFully(ImageInputStreamImpl.java:351) ~[?:1.8.0_51]
	at javax.imageio.stream.ImageInputStreamImpl.readFully(ImageInputStreamImpl.java:361) ~[?:1.8.0_51]
	at com.sun.imageio.plugins.png.PNGImageReader.readHeader(PNGImageReader.java:232) ~[?:1.8.0_51]
	at com.sun.imageio.plugins.png.PNGImageReader.getWidth(PNGImageReader.java:1361) ~[?:1.8.0_51]
	at com.minecolonies.blockout.controls.Image.getImageDimensions(Image.java:100) ~[Image.class:?]
	at com.minecolonies.blockout.controls.ButtonImage.loadImageDimensions(ButtonImage.java:193) ~[ButtonImage.class:?]
	at com.minecolonies.blockout.controls.ButtonImage.loadImageInfo(ButtonImage.java:88) ~[ButtonImage.class:?]
	at com.minecolonies.blockout.controls.ButtonImage.<init>(ButtonImage.java:70) ~[ButtonImage.class:?]
	... 35 more

**Comment by Raycoms** [comment]
fixed
