### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by richy1998** [ldtteam/minecolonies#3874]
Hi Guys.

i get this error every 10-20 mins while i play. this is the chrash report from the server. the Client run well without problems.  i think this happens if a building get finished built or upgrade.

---- Minecraft Crash Report ----
// I feel sad now :(

Time: 9/21/19 2:26 PM
Description: Ticking entity

java.lang.NoSuchMethodError: net.minecraft.entity.item.ItemEntity.getPersistentData()Lnet/minecraft/nbt/CompoundNBT;
	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIInteract.lambda$searchForItems$0(AbstractEntityAIInteract.java:300) ~[?:0.10.374-ALPHA] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_181] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_181] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_181] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_181] {}
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_181] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_181] {}
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_181] {}
	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIInteract.searchForItems(AbstractEntityAIInteract.java:302) ~[?:0.10.374-ALPHA] {}
	at com.minecolonies.coremod.entity.ai.citizen.lumberjack.EntityAIWorkLumberjack.fillItemsList(EntityAIWorkLumberjack.java:646) ~[?:0.10.374-ALPHA] {}
	at com.minecolonies.coremod.entity.ai.citizen.lumberjack.EntityAIWorkLumberjack.gathering(EntityAIWorkLumberjack.java:750) ~[?:0.10.374-ALPHA] {}
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:77) ~[?:0.10.374-ALPHA] {}
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:148) ~[?:0.10.374-ALPHA] {}
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:131) ~[?:0.10.374-ALPHA] {}
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:78) ~[?:0.10.374-ALPHA] {}
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:1.8.0_181] {}
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359) ~[?:1.8.0_181] {}
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_181] {}
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) ~[?:1.8.0_181] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[?:1.8.0_181] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_181] {}
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:1.8.0_181] {}
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:1.8.0_181] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_181] {}
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449) ~[?:1.8.0_181] {}
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:60) ~[?:0.10.374-ALPHA] {}
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:151) ~[?:0.10.374-ALPHA] {}
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_181] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_181] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_181] {}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_181] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_181] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_181] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_181] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_181] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_181] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_181] {}
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:80) ~[?:?] {}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:590) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2186) ~[?:?] {pl:accesstransformer:B,xf:fml:caelus:coremodone,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:460) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:140) ~[?:?] {}
	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:1069) ~[?:0.10.374-ALPHA] {}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2032) ~[?:?] {pl:accesstransformer:B,xf:fml:caelus:coremodone,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:587) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_217390_a(World.java:684) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:394) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:324) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) ~[?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIInteract.lambda$searchForItems$0(AbstractEntityAIInteract.java:300)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIInteract.searchForItems(AbstractEntityAIInteract.java:302)
	at com.minecolonies.coremod.entity.ai.citizen.lumberjack.EntityAIWorkLumberjack.fillItemsList(EntityAIWorkLumberjack.java:646)
	at com.minecolonies.coremod.entity.ai.citizen.lumberjack.EntityAIWorkLumberjack.gathering(EntityAIWorkLumberjack.java:750)
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:77)
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:148)
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:131)
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:78)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:60)
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:151)
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:80)
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:590)
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2186)
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:460)
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:140)
	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:1069)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2032)
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:587)

-- Entity being ticked --
Details:
	Entity Type: minecolonies:citizen (com.minecolonies.coremod.entity.citizen.EntityCitizen)
	Entity ID: 69
	Entity Name: Liliana I. Asger
	Entity's Exact location: 721.54, 64.00, -2188.52
	Entity's Block location: World: (721,64,-2189), Chunk: (at 1,4,3 in 45,-137; contains blocks 720,0,-2192 to 735,255,-2177), Region: (1,-5; contains chunks 32,-160 to 63,-129, blocks 512,0,-2560 to 1023,255,-2049)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:684)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:394)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Richy98'/275, l='OPlanty', x=676.70, y=63.00, z=-2277.74]]
	Chunk stats: ServerChunkCache: 2730
	Level dimension: DimensionType{minecraft:overworld}
	Level name: OPlanty
	Level seed: -967873956366121823
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (718,65,-2248), Chunk: (at 14,4,8 in 44,-141; contains blocks 704,0,-2256 to 719,255,-2241), Region: (1,-5; contains chunks 32,-160 to 63,-129, blocks 512,0,-2560 to 1023,255,-2049)
	Level time: 7195640 game time, 1012729 day time
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 62151 (now: false), thunder time: 12701 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:324)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Linux (amd64) version 4.9.0-9-amd64
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1082857872 bytes (1032 MB) / 1576534016 bytes (1503 MB) up to 1908932608 bytes (1820 MB)
	CPUs: 8
	JVM Flags: 5 total; -Xmx2048M -Xms512M -XX:MaxPermSize=512m -XX:+CMSClassUnloadingEnabled -XX:+CMSPermGenSweepingEnabled
	ModLauncher: 3.2.0+60+b86c1d4
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge.jar object_holder_definalize PLUGINSERVICE 
		/forge.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge.jar capability_inject_definalize PLUGINSERVICE 
		/forge.jar runtimedistcleaner PLUGINSERVICE 
		/forge.jar fml TRANSFORMATIONSERVICE 
	FML: 28.0
	Forge: net.minecraftforge:28.0.88
	FML Language Providers: 
		javafml@28.0
		minecraft@1
	Mod List: 
		betteranimalsplus-1.14.4-7.1.0.jar Better Animals Plus {betteranimalsplus@7.1.0 DONE}
		BetterThanMending-1.3.1.jar BetterThanMending {betterthanmending@1.3.1 DONE}
		BiomesOPlenty-1.14.4-9.0.0.251-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.251 DONE}
		caelus-FORGE-1.14.4-0.11.jar Caelus API {caelus@FORGE-1.14.4-0.11 DONE}
		cfm-7.0.0-pre5-mc1.14.4.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre5 DONE}
		Charm-1.14.4-1.3.4.jar Charm {charm@1.14.4-1.3.4 DONE}
		colytra-FORGE-1.14.4-2.0-beta4.jar Colytra {colytra@FORGE-1.14.4-2.0-beta4 DONE}
		elevatorid-1.14.4-1.5.1.jar Elevator Mod {elevatorid@1.14.4-1.5.1 DONE}
		gravestone-1.15.0.jar Gravestone Mod {gravestone@1.15.0 DONE}
		inventorysorter-1.14.4-15.2.0.jar Simple Inventory Sorter {inventorysorter@15.2.0 DONE}
		ironchest-1.14.4-9.0.4.jar Iron Chests {ironchest@1.14.3-9.0.3 DONE}
		jei-1.14.4-6.0.0.11.jar Just Enough Items {jei@6.0.0.11 DONE}
		structurize-0.10.167-ALPHA.jar Structurize {structurize@unspecified DONE}
		minecolonies-0.10.374-ALPHA-universal.jar Minecolonies {minecolonies@1 DONE}
		travellersboots-1.14.4-1.2.2.jar Traveller's Boots {travellersboots@1.2.2 DONE}
		u_team_core-1.14.4-2.7.0.129.jar U Team Core {uteamcore@2.7.0.129 DONE}
		useful_backpacks-1.14.4-1.7.0.34.jar Useful Backpacks {usefulbackpacks@1.7.0.34 DONE}
		XaerosWorldMap_1.4.9_Forge_1.14.4.jar Xaero's World Map {xaeroworldmap@1.4.9 DONE}
		forge-1.14.4-28.0.88-universal.jar Forge {forge@28.0.88 DONE}
		forge-1.14.4-28.0.88-server.jar Minecraft {minecraft@1.14.4 DONE}
	Player Count: 1 / 6; [ServerPlayerEntity['Richy98'/275, l='OPlanty', x=676.70, y=63.00, z=-2277.74]]
	Data Packs: mod:structurize, mod:minecolonies (incompatible), mod:betteranimalsplus, mod:uteamcore, mod:usefulbackpacks, vanilla, mod:xaeroworldmap, mod:travellersboots, mod:jei, mod:ironchest, mod:inventorysorter, mod:gravestone, mod:forge, mod:elevatorid, mod:colytra, mod:charm, mod:cfm, mod:caelus, mod:biomesoplenty, mod:betterthanmending
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by someaddons** [comment]
updating forge should help

**Comment by Asherslab** [comment]
use the correct forge version for minecolonies, not our issue

**Comment by richy1998** [comment]
What is the correct Version of forge for minecolonies? I dont find anything about versions

**Comment by Raycoms** [comment]
the newest  for 1.14

Am Sa., 21. Sept. 2019 um 11:20 Uhr schrieb richy1998 <
notifications@github.com>:
