### ISSUE TITLE
Disconnect when connecting to server

### ISSUE THREAD

**Issue by G1R-Productions** [ldtteam/minecolonies#3889]
Version: 1.12.2 - 0.10.405 - ALPHA

Disconnecting from minecolonies server when loading into server. I entered the nether while a glowing ancient tome was in my inventory. The follow error occurs when I attempt to connect to the server.

`[Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /127.0.0.1:56389
net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:459) ~[oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.update(NetHandlerPlayServer.java:173) ~[pa.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285) ~[gw.class:?]
        at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:180) [oz.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NullPointerException
        at com.minecolonies.coremod.items.ItemAncientTome.onUpdate(ItemAncientTome.java:43) ~[ItemAncientTome.class:?]
        at net.minecraft.item.ItemStack.updateAnimation(ItemStack.java:526) ~[aip.class:?]
        at net.minecraft.entity.player.InventoryPlayer.decrementAnimations(InventoryPlayer.java:363) ~[aec.class:?]
        at net.minecraft.entity.player.EntityPlayer.onLivingUpdate(EntityPlayer.java:511) ~[aed.class:?]
        at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2179) ~[vp.class:?]
        at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:234) ~[aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:382) ~[oq.class:?]
        ... 9 more`

**Comment by Raycoms** [comment]
fixed

**Comment by Raycoms** [comment]
nvm 1.12

**Comment by Raycoms** [comment]
fixed
