### ISSUE TITLE
Game Crashes every 2nd nightfall

### ISSUE THREAD

**Issue by Halithor** [ldtteam/minecolonies#3905]
### Minecolonies version

Version: minecolonies-0.10.356-ALPHA-universal
Minecraft Version: 1.14.4

### Expected behavior

Game does not crash at nightfall.

### Actual behavior

Exactly at nightfall, on the 2nd nightfall after I've loaded, the game will consistently crash. I've attached the server stack trace. I'm not exactly sure what started this problem, but it has been happening consistently for at least 4 loads now. I have the "Bad Omen" buff, but I can't assuredly say it is related to this issue.

I think it started after I gained by 5th colonist as a child of the colony.

### Steps to reproduce the problem

1) Load the game
2) Wait until second nightfall
3) Game will crash
4) Repeat from step 1

### Stack trace:
```
java.lang.NullPointerException: Exception in server tick loop
	at com.ldtteam.structures.helpers.Structure.rotate(Structure.java:334) ~[?:0.10.167-ALPHA] {}
	at com.minecolonies.api.entity.mobs.util.MobEventsUtils.raiderEvent(MobEventsUtils.java:82) ~[?:0.10.356-ALPHA] {}
	at com.minecolonies.coremod.colony.Colony.onWorldTick(Colony.java:805) ~[?:0.10.356-ALPHA] {}
	at com.minecolonies.coremod.colony.ColonyManager.lambda$onWorldTick$2(ColonyManager.java:836) ~[?:0.10.356-ALPHA] {}
	at com.minecolonies.coremod.colony.ColonyManager$$Lambda$4227/861783068.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51] {}
	at com.minecolonies.coremod.colony.ColonyManager.onWorldTick(ColonyManager.java:836) ~[?:0.10.356-ALPHA] {}
	at com.minecolonies.coremod.event.FMLEventHandler.onWorldTick(FMLEventHandler.java:39) ~[?:0.10.356-ALPHA] {}
	at net.minecraftforge.eventbus.ASMEventHandler_59_FMLEventHandler_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostWorldTick(BasicEventHooks.java:99) ~[?:?] {}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:835) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:161) ~[?:?] {xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}
```

### System Details

```
-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5817380912 bytes (5547 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 3.2.0+60+b86c1d4
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.0.100.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.0.100.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.0.100.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.0.100.jar runtimedistcleaner PLUGINSERVICE 
		/OptiFine_1.14.4_HD_U_F4_pre5.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.14.4-28.0.100.jar fml TRANSFORMATIONSERVICE 
	FML: 28.0
	Forge: net.minecraftforge:28.0.100
	FML Language Providers: 
		javafml@28.0
		minecraft@1
	Mod List: 
		forgemod_VoxelMap-1.9.13b_for_1.14.4.jar VoxelMap {voxelmap@1.9.13 DONE}
		structurize-0.10.167-ALPHA.jar Structurize {structurize@unspecified DONE}
		minecolonies-0.10.356-ALPHA-universal.jar Minecolonies {minecolonies@1 DONE}
		tombstone-4.1.1-1.14.4.jar Corail Tombstone {tombstone@4.1.1 DONE}
		forge-1.14.4-28.0.100-universal.jar Forge {forge@28.0.100 DONE}
		forge-1.14.4-28.0.100-client.jar Minecraft {minecraft@1.14.4 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['Halithor'/85, l='The Colony', x=-351.12, y=56.00, z=688.57]]
	Data Packs: vanilla, mod:voxelmap, mod:tombstone, mod:structurize, mod:minecolonies (incompatible), mod:forge
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
```

**Comment by Raycoms** [comment]
Please update to the latest 1.14
