### ISSUE TITLE
Just clicked on a worker box and crashed to desktop

### ISSUE THREAD

**Issue by Howman** [ldtteam/minecolonies#3991]
### Minecolonies version

Version:  minecolonies-0.10.480-ALPHA-universal
Forge Version: forge-1.14.4-28.1.70-installer

### Expected behavior

For worker box to open and show options 

### Actual behaviour
Crash To desk top

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 10/26/19 6:19 PM
Description: Unexpected error

java.lang.NoClassDefFoundError: com/minecolonies/api/colony/permissions/Action
	at com.minecolonies.coremod.event.EventHandler.onPlayerInteract(EventHandler.java:320) ~[?:0.10.480-ALPHA] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_70_EventHandler_onPlayerInteract_RightClickBlock.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:782) ~[?:?] {re:classloading}
	at net.minecraft.client.multiplayer.PlayerController.func_217292_a(PlayerController.java:268) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.optifine.override.PlayerControllerOF.func_217292_a(PlayerControllerOF.java:98) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1236) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1488) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1321) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:869) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.1.70.jar:28.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$398/45416784.call(Unknown Source) [forge-1.14.4-28.1.70.jar:28.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?] {}
Caused by: java.lang.ClassNotFoundException: com.minecolonies.api.colony.permissions.Action
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:103) ~[modlauncher-4.1.0.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
	... 24 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.minecolonies.coremod.event.EventHandler.onPlayerInteract(EventHandler.java:320)
	at net.minecraftforge.eventbus.ASMEventHandler_70_EventHandler_onPlayerInteract_RightClickBlock.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:782)
	at net.minecraft.client.multiplayer.PlayerController.func_217292_a(PlayerController.java:268)
	at net.optifine.override.PlayerControllerOF.func_217292_a(PlayerControllerOF.java:98)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1236)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1488)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['HOWMAN_'/106, l='MpServer', x=-3488.49, y=63.94, z=22425.69]]
	Chunk stats: Client Chunk Cache: 729, 484
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 0
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (128,65,-16), Chunk: (at 0,4,0 in 8,-1; contains blocks 128,0,-16 to 143,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 6931935 game time, 4376016383 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:574)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1750)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:405)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$398/45416784.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6005361664 bytes (5727 MB) / 9663676416 bytes (9216 MB) up to 9663676416 bytes (9216 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx9G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=512M
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.70.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.70.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.70.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.70.jar runtimedistcleaner PLUGINSERVICE 
		/OptiFine_1.14.4_HD_U_F4.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.14.4-28.1.70.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.70
	FML Language Providers: 
		javafml@28.1
		minecraft@1
	Mod List: 
		forge-1.14.4-28.1.70-client.jar Minecraft {minecraft@1.14.4 DONE}
		angelblock-1.0a.jar Angel Block {angelblock@1.0a DONE}
		tubesreloaded-1.14.4-1.1.0c.jar Tubes Reloaded {tubesreloaded@1.14.4-1.1.0c DONE}
		structurize-0.10.194-ALPHA.jar Structurize {structurize@0.10.194-ALPHA DONE}
		Glowglass-1.14.4-1.1.jar Glowglass {glowglass@1.1 DONE}
		worldedit-forge-mc1.14.4-7.0.1.jar WorldEdit {worldedit@7.0.1;61bc012 DONE}
		BiomesOPlenty-1.14.4-9.0.0.255-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.254 DONE}
		minecolonies-0.10.480-ALPHA-universal.jar Minecolonies {minecolonies@0.10.480-ALPHA DONE}
		furniture-7.0.0-pre5-1.14.4.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre5 DONE}
		Vampirism-1.14.4-1.6.0-alpha+20191021-1133.jar Vampirism {vampirism@1.6.0-alpha+20191021-1127 DONE, teamlapenlib@1.6.0-alpha+20191021-1127 DONE}
		nifty-1.14.4-2.6.jar Nifty {nifty@2.6 DONE}
		metalbarrels-1.3d.jar Metal Barrels {metalbarrels@1.3d DONE}
		forge-1.14.4-28.1.70-universal.jar Forge {forge@28.1.70 DONE}
		ruins-1.14.4.4.jar Ruins {ruins@1.14.3.3 DONE}
		extragolems-9.0.2.jar Extra Golems {golems@TODO-golems_version DONE}
		Neat+1.5-19.jar Neat {neat@1.5-19 DONE}
		glassential-forge-1.14.4-1.1.1.jar Glassential {glassential@1.1.1 DONE}
		ironchest-1.14.4-9.0.4.jar Iron Chests {ironchest@1.14.3-9.0.3 DONE}
	Launched Version: 1.14.4-forge-28.1.70
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 1050/PCIe/SSE2 GL version 4.6.0 NVIDIA 440.97, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
	OptiFine Version: OptiFine_1.14.4_HD_U_F4
	OptiFine Build: 20191024-111639
	Render Distance Chunks: 15
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 440.97
	OpenGlRenderer: GeForce GTX 1050/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

### Steps to reproduce the problem
just click worker box like stonecutter

**Comment by Raycoms** [comment]
Could you try redownloading the jar and try again?

**Comment by Howman** [comment]
re downloaded and I tried again now i do not crash to desktop but nothing happens when i click on the workers box.

**Comment by Howman** [comment]
And if i go to replace the buildings ( sifter, stone mason,  stone smelter ) and i use the structureize  wand to place the buildings there not in the option with decorations

**Comment by Raycoms** [comment]
Should probably run loadBackup command, your previous colony was corrupted
by a corrupted jar it seems

**Comment by Howman** [comment]
on 1.14.4 /mc loadBackup will not work but I can place buildings with out the structureize wand maybe problem with  structurize ( -0.10.194-ALPHA )

**Comment by Raycoms** [comment]
its /mc colony loadbackup or similarly named, just tab through the option.

**Comment by Howman** [comment]
Well you may close this cause i just placed those building with out the structurize I do not want to lose my progress buy going to an earlier snapshot, what i find weird is it is just those 3 building i went around to all the others and the chest are working correctly as far as i can tell.

**Comment by Raycoms** [comment]
very weird, we'll monitor this and check if it happens more regularly

**Comment by someaddons** [comment]
"Java Version: 1.8.0_51, Oracle Corporation" you probably also should update your java, that version causes issues
