### ISSUE TITLE
Server gets into infinite loop when builder trying to build my custom sheme

### ISSUE THREAD

**Issue by PavelS0** [ldtteam/minecolonies#4101]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.488-RELEASE-universal

### Expected behavior

- Builder will build a scheme

### Actual behaviour

- Server crashed

### Steps to reproduce the problem

1. Scan simple scheme 2x2x2 cobblestone blocks.
2. Use build tool with scanned scheme to create request to build
3. When Builder accept request server after 60 sec crashed.

CrashLog:

```
Time: 24.11.19 1:41
Description: Watching Server

java.lang.Error: ServerHangWatchdog detected that a single server tick took 60,00 seconds (should be max 0.05)
	at java.util.IdentityHashMap.get(IdentityHashMap.java:337)
	at net.minecraftforge.registries.GameData$BlockCallbacks$1.get(GameData.java:387)
	at net.minecraftforge.registries.GameData$BlockCallbacks$1.func_148747_b(GameData.java:382)
	at net.minecraft.world.chunk.ChunkPrimer.func_177855_a(SourceFile:21)
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185976_a(ChunkGeneratorOverworld.java:163)
	at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185932_a(ChunkGeneratorOverworld.java:205)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143)
	at net.minecraft.world.World.func_72964_e(World.java:310)
	at net.minecraft.world.World.func_175726_f(World.java:305)
	at net.minecraft.world.World.func_180495_p(World.java:911)
	at com.minecolonies.api.util.BlockPosUtil.getBlock(BlockPosUtil.java:424)
	at com.minecolonies.api.entity.ai.util.StructureIterator.getCurrentBlock(StructureIterator.java:292)
	at com.minecolonies.api.entity.ai.util.StructureIterator.advanceBlocks(StructureIterator.java:262)
	at com.minecolonies.api.entity.ai.util.StructureIterator.advanceBlock(StructureIterator.java:227)
	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructure.lambda$generateStructureGenerator$2(AbstractEntityAIStructure.java:201)
	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructure$$Lambda$1440/1202112056.get(Unknown Source)
	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructure.lambda$generateStructureGenerator$3(AbstractEntityAIStructure.java:214)
	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructure$$Lambda$1441/774446884.get(Unknown Source)
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:77)
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:148)
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:131)
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:80)
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine$$Lambda$1491/809100881.test(Unknown Source)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:516)
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:62)
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:150)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:1086)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 5.0.0-36-generic
	Java Version: 1.8.0_222, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 156959440 bytes (149 MB) / 1528823808 bytes (1458 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 1 total; -Xmx2G
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 33 mods loaded, 33 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored      |
```

**Comment by Raycoms** [comment]
Can you send me that specific schematic?

November 23, 2019 8:27 PM, "PavelS0" <notifications@github.com (mailto:notifications@github.com?to=%22PavelS0%22%20<notifications@github.com>)> wrote:
Minecolonies version
	Version: minecolonies-1.12.2-0.10.488-RELEASE-universal

Expected behavior
	* Builder will build a scheme
Actual behaviour
	* Server crashed
Steps to reproduce the problem
	* Scan simple scheme 2x2x2 cobblestone blocks.
	* Use build tool with scanned scheme to create request to build
	* When Builder accept request server after 60 sec crashed.
	CrashLog:

	Time: 24.11.19 1:41 Description: Watching Server java.lang.Error: ServerHangWatchdog detected that a single server tick took 60,00 seconds (should be max 0.05) at java.util.IdentityHashMap.get(IdentityHashMap.java:337) at net.minecraftforge.registries.GameData$BlockCallbacks$1.get(GameData.java:387) at net.minecraftforge.registries.GameData$BlockCallbacks$1.func_148747_b(GameData.java:382) at net.minecraft.world.chunk.ChunkPrimer.func_177855_a(SourceFile:21) at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185976_a(ChunkGeneratorOverworld.java:163) at net.minecraft.world.gen.ChunkGeneratorOverworld.func_185932_a(ChunkGeneratorOverworld.java:205) at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143) at net.minecraft.world.World.func_72964_e(World.java:310) at net.minecraft.world.World.func_175726_f(World.java:305) at net.minecraft.world.World.func_180495_p(World.java:911) at com.minecolonies.api.util.BlockPosUtil.getBlock(BlockPosUtil.java:424) at com.minecolonies.api.entity.ai.util.StructureIterator.getCurrentBlock(StructureIterator.java:292) at com.minecolonies.api.entity.ai.util.StructureIterator.advanceBlocks(StructureIterator.java:262) at com.minecolonies.api.entity.ai.util.StructureIterator.advanceBlock(StructureIterator.java:227) at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructure.lambda$generateStructureGenerator$2(AbstractEntityAIStructure.java:201) at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructure$$Lambda$1440/1202112056.get(Unknown Source) at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructure.lambda$generateStructureGenerator$3(AbstractEntityAIStructure.java:214) at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructure$$Lambda$1441/774446884.get(Unknown Source) at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:77) at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:148) at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:131) at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:80) at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine$$Lambda$1491/809100881.test(Unknown Source) at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359) at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499) at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486) at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:516) at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:62) at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:150) at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129) at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:763) at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359) at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577) at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178) at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:1086) at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179) at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) at net.minecraft.world.World.func_72866_a(World.java:1996) at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) at net.minecraft.world.World.func_72870_g(World.java:1958) at net.minecraft.world.World.func_72939_s(World.java:1762) at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) at java.lang.Thread.run(Thread.java:748) Minecraft Version: 1.12.2 Operating System: Linux (amd64) version 5.0.0-36-generic Java Version: 1.8.0_222, Private Build Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build Memory: 156959440 bytes (149 MB) / 1528823808 bytes (1458 MB) up to 1908932608 bytes (1820 MB) JVM Flags: 1 total; -Xmx2G IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95 FML: MCP 9.42 Powered by Forge 14.23.5.2847 33 mods loaded, 33 mods active States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored |

**Comment by PavelS0** [comment]
Yep.
This is blueprint from client
https://drive.google.com/open?id=1qxjNSSgLzGnmL7SGLr_K9wYe4BpGWKGp
And this from server cache
https://drive.google.com/open?id=1gFE_or2rnyutENRmjCm1WWMZK2I5JoOa

**Comment by PavelS0** [comment]
After some research i realized that the problem was in my world. I create new world reproduce my colony in crative and.... Its working perfectly! Weird.
