### ISSUE TITLE
Builder is unable to finish building even on 100%

### ISSUE THREAD

**Issue by TheGreyRaven** [ldtteam/minecolonies#4154]
### Minecolonies version

Version: 1.14.4 (Using the modpack Valhelsia from Curse)

### Expected behavior

The builder should complete the building when it reaches 100%.
- 

### Actual behaviour

The builder completes the house and tells me in the chat that he has finished the building, but he does not fully complete the building. When inspecting the building it says 100% but there is a cancel building button and the fence outside the area are still present.
- 

### Steps to reproduce the problem

I do not have any steps to reproduce the error since I am not sure how it appeared in the first place, but this is the server error I get when the builder tries to finish,

Also there is another issue that might not be related to this 'bug', the builder tool does not show the buldings hologram when selecting for example a warehouse its just nothing there. Also that problem I do not have any steps to reproduce since they just appeared out of nowhere.

https://pastebin.com/SEG68Mce

`[m[33m[17:36:43] [Server thread/WARN] [minecolonies/]: Statemachine for transition com.minecolonies.api.entity.ai.statemachine.AITarget@69af2270 threw an exception:
java.lang.NullPointerException: null
        at com.minecolonies.api.advancements.complete_build_request.CompleteBuildRequestTrigger.trigger(CompleteBuildRequestTrigger.java:23) ~[?:0.10.574-ALPHA] {re:classloading}
        at com.minecolonies.coremod.colony.workorders.WorkOrderBuildDecoration.lambda$onCompleted$0(WorkOrderBuildDecoration.java:251) ~[?:0.10.574-ALPHA] {re:classloading}
        at com.minecolonies.coremod.util.AdvancementUtils.TriggerAdvancementPlayersForColony(AdvancementUtils.java:28) ~[?:0.10.574-ALPHA] {re:classloading}
        at com.minecolonies.coremod.colony.workorders.WorkOrderBuildDecoration.onCompleted(WorkOrderBuildDecoration.java:250) ~[?:0.10.574-ALPHA] {re:classloading}
        at com.minecolonies.coremod.colony.workorders.WorkOrderBuild.onCompleted(WorkOrderBuild.java:214) ~[?:0.10.574-ALPHA] {re:classloading}
        at com.minecolonies.coremod.colony.jobs.AbstractJobStructure.complete(AbstractJobStructure.java:120) ~[?:0.10.574-ALPHA] {re:classloading}
        at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructureWithWorkOrder.executeSpecificCompleteActions(AbstractEntityAIStructureWithWorkOrder.java:346) ~[?:0.10.574-ALPHA] {re:classloading}
        at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructure.completeBuild(AbstractEntityAIStructure.java:336) ~[?:0.10.574-ALPHA] {re:classloading}
        at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:77) ~[?:0.10.574-ALPHA] {re:classloading}
        at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:148) ~[?:0.10.574-ALPHA] {re:classloading}
        at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:131) ~[?:0.10.574-ALPHA] {re:classloading}
        at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:124) ~[?:0.10.574-ALPHA] {re:classloading}
        at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:103) ~[?:0.10.574-ALPHA] {re:classloading}
        at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:137) ~[?:0.10.574-ALPHA] {re:classloading}
        at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?] {re:classloading}
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:1.8.0_211] {}
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_211] {}
        at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:1.8.0_211] {}
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_211] {}
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_211] {}
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_211] {}
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_211] {}
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_211] {}
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_211] {}
        at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_211] {}
        at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:80) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:590) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2186) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:apotheosis:apothpotiondmg,xf:fml:caelus:coremodone,pl:runtimedistcleaner:A}
        at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:460) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:140) ~[?:?] {re:classloading}
        at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:1069) ~[?:0.10.574-ALPHA] {re:classloading}
        at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2032) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:apotheosis:apothpotiondmg,xf:fml:caelus:coremodone,pl:runtimedistcleaner:A}
        at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:587) ~[?:?] {re:classloading,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook,pl:runtimedistcleaner:A}
        at net.minecraft.world.World.func_217390_a(World.java:684) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:394) [?:?] {re:classloading,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:324) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211] {}
[m[1;31m[17:36:43] [Server thread/ERROR] [minecolonies/]: Pausing Entity Benedict L. Ashton (com.minecolonies.coremod.job.Builder) at BlockPos{x=264, y=64, z=-49} for 800 Seconds because of error:
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]: java.lang.NullPointerException
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at com.minecolonies.api.advancements.complete_build_request.CompleteBuildRequestTrigger.trigger(CompleteBuildRequestTrigger.java:23)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at com.minecolonies.coremod.colony.workorders.WorkOrderBuildDecoration.lambda$onCompleted$0(WorkOrderBuildDecoration.java:251)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at com.minecolonies.coremod.util.AdvancementUtils.TriggerAdvancementPlayersForColony(AdvancementUtils.java:28)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at com.minecolonies.coremod.colony.workorders.WorkOrderBuildDecoration.onCompleted(WorkOrderBuildDecoration.java:250)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at com.minecolonies.coremod.colony.workorders.WorkOrderBuild.onCompleted(WorkOrderBuild.java:214)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at com.minecolonies.coremod.colony.jobs.AbstractJobStructure.complete(AbstractJobStructure.java:120)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructureWithWorkOrder.executeSpecificCompleteActions(AbstractEntityAIStructureWithWorkOrder.java:346)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructure.completeBuild(AbstractEntityAIStructure.java:336)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:77)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:148)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:131)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:124)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:103)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:137)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at java.util.Iterator.forEachRemaining(Unknown Source)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at java.util.stream.ReferencePipeline.forEach(Unknown Source)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:80)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:590)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2186)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:460)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:140)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:1069)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2032)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:587)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at net.minecraft.world.World.func_217390_a(World.java:684)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:394)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:324)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622)
[m[32m[17:36:43] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:334]:    at java.lang.Thread.run(Unknown Source)`

**Comment by someaddons** [comment]
should be fixed in the newest 1.14

**Comment by TheGreyRaven** [comment]
Okay thank you @someaddons regarding the hologram issue I get this error:
`[m[32m[17:58:05] [Server thread/INFO] [mi.re.1/]: Removing provider: StandardToken{id=bb09324f-5cf9-4df6-8213-11d1832fea25}
[m[1;31m[17:59:16] [Server thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Server
java.lang.NullPointerException: null
        at com.minecolonies.api.advancements.place_structure.PlaceStructureTrigger.trigger(PlaceStructureTrigger.java:23) ~[?:0.10.574-ALPHA] {re:classloading}
        at com.minecolonies.coremod.network.messages.BuildToolPlaceMessage.lambda$handleHut$0(BuildToolPlaceMessage.java:225) ~[?:0.10.574-ALPHA] {re:classloading}
        at com.minecolonies.coremod.util.AdvancementUtils.TriggerAdvancementPlayersForColony(AdvancementUtils.java:28) ~[?:0.10.574-ALPHA] {re:classloading}
        at com.minecolonies.coremod.network.messages.BuildToolPlaceMessage.handleHut(BuildToolPlaceMessage.java:225) ~[?:0.10.574-ALPHA] {re:classloading}
        at com.minecolonies.coremod.network.messages.BuildToolPlaceMessage.onExecute(BuildToolPlaceMessage.java:180) ~[?:0.10.574-ALPHA] {re:classloading}
        at com.minecolonies.coremod.network.NetworkChannel.lambda$null$3(NetworkChannel.java:179) ~[?:0.10.574-ALPHA] {re:classloading}
        at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[?:?] {re:classloading}
        at com.minecolonies.coremod.network.NetworkChannel.lambda$registerMessage$4(NetworkChannel.java:179) ~[?:0.10.574-ALPHA] {re:classloading}
        at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:124) ~[?:?] {re:classloading}
        at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_211] {}
        at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:124) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:157) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:79) ~[?:?] {re:classloading}
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-1.0.0-service.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-1.0.0-service.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
        at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$0(NetworkHooks.java:74) ~[?:?] {re:classloading}
        at java.util.Optional.map(Unknown Source) ~[?:1.8.0_211] {}
        at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:74) ~[?:?] {re:classloading}
        at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1275) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches ServerPlayNetHandler Transformer}
        at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?] {re:classloading}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:699) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:693) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:679) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:626) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211] {}
[m`
Is that also fixed with the latest version?

**Comment by someaddons** [comment]
ye should be :)
