### ISSUE TITLE
Unknow error appears in log

### ISSUE THREAD

**Issue by shivachirr** [ldtteam/minecolonies#424]
### Minecolonies version

curse 1.10.2-0.6.2115

### Expected behavior

no error

### Actual behaviour

error appears in logs

### Steps to reproduce the problem
Unknown

Error Follows

`[08:46:16] [Server thread/WARN] [minecolonies]: Action for target com.minecolonies.coremod.entity.ai.util.AITarget@5a7b3fc threw an exception:
java.lang.ArrayIndexOutOfBoundsException: -1
	at com.minecolonies.coremod.inventory.InventoryCitizen.func_70301_a(InventoryCitizen.java:499) ~[InventoryCitizen.class:?]
	at com.minecolonies.coremod.entity.EntityCitizen.setHeldItem(EntityCitizen.java:1388) ~[EntityCitizen.class:?]
	at com.minecolonies.coremod.entity.ai.citizen.farmer.EntityAIWorkFarmer.equipHoe(EntityAIWorkFarmer.java:618) ~[EntityAIWorkFarmer.class:?]
	at com.minecolonies.coremod.entity.ai.citizen.farmer.EntityAIWorkFarmer.hoeIfAble(EntityAIWorkFarmer.java:544) ~[EntityAIWorkFarmer.class:?]
	at com.minecolonies.coremod.entity.ai.citizen.farmer.EntityAIWorkFarmer.initialize(EntityAIWorkFarmer.java:508) ~[EntityAIWorkFarmer.class:?]
	at com.minecolonies.coremod.entity.ai.util.AITarget.apply(AITarget.java:125) ~[AITarget.class:?]
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.applyTarget(AbstractAISkeleton.java:203) ~[AbstractAISkeleton.class:?]
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.checkOnTarget(AbstractAISkeleton.java:176) ~[AbstractAISkeleton.class:?]
	at java.util.stream.MatchOps$1MatchSink.accept(Unknown Source) [?:1.8.0_111]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source) [?:1.8.0_111]
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) [?:1.8.0_111]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) [?:1.8.0_111]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) [?:1.8.0_111]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) [?:1.8.0_111]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source) [?:1.8.0_111]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source) [?:1.8.0_111]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) [?:1.8.0_111]
	at java.util.stream.ReferencePipeline.anyMatch(Unknown Source) [?:1.8.0_111]
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:129) [AbstractAISkeleton.class:?]
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129) [tr.class:?]
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:900) [sg.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2183) [sf.class:?]
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:685) [sg.class:?]
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:155) [rt.class:?]
	at com.minecolonies.coremod.entity.EntityCitizen.func_70636_d(EntityCitizen.java:812) [EntityCitizen.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013) [sf.class:?]
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:384) [sg.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1964) [aid.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839) [ls.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1934) [aid.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1750) [aid.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620) [ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
[08:46:16] [Server thread/INFO] [minecolonies]: Pausing Entity for 5 Seconds
`

**Comment by Raycoms** [comment]
Thanks for the report. Your farmer doesn't seem to have a hoe.
I added a fix but will push it altogether with some new code in the next days.
