### ISSUE TITLE
Server Crash, and subsequent crash on startup, due to ClassCastException

### ISSUE THREAD

**Issue by AGeyster** [ldtteam/minecolonies#4243]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.592-RELEASE-universal.jar

### Expected behavior

- Minecraft Server maintains uptime when logged off with loaded chunks.

### Actual behaviour

- While server was online and Minecolonies chunks were loaded through ForgeUtil a Colony member reached a position where its pathfinding caused an outage. 

The location of the Minecolonies Villager is the empty block space with a red square marked in the image below:
![image](https://user-images.githubusercontent.com/4007368/72670133-f0f52080-3a07-11ea-86e9-f9c645e6504f.png)

Call Stack:
Time: 1/18/20 8:22 PM
Description: Ticking entity

java.lang.ClassCastException: net.minecraft.pathfinding.PathPoint cannot be cast to com.minecolonies.coremod.entity.pathfinding.PathPointExtended
	at com.minecolonies.coremod.entity.pathfinding.MinecoloniesAdvancedPathNavigate.func_75508_h(MinecoloniesAdvancedPathNavigate.java:415)
	at net.minecraft.pathfinding.PathNavigate.func_75501_e(SourceFile:188)
	at com.minecolonies.coremod.entity.pathfinding.MinecoloniesAdvancedPathNavigate.func_75501_e(MinecoloniesAdvancedPathNavigate.java:128)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:766)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2350)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:1059)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.Entity.func_70098_U(Entity.java:2013)
	at net.minecraft.entity.EntityLivingBase.func_70098_U(EntityLivingBase.java:2480)
	at net.minecraft.world.World.func_72866_a(World.java:1985)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72866_a(World.java:2050)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.minecolonies.coremod.entity.pathfinding.MinecoloniesAdvancedPathNavigate.func_75508_h(MinecoloniesAdvancedPathNavigate.java:415)
	at net.minecraft.pathfinding.PathNavigate.func_75501_e(SourceFile:188)
	at com.minecolonies.coremod.entity.pathfinding.MinecoloniesAdvancedPathNavigate.func_75501_e(MinecoloniesAdvancedPathNavigate.java:128)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:766)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2350)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:1059)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.entity.Entity.func_70098_U(Entity.java:2013)
	at net.minecraft.entity.EntityLivingBase.func_70098_U(EntityLivingBase.java:2480)
	at net.minecraft.world.World.func_72866_a(World.java:1985)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)
	at net.minecraft.world.World.func_72866_a(World.java:2050)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1952)

-- Entity being ticked --
Details:
	Entity Type: minecolonies:sitting_entity (com.minecolonies.coremod.entity.SittingEntity)
	Entity ID: 1368
	Entity Name: entity.SITTING_ENTITY.name
	Entity's Exact location: -405.73, 68.00, -52.49
	Entity's Block location: World: (-406,68,-53), Chunk: (at 10,4,11 in -26,-4; contains blocks -416,0,-64 to -401,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: [EntityCitizen['Isabella T. Askew'/730, l='world', x=-405.73, y=68.38, z=-52.49]]
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1756)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: world
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 1588 Drop: 0
	Level seed: 1137625204
	Level generator: ID 06 - quark_realistic, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-176,64,236), Chunk: (at 0,4,12 in -11,14; contains blocks -176,0,224 to -161,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 510268259 game time, 512061231 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 21713 (now: false), thunder time: 139943 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.9.0-11-amd64
	Java Version: 1.8.0_222, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
	Memory: 1440904320 bytes (1374 MB) / 4519362560 bytes (4310 MB) up to 9544663040 bytes (9102 MB)
	JVM Flags: 2 total; -Xmx10240M -Xms512M
	IntCache: cache: 0, tcache: 0, allocated: 7, tallocated: 112
	FML: MCP 9.42 Powered by Forge 14.23.4.2707 250 mods loaded, 250 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

### Steps to reproduce the problem

1.  Left entire Minecolony chunk loaded, note this was not on any chunk boundaries or chunk loading boundaries.
2.  Villager sat in the bottom of the Minecolony guard tower for Barracks structure.
3.  I believe this sitting Villager shared a space with a tile_entity from Blood Magic of a Blood Lamp
4. ... Profit - Server Crashed and would not restart.

In order to resolve the crash and restart the server successfully I moved the minecolonies:sitting_entity with MC_Edit to a completed open space a few blocks away and made sure it was floating above the ground as per MC_Edit the Villager had the same y-level as the actual ground block.

I do not know if moving away from the Blood Lamp or moving out of the ground resolved this as I did both steps at once.

**Comment by someaddons** [comment]
fixed in the newest version
