### ISSUE TITLE
Error building new Minecolonies buildings, builder tool crashes game

### ISSUE THREAD

**Issue by CmdrWinters** [ldtteam/minecolonies#4277]
### Minecolonies version

Version: 0.10.656-ALPHA

### Expected behavior

- Builder should be building the huts/buildings correlating to the block given

### Actual behaviour

- Builder is instead building supply camps on every single lot, so far the builder's hut and the town hall.
Also, using the building tool crashes the game.

https://youtu.be/nqj_dSJwBjI

###Crashlog from using builder tool

---- Minecraft Crash Report ----
// Why did you do that?

Time: 1/26/20 3:44 PM
Description: Unexpected error

com.google.common.util.concurrent.UncheckedExecutionException: net.minecraft.crash.ReportedException: Tesselating liquid in world
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217) ~[guava-21.0.jar:?] {}
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[guava-21.0.jar:?] {}
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:5060) ~[guava-21.0.jar:?] {}
	at com.ldtteam.structures.client.BlueprintHandler.draw(BlueprintHandler.java:80) ~[?:0.10.210-ALPHA] {re:classloading}
	at com.ldtteam.structures.client.StructureClientHandler.renderStructure(StructureClientHandler.java:32) ~[?:0.10.210-ALPHA] {re:classloading}
	at com.ldtteam.structures.client.StructureClientHandler.renderStructure(StructureClientHandler.java:22) ~[?:0.10.210-ALPHA] {re:classloading}
	at com.ldtteam.structurize.event.ClientEventSubscriber.renderWorldLastEvent(ClientEventSubscriber.java:42) ~[?:0.10.210-ALPHA] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_106_ClientEventSubscriber_renderWorldLastEvent_RenderWorldLastEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:177) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:603) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:423) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:882) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:520) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:202) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.1-30.0.36.jar:30.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$399/688581408.call(Unknown Source) [forge-1.15.1-30.0.36.jar:30.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}
Caused by: net.minecraft.crash.ReportedException: Tesselating liquid in world
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_228794_a_(BlockRendererDispatcher.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.ldtteam.structures.client.BlueprintRenderer.lambda$setup$2(BlueprintRenderer.java:108) ~[?:0.10.210-ALPHA] {re:classloading}
	at com.ldtteam.structures.client.BlueprintRenderer$$Lambda$6422/561822941.accept(Unknown Source) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_51] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51] {}
	at com.ldtteam.structures.client.BlueprintRenderer.setup(BlueprintRenderer.java:91) ~[?:0.10.210-ALPHA] {re:classloading}
	at com.ldtteam.structures.client.BlueprintRenderer.<init>(BlueprintRenderer.java:73) ~[?:0.10.210-ALPHA] {re:classloading}
	at com.ldtteam.structures.client.BlueprintRenderer.buildRendererForBlueprint(BlueprintRenderer.java:56) ~[?:0.10.210-ALPHA] {re:classloading}
	at com.ldtteam.structures.client.BlueprintHandler.lambda$draw$1(BlueprintHandler.java:80) ~[?:0.10.210-ALPHA] {re:classloading}
	at com.ldtteam.structures.client.BlueprintHandler$$Lambda$6409/1699726407.call(Unknown Source) ~[?:?] {}
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:5065) ~[guava-21.0.jar:?] {}
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[guava-21.0.jar:?] {}
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[guava-21.0.jar:?] {}
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[guava-21.0.jar:?] {}
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[guava-21.0.jar:?] {}
	... 26 more
Caused by: java.lang.NullPointerException
	at net.minecraft.world.biome.BiomeColors.func_228360_a_(SourceFile:11) ~[?:?] {re:classloading}
	at net.minecraft.world.biome.BiomeColors$$Lambda$5805/1392409615.getColor(Unknown Source) ~[?:?] {}
	at net.minecraft.world.IWorldReader.func_225525_a_(IWorldReader.java:39) ~[?:?] {re:classloading}
	at net.minecraft.world.biome.BiomeColors.func_228359_a_(SourceFile:14) ~[?:?] {re:classloading}
	at net.minecraft.world.biome.BiomeColors.func_228363_c_(SourceFile:26) ~[?:?] {re:classloading}
	at net.minecraftforge.fluids.FluidAttributes$Water.getColor(FluidAttributes.java:446) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.FluidBlockRenderer.func_228796_a_(FluidBlockRenderer.java:61) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_228794_a_(BlockRendererDispatcher.java:73) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.ldtteam.structures.client.BlueprintRenderer.lambda$setup$2(BlueprintRenderer.java:108) ~[?:0.10.210-ALPHA] {re:classloading}
	at com.ldtteam.structures.client.BlueprintRenderer$$Lambda$6422/561822941.accept(Unknown Source) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_51] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51] {}
	at com.ldtteam.structures.client.BlueprintRenderer.setup(BlueprintRenderer.java:91) ~[?:0.10.210-ALPHA] {re:classloading}
	at com.ldtteam.structures.client.BlueprintRenderer.<init>(BlueprintRenderer.java:73) ~[?:0.10.210-ALPHA] {re:classloading}
	at com.ldtteam.structures.client.BlueprintRenderer.buildRendererForBlueprint(BlueprintRenderer.java:56) ~[?:0.10.210-ALPHA] {re:classloading}
	at com.ldtteam.structures.client.BlueprintHandler.lambda$draw$1(BlueprintHandler.java:80) ~[?:0.10.210-ALPHA] {re:classloading}
	at com.ldtteam.structures.client.BlueprintHandler$$Lambda$6409/1699726407.call(Unknown Source) ~[?:?] {}
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:5065) ~[guava-21.0.jar:?] {}
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[guava-21.0.jar:?] {}
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[guava-21.0.jar:?] {}
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[guava-21.0.jar:?] {}
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[guava-21.0.jar:?] {}
	... 26 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:5060)
	at com.ldtteam.structures.client.BlueprintHandler.draw(BlueprintHandler.java:80)
	at com.ldtteam.structures.client.StructureClientHandler.renderStructure(StructureClientHandler.java:32)
	at com.ldtteam.structures.client.StructureClientHandler.renderStructure(StructureClientHandler.java:22)
	at com.ldtteam.structurize.event.ClientEventSubscriber.renderWorldLastEvent(ClientEventSubscriber.java:42)
	at net.minecraftforge.eventbus.ASMEventHandler_106_ClientEventSubscriber_renderWorldLastEvent_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:177)
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:603)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['CmdrWinters'/4883, l='MpServer', x=-54.84, y=64.00, z=-830.25]]
	Chunk stats: Client Chunk Cache: 1225, 899
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: -3606615888893475271
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (236,63,152), Chunk: (at 12,3,8 in 14,9; contains blocks 224,0,144 to 239,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 462678 game time, 155923 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:442)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1698)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:539)
	at net.minecraft.client.main.Main.main(SourceFile:202)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$399/688581408.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.1
	Minecraft Version ID: 1.15.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 517213088 bytes (493 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.1-30.0.36.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.1-30.0.36.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.0-milestone.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.1-30.0.36.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.1-30.0.36.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.1-30.0.36.jar fml TRANSFORMATIONSERVICE 
	FML: 30.0
	Forge: net.minecraftforge:30.0.36
	FML Language Providers: 
		javafml@30.0
		minecraft@1
	Mod List: 
		forge-1.15.1-30.0.36-client.jar Minecraft {minecraft@1.15.1 DONE}
		mcw-bridges-1.0.3-mc1.15.1.jar Macaw's Bridges {mcwbridges@1.0.3 DONE}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		Biomes-O-Plenty-Mod-1.15.1.jar Biomes O' Plenty {biomesoplenty@1.15.1-10.0.0.263 DONE}
		Project-Vibrant-Journeys-Mod-1.15.1.jar Project: Vibrant Journeys {projectvibrantjourneys@2.0.0 DONE}
		mining-helmet-1.15.1-1.0.2.jar Mining Helmet {mining_helmet@1.0.2 DONE}
		valhelsia_structures-1.15.1-0.0.1.jar Valhelsia Structures {valhelsia_structures@1.15.1-0.0.1 DONE}
		jei-1.15.1-6.0.0.1.jar Just Enough Items {jei@6.0.0.1 DONE}
		Simply-Light-Mod-1.15.1.jar Simply Light {simplylight@1.15.1-0.9.0 DONE}
		Corail-Woodcutter-Mod-1.15.1.jar Corail Woodcutter {corail_woodcutter@1.0.7 DONE}
		Xaeros_Minimap_1.19.7_Forge_1.15.1.jar Xaero's Minimap {xaerominimap@1.19.7 DONE}
		MoreOresInONE-1.0b_1.15.1.jar More Ores in ONE {moreoresinone@1.0b DONE}
		World-Map-Mod-1.15.1.jar Xaero's World Map {xaeroworldmap@1.5.3 DONE}
		Placebo-1.15.1-3.0.0.jar Placebo {placebo@3.0.0 DONE}
		Natures-Compass-Mod-1.15.1.jar Nature's Compass {naturescompass@1.15.1-1.8.3 DONE}
		corail_pillar_extension_biomesoplenty-4.2.1-1.15.1.jar Corail Pillar - Biomes O'Plenty Extension {corail_pillar_extension_biomesoplenty@4.2.1 DONE}
		Structurize-Mod-1.15.1.jar Structurize {structurize@0.10.210-ALPHA DONE}
		minecolonies-0.10.656-ALPHA-universal.jar Minecolonies {minecolonies@0.10.656-ALPHA DONE}
		Apotheosis-1.15.1-3.0.2.jar Apotheosis {apotheosis@3.0.2 DONE}
		forge-1.15.1-30.0.36-universal.jar Forge {forge@30.0.36 DONE}
		Aquaculture-1.15.1-2.0.6.jar Aquaculture 2 {aquaculture@1.15.1-2.0.6 DONE}
		ruins-1.15.1.3.jar Ruins {ruins@1.15.1.3 DONE}
		absentbydesign-1.15.1-1.0.5.jar Absent By Design Mod {absentbydesign@1.15.1-1.0.5 DONE}
		SuperTools-1.0b_1.15.1.jar Super Tools {supertools@1.0b DONE}
		corail_pillar-4.5.4-1.15.1.jar Corail Pillar {corail_pillar@4.5.4 DONE}
		Cyclic-1.15.1-0.1.4.jar Cyclic {cyclic@1.15.1-0.1.4 DONE}
	Launched Version: 1.15.1-forge-30.0.36
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060/PCIe/SSE2 GL version 4.6.0 NVIDIA 431.60, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: mod_resources (incompatible), vanilla, file/fWhip+1.15+.zip
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz

**Comment by Asherslab** [comment]
Please put logs in a https://gist.github.com

**Comment by Raycoms** [comment]
Can you try the newest structurize 1.15 version?

Am Mo., 27. Jan. 2020 um 10:59 Uhr schrieb AshersLab <
notifications@github.com>:

**Comment by Raycoms** [comment]
Should be fixed in latest structurize
