### ISSUE TITLE
Problem when trying to logon to dedicated server 

### ISSUE THREAD

**Issue by Howman** [ldtteam/minecolonies#4289]
### Minecolonies version
minecolonies-1.12.2-0.10.671-ALPHA-universal
### Expected behavior
To work when i log on to server
### Actual behaviour
[22:19:51] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.ClassCastException: net.minecraft.pathfinding.PathPoint cannot be cast to com.minecolonies.coremod.entity.pathfinding.PathPointExtended
	at com.minecolonies.coremod.entity.pathfinding.MinecoloniesAdvancedPathNavigate.func_75508_h(MinecoloniesAdvancedPathNavigate.java:436) ~[MinecoloniesAdvancedPathNavigate.class:?]
	at net.minecraft.pathfinding.PathNavigate.func_75501_e(SourceFile:188) ~[ze.class:?]
	at com.minecolonies.coremod.entity.pathfinding.MinecoloniesAdvancedPathNavigate.func_75501_e(MinecoloniesAdvancedPathNavigate.java:128) ~[MinecoloniesAdvancedPathNavigate.class:?]
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:766) ~[vq.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359) ~[vp.class:?]
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577) ~[vq.class:?]
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178) ~[vd.class:?]
	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:1058) ~[EntityCitizen.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179) ~[vp.class:?]
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) ~[vq.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1996) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) ~[oo.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1958) ~[amu.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1762) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]

### Steps to reproduce the problem
just try to logon and crash

**Comment by Raycoms** [comment]
@someaddons

**Comment by Raycoms** [comment]
Wasn't this fixed?

**Comment by Howman** [comment]
From the Crah Report it tells me that colonist Rose F. Goodenouth is causing my problems 

So I tryed /mc citizens kill colony: 1 citizen: Rose F. Goodenouth on server but it did not work
 i get in server /mineColonies citizens kill <colony: colony-id>: invalid value '1' for required argument colony
   

---- Minecraft Crash Report ----

WARNING: coremods are present:
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 02/02/20 1:56 PM
XRay version: 58
Description: Ticking entity

java.lang.ClassCastException: net.minecraft.pathfinding.PathPoint cannot be cast to com.minecolonies.coremod.entity.pathfinding.PathPointExtended
	at com.minecolonies.coremod.entity.pathfinding.MinecoloniesAdvancedPathNavigate.func_75508_h(MinecoloniesAdvancedPathNavigate.java:436)
	at net.minecraft.pathfinding.PathNavigate.func_75501_e(SourceFile:188)
	at com.minecolonies.coremod.entity.pathfinding.MinecoloniesAdvancedPathNavigate.func_75501_e(MinecoloniesAdvancedPathNavigate.java:128)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:766)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:1058)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.minecolonies.coremod.entity.pathfinding.MinecoloniesAdvancedPathNavigate.func_75508_h(MinecoloniesAdvancedPathNavigate.java:436)
	at net.minecraft.pathfinding.PathNavigate.func_75501_e(SourceFile:188)
	at com.minecolonies.coremod.entity.pathfinding.MinecoloniesAdvancedPathNavigate.func_75501_e(MinecoloniesAdvancedPathNavigate.java:128)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:766)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:1058)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: minecolonies:citizen (com.minecolonies.coremod.entity.citizen.EntityCitizen)
	Entity ID: 430
	Entity Name: Rose F. Goodenouth
	Entity's Exact location: 6784.28, 69.00, 22123.32
	Entity's Block location: World: (6784,69,22123), Chunk: (at 0,4,11 in 424,1382; contains blocks 6784,0,22112 to 6799,255,22127), Region: (13,43; contains chunks 416,1376 to 447,1407, blocks 6656,0,22016 to 7167,255,22527)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: mountainlionkittykatkers
	All players: 1 total; [EntityPlayerMP['HOWMAN_'/347, l='mountainlionkittykatkers', x=6814.50, y=52.84, z=22154.20]]
	Chunk stats: ServerChunkCache: 959 Drop: 0
	Level seed: -6712753192105077325
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-204,64,337), Chunk: (at 4,4,1 in -13,21; contains blocks -208,0,336 to -193,255,351), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 7977761 game time, 7977761 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 75418 (now: false), thunder time: 117779 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 14863118344 bytes (14174 MB) / 15689842688 bytes (14963 MB) up to 15689842688 bytes (14963 MB)
	JVM Flags: 2 total; -Xmx15000M -Xms15000M
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 51 mods loaded, 51 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                     | Version                | Source                                                       | Signature                                |
	|:------ |:---------------------- |:---------------------- |:------------------------------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft              | 1.12.2                 | minecraft.jar                                                | None                                     |
	| LCHIJA | mcp                    | 9.42                   | minecraft.jar                                                | None                                     |
	| LCHIJA | FML                    | 8.0.99.99              | forge-1.12.2-14.23.5.2847-universal.jar                      | None                                     |
	| LCHIJA | forge                  | 14.23.5.2847           | forge-1.12.2-14.23.5.2847-universal.jar                      | None                                     |
	| LCHIJA | movillages             | 1.5.4                  | [1.12]MoVillages-1.5.4.jar                                   | None                                     |
	| LCHIJA | bedrockminer           | 1.0.5                  | BedrockMiner-1.12.2-(v.1.0.5).jar                            | None                                     |
	| LCHIJA | bedrockplus            | 0.7.5                  | bedrockplus-0.7.5.jar                                        | ac38a3286ab9f4777b0023f0f6280caa9369d575 |
	| LCHIJA | bettergolem            | 1.0                    | bettergolem-1.12.2-1.0.jar                                   | None                                     |
	| LCHIJA | biomesoplenty          | 7.0.1.2444             | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar                | None                                     |
	| LCHIJA | ceilingtorch           | v1.2.1                 | ceilingtorch-1.12.2-v1.2.1.jar                               | None                                     |
	| LCHIJA | chesttransporter       | 2.8.8                  | ChestTransporter-1.12.2-2.8.8.jar                            | None                                     |
	| LCHIJA | customnpcs             | 1.12                   | Custom-NPCs-Mod-1.12.2.jar                                   | None                                     |
	| LCHIJA | diamondglass           | 1.12.2-3.3.18          | diamondglass-1.12.2-3.3.18.jar                               | None                                     |
	| LCHIJA | doubledoors            | 1.2                    | doubledoors_1.12-1.2.jar                                     | None                                     |
	| LCHIJA | dynamictrees           | 1.12.2-0.9.7           | DynamicTrees-1.12.2-0.9.7.jar                                | None                                     |
	| LCHIJA | dynamictreesbop        | 1.12.2-1.4.1e          | DynamicTreesBOP-1.12.2-1.4.1e.jar                            | None                                     |
	| LCHIJA | extraglass             | 1.20                   | extra-glass-1.20.jar                                         | None                                     |
	| LCHIJA | golems                 | 7.1.8                  | ExtraGolems-1.12-7.1.8.jar                                   | None                                     |
	| LCHIJA | familiarfauna          | 1.0.11                 | FamiliarFauna-1.12.2-1.0.11.jar                              | None                                     |
	| LCHIJA | com.boydti.fawe        | 3.5.1                  | FastAsyncWorldEdit-forge112-19.11.13-5505943-1282-22.3.5.jar | None                                     |
	| LCHIJA | faufil                 | 1.0.2                  | Faucets+and+Filters-1.0.2.jar                                | None                                     |
	| LCHIJA | cfm                    | 6.3.1                  | furniture-6.3.1-1.12.2.jar                                   | None                                     |
	| LCHIJA | ghostsexplosives       | 2.3.0 - MC 1.12.2      | Ghost's+Explosives+2.3.0+-+MC1.12.2.jar                      | None                                     |
	| LCHIJA | hopperducts            | 1.5                    | hopperducts-mc1.12-1.5.jar                                   | None                                     |
	| LCHIJA | ironchest              | 1.12.2-7.0.67.844      | ironchest-1.12.2-7.0.72.847.jar                              | None                                     |
	| LCHIJA | journeymap             | 1.12.2-5.5.6           | journeymap-1.12.2-5.5.6.jar                                  | None                                     |
	| LCHIJA | lunatriuscore          | 1.2.0.42               | LunatriusCore-1.12.2-1.2.0.42-universal.jar                  | None                                     |
	| LCHIJA | mca                    | 6.1.0                  | MCA-1.12.2-6.1.0-universal.jar                               | None                                     |
	| LCHIJA | mcwbridges             | 1.0                    | mcw-bridges-1.0.3-mc1.12.2.jar                               | None                                     |
	| LCHIJA | guilib                 | $version               | morepaintings-paintings-1.12.2-5.0.1.2.jar                   | None                                     |
	| LCHIJA | paintingselgui         | $version               | morepaintings-paintings-1.12.2-5.0.1.2.jar                   | None                                     |
	| LCHIJA | morepaintings          | $version               | morepaintings-paintings-1.12.2-5.0.1.2.jar                   | None                                     |
	| LCHIJA | netherchest            | 1.1.1                  | netherchest-1.1.1.jar                                        | None                                     |
	| LCHIJA | nifty                  | 1.5                    | nifty-1.12.2-1.5.jar                                         | None                                     |
	| LCHIJA | jp.crafterkina.pipes   | 1.1.0.15               | Pipes-1.12-1.1.0.15.jar                                      | None                                     |
	| LCHIJA | redstonepaste          | 1.7.5                  | redstonepaste-mc1.12-1.7.5.jar                               | None                                     |
	| LCHIJA | schematica             | 1.8.0.169              | Schematica-1.12.2-1.8.0.169-universal.jar                    | None                                     |
	| LCHIJA | lteleporters           | 1.12.2-3.0.2           | simpleteleporters-1.12.2-3.0.2.jar                           | None                                     |
	| LCHIJA | simplewoodenpipes      | 1.1                    | simplewoodenpipes-1.12.2-1.1.jar                             | 075143b8d04af6213d5b5936048e9b8012eb5cec |
	| LCHIJA | snowvillage            | 1.12.2-1.0.0           | SnowVillage-1.12.2-1.0.0.jar                                 | None                                     |
	| LCHIJA | thutcore               | 5.21.0                 | thutcore-1.12.2-5.21.0.jar                                   | None                                     |
	| LCHIJA | thutcore_compat        | 1.0                    | thutcore-1.12.2-5.21.0.jar                                   | None                                     |
	| LCHIJA | thuttech               | 6.1.6                  | thuttech-1.12.2-6.1.6.jar                                    | None                                     |
	| LCHIJA | torchlever             | 1.0                    | TorchLever1.12.2-1.0.jar                                     | None                                     |
	| LCHIJA | vampirism              | 1.5.7                  | Vampirism-1.12.2-1.5.7.jar                                   | None                                     |
	| LCHIJA | teamlapen-lib          | 1.5.7                  | Vampirism-1.12.2-1.5.7.jar                                   | None                                     |
	| LCHIJA | vampirism_integrations | vampirism_integrations | VampirismIntegrations-1.12.2-1.2.0.jar                       | None                                     |
	| LCHIJA | worldedit              | 6.1.10-SNAPSHOT        | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar            | None                                     |
	| LCHIJA | structurize            | 1.12.2-0.10.198-ALPHA  | structurize-1.12.2-0.10.198-ALPHA.jar                        | None                                     |
	| LCHIJA | minecolonies           | 1.12.2-0.10.673-ALPHA  | minecolonies-1.12.2-0.10.673-ALPHA-universal.jar             | None                                     |
	| LCHIJA | snowrealmagic          | 0.3.3                  | SnowRealMagic-0.3.3.jar                                      | None                                     |

	Loaded coremods (and transformers): 
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['HOWMAN_'/347, l='mountainlionkittykatkers', x=6814.50, y=52.84, z=22154.20]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Howman** [comment]
Is there anyway to get back on to server or do i have to start all over again, even if another player comes in to my area it crashes the server

**Comment by Raycoms** [comment]
We got a dev on it

**Comment by Howman** [comment]
I Updated to minecolonies-1.12.2-0.10.681-ALPHA-universal and I am still getting same error

---- Minecraft Crash Report ----

WARNING: coremods are present:
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 03/02/20 11:55 AM
XRay version: 58
Description: Ticking entity

java.lang.ClassCastException: net.minecraft.pathfinding.PathPoint cannot be cast to com.minecolonies.coremod.entity.pathfinding.PathPointExtended
	at com.minecolonies.coremod.entity.pathfinding.MinecoloniesAdvancedPathNavigate.func_75508_h(MinecoloniesAdvancedPathNavigate.java:436)
	at net.minecraft.pathfinding.PathNavigate.func_75501_e(SourceFile:188)
	at com.minecolonies.coremod.entity.pathfinding.MinecoloniesAdvancedPathNavigate.func_75501_e(MinecoloniesAdvancedPathNavigate.java:128)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:766)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:1058)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.minecolonies.coremod.entity.pathfinding.MinecoloniesAdvancedPathNavigate.func_75508_h(MinecoloniesAdvancedPathNavigate.java:436)
	at net.minecraft.pathfinding.PathNavigate.func_75501_e(SourceFile:188)
	at com.minecolonies.coremod.entity.pathfinding.MinecoloniesAdvancedPathNavigate.func_75501_e(MinecoloniesAdvancedPathNavigate.java:128)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:766)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:1058)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: minecolonies:citizen (com.minecolonies.coremod.entity.citizen.EntityCitizen)
	Entity ID: 395
	Entity Name: Rose F. Goodenouth
	Entity's Exact location: 6784.28, 69.00, 22123.32
	Entity's Block location: World: (6784,69,22123), Chunk: (at 0,4,11 in 424,1382; contains blocks 6784,0,22112 to 6799,255,22127), Region: (13,43; contains chunks 416,1376 to 447,1407, blocks 6656,0,22016 to 7167,255,22527)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: mountainlionkittykatkers
	All players: 1 total; [EntityPlayerMP['HOWMAN_'/308, l='mountainlionkittykatkers', x=6814.50, y=52.84, z=22154.20]]
	Chunk stats: ServerChunkCache: 943 Drop: 0
	Level seed: -6712753192105077325
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-204,64,337), Chunk: (at 4,4,1 in -13,21; contains blocks -208,0,336 to -193,255,351), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 8348375 game time, 8348375 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 11857 (now: false), thunder time: 4959 (now: true)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 15045991464 bytes (14348 MB) / 15702949888 bytes (14975 MB) up to 15702949888 bytes (14975 MB)
	JVM Flags: 2 total; -Xmx15000M -Xms15000M
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 51 mods loaded, 51 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                     | Version                | Source                                                       | Signature                                |
	|:------ |:---------------------- |:---------------------- |:------------------------------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft              | 1.12.2                 | minecraft.jar                                                | None                                     |
	| LCHIJA | mcp                    | 9.42                   | minecraft.jar                                                | None                                     |
	| LCHIJA | FML                    | 8.0.99.99              | forge-1.12.2-14.23.5.2847-universal.jar                      | None                                     |
	| LCHIJA | forge                  | 14.23.5.2847           | forge-1.12.2-14.23.5.2847-universal.jar                      | None                                     |
	| LCHIJA | movillages             | 1.5.4                  | [1.12]MoVillages-1.5.4.jar                                   | None                                     |
	| LCHIJA | bedrockminer           | 1.0.5                  | BedrockMiner-1.12.2-(v.1.0.5).jar                            | None                                     |
	| LCHIJA | bedrockplus            | 0.7.5                  | bedrockplus-0.7.5.jar                                        | ac38a3286ab9f4777b0023f0f6280caa9369d575 |
	| LCHIJA | bettergolem            | 1.0                    | bettergolem-1.12.2-1.0.jar                                   | None                                     |
	| LCHIJA | biomesoplenty          | 7.0.1.2444             | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar                | None                                     |
	| LCHIJA | ceilingtorch           | v1.2.1                 | ceilingtorch-1.12.2-v1.2.1.jar                               | None                                     |
	| LCHIJA | chesttransporter       | 2.8.8                  | ChestTransporter-1.12.2-2.8.8.jar                            | None                                     |
	| LCHIJA | customnpcs             | 1.12                   | Custom-NPCs-Mod-1.12.2.jar                                   | None                                     |
	| LCHIJA | diamondglass           | 1.12.2-3.3.18          | diamondglass-1.12.2-3.3.18.jar                               | None                                     |
	| LCHIJA | doubledoors            | 1.2                    | doubledoors_1.12-1.2.jar                                     | None                                     |
	| LCHIJA | dynamictrees           | 1.12.2-0.9.7           | DynamicTrees-1.12.2-0.9.7.jar                                | None                                     |
	| LCHIJA | dynamictreesbop        | 1.12.2-1.4.1e          | DynamicTreesBOP-1.12.2-1.4.1e.jar                            | None                                     |
	| LCHIJA | extraglass             | 1.20                   | extra-glass-1.20.jar                                         | None                                     |
	| LCHIJA | golems                 | 7.1.8                  | ExtraGolems-1.12-7.1.8.jar                                   | None                                     |
	| LCHIJA | familiarfauna          | 1.0.11                 | FamiliarFauna-1.12.2-1.0.11.jar                              | None                                     |
	| LCHIJA | com.boydti.fawe        | 3.5.1                  | FastAsyncWorldEdit-forge112-19.11.13-5505943-1282-22.3.5.jar | None                                     |
	| LCHIJA | faufil                 | 1.0.2                  | Faucets+and+Filters-1.0.2.jar                                | None                                     |
	| LCHIJA | cfm                    | 6.3.1                  | furniture-6.3.1-1.12.2.jar                                   | None                                     |
	| LCHIJA | ghostsexplosives       | 2.3.0 - MC 1.12.2      | Ghost's+Explosives+2.3.0+-+MC1.12.2.jar                      | None                                     |
	| LCHIJA | hopperducts            | 1.5                    | hopperducts-mc1.12-1.5.jar                                   | None                                     |
	| LCHIJA | ironchest              | 1.12.2-7.0.67.844      | ironchest-1.12.2-7.0.72.847.jar                              | None                                     |
	| LCHIJA | journeymap             | 1.12.2-5.5.8           | journeymap-1.12.2-5.5.8.jar                                  | None                                     |
	| LCHIJA | lunatriuscore          | 1.2.0.42               | LunatriusCore-1.12.2-1.2.0.42-universal.jar                  | None                                     |
	| LCHIJA | mca                    | 6.1.0                  | MCA-1.12.2-6.1.0-universal.jar                               | None                                     |
	| LCHIJA | mcwbridges             | 1.0                    | mcw-bridges-1.0.3-mc1.12.2.jar                               | None                                     |
	| LCHIJA | guilib                 | $version               | morepaintings-paintings-1.12.2-5.0.1.2.jar                   | None                                     |
	| LCHIJA | paintingselgui         | $version               | morepaintings-paintings-1.12.2-5.0.1.2.jar                   | None                                     |
	| LCHIJA | morepaintings          | $version               | morepaintings-paintings-1.12.2-5.0.1.2.jar                   | None                                     |
	| LCHIJA | netherchest            | 1.1.1                  | netherchest-1.1.1.jar                                        | None                                     |
	| LCHIJA | nifty                  | 1.5                    | nifty-1.12.2-1.5.jar                                         | None                                     |
	| LCHIJA | jp.crafterkina.pipes   | 1.1.0.15               | Pipes-1.12-1.1.0.15.jar                                      | None                                     |
	| LCHIJA | redstonepaste          | 1.7.5                  | redstonepaste-mc1.12-1.7.5.jar                               | None                                     |
	| LCHIJA | schematica             | 1.8.0.169              | Schematica-1.12.2-1.8.0.169-universal.jar                    | None                                     |
	| LCHIJA | lteleporters           | 1.12.2-3.0.2           | simpleteleporters-1.12.2-3.0.2.jar                           | None                                     |
	| LCHIJA | simplewoodenpipes      | 1.1                    | simplewoodenpipes-1.12.2-1.1.jar                             | 075143b8d04af6213d5b5936048e9b8012eb5cec |
	| LCHIJA | snowvillage            | 1.12.2-1.0.0           | SnowVillage-1.12.2-1.0.0.jar                                 | None                                     |
	| LCHIJA | thutcore               | 5.21.0                 | thutcore-1.12.2-5.21.0.jar                                   | None                                     |
	| LCHIJA | thutcore_compat        | 1.0                    | thutcore-1.12.2-5.21.0.jar                                   | None                                     |
	| LCHIJA | thuttech               | 6.1.6                  | thuttech-1.12.2-6.1.6.jar                                    | None                                     |
	| LCHIJA | torchlever             | 1.0                    | TorchLever1.12.2-1.0.jar                                     | None                                     |
	| LCHIJA | vampirism              | 1.5.7                  | Vampirism-1.12.2-1.5.7.jar                                   | None                                     |
	| LCHIJA | teamlapen-lib          | 1.5.7                  | Vampirism-1.12.2-1.5.7.jar                                   | None                                     |
	| LCHIJA | vampirism_integrations | vampirism_integrations | VampirismIntegrations-1.12.2-1.2.0.jar                       | None                                     |
	| LCHIJA | worldedit              | 6.1.10-SNAPSHOT        | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar            | None                                     |
	| LCHIJA | structurize            | 1.12.2-0.10.198-ALPHA  | structurize-1.12.2-0.10.198-ALPHA.jar                        | None                                     |
	| LCHIJA | minecolonies           | 1.12.2-0.10.681-ALPHA  | minecolonies-1.12.2-0.10.681-ALPHA-universal.jar             | None                                     |
	| LCHIJA | snowrealmagic          | 0.3.3                  | SnowRealMagic-0.3.3.jar                                      | None                                     |

	Loaded coremods (and transformers): 
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['HOWMAN_'/308, l='mountainlionkittykatkers', x=6814.50, y=52.84, z=22154.20]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
