### ISSUE TITLE
Pathfinding Error Crash

### ISSUE THREAD

**Issue by Howman** [ldtteam/minecolonies#4313]
### Minecolonies version

Version: minecolonies-1.12.2-0.10.685-ALPHA-universal

### Expected behavior

For Mincraft / Minecolonies to work with out crashing

### Actual behaviour

---- Minecraft Crash Report ----

WARNING: coremods are present:
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 2/8/20 6:21 PM
XRay version: 58
Description: Ticking entity

java.lang.ArrayStoreException: net.minecraft.pathfinding.PathPoint
	at net.minecraft.pathfinding.Path.func_186309_a(SourceFile:43)
	at net.minecraft.pathfinding.PathNavigate.func_75487_m(SourceFile:324)
	at net.minecraft.pathfinding.PathNavigateGround.func_75487_m(SourceFile:96)
	at net.minecraft.pathfinding.PathNavigate.func_75484_a(SourceFile:159)
	at com.minecolonies.coremod.entity.pathfinding.MinecoloniesAdvancedPathNavigate.func_75484_a(MinecoloniesAdvancedPathNavigate.java:270)
	at com.minecolonies.coremod.entity.pathfinding.MinecoloniesAdvancedPathNavigate.processCompletedCalculationResult(MinecoloniesAdvancedPathNavigate.java:311)
	at com.minecolonies.coremod.entity.pathfinding.MinecoloniesAdvancedPathNavigate.func_75501_e(MinecoloniesAdvancedPathNavigate.java:114)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:891)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:1058)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.pathfinding.Path.func_186309_a(SourceFile:43)
	at net.minecraft.pathfinding.PathNavigate.func_75487_m(SourceFile:324)
	at net.minecraft.pathfinding.PathNavigateGround.func_75487_m(SourceFile:96)
	at net.minecraft.pathfinding.PathNavigate.func_75484_a(SourceFile:159)
	at com.minecolonies.coremod.entity.pathfinding.MinecoloniesAdvancedPathNavigate.func_75484_a(MinecoloniesAdvancedPathNavigate.java:270)
	at com.minecolonies.coremod.entity.pathfinding.MinecoloniesAdvancedPathNavigate.processCompletedCalculationResult(MinecoloniesAdvancedPathNavigate.java:311)
	at com.minecolonies.coremod.entity.pathfinding.MinecoloniesAdvancedPathNavigate.func_75501_e(MinecoloniesAdvancedPathNavigate.java:114)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:891)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:678)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:1058)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:377)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: minecolonies:citizen (com.minecolonies.coremod.entity.citizen.EntityCitizen)
	Entity ID: 191
	Entity Name: Elijah H. Hakebourne
	Entity's Exact location: 21077.30, 63.00, 63490.43
	Entity's Block location: World: (21077,63,63490), Chunk: (at 5,3,2 in 1317,3968; contains blocks 21072,0,63488 to 21087,255,63503), Region: (41,124; contains chunks 1312,3968 to 1343,3999, blocks 20992,0,63488 to 21503,255,63999)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['HOWMAN_'/164, l='New World', x=21038.50, y=74.76, z=63428.97]]
	Chunk stats: ServerChunkCache: 1136 Drop: 0
	Level seed: 9185015736975399211
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: {"landScheme":"vanilla","tempScheme":"large_zones","rainScheme":"small_zones","biomeSize":"huge","amplitude":1.0,"generateBopOre":true,"generatePoisonIvy":false,"generateBerryBushes":true,"generateThorns":true,"generateQuicksand":true,"generateLiquidPoison":true,"generateHotSprings":true,"generateNetherHives":true,"generateEndFeatures":true,"mainNoiseScaleX":80.0,"mainNoiseScaleY":160.0,"mainNoiseScaleZ":80.0,"coordinateScale":684.412,"heightScale":684.412,"upperLimitScale":512.0,"lowerLimitScale":512.0}
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3336993 game time, 3336993 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 44612 (now: false), thunder time: 8558 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3972344392 bytes (3788 MB) / 5368709120 bytes (5120 MB) up to 9663676416 bytes (9216 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx9G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=512M
	IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 108
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F4 55 mods loaded, 55 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                     | Version                    | Source                                                       | Signature                                |
	|:------ |:---------------------- |:-------------------------- |:------------------------------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft              | 1.12.2                     | minecraft.jar                                                | None                                     |
	| LCHIJA | mcp                    | 9.42                       | minecraft.jar                                                | None                                     |
	| LCHIJA | FML                    | 8.0.99.99                  | forge-1.12.2-14.23.5.2847.jar                                | None                                     |
	| LCHIJA | forge                  | 14.23.5.2847               | forge-1.12.2-14.23.5.2847.jar                                | None                                     |
	| LCHIJA | movillages             | 1.5.4                      | [1.12]MoVillages-1.5.4.jar                                   | None                                     |
	| LCHIJA | bedrockminer           | 1.0.5                      | BedrockMiner-1.12.2-(v.1.0.5).jar                            | None                                     |
	| LCHIJA | bedrockplus            | 0.7.5                      | bedrockplus-0.7.5.jar                                        | ac38a3286ab9f4777b0023f0f6280caa9369d575 |
	| LCHIJA | bettergolem            | 1.0                        | bettergolem-1.12.2-1.0.jar                                   | None                                     |
	| LCHIJA | biomesoplenty          | 7.0.1.2444                 | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar                | None                                     |
	| LCHIJA | ceilingtorch           | v1.2.1                     | ceilingtorch-1.12.2-v1.2.1.jar                               | None                                     |
	| LCHIJA | chesttransporter       | 2.8.8                      | ChestTransporter-1.12.2-2.8.8.jar                            | None                                     |
	| LCHIJA | customnpcs             | 1.12                       | Custom-NPCs-Mod-1.12.2.jar                                   | None                                     |
	| LCHIJA | diamondglass           | 1.12.2-3.3.18              | diamondglass-1.12.2-3.3.18.jar                               | None                                     |
	| LCHIJA | doubledoors            | 1.2                        | doubledoors_1.12-1.2.jar                                     | None                                     |
	| LCHIJA | dynamictrees           | 1.12.2-0.9.7               | DynamicTrees-1.12.2-0.9.7.jar                                | None                                     |
	| LCHIJA | dynamictreesbop        | 1.12.2-1.4.1e              | DynamicTreesBOP-1.12.2-1.4.1e.jar                            | None                                     |
	| LCHIJA | extraglass             | 1.20                       | extra-glass-1.20.jar                                         | None                                     |
	| LCHIJA | golems                 | 7.1.8                      | ExtraGolems-1.12-7.1.8.jar                                   | None                                     |
	| LCHIJA | familiarfauna          | 1.0.11                     | FamiliarFauna-1.12.2-1.0.11.jar                              | None                                     |
	| LCHIJA | com.boydti.fawe        | 3.5.1                      | FastAsyncWorldEdit-forge112-19.11.13-5505943-1282-22.3.5.jar | None                                     |
	| LCHIJA | faufil                 | 1.0.2                      | Faucets+and+Filters-1.0.2.jar                                | None                                     |
	| LCHIJA | cfm                    | 6.3.1                      | furniture-6.3.1-1.12.2.jar                                   | None                                     |
	| LCHIJA | ghostsexplosives       | 2.3.0 - MC 1.12.2          | Ghost's+Explosives+2.3.0+-+MC1.12.2.jar                      | None                                     |
	| LCHIJA | hopperducts            | 1.5                        | hopperducts-mc1.12-1.5.jar                                   | None                                     |
	| LCHIJA | ironchest              | 1.12.2-7.0.67.844          | ironchest-1.12.2-7.0.72.847.jar                              | None                                     |
	| LCHIJA | journeymap             | 1.12.2-5.5.8               | journeymap-1.12.2-5.5.8.jar                                  | None                                     |
	| LCHIJA | lunatriuscore          | 1.2.0.42                   | LunatriusCore-1.12.2-1.2.0.42-universal.jar                  | None                                     |
	| LCHIJA | mca                    | 6.1.0                      | MCA-1.12.2-6.1.0-universal.jar                               | None                                     |
	| LCHIJA | mcwbridges             | 1.0                        | mcw-bridges-1.0.3-mc1.12.2.jar                               | None                                     |
	| LCHIJA | guilib                 | $version                   | morepaintings-paintings-1.12.2-5.0.1.2.jar                   | None                                     |
	| LCHIJA | paintingselgui         | $version                   | morepaintings-paintings-1.12.2-5.0.1.2.jar                   | None                                     |
	| LCHIJA | morepaintings          | $version                   | morepaintings-paintings-1.12.2-5.0.1.2.jar                   | None                                     |
	| LCHIJA | neat                   | 1.4-17                     | Neat+1.4-17.jar                                              | None                                     |
	| LCHIJA | netherchest            | 1.1.1                      | netherchest-1.1.1.jar                                        | None                                     |
	| LCHIJA | nifty                  | 1.5                        | nifty-1.12.2-1.5.jar                                         | None                                     |
	| LCHIJA | jp.crafterkina.pipes   | 1.1.0.15                   | Pipes-1.12-1.1.0.15.jar                                      | None                                     |
	| LCHIJA | redstonepaste          | 1.7.5                      | redstonepaste-mc1.12-1.7.5.jar                               | None                                     |
	| LCHIJA | schematica             | 1.8.0.169                  | Schematica-1.12.2-1.8.0.169-universal.jar                    | None                                     |
	| LCHIJA | lteleporters           | 1.12.2-3.0.2               | simpleteleporters-1.12.2-3.0.2.jar                           | None                                     |
	| LCHIJA | simplewoodenpipes      | 1.1                        | simplewoodenpipes-1.12.2-1.1.jar                             | 075143b8d04af6213d5b5936048e9b8012eb5cec |
	| LCHIJA | snowaccumulation       | 1.0.0                      | SnowAccumulation-1.12-1.0.0.jar                              | None                                     |
	| LCHIJA | snowvillage            | 1.12.2-1.0.0               | SnowVillage-1.12.2-1.0.0.jar                                 | None                                     |
	| LCHIJA | structpro              | 4.0                        | structpro-4.0-1.12.1.jar                                     | None                                     |
	| LCHIJA | thutcore               | 5.21.0                     | thutcore-1.12.2-5.21.0.jar                                   | None                                     |
	| LCHIJA | thutcore_compat        | 1.0                        | thutcore-1.12.2-5.21.0.jar                                   | None                                     |
	| LCHIJA | thuttech               | 6.1.6                      | thuttech-1.12.2-6.1.6.jar                                    | None                                     |
	| LCHIJA | torchlever             | 1.0                        | TorchLever1.12.2-1.0.jar                                     | None                                     |
	| LCHIJA | vampirism              | 1.5.7                      | Vampirism-1.12.2-1.5.7.jar                                   | None                                     |
	| LCHIJA | teamlapen-lib          | 1.5.7                      | Vampirism-1.12.2-1.5.7.jar                                   | None                                     |
	| LCHIJA | vampirism_integrations | vampirism_integrations     | VampirismIntegrations-1.12.2-1.2.0.jar                       | None                                     |
	| LCHIJA | worldedit              | 6.1.10-SNAPSHOT            | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar            | None                                     |
	| LCHIJA | worldeditcuife2        | 2.1.2-mf-1.12-14.21.1.2387 | WorldEdit CUI Forge Edition 2-2.1.2-mf-1.12-14.21.1.2387.jar | None                                     |
	| LCHIJA | structurize            | 1.12.2-0.10.198-ALPHA      | structurize-1.12.2-0.10.198-ALPHA.jar                        | None                                     |
	| LCHIJA | minecolonies           | 1.12.2-0.10.685-ALPHA      | minecolonies-1.12.2-0.10.685-ALPHA-universal.jar             | None                                     |
	| LCHIJA | snowrealmagic          | 0.3.3                      | SnowRealMagic-0.3.3.jar                                      | None                                     |

	Loaded coremods (and transformers): 
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['HOWMAN_'/164, l='New World', x=21038.50, y=74.76, z=63428.97]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_F4
	OptiFine Build: 20191023-234904
	Render Distance Chunks: 21
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 450.12
	OpenGlRenderer: GeForce GTX 1050/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

Accrding to crash report problame is with Elijah H. Hakebourne I know what the colanest was doing when crash happend, he was upgrading spruce builder hut 4 to spruce hut 5. I had the pathing problam before thought it was fixed  but I guess not this is a new world not the old one that i was having same pathing problam with.

### Steps to reproduce the problem

I have none just buld and up grade

**Comment by Raycoms** [comment]
Does any of these mods you are using, alter pathfinding behaviour?

**Comment by Howman** [comment]
Really not sure (Mincraft comes alive, Vampirism maybe) but it had worked before but not to sure how long ago but it did work. Right now i am playing on lan server (minecolonies-1.12.2-0.10.679-RELEASE-universal) and no crash yet but I have 5 builder none going to level 5 yet I got 3 at level 4 and one at level 3 and one at one. When this first noticed happening I was up grading builders can't tell you what levels tho I do no remember  it was a while ago. 
I can usually logon then when minecolcnies starts posting in the chat builder  Elijah H. Hakebourne  start then crash to desktop i can try you newest version as there was something to do with path finding on it (minecolonies-1.12.2-0.10.719-ALPHA-universal) just tried still not working.

**Comment by Raycoms** [comment]
okay
A) do you have a modpack with those above we can download
B) Can you send us the world that consistently crashes?

**Comment by Howman** [comment]
you want me to send the collection on mods I am using Is that what your asking cause these are all separate modes downloaded from https://www.curseforge.com/minecraft/mc-mods no mod packs I can send you my mods folder. I did upload one world already in one of my closed issues. i will see if i still have it some where

**Comment by Raycoms** [comment]
Okay, so send the world that instant crashes and the folder with the mods

**Comment by Howman** [comment]
About 240 meg ziped this is the 1 world it stared happening looking to see if i have the other world. any where in particular you would like this uploaded to my one drive if full try this https://mega.nz/#!ggQWlKwQ!BLZmdaoUrq7UFQHdhnO-Kmf8gnS6cQ90opv6lBzIm_U See if that works

**Comment by Raycoms** [comment]
google drive should be fine.

**Comment by Raycoms** [comment]
one drive should also be fine.

**Comment by Raycoms** [comment]
One thing that would be interesting too if you could try that out.
Can you try removing: MCA, vampirisim, golems and the coremods from the game and try to start the world with that and check if it still happens?

**Comment by Howman** [comment]
did the mega link work or did you want me to upload google drive or on drive ?  removed mca, vampirisim, golems one at a time and no change for me. still crashes

**Comment by Raycoms** [comment]
worked, can you try it with Only minecolonies as well?

**Comment by Raycoms** [comment]
no other mods, no coremods

**Comment by Howman** [comment]
just minecolonies in the mods folder and still crashes  
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 2/21/20 5:05 PM
Description: Ticking entity

java.lang.ArrayStoreException: net.minecraft.pathfinding.PathPoint
	at net.minecraft.pathfinding.Path.func_186309_a(SourceFile:43)
	at net.minecraft.pathfinding.PathNavigate.func_75487_m(SourceFile:324)
	at net.minecraft.pathfinding.PathNavigateGround.func_75487_m(SourceFile:96)
	at net.minecraft.pathfinding.PathNavigate.func_75484_a(SourceFile:159)
	at com.minecolonies.coremod.entity.pathfinding.MinecoloniesAdvancedPathNavigate.func_75484_a(MinecoloniesAdvancedPathNavigate.java:270)
	at com.minecolonies.coremod.entity.pathfinding.MinecoloniesAdvancedPathNavigate.processCompletedCalculationResult(MinecoloniesAdvancedPathNavigate.java:318)
	at com.minecolonies.coremod.entity.pathfinding.MinecoloniesAdvancedPathNavigate.func_75501_e(MinecoloniesAdvancedPathNavigate.java:114)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:766)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:1058)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.pathfinding.Path.func_186309_a(SourceFile:43)
	at net.minecraft.pathfinding.PathNavigate.func_75487_m(SourceFile:324)
	at net.minecraft.pathfinding.PathNavigateGround.func_75487_m(SourceFile:96)
	at net.minecraft.pathfinding.PathNavigate.func_75484_a(SourceFile:159)
	at com.minecolonies.coremod.entity.pathfinding.MinecoloniesAdvancedPathNavigate.func_75484_a(MinecoloniesAdvancedPathNavigate.java:270)
	at com.minecolonies.coremod.entity.pathfinding.MinecoloniesAdvancedPathNavigate.processCompletedCalculationResult(MinecoloniesAdvancedPathNavigate.java:318)
	at com.minecolonies.coremod.entity.pathfinding.MinecoloniesAdvancedPathNavigate.func_75501_e(MinecoloniesAdvancedPathNavigate.java:114)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:766)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2359)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:178)
	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:1058)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: minecolonies:citizen (com.minecolonies.coremod.entity.citizen.EntityCitizen)
	Entity ID: 465
	Entity Name: Rose F. Goodenouth
	Entity's Exact location: 6784.27, 69.00, 22123.30
	Entity's Block location: World: (6784,69,22123), Chunk: (at 0,4,11 in 424,1382; contains blocks 6784,0,22112 to 6799,255,22127), Region: (13,43; contains chunks 416,1376 to 447,1407, blocks 6656,0,22016 to 7167,255,22527)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: mountainlionkittykatkers
	All players: 1 total; [EntityPlayerMP['HOWMAN_'/260, l='mountainlionkittykatkers', x=6817.17, y=78.94, z=22055.31]]
	Chunk stats: ServerChunkCache: 2144 Drop: 0
	Level seed: -6712753192105077325
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-204,64,337), Chunk: (at 4,4,1 in -13,21; contains blocks -208,0,336 to -193,255,351), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 8684743 game time, 8684743 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 50874 (now: false), thunder time: 4465 (now: true)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3298069256 bytes (3145 MB) / 4194304000 bytes (4000 MB) up to 9663676416 bytes (9216 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx9G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=512M
	IntCache: cache: 0, tcache: 7, allocated: 20, tallocated: 86
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID           | Version               | Source                                           | Signature |
	|:------ |:------------ |:--------------------- |:------------------------------------------------ |:--------- |
	| LCHIJA | minecraft    | 1.12.2                | minecraft.jar                                    | None      |
	| LCHIJA | mcp          | 9.42                  | minecraft.jar                                    | None      |
	| LCHIJA | FML          | 8.0.99.99             | forge-1.12.2-14.23.5.2847.jar                    | None      |
	| LCHIJA | forge        | 14.23.5.2847          | forge-1.12.2-14.23.5.2847.jar                    | None      |
	| LCHIJA | structurize  | 1.12.2-0.10.198-ALPHA | structurize-1.12.2-0.10.198-ALPHA.jar            | None      |
	| LCHIJA | minecolonies | 1.12.2-0.10.719-ALPHA | minecolonies-1.12.2-0.10.719-ALPHA-universal.jar | None      |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['HOWMAN_'/260, l='mountainlionkittykatkers', x=6817.17, y=78.94, z=22055.31]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Howman** [comment]
Anything else i could do to try and help

**Comment by someaddons** [comment]
found the issue thx to your world, so all good :)

**Comment by Howman** [comment]
I have started a new world. So what should i do to avoid this from happening till there is a fix

**Comment by Raycoms** [comment]
It should be fixed by now.
