### ISSUE TITLE
Game crashed with new Alphas

### ISSUE THREAD

**Issue by Inomutso** [ldtteam/minecolonies#4323]
### Minecolonies version

Version: 
minecolonies-0.10.694-ALPHA-universal.jar
structurize-0.10.250-ALPHA.jar
forge-1.15.2-31.1.0.jar

### Expected behavior

- should run

### Actual behaviour

- Game is crashing

### Steps to reproduce the problem

1. Hi Team

I have just tried to use Version

minecolonies-0.10.694-ALPHA-universal.jar
structurize-0.10.250-ALPHA.jar
forge-1.15.2-31.1.0.jar

but the game crashed after 30 sec. fresh started
started again and just let it run, without any moves or actions but it crashed again

Time: 11.02.20 19:54
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.minecolonies.coremod.entity.citizen.citizenhandlers.CitizenItemHandler.updateArmorDamage(CitizenItemHandler.java:323) ~[?:0.10.694-ALPHA] {re:classloading}
	at com.minecolonies.coremod.entity.citizen.EntityCitizen.handleDamagePerformed(EntityCitizen.java:766) ~[?:0.10.694-ALPHA] {re:classloading}
	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70097_a(EntityCitizen.java:683) ~[?:0.10.694-ALPHA] {re:classloading}
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_213868_a(AbstractArrowEntity.java:379) ~[?:?] {re:classloading}
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_184549_a(AbstractArrowEntity.java:304) ~[?:?] {re:classloading}
	at net.minecraft.entity.projectile.AbstractArrowEntity.func_70071_h_(AbstractArrowEntity.java:222) ~[?:?] {re:classloading}
	at net.minecraft.entity.projectile.ArrowEntity.func_70071_h_(ArrowEntity.java:93) ~[?:?] {re:classloading}
	
days before, i tried 

minecolonies-0.10.687-ALPHA-universal
structurize-0.10.242-ALPHA
forge-1.15.2-31.0.1

when I tried to use the Building Tool and clicked on a block with the Tool in Hand,
the game crashed immediatily, with kind of a rendering Problem.
after that I have updated to forge-1.15.2-31.1.0 , then I was able to use the Building Tool again.

so I had to go back to minecolonies-0.10.691-ALPHA-universal and structurize-0.10.242-ALPHA

regards Inomutso

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:

**Comment by Inomutso** [comment]
latest.log:
    crashlog:
https://gist.github.com/Inomutso/1582315f1eafba99891882d64eb0cd9d

**Comment by Raycoms** [comment]
fix pushed
