### ISSUE TITLE
Scan tool issues

### ISSUE THREAD

**Issue by lunadragnstar** [ldtteam/minecolonies#4333]
Mincolonies 0.10.696-ALPHA  and  Structurize 0.10.250-ALPHA

When using the scan tool, replace doesn't keep the rotation of some of the blocks, specifically the structurize blocks, and at least the fences. Fences aren't "connecting" like they should and will sometimes have connectors where there shouldn't be any. 

Sometimes after selecting the corners of a scan area, when clicking in air to get the outline, it deselects the area and only selects the air block.

**Comment by lunadragnstar** [comment]
Also, when removing items, planted pots don't always get removed. I don't know if it is just because the scan tool isn't seeing the item or if it isn't removing those items when told to, I will have to run some tests (this one has always been an issue, we've just ignored it)

**Comment by lunadragnstar** [comment]
Fence issue
![image](https://user-images.githubusercontent.com/29446488/74504669-f3da1880-4ec2-11ea-94a6-4c9f98702f8d.png)

**Comment by lunadragnstar** [comment]
Using the scan tool to replace doors causes the game to crash

**Comment by Nightenom** [comment]
@Raycoms the rotating problem is caused by that we use the same old blockstate for replacing all its instances
@lunadragnstar can't reproduce door crash, please log
flowers pots are something harder to solve, as there are no item versions for potted flowers, solutions:
count them as empty pots - will replace all of potter pots regardless the flower inside them
count them as flowers - will replace flowers of that type also
rewrite the code so it can accept blockstates and render them - kinda hard :D

**Comment by Nightenom** [comment]
door crash reproduced, they have to be open :D
```
java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.world.World.setBlockState(World.java:186) ~[forge-1.15.2-31.0.14_mapped_snapshot_20200207-1.15.1-recomp.jar:?] {re:classloading,pl:accesstransformer:B}
	at com.ldtteam.structurize.util.BlockUtils.handleCorrectBlockPlacement(BlockUtils.java:293) ~[main/:?] {re:classloading}
	at com.ldtteam.structurize.util.ScanToolOperation.run(ScanToolOperation.java:206) ~[main/:?] {re:classloading}
	at com.ldtteam.structurize.util.ScanToolOperation.apply(ScanToolOperation.java:172) ~[main/:?] {re:classloading}
	at com.ldtteam.structurize.management.Manager.onWorldTick(Manager.java:70) ~[main/:?] {re:classloading}
	at com.ldtteam.structurize.event.EventSubscriber.onWorldTick(EventSubscriber.java:89) ~[main/:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_8_EventSubscriber_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPreWorldTick(BasicEventHooks.java:94) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:880) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:818) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:120) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_242] {}
```
