### ISSUE TITLE
Unable to join Server - Timeout - with minecolonies

### ISSUE THREAD

**Issue by mcenderdragon** [ldtteam/minecolonies#4340]
```
[21:56:46] [Client thread/WARN]: Structure failed Loading because of invalid resource name (probably capitalization issue)
net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: minecolonies:blockhutfortresscornerBlank
	at net.minecraft.util.ResourceLocation.<init>(SourceFile:38) ~[?:?]
	at net.minecraft.util.ResourceLocation.<init>(SourceFile:47) ~[?:?]
	at com.ldtteam.structurize.management.StructureName.init(StructureName.java:104) ~[?:0.10.245-ALPHA]
	at com.ldtteam.structurize.management.StructureName.<init>(StructureName.java:36) ~[?:0.10.245-ALPHA]
	at com.ldtteam.structurize.management.Structures.loadSchematicsForPrefix(Structures.java:322) [?:0.10.245-ALPHA]
	at com.ldtteam.structurize.management.Structures.loadStyleMapsJar(Structures.java:228) [?:0.10.245-ALPHA]
	at com.ldtteam.structurize.management.Structures.loadStyleMaps(Structures.java:135) [?:0.10.245-ALPHA]
	at com.ldtteam.structurize.management.Structures.init(Structures.java:122) [?:0.10.245-ALPHA]
	at com.ldtteam.structurize.network.messages.StructurizeStylesMessage.onExecute(StructurizeStylesMessage.java:80) [?:0.10.245-ALPHA]
	at com.ldtteam.structurize.network.NetworkChannel.lambda$null$3(NetworkChannel.java:95) [?:0.10.245-ALPHA]
	at com.ldtteam.structurize.network.NetworkChannel$$Lambda$5637/1647508629.run(Unknown Source) [?:0.10.245-ALPHA]
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) [?:?]
	at com.ldtteam.structurize.network.NetworkChannel.lambda$registerMessage$4(NetworkChannel.java:95) [?:0.10.245-ALPHA]
	at com.ldtteam.structurize.network.NetworkChannel$$Lambda$4342/1289745291.accept(Unknown Source) [?:0.10.245-ALPHA]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:124) [?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec$$Lambda$5365/1638515546.accept(Unknown Source) [?:?]
	at java.util.Optional.ifPresent(Optional.java:159) [?:1.8.0_51]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:124) [?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:157) [?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:79) [?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel$$Lambda$2013/1268510462.accept(Unknown Source) [?:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) [eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) [eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2015/1085805965.invoke(Unknown Source) [eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) [eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) [?:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$0(NetworkHooks.java:74) [?:?]
	at net.minecraftforge.fml.network.NetworkHooks$$Lambda$5353/1779190637.apply(Unknown Source) [?:?]
	at java.util.Optional.map(Optional.java:215) [?:1.8.0_51]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:74) [?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1783) [?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:55) [?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11) [?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) [?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$5412/1781183107.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?]
	at jeresources.util.LootTableHelper.getManager(LootTableHelper.java:167) [?:0.10.1.74]
	at jeresources.compatibility.minecraft.MinecraftCompat.registerVanillaMobs(MinecraftCompat.java:42) [?:0.10.1.74]
	at jeresources.compatibility.minecraft.MinecraftCompat.init(MinecraftCompat.java:33) [?:0.10.1.74]
	at jeresources.compatibility.Compatibility.init(Compatibility.java:26) [?:0.10.1.74]
	at jeresources.proxy.CommonProxy.initCompatibility(CommonProxy.java:14) [?:0.10.1.74]
	at jeresources.jei.JEIConfig.registerCategories(JEIConfig.java:71) [?:0.10.1.74]
	at mezz.jei.load.PluginLoader.lambda$new$2(PluginLoader.java:108) [?:6.0.0.27]
	at mezz.jei.load.PluginLoader$$Lambda$5611/536669870.accept(Unknown Source) [?:6.0.0.27]
	at mezz.jei.load.PluginCaller.callOnPlugins(PluginCaller.java:26) [?:6.0.0.27]
	at mezz.jei.load.PluginLoader.<init>(PluginLoader.java:108) [?:6.0.0.27]
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:71) [?:6.0.0.27]
	at mezz.jei.startup.ClientLifecycleHandler.onRecipesLoaded(ClientLifecycleHandler.java:127) [?:6.0.0.27]
	at mezz.jei.startup.ClientLifecycleHandler.lambda$new$2(ClientLifecycleHandler.java:104) [?:6.0.0.27]
	at mezz.jei.startup.ClientLifecycleHandler$$Lambda$5177/733718807.accept(Unknown Source) [?:6.0.0.27]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) [eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) [eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2015/1085805965.invoke(Unknown Source) [eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) [eventbus-1.0.0-service.jar:?]
	at net.minecraftforge.client.ForgeHooksClient.onRecipesUpdated(ForgeHooksClient.java:1018) [?:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_199525_a(ClientPlayNetHandler.java:1268) [?:?]
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:28) [?:?]
	at net.minecraft.network.play.server.SUpdateRecipesPacket.func_148833_a(SourceFile:15) [?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) [?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$5412/1781183107.run(Unknown Source) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:861) [?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?]
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.2.1.jar:28.2]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$395/173259631.call(Unknown Source) [forge-1.14.4-28.2.1.jar:28.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?]

```

Version: 
- structurize-0.10.245-ALPHA.jar
- minecolonies-0.10.715-RELEASE-universal.jar
### Expected behavior
No Exception

### Actual behaviour
Exception thrown in log.

### Steps to reproduce the problem
I joined my own server and saw this. I am not 100% sure but maybe this is crashing my netty connection at the client side so I can no longer send packets to the server and get a time out serverside.

**Comment by mcenderdragon** [comment]
I just removed minecolonie & structurie from server & client and now I can join without a problem.

**Comment by Raycoms** [comment]
This is a normal exception, this should not cause any problems.

**Comment by Raycoms** [comment]
(Just an exception that loading something didn't work because of a naming issue, not an exception of crashing something)

**Comment by mcenderdragon** [comment]
removing it did the trick however. So its possible something else went wrong but it was not in the logs.
Edit: it did not happen right from the start but at somepoint I was no longer able to join the server,

**Comment by Raycoms** [comment]
Can we have the whole log?

**Comment by mcenderdragon** [comment]
https://gist.github.com/mcenderdragon/7794d438ecbfa769f954a321d1fd1c22

**Comment by Raycoms** [comment]
Definitely weird, there are a lot of exceptions there (mainly jei) but nothing that should stop you from connecting. Maybe your ping is a bit low, and the additional communication minecolonies has on login does the rest.

**Comment by mcenderdragon** [comment]
is it sending alot from the client to the server? Because my ping was like 60 + a bit of packet loss and the server never got any packets my client send. My internet is fairly fast are you sending tons of tiny packets?

**Comment by Raycoms** [comment]
No, we send like 1-2 big packages from the server to the client.
But maybe that + the other connections the other mods make might be just that bit too much.
However, it works well for 99% of the people. So it is difficult to say what is actually causing it. Have you tried removing JEI for example?

**Comment by mcenderdragon** [comment]
No not yet & it will most likely take some time before I can test that

**Comment by mcenderdragon** [comment]
I readded Minecolonies and it works again. So either A) my internet was wonky while I was testing or B) there was a glitch that was fixed be deleting and readding minecolonies.

**Comment by Raycoms** [comment]
Thanks for the update
