### ISSUE TITLE
Cant initalize schematic "minecolonies:fortresscornerBlank"

### ISSUE THREAD

**Issue by ezacpk** [ldtteam/minecolonies#4372]
### Minecolonies version

Version: minecolonies-0.10.726-BETA-universal - Happens since last minecolonies-0.10.716-RELEASE-universal

### Expected behavior
No warning while Server start.

### Actual behaviour
While initalizing the mod structurize warns that it failed loading "minecolonies:blockhutfortresscornerBlank". 
Path of File: assets\minecolonies\schematics\fortress\

[26Feb2020 13:02:04.334] [Server thread/WARN] [structurize/]: FMLServerStartedEvent
[26Feb2020 13:02:04.335] [Server thread/WARN] [structurize/]: file:///home/mcforge/serverfiles/mods/minecolonies-0.10.726-BETA-universal.jar
[26Feb2020 13:02:04.335] [Server thread/WARN] [structurize/]: /home/mcforge/serverfiles/mods/minecolonies-0.10.726-BETA-universal.jar
[26Feb2020 13:02:04.340] [Server thread/WARN] [structurize/]: /assets/minecolonies
[26Feb2020 13:02:04.340] [Server thread/INFO] [structurize/]: Load huts or decorations from jar
[26Feb2020 13:02:07.982] [Server thread/WARN] [structurize/]: Structure failed Loading because of invalid resource name (probably capitalization issue)
net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: minecolonies:blockhutfortresscornerBlank
        at net.minecraft.util.ResourceLocation.<init>(SourceFile:38) ~[?:?]
        at net.minecraft.util.ResourceLocation.<init>(SourceFile:47) ~[?:?]
        at com.ldtteam.structurize.management.StructureName.init(StructureName.java:104) ~[?:0.10.263-ALPHA]
        at com.ldtteam.structurize.management.StructureName.<init>(StructureName.java:36) ~[?:0.10.263-ALPHA]
        at com.ldtteam.structurize.management.Structures.loadSchematicsForPrefix(Structures.java:322) [?:0.10.263-ALPHA]
        at com.ldtteam.structurize.management.Structures.loadStyleMapsJar(Structures.java:228) [?:0.10.263-ALPHA]
        at com.ldtteam.structurize.management.Structures.loadStyleMaps(Structures.java:135) [?:0.10.263-ALPHA]
        at com.ldtteam.structurize.management.Structures.init(Structures.java:122) [?:0.10.263-ALPHA]
        at com.ldtteam.structurize.event.EventSubscriber.onServerStarting(EventSubscriber.java:60) [?:0.10.263-ALPHA]
        at net.minecraftforge.eventbus.ASMEventHandler_52_EventSubscriber_onServerStarting_Load.invoke(.dynamic) [?:?]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) [eventbus-2.0.0-milestone.1-service.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) [eventbus-2.0.0-milestone.1-service.jar:?]
        at net.minecraft.server.MinecraftServer.func_213194_a(MinecraftServer.java:412) [?:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:362) [?:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:211) [?:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:611) [?:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
[26Feb2020 13:02:07.983] [Server thread/WARN] [structurize/]: schematics/fortress/fortresscornerBlank
[26Feb2020 13:02:08.143] [Server thread/WARN] [structurize/]: file:///home/mcforge/serverfiles/mods/structurize-0.10.263-ALPHA.jar
[26Feb2020 13:02:08.143] [Server thread/WARN] [structurize/]: /home/mcforge/serverfiles/mods/structurize-0.10.263-ALPHA.jar
[26Feb2020 13:02:08.146] [Server thread/WARN] [structurize/]: /assets/structurize

### Steps to reproduce the problem
1. Start Server
2. Check the Logs / Console while starting the Server
3. Warning shows
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/ezacpk/0ff46e25e0eb7e8c8917e8bd66b07f63
- crashlog: Server doesnt crash

**Comment by Raycoms** [comment]
No worries. No problem. Fixed soon
