### ISSUE TITLE
techcolonies is not working

### ISSUE THREAD

**Issue by mcplaysnlENG** [ldtteam/minecolonies#4402]
hi team minecolonies i have a issue the issue is that techcolonies wont start up if i launch
the modpack it crash this is the logs file 

[19:52:35] [main/INFO]: ModLauncher running: args [--username, fake_unspeakeble, --version, forge-31.1.18, --gameDir, C:\Users\Lucca\Twitch\Minecraft\Instances\MC-TechColonies (1), --assetsDir, C:\Users\Lucca\Twitch\Minecraft\Install\assets, --assetIndex, 1.15, --uuid, e1dcaaf329d7481ea8775c74ef5a24fe, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 1024, --height, 768, --launchTarget, fmlclient, --fml.forgeVersion, 31.1.18, --fml.mcVersion, 1.15.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200122.131323]
[19:52:35] [main/INFO]: ModLauncher 5.0.0-milestone.4+67+b1a340b starting: java version 1.8.0_51 by Oracle Corporation
[19:52:36] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[19:52:37] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/username/Twitch/Minecraft/Instances/MC-TechColonies%20(1)/mods/MixinBootstrap-1.0.2.jar Service=ModLauncher Env=CLIENT
[19:52:39] [main/INFO]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 10:99 token recognition error at: ';'
[19:52:40] [main/INFO]: Successfully loaded Mixin Connector [be.nevoka.betterbedrockgenerator.MixinConnector]
[19:52:40] [main/INFO]: Invoking Mixin Connector
[19:52:40] [main/INFO]: Launching target 'fmlclient' with arguments [--version, forge-31.1.18, --gameDir, C:\Users\Lucca\Twitch\Minecraft\Instances\MC-TechColonies (1), --assetsDir, C:\Users\Lucca\Twitch\Minecraft\Install\assets, --uuid, e1dcaaf329d7481ea8775c74ef5a24fe, --username, fake_unspeakeble, --assetIndex, 1.15, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 1024, --height, 768]
[19:52:40] [main/WARN]: Error loading class: net/minecraft/entity/player/PlayerEntity (java.lang.ClassNotFoundException: null)
[19:52:40] [main/WARN]: @Mixin target net.minecraft.entity.player.PlayerEntity was not found dankstorage.mixins.json:MixinPlayerEntity
[19:52:40] [main/WARN]: Error loading class: net/minecraft/item/BowItem (java.lang.ClassNotFoundException: null)
[19:52:40] [main/WARN]: @Mixin target net.minecraft.item.BowItem was not found dankstorage.mixins.json:MixinBowItem
[19:52:40] [main/WARN]: Error loading class: net/minecraft/block/Block (java.lang.ClassNotFoundException: null)
[19:52:40] [main/WARN]: @Mixin target net.minecraft.block.Block was not found dankstorage.mixins.json:MixinBlock
[19:52:40] [main/WARN]: Error loading class: net/minecraft/world/gen/NoiseChunkGenerator (java.lang.ClassNotFoundException: null)
[19:52:40] [main/WARN]: @Mixin target net.minecraft.world.gen.NoiseChunkGenerator was not found assets/betterbedrockgenerator/betterbedrockgenerator.mixins.json:MixinFlattenBedrock
[19:52:40] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[19:52:40] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[19:52:40] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[19:52:40] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[19:52:40] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
[19:52:40] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
[19:52:40] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.reflect.InvocationTargetException
[19:52:40] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:52:40] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[19:52:40] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:52:40] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[19:52:40] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
[19:52:40] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$453/1122297225.call(Unknown Source)
[19:52:40] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[19:52:40] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 4 more
[19:52:40] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.NoClassDefFoundError: net/minecraft/util/Util
[19:52:40] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.client.main.Main.main(SourceFile:60)
[19:52:40] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	... 11 more
[19:52:40] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: Caused by: java.lang.ClassNotFoundException: net.minecraft.util.Util
[19:52:40] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
[19:52:40] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[19:52:40] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:101)
[19:52:40] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[19:52:40] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	... 12 more

can you pls fix it 

Greetings minecraft player fake_unspeakeble

**Comment by mcplaysnlENG** [comment]
pls fix it

**Comment by Raycoms** [comment]
This is a modpack issue and not a minecolonie smod issue. Please visit our discord for support on that.
