### ISSUE TITLE
Crash after edit config

### ISSUE THREAD

**Issue by Kao713** [ldtteam/minecolonies#4446]
### Minecolonies version

Version: minecolonies-0.10.768-ALPHA

### Expected behavior

Edit the config file and start the game and play. 
### Actual behaviour

If edit anything in the config file, when the game is starting enters in an loadding loop and never starts. Only happens with this mod. If delete the config file it starts as expected

### Steps to reproduce the problem

1. Edit config
2. Start the game

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
[17:07:29] [main/INFO]: ModLauncher running: args [--username, KaoruDeVil, --version, forge-31.1.0, --gameDir, C:\Users\kaoru\Twitch\Minecraft\Instances\Minecolonias, --assetsDir, C:\Users\kaoru\Twitch\Minecraft\Install\assets, --assetIndex, 1.15, --uuid, 36591c5f2a0f4936aeeec6a44a3b998c, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 1024, --height, 768, --launchTarget, fmlclient, --fml.forgeVersion, 31.1.0, --fml.mcVersion, 1.15.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200122.131323]
[17:07:29] [main/INFO]: ModLauncher 5.0.0-milestone.4+67+b1a340b starting: java version 1.8.0_51 by Oracle Corporation
[17:07:30] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[17:07:32] [main/INFO]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 36:0 token recognition error at: 'S'
[17:07:32] [main/INFO]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 36:1 token recognition error at: 'pa'
[17:07:32] [main/INFO]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 36:3 token recognition error at: 'w'
[17:07:32] [main/INFO]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 36:4 token recognition error at: 'n'
[17:07:32] [main/INFO]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 36:5 token recognition error at: 'e'
[17:07:32] [main/INFO]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 36:6 token recognition error at: 'r'
[17:07:32] [main/INFO]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 36:8 token recognition error at: 'N'
[17:07:32] [main/INFO]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 36:9 token recognition error at: 'B'
[17:07:32] [main/INFO]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 36:10 token recognition error at: 'T'
[17:07:33] [main/INFO]: Launching target 'fmlclient' with arguments [--version, forge-31.1.0, --gameDir, C:\Users\kaoru\Twitch\Minecraft\Instances\Minecolonias, --assetsDir, C:\Users\kaoru\Twitch\Minecraft\Install\assets, --uuid, 36591c5f2a0f4936aeeec6a44a3b998c, --username, KaoruDeVil, --assetIndex, 1.15, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 1024, --height, 768]
[17:07:38] [Render thread/INFO]: Setting user: KaoruDeVil
[17:07:54] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[17:07:58] [modloading-worker-2/INFO]: Forge mod loading, version 31.1.0, for MC 1.15.2 with MCP 20200122.131323
[17:07:58] [modloading-worker-2/INFO]: MinecraftForge v31.1.0 Initialized
[17:07:59] [modloading-worker-2/WARN]: Structurize starting up
[17:08:01] [Render thread/INFO]: Blocks registered.
[17:08:03] [Render thread/INFO]: Items registered.
[17:08:03] [Render thread/WARN]: No data fixer registered for entity minecolonies:citizen
[17:08:03] [Render thread/WARN]: No data fixer registered for entity minecolonies:fishhook
[17:08:03] [Render thread/WARN]: No data fixer registered for entity minecolonies:mercenary
[17:08:03] [Render thread/WARN]: No data fixer registered for entity minecolonies:barbarian
[17:08:03] [Render thread/WARN]: No data fixer registered for entity minecolonies:archerbarbarian
[17:08:03] [Render thread/WARN]: No data fixer registered for entity minecolonies:chiefbarbarian
[17:08:03] [Render thread/WARN]: No data fixer registered for entity minecolonies:pirate
[17:08:03] [Render thread/WARN]: No data fixer registered for entity minecolonies:archerpirate
[17:08:03] [Render thread/WARN]: No data fixer registered for entity minecolonies:chiefpirate
[17:08:03] [Render thread/WARN]: No data fixer registered for entity minecolonies:sittingentity
[17:08:06] [Render thread/WARN]: No data fixer registered for entity biomesoplenty:boat_bop
[17:08:09] [Render thread/INFO]: Narrator library for x64 successfully loaded
[17:08:09] [Render thread/INFO]: Reloading ResourceManager: Default, Mod Resources
[17:08:17] [Server-Worker-3/WARN]: Configuration file C:\Users\kaoru\Twitch\Minecraft\Instances\Minecolonias\config\journeymap-common.toml is not correct. Correcting
[17:08:17] [Server-Worker-3/WARN]: Incorrect key admins.serverAdmins was corrected from [mysticdrew, 12341234132] to [mysticdrew, 12341234132]
[17:08:17] [Server-Worker-3/INFO]: Loading JourneyMap Forge Configs
[17:08:17] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: com.electronwill.nightconfig.core.io.ParsingException: Invalid bare key: ?
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1621) ~[?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51]
Caused by: com.electronwill.nightconfig.core.io.ParsingException: Invalid bare key: ?
	at com.electronwill.nightconfig.toml.TableParser.parseKey(TableParser.java:175) ~[toml-3.6.2.jar:?]
	at com.electronwill.nightconfig.toml.TableParser.parseDottedKey(TableParser.java:145) ~[toml-3.6.2.jar:?]
	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:55) ~[toml-3.6.2.jar:?]
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:44) ~[toml-3.6.2.jar:?]
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37) ~[toml-3.6.2.jar:?]
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113) ~[core-3.6.2.jar:?]
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219) ~[core-3.6.2.jar:?]
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[core-3.6.2.jar:?]
	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73) ~[core-3.6.2.jar:?]
	at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85) ~[core-3.6.2.jar:?]
	at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:53) ~[?:?]
	at net.minecraftforge.fml.config.ConfigFileTypeHandler$$Lambda$3181/562324245.apply(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:99) ~[?:?]
	at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:83) ~[?:?]
	at net.minecraftforge.fml.config.ConfigTracker$$Lambda$3180/296773447.accept(Unknown Source) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_51]
	at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2062) ~[?:1.8.0_51]
	at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:83) ~[?:?]
	at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:152) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$startModLoading$6(ClientModLoader.java:123) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$3174/1344661388.run(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2043/1070366556.run(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.startModLoading(ClientModLoader.java:123) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$onreload$3(ClientModLoader.java:105) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$3098/1317025467.run(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:113) ~[?:?]
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$2043/1070366556.run(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51]
	... 5 more
[17:08:19] [Render thread/INFO]: Reloading ResourceManager: Default, Mod Resources
[17:08:19] [Server-Worker-1/WARN]: Exception loading blockstate definition: minecraft:blockstates/green_bed.json: java.io.FileNotFoundException: minecraft:blockstates/green_bed.json
[17:08:19] [Server-Worker-1/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/green_bed.json' missing model for variant: 'minecraft:green_bed#facing=south,occupied=true,part=foot'
[17:08:19] [Server-Worker-1/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/green_bed.json' missing model for variant: 'minecraft:green_bed#facing=west,occupied=false,part=foot'
[17:08:19] [Server-Worker-1/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/green_bed.json' missing model for variant: 'minecraft:green_bed#facing=west,occupied=true,part=foot'
[17:08:19] [Server-Worker-1/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/green_bed.json' missing model for variant: 'minecraft:green_bed#facing=north,occupied=false,part=foot'
[17:08:19] [Server-Worker-1/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/green_bed.json' missing model for variant: 'minecraft:green_bed#facing=east,occupied=false,part=head'
[17:08:19] [Server-Worker-1/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/green_bed.json' missing model for variant: 'minecraft:green_bed#facing=east,occupied=true,part=head'
[17:08:19] [Server-Worker-1/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/green_bed.json' missing model for variant: 'minecraft:green_bed#facing=east,occupied=false,part=foot'
[17:08:19] [Server-Worker-1/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/green_bed.json' missing model for variant: 'minecraft:green_bed#facing=south,occupied=false,part=foot'
[17:08:19] [Server-Worker-1/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/green_bed.json' missing model for variant: 'minecraft:green_bed#facing=north,occupied=true,part=foot'
[17:08:19] [Server-Worker-1/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/green_bed.json' missing model for variant: 'minecraft:green_bed#facing=south,occupied=true,part=head'
[17:08:19] [Server-Worker-1/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/green_bed.json' missing model for variant: 'minecraft:green_bed#facing=north,occupied=false,part=head'
[17:08:19] [Server-Worker-1/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/green_bed.json' missing model for variant: 'minecraft:green_bed#facing=north,occupied=true,part=head'
[17:08:19] [Server-Worker-1/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/green_bed.json' missing model for variant: 'minecraft:green_bed#facing=west,occupied=false,part=head'
[17:08:19] [Server-Worker-1/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/green_bed.json' missing model for variant: 'minecraft:green_bed#facing=west,occupied=true,part=head'
[17:08:19] [Server-Worker-1/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/green_bed.json' missing model for variant: 'minecraft:green_bed#facing=south,occupied=false,part=head'
[17:08:19] [Server-Worker-1/WARN]: Exception loading blockstate definition: 'minecraft:blockstates/green_bed.json' missing model for variant: 'minecraft:green_bed#facing=east,occupied=true,part=foot'
[17:08:27] [Server-Worker-1/WARN]: Unable to resolve texture reference: #missing in minecolonies:block/blockhutwarehouse
[17:08:27] [Server-Worker-1/WARN]: Unable to resolve texture reference: #missing in minecolonies:item/blockwaypoint
[17:08:27] [Server-Worker-1/WARN]: Unable to resolve texture reference: #missing in 
[17:08:27] [Server-Worker-1/WARN]: Unable to resolve texture reference: #missing in minecolonies:block/blockhutfisherman
[17:08:27] [Server-Worker-1/WARN]: Unable to resolve texture reference: #missing in minecolonies:item/blockhutbuilder
[17:08:27] [Server-Worker-1/WARN]: Unable to resolve texture reference: #missing in minecolonies:block/blockhutcrusher
[17:08:27] [Server-Worker-1/WARN]: Unable to resolve texture reference: #missing in minecolonies:block/blockhuttownhall
[17:08:27] [Server-Worker-1/WARN]: Unable to resolve texture reference: #missing in minecolonies:block/blockhutsmeltery
[17:08:27] [Server-Worker-1/WARN]: Unable to resolve texture reference: #missing in minecolonies:block/blockpostbox
[17:08:27] [Server-Worker-1/WARN]: Unable to resolve texture reference: #missing in minecolonies:block/blockhutchickenherder
[17:08:27] [Server-Worker-1/WARN]: Unable to resolve texture reference: #missing in minecolonies:block/blockhutcowboy
[17:08:27] [Server-Worker-1/WARN]: Unable to resolve texture reference: #missing in minecolonies:block/blockhutsifter
[17:08:27] [Server-Worker-1/WARN]: Unable to resolve texture reference: #missing in minecolonies:item/blockhutfisherman
[17:08:27] [Server-Worker-1/WARN]: Unable to resolve texture reference: #missing in minecolonies:item/blockhutcowboy
[17:08:27] [Server-Worker-1/WARN]: Unable to resolve texture reference: #missing in minecolonies:item/blockhutchickenherder
[17:08:27] [Server-Worker-1/WARN]: Unable to resolve texture reference: #missing in minecolonies:block/blockhutbuilder
[17:08:27] [Server-Worker-1/WARN]: Unable to resolve texture reference: #missing in minecolonies:item/blockhutbarracks
[17:08:27] [Server-Worker-1/WARN]: Unable to resolve texture reference: #missing in minecolonies:item/blockhuttownhall
[17:08:27] [Server-Worker-1/WARN]: Unable to resolve texture reference: #missing in minecolonies:block/blockhutbarracks
[17:08:27] [Server-Worker-1/WARN]: Unable to resolve texture reference: #missing in minecolonies:block/blockwaypoint
[17:08:27] [Server-Worker-1/WARN]: Unable to resolve texture reference: #missing in minecolonies:item/blockhutwarehouse
[17:08:27] [Server-Worker-1/WARN]: Unable to resolve texture reference: #missing in minecolonies:item/blockhutsmeltery
[17:08:27] [Server-Worker-1/WARN]: Unable to resolve texture reference: #missing in minecolonies:item/blockhutcrusher
[17:08:27] [Server-Worker-1/WARN]: Unable to resolve texture reference: #missing in minecolonies:item/blockhutsifter
[17:08:27] [Server-Worker-1/WARN]: Unable to resolve texture reference: #missing in minecolonies:item/blockpostbox
[17:08:27] [Server-Worker-6/WARN]: Configuration file C:\Users\kaoru\Twitch\Minecraft\Instances\Minecolonias\config\journeymap-common.toml is not correct. Correcting
[17:08:27] [Server-Worker-6/WARN]: Incorrect key admins.serverAdmins was corrected from [mysticdrew, 12341234132] to [mysticdrew, 12341234132]
[17:08:27] [Server-Worker-6/INFO]: Loading JourneyMap Forge Configs
[17:08:35] [Server-Worker-7/WARN]: Unable to resolve texture reference: #missing in minecolonies:block/blockhutwarehouse
[17:08:35] [Server-Worker-7/WARN]: Unable to resolve texture reference: #missing in minecolonies:item/blockwaypoint
[17:08:35] [Server-Worker-7/WARN]: Unable to resolve texture reference: #missing in 
[17:08:35] [Server-Worker-7/WARN]: Unable to resolve texture reference: #missing in minecolonies:block/blockhutfisherman
[17:08:35] [Server-Worker-7/WARN]: Unable to resolve texture reference: #missing in minecolonies:item/blockhutbuilder
[17:08:35] [Server-Worker-7/WARN]: Unable to resolve texture reference: #missing in minecolonies:block/blockhutcrusher
[17:08:35] [Server-Worker-7/WARN]: Unable to resolve texture reference: #missing in minecolonies:block/blockhuttownhall
[17:08:35] [Server-Worker-7/WARN]: Unable to resolve texture reference: #missing in minecolonies:block/blockhutsmeltery
[17:08:35] [Server-Worker-7/WARN]: Unable to resolve texture reference: #missing in minecolonies:block/blockpostbox
[17:08:35] [Server-Worker-7/WARN]: Unable to resolve texture reference: #missing in minecolonies:block/blockhutchickenherder
[17:08:35] [Server-Worker-7/WARN]: Unable to resolve texture reference: #missing in minecolonies:block/blockhutcowboy
[17:08:35] [Server-Worker-7/WARN]: Unable to resolve texture reference: #missing in minecolonies:block/blockhutsifter
[17:08:35] [Server-Worker-7/WARN]: Unable to resolve texture reference: #missing in minecolonies:item/blockhutfisherman
[17:08:35] [Server-Worker-7/WARN]: Unable to resolve texture reference: #missing in minecolonies:item/blockhutcowboy
[17:08:35] [Server-Worker-7/WARN]: Unable to resolve texture reference: #missing in minecolonies:item/blockhutchickenherder
[17:08:35] [Server-Worker-7/WARN]: Unable to resolve texture reference: #missing in minecolonies:block/blockhutbuilder
[17:08:35] [Server-Worker-7/WARN]: Unable to resolve texture reference: #missing in minecolonies:item/blockhutbarracks
[17:08:35] [Server-Worker-7/WARN]: Unable to resolve texture reference: #missing in minecolonies:item/blockhuttownhall
[17:08:35] [Server-Worker-7/WARN]: Unable to resolve texture reference: #missing in minecolonies:block/blockhutbarracks
[17:08:35] [Server-Worker-7/WARN]: Unable to resolve texture reference: #missing in minecolonies:block/blockwaypoint
[17:08:35] [Server-Worker-7/WARN]: Unable to resolve texture reference: #missing in minecolonies:item/blockhutwarehouse
[17:08:35] [Server-Worker-7/WARN]: Unable to resolve texture reference: #missing in minecolonies:item/blockhutsmeltery
[17:08:35] [Server-Worker-7/WARN]: Unable to resolve texture reference: #missing in minecolonies:item/blockhutcrusher
[17:08:35] [Server-Worker-7/WARN]: Unable to resolve texture reference: #missing in minecolonies:item/blockhutsifter
[17:08:35] [Server-Worker-7/WARN]: Unable to resolve texture reference: #missing in minecolonies:item/blockpostbox
[17:08:37] [Server-Worker-1/WARN]: Texture minecolonies:blocks/tallgrass with size 265x265 limits mip level from 4 to 0
[17:08:37] [Server-Worker-7/WARN]: Texture minecolonies:blocks/tallgrass with size 265x265 limits mip level from 4 to 0
[17:09:15] [Render thread/INFO]: Stopping!
[17:09:15] [Render thread/ERROR]: Shutdown failure!
java.lang.NullPointerException: null
	at net.minecraft.client.renderer.model.ModelManager.close(ModelManager.java:102) ~[?:?]
	at net.minecraft.client.Minecraft.close(Minecraft.java:853) [?:?]
	at net.minecraft.client.Minecraft.func_71405_e(Minecraft.java:840) [?:?]
	at net.minecraft.client.main.Main.main(SourceFile:218) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.0.jar:31.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$394/358019805.call(Unknown Source) [forge-1.15.2-31.1.0.jar:31.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?]

- crashlog:

**Comment by Raycoms** [comment]
You seem to have added invalid value sin the config file. Forge fails to parse in that case.

Please revise the file or else report to forge.
