### ISSUE TITLE
Townhall / Client Crash

### ISSUE THREAD

**Issue by djpanda** [ldtteam/minecolonies#4485]
### Minecolonies version
minecolonies-0.11.776-ALPHA-universal.jar
Version: 

### Expected behavior

- See infos of the citizens

### Actual behaviour

- Client crashes if you try to open the tab

### Steps to reproduce the problem

1. Open up townhall UI
2. Switch to Citizens tab (who showes names of the citizens on the right side and infos of the selected citizen on the left)
3. client crashes

### Logs: Latest.log and crashlog at https://gist.github.com/

- crashlog:
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 3/22/20 8:23 PM
Description: mouseClicked event handler

java.lang.NullPointerException: mouseClicked event handler
	at com.minecolonies.coremod.client.gui.WindowCitizen.createSkillContent(WindowCitizen.java:339) ~[?:0.11.776-ALPHA] {re:classloading}
	at com.minecolonies.coremod.client.gui.WindowTownHall.fillCitizenInfo(WindowTownHall.java:887) ~[?:0.11.776-ALPHA] {re:classloading}
	at com.minecolonies.coremod.client.gui.WindowTownHall$$Lambda$10245/985692864.accept(Unknown Source) ~[?:?] {}
	at com.minecolonies.coremod.client.gui.AbstractWindowSkeleton.onButtonClicked(AbstractWindowSkeleton.java:107) ~[?:0.11.776-ALPHA] {re:classloading}
	at com.ldtteam.blockout.controls.Button.handleClick(Button.java:95) ~[?:0.10.284-BETA] {re:classloading}
	at com.ldtteam.blockout.Pane.click(Pane.java:479) ~[?:0.10.284-BETA] {re:classloading}
	at com.ldtteam.blockout.views.View$$Lambda$10267/545245281.accept(Unknown Source) ~[?:?] {}
	at com.ldtteam.blockout.views.View.mouseEventProcessor(View.java:307) ~[?:0.10.284-BETA] {re:classloading}
	at com.ldtteam.blockout.views.View.mouseClickableEventHandler(View.java:271) ~[?:0.10.284-BETA] {re:classloading}
	at com.ldtteam.blockout.views.View.click(View.java:141) ~[?:0.10.284-BETA] {re:classloading}
	at com.ldtteam.blockout.views.View$$Lambda$10267/545245281.accept(Unknown Source) ~[?:?] {}
	at com.ldtteam.blockout.views.View.mouseEventProcessor(View.java:307) ~[?:0.10.284-BETA] {re:classloading}
	at com.ldtteam.blockout.views.View.mouseClickableEventHandler(View.java:271) ~[?:0.10.284-BETA] {re:classloading}
	at com.ldtteam.blockout.views.View.click(View.java:141) ~[?:0.10.284-BETA] {re:classloading}
	at com.ldtteam.blockout.views.ScrollingContainer.click(ScrollingContainer.java:85) ~[?:0.10.284-BETA] {re:classloading}
	at com.ldtteam.blockout.views.View$$Lambda$10267/545245281.accept(Unknown Source) ~[?:?] {}
	at com.ldtteam.blockout.views.View.mouseEventProcessor(View.java:307) ~[?:0.10.284-BETA] {re:classloading}
	at com.ldtteam.blockout.views.View.mouseClickableEventHandler(View.java:271) ~[?:0.10.284-BETA] {re:classloading}
	at com.ldtteam.blockout.views.View.click(View.java:141) ~[?:0.10.284-BETA] {re:classloading}
	at com.ldtteam.blockout.views.View$$Lambda$10267/545245281.accept(Unknown Source) ~[?:?] {}
	at com.ldtteam.blockout.views.View.mouseEventProcessor(View.java:307) ~[?:0.10.284-BETA] {re:classloading}
	at com.ldtteam.blockout.views.View.mouseClickableEventHandler(View.java:271) ~[?:0.10.284-BETA] {re:classloading}
	at com.ldtteam.blockout.views.View.click(View.java:141) ~[?:0.10.284-BETA] {re:classloading}
	at com.ldtteam.blockout.views.View$$Lambda$10267/545245281.accept(Unknown Source) ~[?:?] {}
	at com.ldtteam.blockout.views.View.mouseEventProcessor(View.java:307) ~[?:0.10.284-BETA] {re:classloading}
	at com.ldtteam.blockout.views.View.mouseClickableEventHandler(View.java:271) ~[?:0.10.284-BETA] {re:classloading}
	at com.ldtteam.blockout.views.View.click(View.java:141) ~[?:0.10.284-BETA] {re:classloading}
	at com.ldtteam.blockout.views.View$$Lambda$10267/545245281.accept(Unknown Source) ~[?:?] {}
	at com.ldtteam.blockout.views.View.mouseEventProcessor(View.java:307) ~[?:0.10.284-BETA] {re:classloading}
	at com.ldtteam.blockout.views.View.mouseClickableEventHandler(View.java:271) ~[?:0.10.284-BETA] {re:classloading}
	at com.ldtteam.blockout.views.View.click(View.java:141) ~[?:0.10.284-BETA] {re:classloading}
	at com.ldtteam.blockout.views.View$$Lambda$10267/545245281.accept(Unknown Source) ~[?:?] {}
	at com.ldtteam.blockout.views.View.mouseEventProcessor(View.java:307) ~[?:0.10.284-BETA] {re:classloading}
	at com.ldtteam.blockout.views.View.mouseClickableEventHandler(View.java:271) ~[?:0.10.284-BETA] {re:classloading}
	at com.ldtteam.blockout.views.View.click(View.java:141) ~[?:0.10.284-BETA] {re:classloading}
	at com.ldtteam.blockout.views.View$$Lambda$10267/545245281.accept(Unknown Source) ~[?:?] {}
	at com.ldtteam.blockout.views.View.mouseEventProcessor(View.java:307) ~[?:0.10.284-BETA] {re:classloading}
	at com.ldtteam.blockout.views.View.mouseClickableEventHandler(View.java:271) ~[?:0.10.284-BETA] {re:classloading}
	at com.ldtteam.blockout.views.View.click(View.java:141) ~[?:0.10.284-BETA] {re:classloading}
	at com.ldtteam.blockout.BOScreen.mouseClicked(BOScreen.java:166) ~[?:0.10.284-BETA] {re:classloading}
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:82) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$8603/1105782740.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:446) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:80) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:163) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$7949/54860016.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:162) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$6577/924150779.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:98) ~[?:?] {re:classloading}
	at net.minecraft.client.MainWindow.func_227802_e_(SourceFile:301) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:customwindowtitle:CustomWindowTitle,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:554) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:customwindowtitle:CustomWindowTitle,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.25.jar:31.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$452/431097582.call(Unknown Source) [forge-1.15.2-31.1.25.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.minecolonies.coremod.client.gui.WindowCitizen.createSkillContent(WindowCitizen.java:339)
	at com.minecolonies.coremod.client.gui.WindowTownHall.fillCitizenInfo(WindowTownHall.java:887)
	at com.minecolonies.coremod.client.gui.WindowTownHall$$Lambda$10245/985692864.accept(Unknown Source)
	at com.minecolonies.coremod.client.gui.AbstractWindowSkeleton.onButtonClicked(AbstractWindowSkeleton.java:107)
	at com.ldtteam.blockout.controls.Button.handleClick(Button.java:95)
	at com.ldtteam.blockout.Pane.click(Pane.java:479)
	at com.ldtteam.blockout.views.View$$Lambda$10267/545245281.accept(Unknown Source)
	at com.ldtteam.blockout.views.View.mouseEventProcessor(View.java:307)
	at com.ldtteam.blockout.views.View.mouseClickableEventHandler(View.java:271)
	at com.ldtteam.blockout.views.View.click(View.java:141)
	at com.ldtteam.blockout.views.View$$Lambda$10267/545245281.accept(Unknown Source)
	at com.ldtteam.blockout.views.View.mouseEventProcessor(View.java:307)
	at com.ldtteam.blockout.views.View.mouseClickableEventHandler(View.java:271)
	at com.ldtteam.blockout.views.View.click(View.java:141)
	at com.ldtteam.blockout.views.ScrollingContainer.click(ScrollingContainer.java:85)
	at com.ldtteam.blockout.views.View$$Lambda$10267/545245281.accept(Unknown Source)
	at com.ldtteam.blockout.views.View.mouseEventProcessor(View.java:307)
	at com.ldtteam.blockout.views.View.mouseClickableEventHandler(View.java:271)
	at com.ldtteam.blockout.views.View.click(View.java:141)
	at com.ldtteam.blockout.views.View$$Lambda$10267/545245281.accept(Unknown Source)
	at com.ldtteam.blockout.views.View.mouseEventProcessor(View.java:307)
	at com.ldtteam.blockout.views.View.mouseClickableEventHandler(View.java:271)
	at com.ldtteam.blockout.views.View.click(View.java:141)
	at com.ldtteam.blockout.views.View$$Lambda$10267/545245281.accept(Unknown Source)
	at com.ldtteam.blockout.views.View.mouseEventProcessor(View.java:307)
	at com.ldtteam.blockout.views.View.mouseClickableEventHandler(View.java:271)
	at com.ldtteam.blockout.views.View.click(View.java:141)
	at com.ldtteam.blockout.views.View$$Lambda$10267/545245281.accept(Unknown Source)
	at com.ldtteam.blockout.views.View.mouseEventProcessor(View.java:307)
	at com.ldtteam.blockout.views.View.mouseClickableEventHandler(View.java:271)
	at com.ldtteam.blockout.views.View.click(View.java:141)
	at com.ldtteam.blockout.views.View$$Lambda$10267/545245281.accept(Unknown Source)
	at com.ldtteam.blockout.views.View.mouseEventProcessor(View.java:307)
	at com.ldtteam.blockout.views.View.mouseClickableEventHandler(View.java:271)
	at com.ldtteam.blockout.views.View.click(View.java:141)
	at com.ldtteam.blockout.views.View$$Lambda$10267/545245281.accept(Unknown Source)
	at com.ldtteam.blockout.views.View.mouseEventProcessor(View.java:307)
	at com.ldtteam.blockout.views.View.mouseClickableEventHandler(View.java:271)
	at com.ldtteam.blockout.views.View.click(View.java:141)
	at com.ldtteam.blockout.BOScreen.mouseClicked(BOScreen.java:166)
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:82)
	at net.minecraft.client.MouseHelper$$Lambda$8603/1105782740.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: com.ldtteam.blockout.BOScreen
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:446)
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:80)
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:163)
	at net.minecraft.client.MouseHelper$$Lambda$7949/54860016.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94)
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:162)
	at net.minecraft.client.MouseHelper$$Lambda$6577/924150779.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:98)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['_djpanda_'/77781, l='MpServer', x=-1088.57, y=64.00, z=-521.75]]
	Chunk stats: Client Chunk Cache: 729, 483
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 6465825770476095769
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-16,70,208), Chunk: (at 0,4,0 in -1,13; contains blocks -16,0,208 to -1,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 54509752 game time, 1383 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:442)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1764)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:568)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$452/431097582.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1069438600 bytes (1019 MB) / 3315073024 bytes (3161 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 12
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6912m -Xms256m -XX:PermSize=256m
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.25.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.25.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.4-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.25.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.25.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.25.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.2.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.25
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		incontrol-1.15-4.0.1.jar InControl {incontrol@1.15-4.0.1 DONE}
		mcw-windows-1.0.0-mc1.15.1_1.15.2.jar Macaw's Windows {mcwwindows@1.0.0 DONE}
		SilentMechanisms-1.15.2-0.7.0+50.jar Silent's Mechanisms {silents_mechanisms@0.7.0+50 DONE}
		Industrial Agriculture[Core]-1.15.2-1.6.6.jar Industrial Agriculture {industrialagriculture@1.15.2-1.6.6 DONE}
		KleeSlabs_1.15.2-8.0.0.jar KleeSlabs {kleeslabs@8.0.0 DONE}
		noautojump-1.15.2-1.jar No Auto-Jump {noautojump@1.15.2-1 DONE}
		IronJetpacks-1.15.2-3.0.1.jar Iron Jetpacks {ironjetpacks@3.0.1 DONE}
		CoffeeSpawner-1.15.1-6.0.0.jar Coffee Spawner {coffeespawner@1.15.1-6.0.0 DONE}
		BetterTitleScreen-1.15.2-1.9.jar Better Title Screen {bettertitlescreen@1.15.2-1.9 DONE}
		XaerosWorldMap_1.5.6_Forge_1.15.2.jar Xaero's World Map {xaeroworldmap@1.5.6 DONE}
		Controlling-6.1.1.jar Controlling {controlling@6.1.1 DONE}
		ReAuth-1.14-3.8.0.jar ReAuth {reauth@3.8.0 DONE}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 DONE}
		dankstorage-2.5.jar Dank Storage {dankstorage@2.5 DONE}
		Powah-1.15.2-1.1.9.jar Powah {powah@1.1.9 DONE}
		dimensionalworld-1.0.0.jar Buuz135DimensionalWorld {dimensionalworld@NONE DONE}
		rangedpumps-0.7.1.jar Ranged Pumps {rangedpumps@0.7.1 DONE}
		WitherSkeletonTweaks-1.15.1-4.0.0.jar Wither Skeleton Tweaks {wstweaks@4.0.0 DONE}
		randompatches-1.15.2-1.21.1.1.jar RandomPatches {randompatches@1.15.2-1.21.1.1 DONE}
		Morpheus-1.15.2-4.2.50.jar Morpheus {morpheus@version DONE}
		MekanismGenerators-1.15.2-9.9.16.408.jar Mekanism: Generators {mekanismgenerators@9.9.16 DONE}
		speedyhoppers-1.15.2-2.jar Speedy Hoppers {speedyhoppers@1.15.2-2 DONE}
		carpetstairsmod-mc1.15-v1.3.jar Carpet Stairs Mod {carpetstairsmod@1.1 DONE}
		MysticalAgradditions-1.15.2-3.0.0.jar Mystical Agradditions {mysticalagradditions@3.0.0 DONE}
		mysticallib-1.15.2-2.0.0.jar Mystical Lib {mysticallib@1.15.2-2.0.0 DONE}
		absentbydesign-1.15.2-1.0.5 .jar Absent By Design Mod {absentbydesign@1.15.2-1.0.5  DONE}
		refinedstorage-1.8.1.jar Refined Storage {refinedstorage@1.8.1 DONE}
		PackMenu-1.15.2-1.1.7.jar Pack Menu {packmenu@1.1.7 DONE}
		industrial-foregoing-1.15.2-2.2.2-28d4a81.jar Industrial Foregoing {industrialforegoing@2.2.2 DONE}
		AmbientSounds_v3.0.19_mc1.15.2.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		Industrial Agriculture[Silent's Mechanisms]-1.15.2-1.6.0.jar Industrial Agriculture Plugin-Silent's Mechanisms {iapsm@1.15.2-1.6.0 DONE}
		valkyrielib-1.15.2-3.0.2.1.jar ValkyrieLib {valkyrielib@1.15.2-3.0.2.1 DONE}
		Lollipop-1.15.2-1.0.11.jar Lollipop {lollipop@1.0.11 DONE}
		SilentGear-1.15.2-1.5.4+79.jar Silent Gear {silentgear@1.5.4+79 DONE}
		Patchouli-1.15.2-1.2-28.jar Patchouli {patchouli@1.15.2-1.2-28 DONE}
		ClothConfig2-2.0.jar Cloth Config Forge v2 API {cloth-config2@2.0 DONE}
		OreExcavation-1.7.151.jar Ore Excavation {oreexcavation@NONE DONE}
		tanknull-1.8a.jar Tank Null {tanknull@1.8a DONE}
		lostcities-1.15-3.0.0-alpha.jar LostCities {lostcities@1.15-3.0.0-alpha DONE}
		libnonymous-1.15.2-1.1.1.5.jar Libnonymous {libnonymous@1.1.1.5 DONE}
		elevatorid-1.15.2-1.7.0.jar Elevator Mod {elevatorid@1.15.2-1.7.0 DONE}
		tombstone-4.2.5-1.15.2.jar Corail Tombstone {tombstone@4.2.5 DONE}
		Server Utils-1.15.2-1.1.10.jar Elrol's Server Utilities {serverutilities@1.15.2-1.1.10 DONE}
		NaturesAura-23.3.jar Nature's Aura {naturesaura@version DONE}
		MekanismTools-1.15.2-9.9.16.408.jar Mekanism: Tools {mekanismtools@9.9.16 DONE}
		AI-Improvements-1.15.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 DONE}
		nosoliciting-1.1.jar No Soliciting {nosoliciting@1.1 DONE}
		BetterBurning-1.15.2-1.3.1.jar BetterBurning {betterburning@1.3.1 DONE}
		bwncr-1.15.1-3.6.13.jar Bad Wither No Cookie Reloaded {bwncr@1.15.1-3.6.13 DONE}
		CustomWindowTitle-1.15.2-v1.0.0.jar Custom Window Title {customwindowtitle@1.0.0 DONE}
		speedyladders-1.15.2-1.jar Speedy Ladders {speedyladders@1.15.2-1 DONE}
		ServerTabInfo-1.15.2-1.2.6.jar Server Tab Info {servertabinfo@1.2.6 DONE}
		SimpleDiscordRichPresence-1.15.2-1.2.4.jar Simple Discord Rich Presence {sdrp@1.15.2-1.2.4 DONE}
		Cyclic-1.15.2-0.2.0.jar Cyclic {cyclic@1.15.2-0.2.0 DONE}
		Industrial Agriculture[Industrial Foregoing]-1.15.2-1.6.1.jar Industrial Agriculture Plugin-Industrial Foregoing {iapif@1.15.2-1.6.1 DONE}
		Kiwi-1.15.2-2.7.0.jar Kiwi {kiwi@2.7.0 DONE}
		ClientTweaks_1.15.2-4.1.1.jar Client Tweaks {clienttweaks@4.1.1 DONE}
		Cucumber-1.15.2-3.0.3.jar Cucumber Library {cucumber@3.0.3 DONE}
		craftingstation-3.1.0.jar Crafting Station {craftingstation@3.1.0 DONE}
		janoeo-3.2.jar Just Another Nether/Overworld/End Ores {janoeo@3.2 DONE}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 DONE}
		buzzierbees-1.3.jar Buzzier Bees {buzzierbees@1.3 DONE}
		AttributeFix-1.15.2-7.0.1.jar AttributeFix {attributefix@7.0.1 DONE}
		Mekanism-1.15.2-9.9.16.408.jar Mekanism {mekanism@9.9.16 DONE}
		invtweaks-1.15.2-1.0.1.jar Inventory Tweaks Reborn {invtweaks@1.15.2-1.0.1 DONE}
		LightOverlay-4.3.jar Light Overlay Forge {lightoverlay-forge@4.3 DONE}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 DONE}
		premenuscreen-1.3.jar Pre Menu Screen {premenuscreen@1.3 DONE}
		gardentools-1.15.2-1.0.0.jar Garden Tools {gardentools@1.15.2-1.0.0 DONE}
		DimStorage-1.15.2-3.0.1.jar DimStorage {dimstorage@3.0.1 DONE}
		BonsaiTrees-2.1.2.6.jar Bonsai Trees 2 {bonsaitrees2@2.1.2.6 DONE}
		mcjtylib-1.15-4.0.2-alpha.jar McJtyLib {mcjtylib@1.15-4.0.2-alpha DONE}
		rftoolsbase-1.15-1.0.0-alpha.jar RFToolsBase {rftoolsbase@1.15-1.0.0-alpha DONE}
		xnet-1.15-2.0.1-alpha.jar XNet {xnet@1.15-2.0.1-alpha DONE}
		rftoolsstorage-1.15-1.0.2-alpha.jar RFToolsStorage {rftoolsstorage@1.15-1.0.2-alpha DONE}
		netherpunishment-1.15.2-0.0.0.1.jar netherpunishment {netherpunishment@NONE DONE}
		ToastControl-1.15.2-3.0.1.jar Toast Control {toastcontrol@3.0.1 DONE}
		traverse-1.15.2-3.0.0.jar Traverse {traverse@1.15.2-3.0.0 DONE}
		CraftTweaker-1.15.2-6.0.0.9.jar CraftTweaker {crafttweaker@6.0.0.9 DONE}
		extradisks-1.15.1-1.2.jar Extra Disks {extradisks@1.15.1-1.2 DONE}
		forge-1.15.2-31.1.25-universal.jar Forge {forge@31.1.25 DONE}
		MysticalAgriculture-1.15.2-3.0.1.jar Mystical Agriculture {mysticalagriculture@3.0.1 DONE}
		colouredchat-1.15.1-1.4.5.jar ColouredChat {colouredchat@1.15.1-1.4.5 DONE}
		forge-1.15.2-31.1.25-client.jar Minecraft {minecraft@1.15.2 DONE}
		cofh_core-1.15.2-0.3.2b.jar CoFH Core {cofh_core@0.3.2b DONE}
		ensorcellation-1.15.2-0.3.0b.jar Ensorcellation {ensorcellation@0.3.0b DONE}
		rftoolsutility-1.15-2.0.0-alpha.jar RFToolsUtility {rftoolsutility@1.15-2.0.0-alpha DONE}
		theoneprobe-1.15-2.0.1.jar The One Probe {theoneprobe@1.15-2.0.1 DONE}
		swingthroughgrass-1.15.2-1.4.0.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.0 DONE}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		titanium-1.15.2-2.3.7.jar Titanium {titanium@2.3.7 DONE}
		SilentLib-1.15.2-4.6.0+48.jar Silent Lib {silentlib@4.6.0+48 DONE}
		archers_paradox-1.15.2-0.3.0b.jar Archer's Paradox {archers_paradox@0.3.0b DONE}
		Ding-1.15.1-1.1.0.jar Ding {ding@1.1.0 DONE}
		rftoolsbuilder-1.15-2.0.0-alpha.jar RFToolsBuilder {rftoolsbuilder@1.15-2.0.0-alpha DONE}
		jnemloadscreen-1.0.0.0.jar JNEM Loadscreen {jnemloadscreen@1.0.0.0 DONE}
		Xaeros_Minimap_20.5.2_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.5.2 DONE}
		JAOPCA-1.15.2-3.0.0.21.jar JAOPCA {jaopca@3.0.0.21 DONE}
		extratags-1.0.jar Extra Tags {extratags@1.0 DONE}
		FastWorkbench-1.15.1-3.0.0.jar FastWorkbench {fastbench@3.0.0 DONE}
		StorageDrawers-1.15.2-7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 DONE}
		backpacked-1.4.1-1.15.2.jar Backpacked {backpacked@1.4.1 DONE}
		harvest-1.15.2-1.0.1.jar Harvest {harvest@1.0.1 DONE}
		structurize-0.10.284-BETA.jar Structurize {structurize@0.10.284-BETA DONE}
		minecolonies-0.11.776-ALPHA-universal.jar Minecolonies {minecolonies@0.11.776-ALPHA DONE}
		FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 DONE}
		World-Stripper-1.7.2-1.15.1.jar World Stripper {worldstripper@1.7.2 DONE}
		Transport-1.15.2-2.1.2.jar Transport {transport@1.15.2-2.1.2 DONE}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		moredragoneggs-1.0.jar More Dragon Eggs {moredragoneggs@1.0 DONE}
		Aquaculture-1.15.2-2.0.11.jar Aquaculture 2 {aquaculture@1.15.2-2.0.11 DONE}
		betterbedrockgenerator-1.15.2-0.0.6.jar Better Bedrock Generator {betterbedrockgenerator@0.0.6 DONE}
		Industrial Agriculture[Mekanism]-1.15.2-1.6.1.jar Industrial Agriculture Plugin-Mekanism {iapmekanism@1.15.2-1.6.1 DONE}
		refinedstorageaddons-0.6.1.jar Refined Storage Addons {refinedstorageaddons@0.6.1 DONE}
		SolarGeneration-1.15.2-1.2.0.jar Solar Generation {solargeneration@1.2.0 DONE}
	Kiwi Modules: 
		kiwi:contributors
	Launched Version: forge-31.1.25
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 3GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 442.59, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz

**Comment by Raycoms** [comment]
Fixed in newer version
