### ISSUE TITLE
Custom Schematics Issue

### ISSUE THREAD

**Issue by Jakmoko** [ldtteam/minecolonies#4488]
Minecolonies version
minecolonies-0.10.771-RELEASE-universal

Version: 
Minecraft Forge 31.1.22

Expected behavior
1. Select Custom Schematic
2. Place Citizen's Hut Block
3. Build options
4. Build building

Actual behaviour
After placing the citizen's hut block, I open it's GUI and select build options, It crashes everytime
Creates a crash report. Cannot build ANY custom schematic created.
Followed the steps in the wiki on how to create a custom schematic.
citizen5 blueprint located in /structurize/Schematics/please (schematic name)

Steps to reproduce the problem
1. Create custom schematic in a superflat world
2. Use it in a survival world
3. So that this happens
4. ... Profit

Crash Report
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 3/23/20 9:49 PM
Description: Ticking screen

java.lang.NullPointerException: Ticking screen
	at com.ldtteam.structures.helpers.Structure.rotate(Structure.java:322) ~[?:0.10.282-RELEASE] {re:classloading}
	at com.minecolonies.coremod.client.gui.WindowBuildBuilding.updateResources(WindowBuildBuilding.java:257) ~[?:0.10.771-RELEASE] {re:classloading}
	at com.minecolonies.coremod.client.gui.WindowBuildBuilding.onStyleDropDownChanged(WindowBuildBuilding.java:406) ~[?:0.10.771-RELEASE] {re:classloading}
	at com.minecolonies.coremod.client.gui.WindowBuildBuilding$$Lambda$6123/1011464970.accept(Unknown Source) ~[?:?] {}
	at com.ldtteam.blockout.views.DropDownList.setSelectedIndex(DropDownList.java:215) ~[?:0.10.282-RELEASE] {re:classloading}
	at com.minecolonies.coremod.client.gui.WindowBuildBuilding.updateStyles(WindowBuildBuilding.java:216) ~[?:0.10.771-RELEASE] {re:classloading}
	at com.minecolonies.coremod.client.gui.WindowBuildBuilding.onOpened(WindowBuildBuilding.java:432) ~[?:0.10.771-RELEASE] {re:classloading}
	at com.ldtteam.blockout.BOScreen.tick(BOScreen.java:228) ~[?:0.10.282-RELEASE] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$runTick$19(Minecraft.java:1366) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$3025/497289960.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:446) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1365) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:905) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:554) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.22.jar:31.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$400/245530164.call(Unknown Source) [forge-1.15.2-31.1.22.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.ldtteam.structures.helpers.Structure.rotate(Structure.java:322)
	at com.minecolonies.coremod.client.gui.WindowBuildBuilding.updateResources(WindowBuildBuilding.java:257)
	at com.minecolonies.coremod.client.gui.WindowBuildBuilding.onStyleDropDownChanged(WindowBuildBuilding.java:406)
	at com.minecolonies.coremod.client.gui.WindowBuildBuilding$$Lambda$6123/1011464970.accept(Unknown Source)
	at com.ldtteam.blockout.views.DropDownList.setSelectedIndex(DropDownList.java:215)
	at com.minecolonies.coremod.client.gui.WindowBuildBuilding.updateStyles(WindowBuildBuilding.java:216)
	at com.minecolonies.coremod.client.gui.WindowBuildBuilding.onOpened(WindowBuildBuilding.java:432)
	at com.ldtteam.blockout.BOScreen.tick(BOScreen.java:228)
	at net.minecraft.client.Minecraft.lambda$runTick$19(Minecraft.java:1366)
	at net.minecraft.client.Minecraft$$Lambda$3025/497289960.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: com.ldtteam.blockout.BOScreen
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:446)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['BlazingSage'/273, l='MpServer', x=130.88, y=64.00, z=218.52]]
	Chunk stats: Client Chunk Cache: 225, 121
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: -2603645548436628783
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (128,64,240), Chunk: (at 0,4,0 in 8,15; contains blocks 128,0,240 to 143,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 278602 game time, 505291 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:442)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1764)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:568)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$400/245530164.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 845672400 bytes (806 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.22.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.22.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.4-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.22.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.22.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.22.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.22
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		forge-1.15.2-31.1.22-client.jar Minecraft {minecraft@1.15.2 DONE}
		structurize-0.10.282-RELEASE.jar Structurize {structurize@0.10.282-RELEASE DONE}
		forge-1.15.2-31.1.22-universal.jar Forge {forge@31.1.22 DONE}
		minecolonies-0.10.771-RELEASE-universal.jar Minecolonies {minecolonies@0.10.771-RELEASE DONE}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		journeymap-1.15.2-5.7.0beta1.jar Journeymap {journeymap@1.15.2-5.7.0beta1 DONE}
		StorageDrawers-1.15.2-7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 DONE}
		OreExcavation-1.7.151.jar Ore Excavation {oreexcavation@NONE DONE}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 DONE}
	Launched Version: 1.15.2-forge-31.1.22
	Backend library: LWJGL version 3.2.2 build 10

**Comment by Raycoms** [comment]
This is a classic problem if the building can't load citizen1-citizen5.

Put all 5 citizen hut scan files into that folder. citizen1, citizen2, citizen3, etc.

And this won't happen.
