### ISSUE TITLE
1.15.2 Crash on launch on server

### ISSUE THREAD

**Issue by Aymou84** [ldtteam/minecolonies#4521]
### Minecolonies version

Version: minecolonies-0.11.777-ALPHA-universal & minecolonies-0.11.790-ALPHA-universal.jar

### Expected behavior
 Launching my server

-  i would like to play modded minecraft with my friends

### Actual behaviour

-  I recently installed minecolonies on my minecraft server on a VPS that works on linux. Whenever i use it, it crashes the server before it launches. I have no issue with other mods.

crash report :

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

### Steps to reproduce the problem

1.  Install last version of java
2.  install forge-1.15.2-31.1.27
3. put the last version of minecolonies and structurize in an empty mod folder
3.  server crashes
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log:
- crashlog:---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 3/27/20, 2:49 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at com.ldtteam.structurize.util.StructureUtils.calculateMD5(StructureUtils.java:48) ~[?:0.10.288-ALPHA] {re:classloading}
	at com.ldtteam.structurize.util.StructureUtils.calculateMD5(StructureUtils.java:108) ~[?:0.10.288-ALPHA] {re:classloading}
	at com.ldtteam.structurize.management.Structures.loadSchematicsForPrefix(Structures.java:333) ~[?:0.10.288-ALPHA] {re:classloading,pl:runtimedistcleaner:A}
	at com.ldtteam.structurize.management.Structures.loadStyleMapsJar(Structures.java:238) ~[?:0.10.288-ALPHA] {re:classloading,pl:runtimedistcleaner:A}
	at com.ldtteam.structurize.management.Structures.loadStyleMaps(Structures.java:145) ~[?:0.10.288-ALPHA] {re:classloading,pl:runtimedistcleaner:A}
	at com.ldtteam.structurize.management.Structures.init(Structures.java:122) ~[?:0.10.288-ALPHA] {re:classloading,pl:runtimedistcleaner:A}
	at com.ldtteam.structurize.event.EventSubscriber.onServerStarting(EventSubscriber.java:58) ~[?:0.10.288-ALPHA] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_7_EventSubscriber_onServerStarting_Load.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraft.server.MinecraftServer.func_213194_a(MinecraftServer.java:414) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:364) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:211) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:834) [?:?] {}
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
	at java.lang.ClassLoader.findClass(ClassLoader.java:718) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:92) ~[modlauncher-5.0.0-milestone.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?] {}
	... 15 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Linux (amd64) version 4.15.0-72-generic
	Java Version: 11.0.6, Ubuntu
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Ubuntu
	Memory: 410061312 bytes (391 MB) / 779091968 bytes (743 MB) up to 2042626048 bytes (1948 MB)
	CPUs: 2
	JVM Flags: 0 total; 
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.27.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.27.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.15.2-31.1.27.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-2.0.4-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.27.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.27.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.27
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		forge-1.15.2-31.1.27-server.jar Minecraft {minecraft@1.15.2 DONE}
		structurize-0.10.288-ALPHA.jar Structurize {structurize@0.10.288-ALPHA DONE}
		forge-1.15.2-31.1.27-universal.jar Forge {forge@31.1.27 DONE}
		minecolonies-0.11.790-ALPHA-universal.jar Minecolonies {minecolonies@0.11.790-ALPHA DONE}
	Player Count: 0 / 20; []
	Data Packs: vanilla, mod:forge (incompatible), mod:minecolonies (incompatible), mod:structurize (incompatible)
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Nightenom** [comment]
forge does not support java 11
please use java 8

**Comment by nmarshall23** [comment]
FYI fixing this is easy, just add these [dependencies](https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j)

```
<dependencies>
    <dependency>
        <groupId>javax.xml.bind</groupId>
        <artifactId>jaxb-api</artifactId>
        <version>2.3.0</version>
    </dependency>
    <dependency>
        <groupId>com.sun.xml.bind</groupId>
        <artifactId>jaxb-impl</artifactId>
        <version>2.3.0</version>
    </dependency>
    <dependency>
        <groupId>org.glassfish.jaxb</groupId>
        <artifactId>jaxb-runtime</artifactId>
        <version>2.3.0</version>
    </dependency>
    <dependency>
        <groupId>javax.activation</groupId>
        <artifactId>activation</artifactId>
        <version>1.1.1</version>
    </dependency>
</dependencies>
```

**Comment by marchermans** [comment]
@nmarshall23 Nope that is not how we fix this.
Forge and Mojang force anyone who wants to run MC to use Java 8. This is the official stance from Mojang, and the only version they offer support for to the Forge Team, as such it is the official version the Forge Team offers us support for, and that means it is the only Java version we offer support for and in turn code for.

Since Java 11 Is not supported by any party that is involved in MC modding, being Mojang, Forge or us we are not going to add support for it on our lonesome and i am sorry to say that he will need to use Java 8

**Comment by Raycoms** [comment]
If you want you can add this to minecolonies/structurize and compile a jar for yourself for your own use for your own discretion.

**Comment by nmarshall23** [comment]
I was not aware that Mojang only supports Java 8. 
That's unfortunate I was hoping to see if the improvements to GC in java 14 would let me allocate less RAM to Java.
