### ISSUE TITLE
Game crashes when hospital is built

### ISSUE THREAD

**Issue by Deedubsy** [ldtteam/minecolonies#4523]
Version: 0.10.771-RELEASE-universal

Game crashes when trying to heal an injured citizen.

### Steps to reproduce the problem
Build a Hospital while having an injured citizen.

- crashlog:
---- Minecraft Crash Report ----
// Oops.

Time: 3/28/20 3:03 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.minecolonies.coremod.entity.ai.minimal.EntityAISickTask.cure(EntityAISickTask.java:305) ~[?:0.10.771-RELEASE] {re:classloading}
	at com.minecolonies.coremod.entity.ai.minimal.EntityAISickTask.waitForCure(EntityAISickTask.java:360) ~[?:0.10.771-RELEASE] {re:classloading}
	at com.minecolonies.coremod.entity.ai.minimal.EntityAISickTask.func_75246_d(EntityAISickTask.java:182) ~[?:0.10.771-RELEASE] {re:classloading}
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?] {re:classloading}
	at com.minecolonies.api.entity.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:222) ~[?:0.10.771-RELEASE] {re:classloading}
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:595) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2261) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:462) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:159) ~[?:?] {re:classloading}
	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:1114) ~[?:0.10.771-RELEASE] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2103) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:600) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld$$Lambda$5019/1642911523.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:536) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:401) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:847) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:782) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:635) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.minecolonies.coremod.entity.ai.minimal.EntityAISickTask.cure(EntityAISickTask.java:305)
	at com.minecolonies.coremod.entity.ai.minimal.EntityAISickTask.waitForCure(EntityAISickTask.java:360)
	at com.minecolonies.coremod.entity.ai.minimal.EntityAISickTask.func_75246_d(EntityAISickTask.java:182)
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55)
	at com.minecolonies.api.entity.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:222)
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:595)
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2261)
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:462)
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:159)
	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:1114)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2103)
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274)
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:600)
	at net.minecraft.world.server.ServerWorld$$Lambda$5019/1642911523.accept(Unknown Source)

-- Entity being ticked --
Details:
	Entity Type: minecolonies:citizen (com.minecolonies.coremod.entity.citizen.EntityCitizen)
	Entity ID: 347
	Entity Name: Mason N. Garret
	Entity's Exact location: 638.50, 84.56, 537.50
	Entity's Block location: World: (638,84,537), Chunk: (at 14,5,9 in 39,33; contains blocks 624,0,528 to 639,255,543), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
	Entity's Momentum: 0.00, -0.05, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:536)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:401)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['deedubsy'/190, l='Seed!', x=559.08, y=80.25, z=511.71]]
	Chunk stats: ServerChunkCache: 4870
	Level dimension: DimensionType{minecraft:overworld}
	Level name: Seed!
	Level seed: -2084759484
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (212,64,252), Chunk: (at 4,4,12 in 13,15; contains blocks 208,0,240 to 223,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 7068075 game time, 9351327 day time
	Known server brands: vanilla, forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 160605 (now: false), thunder time: 31014 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:847)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:782)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:635)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4070763416 bytes (3882 MB) / 8522825728 bytes (8128 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.0-milestone.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.0.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.0.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.0
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		forge-1.15.2-31.1.0-client.jar Minecraft {minecraft@1.15.2 DONE}
		DungeonCrawl-1.15.2-1.6.3.jar Dungeon Crawl {dungeoncrawl@1.6.3 DONE}
		AmbientSounds_v3.0.19_mc1.15.2.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		structurize-0.10.282-RELEASE.jar Structurize {structurize@0.10.282-RELEASE DONE}
		minecolonies-0.10.771-RELEASE-universal.jar Minecolonies {minecolonies@0.10.771-RELEASE DONE}
		Blur-1.1.0-1.jar Blur {blur@1.1.0-1 DONE}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 DONE}
		forge-1.15.2-31.1.0-universal.jar Forge {forge@31.1.0 DONE}
		FastLeafDecay-v20.jar FastLeafDecay {fastleafdecay@v20 DONE}
		gravestone-1.17.3.jar Gravestone Mod {gravestone@1.17.3 DONE}
		journeymap-1.15.2-5.7.0beta1.jar Journeymap {journeymap@1.15.2-5.7.0beta1 DONE}
		FastWorkbench-1.15.1-3.0.0.jar FastWorkbench {fastbench@3.0.0 DONE}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['deedubsy'/190, l='Seed!', x=559.08, y=80.25, z=511.71]]
	Data Packs: vanilla, mod:ambientsounds (incompatible), mod:blur (incompatible), mod:dungeoncrawl (incompatible), mod:forge (incompatible), mod:journeymap (incompatible), mod:minecolonies (incompatible), mod:structurize (incompatible), mod:jei (incompatible), mod:cfm (incompatible), mod:fastbench (incompatible), mod:fastleafdecay, mod:gravestone, mod:placebo (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by someaddons** [comment]
already fixed in the newest
