### ISSUE TITLE
no renderer for minecolonies:citizen

### ISSUE THREAD

**Issue by MoPhliFra** [ldtteam/minecolonies#4583]
Never reported an issue on Github before but when I start the game with OptiFine on version 1.15.2
this message appears after crash on loading the game:

The game crashed whilst initializing game
--- Minecraft Crash Report ----
// Shall we play a game?

Time: 06.04.20 16:53
Description: Initializing game

java.lang.IllegalStateException: No renderer registered for minecolonies:citizen
	at net.minecraft.client.renderer.entity.EntityRendererManager.<init>(EntityRendererManager.java:222) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:425) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:166) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.37.jar:31.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$417/643587433.call(Unknown Source) [forge-1.15.2-31.1.37.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.<init>(EntityRendererManager.java:222)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:425)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$417/643587433.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 15531383960 bytes (14811 MB) / 17548967936 bytes (16736 MB) up to 18253611008 bytes (17408 MB)
	CPUs: 16
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx17G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.37.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.37.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.4-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.37.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.37.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.15.2_HD_U_G1_pre13.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.1.37.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.37
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		forge-1.15.2-31.1.37-client.jar Minecraft {minecraft@1.15.2 COMMON_SETUP}
		SereneSeasons-1.15.2-3.0.0.68-universal.jar Serene Seasons {sereneseasons@1.15.2-3.0.0.68 COMMON_SETUP}
		Useful-Backpacks-Mod-1.15.2.jar Useful Backpacks {usefulbackpacks@1.9.0.52 COMMON_SETUP}
		DungeonCrawl-1.15.2-1.6.3.jar Dungeon Crawl {dungeoncrawl@1.6.3 COMMON_SETUP}
		AmbientSounds_v3.0.19_mc1.15.2.jar Ambient Sounds {ambientsounds@3.0.3 COMMON_SETUP}
		structurize-0.10.282-RELEASE.jar Structurize {structurize@0.10.282-RELEASE COMMON_SETUP}
		u_team_core-1.15.2-2.11.0.156.jar U Team Core {uteamcore@2.11.0.156 COMMON_SETUP}
		minecolonies-0.11.813-ALPHA-universal.jar Minecolonies {minecolonies@0.11.813-ALPHA COMMON_SETUP}
		MrCrayfishs-Furniture-Mod-1.15.2.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 COMMON_SETUP}
		Mine+and+Slash-1.15.2-3.5.1.jar Mine and Slash {mmorpg@3.5.1 COMMON_SETUP}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 COMMON_SETUP}
		Mekanism-1.15.2-9.9.18.410.jar Mekanism {mekanism@9.9.18 COMMON_SETUP}
		BetterPvP_20.7.0_Forge_1.15.2.jar Better PVP Mod {xaerobetterpvp@20.7.0 COMMON_SETUP}
		forge-1.15.2-31.1.37-universal.jar Forge {forge@31.1.37 COMMON_SETUP}
		dimdungeons-1.051-forge-1.15.2.jar Dimensional Dungeons {dimdungeons@1.15.2-1.05 COMMON_SETUP}
		FastLeafDecay-v20.jar FastLeafDecay {fastleafdecay@v20 COMMON_SETUP}
		curios-FORGE-1.15.2-2.0.2.1.jar Curios API {curios@FORGE-1.15.2-2.0.2.1 COMMON_SETUP}
		TerraForged-1.15.2-0.0.12.jar TerraForged {terraforged@0.0.12 COMMON_SETUP}
		gravestone-1.17.3.jar Gravestone Mod {gravestone@1.17.3 COMMON_SETUP}
		XaerosWorldMap_1.5.6_Forge_1.15.2.jar Xaero's World Map {xaeroworldmap@1.5.6 COMMON_SETUP}
	Launched Version: 1.15.2-forge-31.1.37
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.75, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 16x AMD Ryzen 7 1700X Eight-Core Processor 
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre13
	OptiFine Build: 20200401-232147
	Render Distance Chunks: 22
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 445.75
	OpenGlRenderer: GeForce GTX 1070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16

**Comment by someaddons** [comment]
-> Optifines issue

**Comment by Raycoms** [comment]
If this doesn't work, then no custom mob entity works with forge. So thats a optifine issue. Please report it to them.
