### ISSUE TITLE
[1.15.2] Research is not progressing

### ISSUE THREAD

**Issue by AlienXAXS** [ldtteam/minecolonies#4636]
### Minecolonies version
Version:  minecolonies-0.11.827-ALPHA-universal

### Expected behavior
Upon starting a research, I expect to see research progress after at least 30 minutes.

### Actual behaviour
The required items are consumed, after checking the University block after 30-60 minutes, the research has not progressed at all.

This image is research that has been going for at least 24 hours.
![image](https://user-images.githubusercontent.com/1773445/79284729-6d868680-7eb3-11ea-8a32-7e0bba72fab5.png)

### Steps to reproduce the problem
I do not have steps to reproduce the issue, however I do wonder if it's possible that as our world started before research was finalised in code, that the mod has got itself into a state that it did not rather like.

For example: We already had a hospital before we needed to research it.

### Logs: Latest.log and crashlog at https://gist.github.com/
This log is from the server: https://gist.githubusercontent.com/AlienXAXS/dae8f20f0e34f3110f33fd92e92da720/raw/c9b640f1d563b38be3cdaadb0001618fa3248279/latest.log

If there is any data that would help you debug this issue, please let me know.
Will happily host the world somewhere for you to download for example :)

**Comment by Raycoms** [comment]
Do you have a worker working there?

**Comment by AlienXAXS** [comment]
Sorry i should have specified that, Yes i do.

The worker is running around, as i would expect going to bookshelves and the such.

**Comment by AlienXAXS** [comment]
I would like to point out, that it's possible that the university block is not always in a loaded chunk as it's built quite far from the main town due to building decisions by the players.  I do not know if this matters much - but i thought i would say.

However, please note that we were building around the university for an hour yesterday, I say the above more in terms of the chunk will often be loaded and unloaded instead of being loaded along side the town hall block etc.

**Comment by Asherslab** [comment]
If the university or worker is unloaded they won't do anything

**Comment by Raycoms** [comment]
Can you send me your world?

**Comment by Raycoms** [comment]
```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_242]
    at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_242]
    at com.minecolonies.coremod.colony.buildings.AbstractBuildingGuards.getNextPatrolTarget(AbstractBuildingGuards.java:489) ~[?:0.11.827-ALPHA]
    at com.minecolonies.coremod.colony.buildings.AbstractBuildingGuards.startPatrolNext(AbstractBuildingGuards.java:460) ~[?:0.11.827-ALPHA]
    at com.minecolonies.coremod.colony.buildings.AbstractBuildingGuards.onColonyTick(AbstractBuildingGuards.java:433) ~[?:0.11.827-ALPHA]
    at com.minecolonies.coremod.colony.managers.BuildingManager.onColonyTick(BuildingManager.java:173) ~[?:0.11.827-ALPHA]
    at com.minecolonies.coremod.colony.Colony.worldTickSlow(Colony.java:397) ~[?:0.11.827-ALPHA]
    at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.checkCondition(BasicTransition.java:85) ~[?:0.11.827-ALPHA]
    at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:120) ~[?:0.11.827-ALPHA]
    at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:124) ~[?:0.11.827-
```

The colony tick is crashing, that's why, we'll investigate it.

**Comment by Raycoms** [comment]
Fixed

**Comment by Ashan040** [comment]
Hi I think I have same problem. How to fix it ?

**Comment by Thodor12** [comment]
Please don't necrobump old issues. 1.15.2 is not supported anymore.
