### ISSUE TITLE
null pointer exception if far away from colony (ies) every 5 sec makes minecraft laggy

### ISSUE THREAD

**Issue by ArnoSaxena** [ldtteam/minecolonies#464]
### Minecolonies version

minecolonies-universal-1.11-0.6.2265

### Expected behaviour

- not throw an exception?

### Actual behaviour

- when far away from colony, the below shown exception is thrown every 5 seconds. Obviously the currentStructure object can be null at that point. 

### Steps to reproduce the problem

1. get far away from colony
2. see minecraft gets laggy and exception logged every 5 seconds

### addition ###
could it be, this happenes only, if new area is created by minecraft? I have the impression if I turn around and head back the way I came, the exceptions will decrease...

### Thrown exception ###
[18:08:35] [Server thread/WARN] [minecolonies]: Action for target com.minecolonies.coremod.entity.ai.util.AITarget@76691df7 threw an exception:
java.lang.NullPointerException
	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructure.lambda$generateStructureGenerator$69(AbstractEntityAIStructure.java:344) ~[AbstractEntityAIStructure.class:?]
	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructure.lambda$generateStructureGenerator$71(AbstractEntityAIStructure.java:349) ~[AbstractEntityAIStructure.class:?]
	at com.minecolonies.coremod.entity.ai.util.AITarget.apply(AITarget.java:125) ~[AITarget.class:?]
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.applyTarget(AbstractAISkeleton.java:203) ~[AbstractAISkeleton.class:?]
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.checkOnTarget(AbstractAISkeleton.java:176) ~[AbstractAISkeleton.class:?]
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) [?:1.8.0_74]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351) [?:1.8.0_74]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) [?:1.8.0_74]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) [?:1.8.0_74]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) [?:1.8.0_74]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) [?:1.8.0_74]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) [?:1.8.0_74]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) [?:1.8.0_74]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:1.8.0_74]
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449) [?:1.8.0_74]
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:129) [AbstractAISkeleton.class:?]
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129) [uj.class:?]
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:769) [sx.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2255) [sw.class:?]
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:573) [sx.class:?]
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:171) [sk.class:?]
	at com.minecolonies.coremod.entity.EntityCitizen.func_70636_d(EntityCitizen.java:808) [EntityCitizen.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2085) [sw.class:?]
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:296) [sx.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1961) [ajs.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840) [lw.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1931) [ajs.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1747) [ajs.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621) [lw.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [cch.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]

**Comment by Raycoms** [comment]
It's quite strange that this happens.
This error is thrown when the builder can't access the nbt file anymore.
Can you still reproduce this with the most recent version?
