### ISSUE TITLE
Minecolonies Builder, error log

### ISSUE THREAD

**Issue by Imothep80** [ldtteam/minecolonies#4642]
### Minecolonies version

Version: 0.11.810-BETA

### Expected behavior

- Hm. No Crash?

### Actual behaviour

- It Looks a bit random. This is the second time this happend. In booth cases the potted item results in a massive lag and forge shutdown the Server "A single server tick took 60.00 seconds (should be max 0.05)" "Considering it to be crashed, server will forcibly shutdown."

### Steps to reproduce the problem

1. Currently i can't reproduce it. But try to build a Citizen House in lvl 5
2. 
3. 
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/

- latest.log: https://gist.github.com/Imothep80/1112278bb97a9c86b98f6d6ece9bf27e
- crashlog:

**Comment by Raycoms** [comment]
Can we get the crash log?

**Comment by Imothep80** [comment]
Sure: https://gist.github.com/Imothep80/e31adf928a598c56e3fea7831c979368

**Comment by Raycoms** [comment]
```
java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)
	at java.util.AbstractList$Itr.hasNext(AbstractList.java:351) ~[?:1.8.0_242] {}
	at com.raoulvdberge.refinedstorage.apiimpl.autocrafting.task.v5.CraftingTask.getCraftingMonitorElements(CraftingTask.java:1093) ~[?:1.8.1] {re:classloading}
	at com.raoulvdberge.refinedstorage.network.craftingmonitor.CraftingMonitorUpdateMessage.encode(CraftingMonitorUpdateMessage.java:89) ~[?:1.8.1] {re:classloading}
	at com.raoulvdberge.refinedstorage.network.NetworkHandler$$Lambda$5267/33330934.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryEncode$4(IndexedMessageCodec.java:134) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec$$Lambda$6997/1294833509.accept(Unknown Source) ~[?:?] {}

```

While th elog before the crash was minecolonies related and is an issue, the crash was actually refined storage.

**Comment by Imothep80** [comment]
Nice to know. I send this Information to the Developer of Refined Storage. Thanks.

**Comment by someaddons** [comment]
ye refined storage crafting is known to be very laggy

**Comment by Raycoms** [comment]
should be fixed
