### ISSUE TITLE
1.14.4 crash in multiplayer

### ISSUE THREAD

**Issue by mcenderdragon** [ldtteam/minecolonies#4737]
MC: 1.14.4
minecolonies-0.10.715-RELEASE-universal.ja

```
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 4/24/20 8:28 PM
Description: Rendering entity in world

java.lang.NoClassDefFoundError: com/minecolonies/coremod/entity/citizen/citizenhandlers/CitizenSleepHandler$1
	at com.minecolonies.coremod.entity.citizen.citizenhandlers.CitizenSleepHandler.getBedOrientationInDegrees(CitizenSleepHandler.java:79) ~[?:0.10.715-RELEASE] {re:classloading}
	at com.minecolonies.coremod.client.render.RenderBipedCitizen.func_77043_a(RenderBipedCitizen.java:250) ~[?:0.10.715-RELEASE] {re:classloading}
	at net.minecraft.client.renderer.entity.LivingRenderer.func_76986_a(LivingRenderer.java:98) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:midnight:LivingRendererTransformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.MobRenderer.func_76986_a(SourceFile:40) ~[?:?] {re:classloading}
	at com.minecolonies.coremod.client.render.RenderBipedCitizen.func_76986_a(RenderBipedCitizen.java:104) ~[?:0.10.715-RELEASE] {re:classloading}
	at net.minecraft.client.renderer.entity.MobRenderer.func_76986_a(SourceFile:15) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_188391_a(EntityRendererManager.java:370) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_188388_a(EntityRendererManager.java:359) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_215326_a(WorldRenderer.java:543) ~[?:?] {re:classloading,xf:fml:journeymap:WorldRenderer.markForRerender,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_181560_a(GameRenderer.java:713) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_78471_a(GameRenderer.java:640) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:494) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:890) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:384) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.2.1.jar:28.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$399/310212872.call(Unknown Source) [forge-1.14.4-28.2.1.jar:28.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-4.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-4.1.0.jar:?] {}
Caused by: java.lang.ClassNotFoundException: com.minecolonies.coremod.entity.citizen.citizenhandlers.CitizenSleepHandler$1
	at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_51] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:103) ~[modlauncher-4.1.0.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
	... 26 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.minecolonies.coremod.entity.citizen.citizenhandlers.CitizenSleepHandler.getBedOrientationInDegrees(CitizenSleepHandler.java:79)
	at com.minecolonies.coremod.client.render.RenderBipedCitizen.func_77043_a(RenderBipedCitizen.java:250)
	at net.minecraft.client.renderer.entity.LivingRenderer.func_76986_a(LivingRenderer.java:98)
	at net.minecraft.client.renderer.entity.MobRenderer.func_76986_a(SourceFile:40)
	at com.minecolonies.coremod.client.render.RenderBipedCitizen.func_76986_a(RenderBipedCitizen.java:104)
	at net.minecraft.client.renderer.entity.MobRenderer.func_76986_a(SourceFile:15)

-- Entity being rendered --
Details:
	Entity Type: minecolonies:citizen (com.minecolonies.coremod.entity.citizen.EntityCitizen)
	Entity ID: 39701
	Entity Name: Chase P. Bauer
	Entity's Exact location: 151.50, 79.00, 235.50
	Entity's Block location: World: (151,79,235), Chunk: (at 7,4,11 in 9,14; contains blocks 144,0,224 to 159,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: com.minecolonies.coremod.client.render.RenderBipedCitizen@2151f47
	Location: -41.87,-9.62,-85.73 - World: (-42,-10,-86), Chunk: (at 6,-1,10 in -3,-6; contains blocks -48,0,-96 to -33,255,-81), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Rotation: -25.3125
	Delta: 0.3399837
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_188391_a(EntityRendererManager.java:370)
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_188388_a(EntityRendererManager.java:359)
	at net.minecraft.client.renderer.WorldRenderer.func_215326_a(WorldRenderer.java:543)
	at net.minecraft.client.renderer.GameRenderer.func_181560_a(GameRenderer.java:713)
	at net.minecraft.client.renderer.GameRenderer.func_78471_a(GameRenderer.java:640)

-- Affected level --
Details:
	All players: 3 total; [ClientPlayerEntity['MCenderdragon'/168342, l='MpServer', x=193.40, y=87.00, z=321.01], RemoteClientPlayerEntity['Mantes'/129956, l='MpServer', x=101.76, y=71.00, z=218.81], RemoteClientPlayerEntity['wugand'/148756, l='MpServer', x=106.32, y=70.00, z=195.10]]
	Chunk stats: Client Chunk Cache: 729, 500
	Level dimension: DimensionType{futurepack:menelaus}
	Derived: true
	Level name: MpServer
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:410)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1750)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$399/310212872.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 639734576 bytes (610 MB) / 2078801920 bytes (1982 MB) up to 3008888832 bytes (2869 MB)
	CPUs: 4
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3228m -Xms256m -XX:PermSize=256m
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.2.1.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.1.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.1-milestone.0.1+94458e7-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.2.1.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.1.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.2.1.jar fml TRANSFORMATIONSERVICE 
	FML: 28.2
	Forge: net.minecraftforge:28.2.1
	FML Language Providers: 
		javafml@28.2
		minecraft@1
	Mod List: 
		forge-1.14.4-28.2.1-client.jar Minecraft {minecraft@1.14.4 DONE}
		blockdrops-1.14.4-1.0.2.jar Block Drops {blockdrops@1.0.2 DONE}
		illuminations-0.1.0-1.14.4.jar Illuminations for Forge {illuminations@1.0.0.0 DONE}
		mcpaint-1.4.5.jar Mc Paint {mcpaint@1.4.5 DONE}
		justenoughbeacons-1.2.jar Just Enough Beacons {justenoughbeacons@1.2 DONE}
		compactores-1.14.4-1.2.2.jar Compact Ores {compactores@1.2.2 DONE}
		SilentLib-1.14.4-4.4.0+44.jar Silent Lib {silentlib@4.4.0+44 DONE}
		Futurepack-1.14.4-28.0.108.jar Futurepack {futurepack@28.0.108 DONE}
		DeathFinder-v1.2-1.14.4.jar Death Finder {deathfinder@1.2 DONE}
		jei-1.14.4-6.0.0.27.jar Just Enough Items {jei@6.0.0.27 DONE}
		extragolems-9.0.5.jar Extra Golems {golems@9.0.5 DONE}
		Neat 1.5-19.jar Neat {neat@1.5-19 DONE}
		create-mc1.14.4_v0.2.2a.jar Create {create@mc1.14-0.2.2a DONE}
		Waystones_1.14.4-5.1.1.jar Waystones {waystones@5.1.1 DONE}
		FTBUtilitiesBackups-2.0.0.11.jar FTB Utilities: Backups {ftbbackups@2.0.0.11 DONE}
		journeymap-1.14.4-5.7.0b1.jar Journeymap {journeymap@1.14.4-5.7.0b1 DONE}
		Controlling-5.0.6.jar Controlling {controlling@5.0.6 DONE}
		globaldatapack-1.14.4-1.2.1.jar Dark Roleplay - Global Datapacks {globaldatapack@1.14.4-1.2 DONE}
		StorageDrawers-1.14.4-6.0.7.jar Storage Drawers {storagedrawers@1.14.4-6.0.6 DONE}
		OreExcavation-1.6.147.jar Ore Excavation {oreexcavation@NONE DONE}
		SimpleStorageNetwork-1.14.4-0.2.0.jar Simple Storage Network {storagenetwork@1.14.4-0.2.0 DONE}
		AssistedProgression-1.14.4-2.1.jar Assisted Progression {assistedprogression@1.14.4-2.0-B33 DONE}
		themidnight-0.4.6.jar The Midnight {midnight@0.4.6 DONE}
		mightyarchitect-mc1.14.4_v0.5.jar The Mighty Architect {mightyarchitect@0.5 DONE}
		BasicNetherOres-1.14.4-3.2.2.jar Basic Nether Ores {bno@3.2.2 DONE}
		obfuscate-0.4.1-1.14.4.jar Obfuscate {obfuscate@0.4.1 DONE}
		petyourwolf-1.2.1-1.14.4.jar Pet Your Wolf {petyourwolf@1.2.1 DONE}
		structurize-0.10.245-ALPHA.jar Structurize {structurize@0.10.245-ALPHA DONE}
		Nucleus-1.14.4-5.0.jar Nucleus {nucleus@1.14.4-5.0-B87 DONE}
		minecolonies-0.10.715-RELEASE-universal.jar Minecolonies {minecolonies@0.10.715-RELEASE DONE}
		Morpheus-1.14.4-4.2.44.jar Morpheus {morpheus@version DONE}
		cc-tweaked-1.14.4-1.86.2.jar CC: Tweaked {computercraft@1.86.2 DONE}
		Hwyla-forge-1.10.6-B67_1.14.4.jar Waila {waila@version DONE}
		JustEnoughResources-1.14.4-0.10.1.76.jar Just Enough Resources {jeresources@0.10.1.76 DONE}
		CraftTweaker-1.14.4-5.0.1.165.jar CraftTweaker {crafttweaker@5.0.1.165 DONE}
		forge-1.14.4-28.2.1-universal.jar Forge {forge@28.2.1 DONE}
		petcollars-1.21.jar Pet Collars {petcollars@1.21 DONE}
		ScalingHealth-1.14.4-2.5.2+50.jar Scaling Health {scalinghealth@2.5.2+49 DONE}
		FastLeafDecay-v17.jar FastLeafDecay {fastleafdecay@v17 DONE}
		defaultdimension-0.1.jar Default Dimension {defaultdimension@0.1 DONE}
		infernalmobs-1.14.4.6.jar Infernal Mobs {infernalmobs@1.14.4.6 DONE}
		corpse-1.14.4-1.0.4.jar Corpse {corpse@1.14.4-1.0.4 DONE}
		BetterAdvancements-1.14.4-0.1.0.90.jar Better Advancements {betteradvancements@0.1.0.90 DONE}
	Launched Version: forge-28.2.1
	LWJGL: 3.2.2 build 10
	OpenGL: Intel(R) HD Graphics 630 GL version 4.5.0 - Build 22.20.16.4749, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
```

**Comment by someaddons** [comment]
happens sometimes when the mod isnt correctly loaded, redownload it/relaunch client

**Comment by mcenderdragon** [comment]
Any ideas why it only happens sometimes? I have a similar issue with other mods where randomly anonymous classes or lamdas are missing.

**Comment by someaddons** [comment]
maybe an launcher issue with downloading/updating, or a forge issue with loading mods correctly

**Comment by Raycoms** [comment]
Maybe report this to forge as an issue with logs of different mods.
