### ISSUE TITLE
1.15.2

### ISSUE THREAD

**Issue by FoamyLemming** [ldtteam/minecolonies#4842]
### Minecolonies version 1

Version: 0.11.852 Alpha

### Expected behavior

the supply camp would be built

### Actual behaviour

when the tick is clicked Minecraft freezes says saving word and crashes

### Steps to reproduce the problem

1. get the puppy camp
2. press the tick/ confirm button after choosing where to place it
3. it freezes
4. says saving word and glitches 

### Logs: ---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 2/05/20 6:06 PM
Description: mouseClicked event handler

java.lang.NoSuchMethodError: com.ldtteam.structures.lib.BlueprintUtils.getPrimaryBlockOffset(Lcom/ldtteam/structures/blueprints/v1/Blueprint;)Lnet/minecraft/util/Tuple;
	at com.minecolonies.coremod.client.gui.WindowMinecoloniesBuildTool.paste(WindowMinecoloniesBuildTool.java:88) ~[?:0.11.852-ALPHA] {re:classloading}
	at com.ldtteam.structurize.client.gui.WindowBuildTool.paste(WindowBuildTool.java:306) ~[?:0.10.306-ALPHA] {re:classloading}
	at com.ldtteam.structurize.client.gui.WindowBuildTool.pasteNice(WindowBuildTool.java:271) ~[?:0.10.306-ALPHA] {re:classloading}
	at com.minecolonies.coremod.client.gui.WindowMinecoloniesBuildTool.checkAndPlace(WindowMinecoloniesBuildTool.java:133) ~[?:0.11.852-ALPHA] {re:classloading}
	at com.ldtteam.structurize.client.gui.WindowBuildTool.confirmClicked(WindowBuildTool.java:1074) ~[?:0.10.306-ALPHA] {re:classloading}
	at com.ldtteam.structurize.client.gui.AbstractWindowSkeleton.lambda$registerButton$0(AbstractWindowSkeleton.java:40) ~[?:0.10.306-ALPHA] {re:classloading}
	at com.ldtteam.structurize.client.gui.AbstractWindowSkeleton.onButtonClicked(AbstractWindowSkeleton.java:67) ~[?:0.10.306-ALPHA] {re:classloading}
	at com.ldtteam.blockout.controls.Button.handleClick(Button.java:95) ~[?:0.10.306-ALPHA] {re:classloading}
	at com.ldtteam.blockout.Pane.click(Pane.java:480) ~[?:0.10.306-ALPHA] {re:classloading}
	at com.ldtteam.blockout.views.View.mouseEventProcessor(View.java:307) ~[?:0.10.306-ALPHA] {re:classloading}
	at com.ldtteam.blockout.views.View.mouseClickableEventHandler(View.java:271) ~[?:0.10.306-ALPHA] {re:classloading}
	at com.ldtteam.blockout.views.View.click(View.java:141) ~[?:0.10.306-ALPHA] {re:classloading}
	at com.ldtteam.blockout.views.View.mouseEventProcessor(View.java:307) ~[?:0.10.306-ALPHA] {re:classloading}
	at com.ldtteam.blockout.views.View.mouseClickableEventHandler(View.java:271) ~[?:0.10.306-ALPHA] {re:classloading}
	at com.ldtteam.blockout.views.View.click(View.java:141) ~[?:0.10.306-ALPHA] {re:classloading}
	at com.ldtteam.blockout.BOScreen.mouseClicked(BOScreen.java:170) ~[?:0.10.306-ALPHA] {re:classloading}
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:82) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:446) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:80) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:163) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:162) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.1.jar:build 12] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.1.jar:build 12] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3050) ~[lwjgl-glfw-3.2.1.jar:build 12] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:98) ~[?:?] {re:classloading}
	at net.minecraft.client.MainWindow.func_227802_e_(SourceFile:301) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) ~[1.15.2-forge-31.1.0.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.15.2-31.1.0.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.minecolonies.coremod.client.gui.WindowMinecoloniesBuildTool.paste(WindowMinecoloniesBuildTool.java:88)
	at com.ldtteam.structurize.client.gui.WindowBuildTool.paste(WindowBuildTool.java:306)
	at com.ldtteam.structurize.client.gui.WindowBuildTool.pasteNice(WindowBuildTool.java:271)
	at com.minecolonies.coremod.client.gui.WindowMinecoloniesBuildTool.checkAndPlace(WindowMinecoloniesBuildTool.java:133)
	at com.ldtteam.structurize.client.gui.WindowBuildTool.confirmClicked(WindowBuildTool.java:1074)
	at com.ldtteam.structurize.client.gui.AbstractWindowSkeleton.lambda$registerButton$0(AbstractWindowSkeleton.java:40)
	at com.ldtteam.structurize.client.gui.AbstractWindowSkeleton.onButtonClicked(AbstractWindowSkeleton.java:67)
	at com.ldtteam.blockout.controls.Button.handleClick(Button.java:95)
	at com.ldtteam.blockout.Pane.click(Pane.java:480)
	at com.ldtteam.blockout.views.View.mouseEventProcessor(View.java:307)
	at com.ldtteam.blockout.views.View.mouseClickableEventHandler(View.java:271)
	at com.ldtteam.blockout.views.View.click(View.java:141)
	at com.ldtteam.blockout.views.View.mouseEventProcessor(View.java:307)
	at com.ldtteam.blockout.views.View.mouseClickableEventHandler(View.java:271)
	at com.ldtteam.blockout.views.View.click(View.java:141)
	at com.ldtteam.blockout.BOScreen.mouseClicked(BOScreen.java:170)
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:82)

-- Affected screen --
Details:
	Screen name: com.ldtteam.blockout.BOScreen
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:446)
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:80)
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:163)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94)
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:162)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3050)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:98)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['FoamyLemning446'/160, l='MpServer', x=429.39, y=64.00, z=178.31]]
	Chunk stats: Client Chunk Cache: 2401, 1870
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: -4580610765774346026
	Level generator: ID 02 - largeBiomes, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (160,67,145), Chunk: (at 0,4,1 in 10,9; contains blocks 160,0,144 to 175,255,159), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 20603 game time, 28009 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:442)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1764)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:568)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Mac OS X (x86_64) version 10.15.4
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 816918288 bytes (779 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.0-milestone.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.0.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.0.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.0
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		forge-1.15.2-31.1.0-client.jar Minecraft {minecraft@1.15.2 DONE}
		structurize-0.10.306-ALPHA.jar Structurize {structurize@0.10.306-ALPHA DONE}
		forge-1.15.2-31.1.0-universal.jar Forge {forge@31.1.0 DONE}
		minecolonies-0.11.852-ALPHA-universal.jar Minecolonies {minecolonies@0.11.852-ALPHA DONE}
	Launched Version: 1.15.2-forge-31.1.0
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: AMD Radeon Pro 560 OpenGL Engine GL version 2.1 ATI-3.8.24, ATI Technologies Inc.
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz

**Comment by Raycoms** [comment]
Update both structurize and minecolonies to the newest version please.

**Comment by maximus1218** [comment]
Hey Raycoms, I have downloaded the newest versions of each on curse forge but I am still having the same issues. I'm thinking that maybe I just can't find the download for the newest version. Could you send me download links to the newest versions of structurize and minecolonies?

**Comment by someaddons** [comment]
https://www.curseforge.com/minecraft/mc-mods/structurize/files/all
https://www.curseforge.com/minecraft/mc-mods/minecolonies/files/all

Top file on both

**Comment by maximus1218** [comment]
Thank you!
