### ISSUE TITLE
Crash Report RE: Ticking Entity related to fulfilling a builder's last requested item

### ISSUE THREAD

**Issue by Scorch-Mechanic** [ldtteam/minecolonies#4860]
### Minecolonies version: 0.11.913

I fulfilled the builder's last request for upgrading my wooden university to level 2 (the last requested item was a powered rail). This was through the builder's block "fulfill" button, not the builder's requests menu.

The citizen named in the crash log isn't the builder. The citizen named in the crash log is one of my deliverymen. I had extras of the last few items the builder needed in the warehouse already, is it possible the crash is related to the deliveryman wigging out when I fulfilled the builder's request before he did?

### Log: 

- crashlog: [crash-2020-05-03_05.34.40-server.txt](https://github.com/ldtteam/minecolonies/files/4570294/crash-2020-05-03_05.34.40-server.txt)

**Comment by Scorch-Mechanic** [comment]
Updated to 917. Still crashing out here, still the same deliveryman mentioned in the log.

[crash-2020-05-03_08.05.06-server.txt](https://github.com/ldtteam/minecolonies/files/4570824/crash-2020-05-03_08.05.06-server.txt)
[latest.log](https://github.com/ldtteam/minecolonies/files/4570826/latest.log)

I followed the offending deliveryman around for a few minutes and everything was fine right up until he went back to his delivery hut to do... whatever deliverymen have to do in their huts that's related to their jobs, I guess. Soon as he stopped next to the deliveryman hut block the game crashed with the related above logs.

**Comment by SakuraOran** [comment]
/mc colony requestsystem-reset-all

That should fix it

**Comment by Scorch-Mechanic** [comment]
It did fix it! for about, er, five minutes. Different deliveryman, same error.

[latest.log](https://github.com/ldtteam/minecolonies/files/4570900/latest.log)
[crash-2020-05-03_08.51.24-server.txt](https://github.com/ldtteam/minecolonies/files/4570901/crash-2020-05-03_08.51.24-server.txt)

**Comment by Raycoms** [comment]
Yep as I thought

@OrionDevelopment

**Comment by Raycoms** [comment]
```
java.lang.IllegalArgumentException: The given token is not registered as a request to this manager
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.getRequest(RequestHandler.java:541) ~[?:0.11.917-ALPHA] {re:classloading}
	at com.minecolonies.coremod.colony.requestsystem.management.manager.StandardRequestManager.updateRequestState(StandardRequestManager.java:289) ~[?:0.11.917-ALPHA] {re:classloading}
	at com.minecolonies.coremod.colony.jobs.JobDeliveryman.cancelAssignedRequests(JobDeliveryman.java:284) ~[?:0.11.917-ALPHA] {re:classloading}
	at com.minecolonies.coremod.colony.jobs.JobDeliveryman.setActive(JobDeliveryman.java:268) ~[?:0.11.917-ALPHA] {re:classloading}
	at com.minecolonies.coremod.entity.ai.minimal.EntityAIEatTask.searchRestaurant(EntityAIEatTask.java:463) ~[?:0.11.917-ALPHA] {re:classloading}
	at com.minecolonies.coremod.entity.ai.minimal.EntityAIEatTask.func_75246_d(EntityAIEatTask.java:194) ~[?:0.11.917-ALPHA] {re:classloading}
```

**Comment by Anesos** [comment]
Looks like you guys may have a track on this already, but wanted to add to the thread that we're having the same problem on my server. Seen on 909 and now 918 as well.
Crashlog from 909: https://gist.github.com/Anesos/89a341e53b73ed08fcba9e8bd02f7857

Relevant section from 918:
```
java.lang.IllegalArgumentException: The given token is not registered as a request to this manager
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.getRequest(RequestHandler.java:541) ~[?:0.11.918-BETA] {re:classloading}
	at com.minecolonies.coremod.colony.requestsystem.management.manager.StandardRequestManager.updateRequestState(StandardRequestManager.java:289) ~[?:0.11.918-BETA] {re:classloading}
	at com.minecolonies.coremod.colony.jobs.JobDeliveryman.cancelAssignedRequests(JobDeliveryman.java:284) ~[?:0.11.918-BETA] {re:classloading}
	at com.minecolonies.coremod.colony.jobs.JobDeliveryman.setActive(JobDeliveryman.java:268) ~[?:0.11.918-BETA] {re:classloading}
	at com.minecolonies.coremod.entity.ai.minimal.EntityAIEatTask.searchRestaurant(EntityAIEatTask.java:463) ~[?:0.11.918-BETA] {re:classloading}
	at com.minecolonies.coremod.entity.ai.minimal.EntityAIEatTask.func_75246_d(EntityAIEatTask.java:194) ~[?:0.11.918-BETA] {re:classloading}
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?] {re:classloading}
	at com.performant.coremod.entity.ai.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:368) ~[?:1.15-2.09m] {re:classloading}
```

**Comment by Perlo0ung** [comment]
Can confirm, got the same problem on 918. My server instantly crashes on startup, with no way to reset.

[Crashlog](https://pastebin.com/FsYuXL38)

**Comment by Raycoms** [comment]
Can you try out the newest?

**Comment by Perlo0ung** [comment]
Exception is caught and logged as warning, but its still happening (server does run tho obviously):

[Part of logfile](https://pastebin.com/TUSLct5w)

**Comment by Raycoms** [comment]
okay that is fine then, I was aiming at fixing the stackoverflow first.

**Comment by Perlo0ung** [comment]
Yeah sure, u'r commit said "bandaid" which is exactly what it does 👍
