### ISSUE TITLE
Random game crashes

### ISSUE THREAD

**Issue by apocalypse3000** [ldtteam/minecolonies#5100]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: 0.11.938 & Structurize 0.10.317

### Expected behavior

- GUI of any block (NPC) I open

### Actual behaviour

- Game crashes - java.lang.NullPointerException: Ticking screen

Here are some broadcast videos with crashes
First: https://www.twitch.tv/videos/634886687 (crash is on time 16:23)
Second: https://www.twitch.tv/videos/634909124 (crash on 7:24)

### Steps to reproduce the problem

Seems like game crashes randomly so it's hard to reproduce.
Maybe installing and using same mods? Same items in inventory? I'm not really sure.

### Logs: Latest.log and crashlog at https://gist.github.com/

Crash 1: https://gist.github.com/apocalypse3000/8efa6e1892d6228ca79c9d98bd284746
Log 1: https://gist.github.com/apocalypse3000/e24cea213d77422217f00f9f5b6c0235

Crash 2: https://gist.github.com/apocalypse3000/81599bb5071ee671c4f6c5b42c306d87
Log 2: https://gist.github.com/apocalypse3000/01cd0b29fb309006129aff234abd030a

**Comment by someaddons** [comment]
> Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

**Comment by Aphenon** [comment]
Will this be fixed on 1.14.4?

**Comment by ToMe25** [comment]
No.
The 1.14.4 version is End of Life, and thus no longer supported.

**Comment by Raycoms** [comment]
Fixed in newest

**Comment by MeikelLP** [comment]
I have a similar issue:

```
java.lang.NullPointerException: Ticking screen
	at com.minecolonies.coremod.client.gui.WindowHutMinerModule$2.updateElement(WindowHutMinerModule.java:119) ~[minecolonies:0.14.34-ALPHA] {re:classloading}
	at com.ldtteam.blockout.views.ScrollingListContainer.refreshElementPanes(ScrollingListContainer.java:54) ~[structurize:0.13.148-ALPHA] {re:classloading}
	at com.ldtteam.blockout.views.ScrollingList.refreshElementPanes(ScrollingList.java:80) ~[structurize:0.13.148-ALPHA] {re:classloading}
	at com.ldtteam.blockout.views.ScrollingList.setDataProvider(ScrollingList.java:72) ~[structurize:0.13.148-ALPHA] {re:classloading}
	at com.minecolonies.coremod.client.gui.WindowHutMinerModule.onOpened(WindowHutMinerModule.java:108) ~[minecolonies:0.14.34-ALPHA] {re:classloading}
	at com.ldtteam.blockout.BOScreen.func_231023_e_(BOScreen.java:247) ~[structurize:0.13.148-ALPHA] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$tick$20(Minecraft.java:1450) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:valhelsia_tweaks.mixins.json:DisplayMemoryWarningScreenMixin,pl:mixin:APP:valhelsia_tweaks.mixins.json:RemoveExperimentalSettingsWarningMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:client.ScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1449) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:valhelsia_tweaks.mixins.json:DisplayMemoryWarningScreenMixin,pl:mixin:APP:valhelsia_tweaks.mixins.json:RemoveExperimentalSettingsWarningMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:valhelsia_tweaks.mixins.json:DisplayMemoryWarningScreenMixin,pl:mixin:APP:valhelsia_tweaks.mixins.json:RemoveExperimentalSettingsWarningMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:kubejs-common.mixins.json:MinecraftMixin,pl:mixin:APP:valhelsia_tweaks.mixins.json:DisplayMemoryWarningScreenMixin,pl:mixin:APP:valhelsia_tweaks.mixins.json:RemoveExperimentalSettingsWarningMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.5.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.0.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
```

Shall I open a new issue?

**Comment by MeikelLP** [comment]
I will open a new one. This is a blocker as I can no longer open the GUI of the miner
