### ISSUE TITLE
Crashing every time I try to build

### ISSUE THREAD

**Issue by M0chicat** [ldtteam/minecolonies#5130]
I am using Minecolonies in version 1.15.2

Anytime I attempt to use the building tool to create a building my game shows me a saving world loading screen and then crashes. I am able to use the tool to look at all the different buildings and move them around but the moment I hit the green check mark my game crashes. I'm not sure what could be causing this but I do run my game with a couple other mods. I have also tried running a new modpack with only Minecolonies and Structurize but got the same results.

My Other Mods:
Abnormal's Core
Better Animals Plus
Biomes O' Plenty
Botania
Botania: Garden of Glass
Buzzier Bees
Curios API
Decorative Blocks
Doggy Talents
Falling Tree
Fast Leaf Decay
GraveStone Mod
Journey Map
Just Enough Items
Minecolonies
MrCrayfishes Furniture Mod
MrCrayfishes Vehicle Mod
No recipe Book
Obfuscate
Open Blocks Elevator
Pam's HarvestCraft 2 - crops
Pam's HarvestCraft 2 - Food core
Pam's HarvestCraft 2 - Trees
Patchouli
SimpleHarvest
Structurize
TheMidnight
U Team Core
Useful Backpacks
Varpirism- Become a Vampire!

Crash Report:
---- Minecraft Crash Report ----
// You're mean.

Time: 5/31/20 11:56 PM
Description: mouseClicked event handler

java.lang.NoSuchMethodError: com.ldtteam.structures.lib.BlueprintUtils.getPrimaryBlockOffset(Lcom/ldtteam/structures/blueprints/v1/Blueprint;)Lnet/minecraft/util/Tuple;
	at com.minecolonies.coremod.client.gui.WindowMinecoloniesBuildTool.place(WindowMinecoloniesBuildTool.java:59) ~[?:0.10.771-RELEASE] {re:classloading}
	at com.ldtteam.structurize.client.gui.WindowBuildTool.confirmClicked(WindowBuildTool.java:1092) ~[?:0.10.313-RELEASE] {re:classloading}
	at com.ldtteam.structurize.client.gui.WindowBuildTool$$Lambda$8881/695185976.run(Unknown Source) ~[?:?] {}
	at com.ldtteam.structurize.client.gui.AbstractWindowSkeleton.lambda$registerButton$0(AbstractWindowSkeleton.java:40) ~[?:0.10.313-RELEASE] {re:classloading}
	at com.ldtteam.structurize.client.gui.AbstractWindowSkeleton$$Lambda$8872/815196841.accept(Unknown Source) ~[?:?] {}
	at com.ldtteam.structurize.client.gui.AbstractWindowSkeleton.onButtonClicked(AbstractWindowSkeleton.java:67) ~[?:0.10.313-RELEASE] {re:classloading}
	at com.ldtteam.blockout.controls.Button.handleClick(Button.java:95) ~[?:0.10.313-RELEASE] {re:classloading}
	at com.ldtteam.blockout.Pane.click(Pane.java:480) ~[?:0.10.313-RELEASE] {re:classloading}
	at com.ldtteam.blockout.views.View$$Lambda$8949/1790558058.accept(Unknown Source) ~[?:?] {}
	at com.ldtteam.blockout.views.View.mouseEventProcessor(View.java:307) ~[?:0.10.313-RELEASE] {re:classloading}
	at com.ldtteam.blockout.views.View.mouseClickableEventHandler(View.java:271) ~[?:0.10.313-RELEASE] {re:classloading}
	at com.ldtteam.blockout.views.View.click(View.java:141) ~[?:0.10.313-RELEASE] {re:classloading}
	at com.ldtteam.blockout.views.View$$Lambda$8949/1790558058.accept(Unknown Source) ~[?:?] {}
	at com.ldtteam.blockout.views.View.mouseEventProcessor(View.java:307) ~[?:0.10.313-RELEASE] {re:classloading}
	at com.ldtteam.blockout.views.View.mouseClickableEventHandler(View.java:271) ~[?:0.10.313-RELEASE] {re:classloading}
	at com.ldtteam.blockout.views.View.click(View.java:141) ~[?:0.10.313-RELEASE] {re:classloading}
	at com.ldtteam.blockout.BOScreen.mouseClicked(BOScreen.java:170) ~[?:0.10.313-RELEASE] {re:classloading}
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:82) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$6671/192470239.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:446) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:80) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:163) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$6670/1263163025.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:162) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$5259/191047060.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:105) ~[?:?] {re:classloading}
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:296) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:946) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.15.2-31.2.5.jar:31.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$413/2084920982.call(Unknown Source) [forge-1.15.2-31.2.5.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.minecolonies.coremod.client.gui.WindowMinecoloniesBuildTool.place(WindowMinecoloniesBuildTool.java:59)
	at com.ldtteam.structurize.client.gui.WindowBuildTool.confirmClicked(WindowBuildTool.java:1092)
	at com.ldtteam.structurize.client.gui.WindowBuildTool$$Lambda$8881/695185976.run(Unknown Source)
	at com.ldtteam.structurize.client.gui.AbstractWindowSkeleton.lambda$registerButton$0(AbstractWindowSkeleton.java:40)
	at com.ldtteam.structurize.client.gui.AbstractWindowSkeleton$$Lambda$8872/815196841.accept(Unknown Source)
	at com.ldtteam.structurize.client.gui.AbstractWindowSkeleton.onButtonClicked(AbstractWindowSkeleton.java:67)
	at com.ldtteam.blockout.controls.Button.handleClick(Button.java:95)
	at com.ldtteam.blockout.Pane.click(Pane.java:480)
	at com.ldtteam.blockout.views.View$$Lambda$8949/1790558058.accept(Unknown Source)
	at com.ldtteam.blockout.views.View.mouseEventProcessor(View.java:307)
	at com.ldtteam.blockout.views.View.mouseClickableEventHandler(View.java:271)
	at com.ldtteam.blockout.views.View.click(View.java:141)
	at com.ldtteam.blockout.views.View$$Lambda$8949/1790558058.accept(Unknown Source)
	at com.ldtteam.blockout.views.View.mouseEventProcessor(View.java:307)
	at com.ldtteam.blockout.views.View.mouseClickableEventHandler(View.java:271)
	at com.ldtteam.blockout.views.View.click(View.java:141)
	at com.ldtteam.blockout.BOScreen.mouseClicked(BOScreen.java:170)
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:82)
	at net.minecraft.client.MouseHelper$$Lambda$6671/192470239.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: com.ldtteam.blockout.BOScreen
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:446)
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:80)
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:163)
	at net.minecraft.client.MouseHelper$$Lambda$6670/1263163025.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94)
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:162)
	at net.minecraft.client.MouseHelper$$Lambda$5259/191047060.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:105)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['M0chi'/108, l='MpServer', x=-687.83, y=64.00, z=-828.47]]
	Chunk stats: Client Chunk Cache: 625, 361
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 6556163760114030736
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-96,75,-174), Chunk: (at 0,4,2 in -6,-11; contains blocks -96,0,-176 to -81,255,-161), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 108955 game time, 113645 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:442)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1763)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:567)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$413/2084920982.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 329389632 bytes (314 MB) / 1897398272 bytes (1809 MB) up to 2863661056 bytes (2731 MB)
	CPUs: 8
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3072m -Xms256m -XX:PermSize=256m
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.5.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.5.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.5.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.5.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.2.5.jar fml TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.5
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		forge-1.15.2-31.2.5-client.jar Minecraft {minecraft@1.15.2 DONE}
		useful_backpacks-1.15.2-1.9.4.63.jar Useful Backpacks {usefulbackpacks@1.9.4.63 DONE}
		pamhc2trees-1.15.2-1.0.5.jar Pam's HarvestCraft 2 Fruit Trees {pamhc2trees@version DONE}
		BiomesOPlenty-1.15.2-10.0.0.363-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.363 DONE}
		pamhc2crops-1.15.2-1.0.5.jar Pam's HarvestCraft 2 Crops {pamhc2crops@version DONE}
		jei-1.15.2-6.0.0.4.jar Just Enough Items {jei@6.0.0.4 DONE}
		FallingTree-1.15.2-2.1.3+28.jar Falling Tree {falling_tree@2.1.3+28 DONE}
		DoggyTalents-1.15.2-1.15.2.3.jar Doggy Talents {doggytalents@1.15.2.3 DONE}
		Abnormals-Core-1.15.2-v1.0.5.jar Abnormals Core {abnormals_core@1.0.5 DONE}
		Buzzier-Bees-1.15.2-v1.5.0.jar Buzzier Bees {buzzierbees@v1.5.0 DONE}
		curios-FORGE-1.15.2-2.0.2.3.jar Curios API {curios@FORGE-1.15.2-2.0.2.3 DONE}
		Botania-r1.15-384.jar Botania {botania@r1.15-384 DONE}
		Patchouli-1.15.2-1.2-33.jar Patchouli {patchouli@1.15.2-1.2-33 DONE}
		pamhc2foodcore-1.15.2-1.0.3.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version DONE}
		gravestone-1.17.5.jar Gravestone Mod {gravestone@1.17.5 DONE}
		journeymap-1.15.2-5.7.0b2.jar Journeymap {journeymap@5.7.0b2 DONE}
		gardenofglass-1.2.jar Garden of Glass {gardenofglass@1.2 DONE}
		themidnight-0.5.8.jar The Midnight {midnight@0.5.8 DONE}
		Harvest-forge-1.15.1-1.2.11-24.jar Harvest {harvest@version DONE}
		elevatorid-1.15.2-1.7.1.jar Elevator Mod {elevatorid@1.15.2-1.7.1 DONE}
		decorative_blocks-6d.jar Decorative Blocks {decorative_blocks@1.6 DONE}
		obfuscate-0.4.3-1.15.2.jar Obfuscate {obfuscate@0.4.3 DONE}
		vehicle-mod-0.44.0-1.15.2.jar MrCrayfish's Vehicle Mod {vehicle@0.44.0 DONE}
		betteranimalsplus-1.15.2-8.2.1.96.jar Better Animals Plus {betteranimalsplus@8.2.1.96 DONE}
		structurize-0.10.313-RELEASE.jar Structurize {structurize@0.10.313-RELEASE DONE}
		u_team_core-1.15.2-2.11.0.156.jar U Team Core {uteamcore@2.11.0.156 DONE}
		noRecipeBook_v1.5.4formc1.15.2.jar No Recipe Book {norecipebook@1.5.4 DONE}
		minecolonies-0.10.771-RELEASE-universal.jar Minecolonies {minecolonies@0.10.771-RELEASE DONE}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		Vampirism-1.15.2-1.6.0-beta.2.jar Vampirism {vampirism@1.6.0-beta.2 DONE, teamlapenlib@1.6.0-beta.2 DONE}
		forge-1.15.2-31.2.5-universal.jar Forge {forge@31.2.5 DONE}
		FastLeafDecay-v22.jar FastLeafDecay {fastleafdecay@v22 DONE}
	Launched Version: forge-31.2.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 670/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.87, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x AMD Ryzen 5 3400G with Radeon Vega Graphics

**Comment by MatthiasMann** [comment]
Update both minecolonies and structurize to the latest alpha version from curseforge.
