### ISSUE TITLE
NullPointer in EntityAIKnight

### ISSUE THREAD

**Issue by Strohtaler** [ldtteam/minecolonies#5149]
### Minecolonies version 
Version: actual source code
Branch: version/1.15
Commit: [d2510ac
](https://github.com/Strohtaler/minecolonies/commit/d2510aca15a669f2e74b936d18cc2892c069bd89)

### Actual behaviour
One Knight, later a second one, requested to contact the mod authors after examining the latest log, because something wrong with the AI.
#### Excerpt:
```latest.log
[03Jun2020 20:17:37.556] [Server thread/WARN] [minecolonies/]: Statemachine for transition com.minecolonies.api.entity.ai.statemachine.AITarget@301c4afd threw an exception:
java.lang.NullPointerException: null
	at com.minecolonies.coremod.entity.ai.citizen.guard.EntityAIKnight.attackPhysical(EntityAIKnight.java:200) ~[?:unspecified]
	at com.minecolonies.coremod.entity.ai.citizen.guard.EntityAIKnight$$Lambda$5297/163154545.get(Unknown Source) ~[?:?]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:79) ~[?:unspecified]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:151) [?:unspecified]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:134) [?:unspecified]
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:126) [?:unspecified]
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:105) [?:unspecified]
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:133) [?:unspecified]
```

### Logs: latest.log and ~~crashlog~~
- latest.log: https://gist.github.com/Strohtaler/6a4568daf065faebeabb57197b30ebd3
- crashlog: none

### Notes
- playing with a colony created under some previous version, that is, before updating to latest version
- _probably_ related to knighttaunt (#5138) (like missing the `KNIGHT_TAUNT` effect since colony was created before we had that effect?)

**Comment by Raycoms** [comment]
fixed in next update

**Comment by Strohtaler** [comment]
just tested it, looks good (just a short test, didn't get that much time now)
