### ISSUE TITLE
AI issue

### ISSUE THREAD

**Issue by erbauerderbeste** [ldtteam/minecolonies#5221]
Version:1.15.2-0.11.958-ALPHA-universal

 There was no unexpected behavior, but my lumberjack advised me to post my latest log because of an alleged issue caught by their AI.

https://user-images.githubusercontent.com/66880604/84576069-33057100-adb2-11ea-9deb-cd7a71f79330.png

I don't know exactly what caused the issue, it might have been the layout of my treefarm (see above)
 or a very large oak tree, but unless it's one of these things, I have no clue of what might have happened.

- latest.log: https://gist.github.com/erbauerderbeste/c1bb9935729108ef26b546797f23f796

**Comment by PowerSchill** [comment]
Specific code block. 

```
13Jun2020 18:23:55.880] [Server thread/WARN] [minecolonies/]: Statemachine for transition com.minecolonies.api.entity.ai.statemachine.AITarget@71716dfe threw an exception:
java.lang.NullPointerException: null
	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIInteract.gatherItems(AbstractEntityAIInteract.java:357) ~[?:1.15.2-0.11.958]
	at com.minecolonies.coremod.entity.ai.citizen.lumberjack.EntityAIWorkLumberjack.gathering(EntityAIWorkLumberjack.java:826) ~[?:1.15.2-0.11.958]
	at com.minecolonies.coremod.entity.ai.citizen.lumberjack.EntityAIWorkLumberjack$$Lambda$5986/561276978.get(Unknown Source) ~[?:?]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:79) ~[?:1.15.2-0.11.958]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:150) [?:1.15.2-0.11.958]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:133) [?:1.15.2-0.11.958]
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:126) [?:1.15.2-0.11.958]
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:105) [?:1.15.2-0.11.958]
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:131) [?:1.15.2-0.11.958]
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) [?:?]
	at com.minecolonies.api.entity.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:222) [?:1.15.2-0.11.958]
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:856) [?:?]
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2262) [?:?]
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:649) [?:?]
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:159) [?:?]
	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:379) [?:1.15.2-0.11.958]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2104) [?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:397) [?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:600) [?:?]
	at net.minecraft.world.server.ServerWorld$$Lambda$5453/599585795.accept(Unknown Source) [?:?]
	at net.minecraft.world.World.func_217390_a(World.java:536) [?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:401) [?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849) [?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:163) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[13Jun2020 18:23:55.976] [Server thread/ERROR] [minecolonies/]: Pausing Entity Maud W. Clopton (com.minecolonies.coremod.job.Lumberjack) at BlockPos{x=-508, y=69, z=16} for 100 Seconds because of error:
[13Jun2020 18:23:55.976] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: java.lang.NullPointerException
[13Jun2020 18:23:55.977] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIInteract.gatherItems(AbstractEntityAIInteract.java:357)
[13Jun2020 18:23:55.977] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at com.minecolonies.coremod.entity.ai.citizen.lumberjack.EntityAIWorkLumberjack.gathering(EntityAIWorkLumberjack.java:826)
[13Jun2020 18:23:55.977] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at com.minecolonies.coremod.entity.ai.citizen.lumberjack.EntityAIWorkLumberjack$$Lambda$5986/561276978.get(Unknown Source)
[13Jun2020 18:23:55.984] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:79)
[13Jun2020 18:23:55.984] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:150)
[13Jun2020 18:23:55.984] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:133)
[13Jun2020 18:23:55.984] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:126)
[13Jun2020 18:23:55.985] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:105)
[13Jun2020 18:23:55.985] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:131)
[13Jun2020 18:23:55.985] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55)
[13Jun2020 18:23:55.985] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at com.minecolonies.api.entity.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:222)
[13Jun2020 18:23:55.986] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:856)
[13Jun2020 18:23:55.986] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2262)
[13Jun2020 18:23:57.629] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:649)
[13Jun2020 18:23:57.629] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:159)
[13Jun2020 18:23:57.629] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:379)
[13Jun2020 18:23:57.630] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2104)
[13Jun2020 18:23:57.630] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:397)
[13Jun2020 18:23:57.630] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:600)
[13Jun2020 18:23:57.631] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at net.minecraft.world.server.ServerWorld$$Lambda$5453/599585795.accept(Unknown Source)
[13Jun2020 18:23:57.631] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at net.minecraft.world.World.func_217390_a(World.java:536)
[13Jun2020 18:23:57.631] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:401)
[13Jun2020 18:23:57.631] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849)
[13Jun2020 18:23:57.632] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
[13Jun2020 18:23:57.632] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:163)
[13Jun2020 18:23:57.632] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
[13Jun2020 18:23:57.633] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at java.lang.Thread.run(Thread.java:745)
[13Jun2020 18:27:14.982] [Render thread/ERROR] [net.minecraft.client.MainWindow/]: ########## GL ERROR ##########
```

**Comment by Raycoms** [comment]
I got the fix ready

**Comment by PowerSchill** [comment]
Is it?

```java
final int currentIndex = Objects.requireNonNull(worker.getNavigator().getPath()).getCurrentPathIndex();
```

**Comment by Raycoms** [comment]
No, another null check
