### ISSUE TITLE
Crash with newest mc + structurize

### ISSUE THREAD

**Issue by cozyducking** [ldtteam/minecolonies#5232]
### Minecolonies version # Update to the newest minecolonies and structurize alpha first and see if your issue might be already fixed!

Version: 
structurize-0.10.323-ALPHA
minecolonies-1.15.2-0.11.959-universal

### Expected behavior

Minecraft to launch and work. 

- 

### Actual behaviour

- 
Crashes to desktop when trying to load up minecraft. 
Older structurize version it doesn't crash (but obviously hinders me from playing the newest mc version)

Crashlog:
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 6/15/20 10:50 PM
Description: Initializing game

java.lang.RuntimeException: Something crashed the event bus earlier in the loading stage. This is NOT a Cooking for Blockheads issue! Scroll up in your latest.log to find the real crash log.
	at net.blay09.mods.cookingforblockheads.client.TileEntityRenderers.initBlockColors(TileEntityRenderers.java:39) ~[?:8.0.2] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_108_TileEntityRenderers_initBlockColors_Block.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168) ~[?:31.2] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:260) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader$$Lambda$6278/1662314855.accept(Unknown Source) ~[?:?] {}
	at java.util.HashMap.forEach(HashMap.java:1280) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:218) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:260) ~[?:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.onBlockColorsInit(ForgeHooksClient.java:207) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.color.BlockColors.func_186723_a(BlockColors.java:76) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:419) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_client.json:block_manipulation.MixinMinecraftClient_B,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_client.json:MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:166) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.15.2-31.2.20.jar:31.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$472/1714922341.call(Unknown Source) [forge-1.15.2-31.2.20.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.blay09.mods.cookingforblockheads.client.TileEntityRenderers.initBlockColors(TileEntityRenderers.java:39)
	at net.minecraftforge.eventbus.ASMEventHandler_108_TileEntityRenderers_initBlockColors_Block.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168)
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:260)
	at net.minecraftforge.fml.ModLoader$$Lambda$6278/1662314855.accept(Unknown Source)
	at java.util.HashMap.forEach(HashMap.java:1280)
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:218)
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:260)
	at net.minecraftforge.client.ForgeHooksClient.onBlockColorsInit(ForgeHooksClient.java:207)
	at net.minecraft.client.renderer.color.BlockColors.func_186723_a(BlockColors.java:76)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:419)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$472/1714922341.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1852184640 bytes (1766 MB) / 3943694336 bytes (3761 MB) up to 9535225856 bytes (9093 MB)
	CPUs: 4
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10230m -Xms256m -XX:PermSize=256m
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.20.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.20.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.20.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.20.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.15.2_HD_U_G1_pre26.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.20.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/OptiForge-MC1.15.2-0.1.23.jar optiforge TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.20
	FML Language Providers: 
		javafml@31.2
		minecraft@1
		kotlinfml@1.5.2
	Mod List: 
		followingvillagers-1.15.2-1.4.0.jar Following Villagers {followingvillagers@1.15.2-1.4.0 CREATE_REGISTRIES}
		ClientTweaks_1.15.2-4.1.2.jar Client Tweaks {clienttweaks@4.1.2 CREATE_REGISTRIES}
		doubledoors_1.15-2.1.jar Double Doors {doubledoors@2.1 CREATE_REGISTRIES}
		TrashSlot_1.14.4-10.4.8.jar TrashSlot {trashslot@10.4.8 CREATE_REGISTRIES}
		torchslabmod-1.15.2_v1.6.15.jar Torch Slab Mod {torchslabmod@1.6.15 CREATE_REGISTRIES}
		XPFromHarvest-1.15.2-1.2.0.jar XP From Harvest {xpfromharvest@1.2.0 CREATE_REGISTRIES}
		EquipmentTooltips-1.15.2-1.4.3+14.jar Equipment Tooltips {equipmenttooltips@1.4.3+14 CREATE_REGISTRIES}
		mining-helmet-1.15.2-1.0.8.jar Mining Helmet {mining_helmet@1.0.8 CREATE_REGISTRIES}
		equaldragons-1.2.jar Equal Dragons {equaldragons@1.2 CREATE_REGISTRIES}
		OptiForge-MC1.15.2-0.1.23.jar OptiForge {optiforge@0.1.23 CREATE_REGISTRIES}
		SwordBlockingCombat-v1.4-1.15.2.jar Sword Blocking Combat {swordblockingcombat@1.4 CREATE_REGISTRIES}
		FallingTree-1.15.2-2.1.4.jar Falling Tree {falling_tree@2.1.4 CREATE_REGISTRIES}
		AttributeFix-1.15.2-7.0.2.jar AttributeFix {attributefix@7.0.2 CREATE_REGISTRIES}
		Abnormals-Core-1.15.2-1.0.6.jar Abnormals Core {abnormals_core@1.0.6 CREATE_REGISTRIES}
		Buzzier-Bees-1.15.2-1.5.1.jar Buzzier Bees {buzzierbees@1.5.1 CREATE_REGISTRIES}
		mcw-windows-1.0.1-mc1.15.2_1.15.1.jar Macaw's Windows {mcwwindows@1.0.1 CREATE_REGISTRIES}
		Upgrade-Aquatic-1.15.2-v1.6.1.jar Upgrade Aquatic {upgrade_aquatic@1.6.1 CREATE_REGISTRIES}
		KleeSlabs_1.14.4-7.4.8.jar KleeSlabs {kleeslabs@7.4.8 ERROR}
		extraboats-1.3.6-1.15.2.jar Extra Boats {extraboats@1.3.6 CREATE_REGISTRIES}
		BowInfinityFix-1.15.2-rv8.jar Bow Infinity Fix {bowinfinityfix@rv8 CREATE_REGISTRIES}
		create-mc1.15.2_v0.2.4d.jar Create {create@mc1.15.2_v0.2.4d CREATE_REGISTRIES}
		villagernames_1.15-2.4.jar Villager Names {villagernames@2.4 CREATE_REGISTRIES}
		TerraForged-1.15.2-0.0.14.jar TerraForged {terraforged@0.0.14 CREATE_REGISTRIES}
		Clumps-5.0.2.jar Clumps {clumps@5.0.2 CREATE_REGISTRIES}
		mgui-1.15.2-2.1.1.jar mgui {mgui@2.1.1 CREATE_REGISTRIES}
		JRFTL+[1.15.2]-1.1.jar JRFTL {jrftl@1.1 CREATE_REGISTRIES}
		CookingForBlockheads_1.15.2-8.0.2.jar Cooking for Blockheads {cookingforblockheads@8.0.2 CREATE_REGISTRIES}
		ReAuth-1.14-1.15-3.8.1.jar ReAuth {reauth@3.8.1 CREATE_REGISTRIES}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 CREATE_REGISTRIES}
		comforts-FORGE-1.15.2-2.0.0.3.jar Comforts {comforts@FORGE-1.15.2-2.0.0.3 CREATE_REGISTRIES}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 CREATE_REGISTRIES}
		decorative_blocks-6d.jar Decorative Blocks {decorative_blocks@1.6 CREATE_REGISTRIES}
		DungeonCrawl-1.15.2-1.6.3.jar Dungeon Crawl {dungeoncrawl@1.6.3 CREATE_REGISTRIES}
		betteranimalsplus-1.14.4-9.0.1.jar Better Animals Plus {betteranimalsplus@9.0.1 ERROR}
		MutantBeasts-1.15.2-1.0.7.jar Mutant Beasts {mutantbeasts@1.15.2-1.0.7 CREATE_REGISTRIES}
		Bookshelf-1.15.2-5.6.40.jar Bookshelf {bookshelf@5.6.40 CREATE_REGISTRIES}
		The-Endergetic-Expansion-1.15.2-v1.3.1.jar The Endergetic Expansion {endergetic@1.3.1 CREATE_REGISTRIES}
		nhacampfire_1.15-2.3.jar No Hostiles Around Campfire {nhacampfire@2.3 CREATE_REGISTRIES}
		mcw-doors-1.0.0-mc1.15.2.jar Macaw's Doors {mcwdoors@1.0.0 CREATE_REGISTRIES}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version CREATE_REGISTRIES}
		immersive-portals-0.22(forMc1.15withForge).jar Immersive Portals {immersive_portals@0.22 CREATE_REGISTRIES}
		Swamp-Expansion-1.15.2-v1.7.1.jar Swamp Expansion {swampexpansion@NONE CREATE_REGISTRIES}
		forge-1.15.2-31.2.20-universal.jar Forge {forge@31.2.20 CREATE_REGISTRIES}
		ruins-1.15.2.1.jar Ruins {ruins@1.15.2.1 CREATE_REGISTRIES}
		ironchest-1.14.4-9.1.5.jar Iron Chests {ironchest@1.14.3-9.0.3 CREATE_REGISTRIES}
		forge-1.15.2-31.2.20-client.jar Minecraft {minecraft@1.15.2 CREATE_REGISTRIES}
		cofh_core-1.15.2-0.4.0b.jar CoFH Core {cofh_core@0.4.0b CREATE_REGISTRIES}
		mcw-bridges-1.0.4fix-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.4 CREATE_REGISTRIES}
		dwmh-1.15.2-4.0.0.jar Dude! Where's my Horse? {dwmh@NONE CREATE_REGISTRIES}
		TipTheScales-1.15.2-2.0.1.jar TipTheScales {tipthescales@1.15.2-2.0.1 CREATE_REGISTRIES}
		EnchantmentDescriptions-1.15.2-2.0.8.jar EnchantmentDescriptions {enchdesc@2.0.8 CREATE_REGISTRIES}
		swingthroughgrass-1.15.2-1.4.0.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.0 CREATE_REGISTRIES}
		pandoras_creatures-1.15.2-1.0.0.jar Pandoras Creatures {pandoras_creatures@1.15.2-1.0.0 CREATE_REGISTRIES}
		AmbientSounds_v3.0.20_mc1.15.2.jar Ambient Sounds {ambientsounds@3.0.3 CREATE_REGISTRIES}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 CREATE_REGISTRIES}
		ToolBelt-1.15.2-1.14.1.jar Tool Belt {toolbelt@1.14.1 CREATE_REGISTRIES}
		BiomesOPlenty-1.15.2-10.0.0.363-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.363 CREATE_REGISTRIES}
		phosphor-forge-mc1.15.2-0.5.2+build.4.jar Phosphor {phosphor@0.5.2+build.4 CREATE_REGISTRIES}
		craftablechainmail-1.15.2-1.1.jar Leo's Craftable Chainmail {craftablechainmail@1.15.2-1.1 CREATE_REGISTRIES}
		valhelsia_structures-15.0.3a.jar Valhelsia Structures {valhelsia_structures@15.0.3a CREATE_REGISTRIES}
		forbidden_arcanus-1.15.2-1.3.1.jar Forbidden & Arcanus {forbidden_arcanus@1.15.2-1.3.1 CREATE_REGISTRIES}
		archers_paradox-1.15.2-0.4.0b.jar Archer's Paradox {archers_paradox@0.4.0b CREATE_REGISTRIES}
		astikorcarts-1.0.2-1.15.2.jar AstikorCarts {astikorcarts@1.0.2 CREATE_REGISTRIES}
		lycanitesmobs-1.15.2-2.2.3.2.jar Lycanites Mobs {lycanitesmobs@1.15.2-2.2.3.2 CREATE_REGISTRIES}
		Bountiful-1.15.2-3.1.2.jar Bountiful {bountiful@1.15.2-3.1.2 CREATE_REGISTRIES}
		paintings-1.14.4-6.0.1.5.jar Paintings ++ {paintings@1.14.4-6.0.1.5 CREATE_REGISTRIES}
		curios-FORGE-1.15.2-2.0.2.4.jar Curios API {curios@FORGE-1.15.2-2.0.2.4 CREATE_REGISTRIES}
		tetra-1.15.2-2.8.1.jar Tetra {tetra@1.15.2-2.8.1 CREATE_REGISTRIES}
		Botania-r1.15-384.jar Botania {botania@r1.15-384 CREATE_REGISTRIES}
		Patchouli-1.15.2-1.2-34.jar Patchouli {patchouli@1.15.2-1.2-34 CREATE_REGISTRIES}
		corail_woodcutter-1.1.3-1.15.2.jar Corail Woodcutter {corail_woodcutter@1.1.3 CREATE_REGISTRIES}
		MaterialMaster-v1.2-1.15.2.jar Material Master {materialmaster@1.2 CREATE_REGISTRIES}
		collective-1.15.2-1.20.jar Collective {collective@1.20 CREATE_REGISTRIES}
		cyclepaintings_1.15-1.3.jar Cycle Paintings {cyclepaintings@1.3 CREATE_REGISTRIES}
		FastWorkbench-1.15.1-3.0.0.jar FastWorkbench {fastbench@3.0.0 CREATE_REGISTRIES}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 CREATE_REGISTRIES}
		sit-1.15.1-v1.3.jar Sit {sit@v1.3 CREATE_REGISTRIES}
		OreExcavation-1.7.151.jar Ore Excavation {oreexcavation@NONE CREATE_REGISTRIES}
		themidnight-0.5.9.jar The Midnight {midnight@0.5.9 CREATE_REGISTRIES}
		tombstone-4.4.1-1.15.2.jar Corail Tombstone {tombstone@4.4.1 CREATE_REGISTRIES}
		Quark-r2.1-245.jar Quark {quark@r2.1-245 CREATE_REGISTRIES}
		structurize-0.10.323-ALPHA.jar Structurize {structurize@0.10.323-ALPHA CREATE_REGISTRIES}
		minecolonies-1.15.2-0.11.959-universal.jar Minecolonies {minecolonies@1.15.2-0.11.959 CREATE_REGISTRIES}
		FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 CREATE_REGISTRIES}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 CREATE_REGISTRIES}
		AI-Improvements-1.15.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 CREATE_REGISTRIES}
		betterbedrockgenerator-1.15.2-0.0.7.jar Better Bedrock Generator {betterbedrockgenerator@0.0.7 CREATE_REGISTRIES}
		FastLeafDecay-v22.jar FastLeafDecay {fastleafdecay@v22 CREATE_REGISTRIES}
		CosmeticArmorReworked-1.14.4-v3.jar CosmeticArmorReworked {cosmeticarmorreworked@1.14.4-v3 CREATE_REGISTRIES}
		SoundFilters-0.13_for_1.15.2.jar Sound Filters {soundfilters@0.13_for_1.15.2 CREATE_REGISTRIES}
	Launched Version: forge-31.2.20
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 441.87, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 4x Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre26
	OptiFine Build: 20200615-011655
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 441.87
	OpenGlRenderer: GeForce GTX 1070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by cozyducking** [comment]
Was older mods causing problems.

**Comment by Raycoms** [comment]
:+1:
