### ISSUE TITLE
Unable to place Plantation (with Build Tool)

### ISSUE THREAD

**Issue by Strohtaler** [ldtteam/minecolonies#5260]
### Minecolonies version
Minecolonies: unspecified, commit c49635501eb08204e2ca3bce7d73e08de48346e3
Structurize: 0.10.324-ALPHA
Minecraft: 1.15.2
Forge: 31.2.20
Single-player/survival gamemode

### Expected behavior
Placing the Plantation (wooden) with the Build Tool and accepting it, the block should be placed and surrounded with construction tape.

### Actual behaviour
The block, where the Anchor Point should go, _pops out_ and just one solid substitution block (`structurize:blocksolidsubstitution`) is placed there.
Exception in log:
```
[20Jun2020 10:36:37.706] [Server thread/WARN] [minecolonies/]: Colony at place is null! dim:0 pos:BlockPos{x=721, y=70, z=215}
[20Jun2020 10:36:37.706] [Server thread/ERROR] [minecolonies/]: BuildTool: building is null!
java.lang.Exception: null
	at com.minecolonies.coremod.network.messages.server.BuildToolPlaceMessage.setupBuilding(BuildToolPlaceMessage.java:333) [?:unspecified]
	at com.minecolonies.coremod.network.messages.server.BuildToolPlaceMessage.handleHut(BuildToolPlaceMessage.java:257) [?:unspecified]
	at com.minecolonies.coremod.network.messages.server.BuildToolPlaceMessage.onExecute(BuildToolPlaceMessage.java:172) [?:unspecified]
	at com.minecolonies.coremod.network.NetworkChannel.lambda$null$3(NetworkChannel.java:221) [?:unspecified]
	at com.minecolonies.coremod.network.NetworkChannel$$Lambda$5624/1885351753.run(Unknown Source) [?:unspecified]
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) [?:?]
```
(placing other blocks/huts is working as expected)

### Steps to reproduce the problem
1. craft a plantation block
2. use the build tool to position it
3. select wooden plantation1
4. click the green check mark

### Logs: Latest.log and crashlog at https://gist.github.com/
- latest.log: [gist](https://gist.github.com/Strohtaler/2d1c8723223332482133517810c2b1a1)
- ~~crashlog~~:

**Comment by Raycoms** [comment]
That is a schematic issue then. Please in #5006

**Comment by Strohtaler** [comment]
sure, but anyway throwing an Exception is not the best user-friendly way

**Comment by Raycoms** [comment]
It's because this is difficult to detect if the schematic got an invalid hut. @lunadragnstar 

And @Strohtaler please tell us which style.

**Comment by Strohtaler** [comment]
Style: wooden (.../schematics/wooden/plantation1.blueprint)
