### ISSUE TITLE
Nullpointer

### ISSUE THREAD

**Issue by Kroko1337** [ldtteam/minecolonies#5262]
java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at com.minecolonies.coremod.colony.buildings.AbstractBuilding.onRequestedRequestCancelled(AbstractBuilding.java:1280)
    at com.minecolonies.coremod.colony.requestsystem.requesters.BuildingBasedRequester.lambda$onRequestedRequestCancelled$1(BuildingBasedRequester.java:83)
    at com.minecolonies.coremod.colony.requestsystem.requesters.BuildingBasedRequester$$Lambda$6341/979158901.accept(Unknown Source)
    at java.util.Optional.ifPresent(Optional.java:159)
    at com.minecolonies.coremod.colony.requestsystem.requesters.BuildingBasedRequester.onRequestedRequestCancelled(BuildingBasedRequester.java:83)
    at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.processDirectCancellationAndNotifyRequesterOf(RequestHandler.java:427)
    at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.onRequestCancelledDirectly(RequestHandler.java:418)
    at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.onRequestCancelled(RequestHandler.java:394)
    at com.minecolonies.coremod.colony.requestsystem.management.manager.StandardRequestManager.updateRequestState(StandardRequestManager.java:310)
    at com.minecolonies.coremod.colony.interactionhandling.RequestBasedInteractionResponseHandler.onServerResponseTriggered(RequestBasedInteractionResponseHandler.java:160)
    at com.minecolonies.coremod.colony.CitizenData.onResponseTriggered(CitizenData.java:242)
    at com.minecolonies.coremod.network.messages.TriggerServerResponseHandlerMessage.messageOnServerThread(TriggerServerResponseHandlerMessage.java:118)
    at com.minecolonies.coremod.network.messages.TriggerServerResponseHandlerMessage.messageOnServerThread(TriggerServerResponseHandlerMessage.java:18)
    at com.minecolonies.coremod.network.messages.AbstractMessage.lambda$onMessage$0(AbstractMessage.java:27)
    at com.minecolonies.coremod.network.messages.AbstractMessage$$Lambda$5744/608256961.run(Unknown Source)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(SourceFile:529)
    ... 5 more

**Comment by Asherslab** [comment]
***use the issue template***
