### ISSUE TITLE
Minecolonies crashes when i try to place the supplycamp

### ISSUE THREAD

**Issue by GeorgeNotF0und** [ldtteam/minecolonies#5306]
Can someone explain to me why is it crashing??

---- Minecraft Crash Report ---
// I bet Cylons wouldn't have this problem.

Time: 28.06.20 00:28
Description: mouseClicked event handler

java.lang.NoSuchMethodError: com.ldtteam.structures.lib.BlueprintUtils.getPrimaryBlockOffset(Lcom/ldtteam/structures/blueprints/v1/Blueprint;)Lnet/minecraft/util/Tuple;
	at com.minecolonies.coremod.client.gui.WindowMinecoloniesBuildTool.paste(WindowMinecoloniesBuildTool.java:86) ~[?:0.10.771-RELEASE] {re:classloading}
	at com.ldtteam.structurize.client.gui.WindowBuildTool.paste(WindowBuildTool.java:306) ~[?:0.10.313-RELEASE] {re:classloading}
	at com.ldtteam.structurize.client.gui.WindowBuildTool.pasteNice(WindowBuildTool.java:271) ~[?:0.10.313-RELEASE] {re:classloading}
	at com.minecolonies.coremod.client.gui.WindowMinecoloniesBuildTool.checkAndPlace(WindowMinecoloniesBuildTool.java:127) ~[?:0.10.771-RELEASE] {re:classloading}
	at com.ldtteam.structurize.client.gui.WindowBuildTool.confirmClicked(WindowBuildTool.java:1074) ~[?:0.10.313-RELEASE] {re:classloading}
	at com.ldtteam.structurize.client.gui.WindowBuildTool$$Lambda$5985/457999110.run(Unknown Source) ~[?:?] {}
	at com.ldtteam.structurize.client.gui.AbstractWindowSkeleton.lambda$registerButton$0(AbstractWindowSkeleton.java:40) ~[?:0.10.313-RELEASE] {re:classloading}
	at com.ldtteam.structurize.client.gui.AbstractWindowSkeleton$$Lambda$5976/1730735.accept(Unknown Source) ~[?:?] {}
	at com.ldtteam.structurize.client.gui.AbstractWindowSkeleton.onButtonClicked(AbstractWindowSkeleton.java:67) ~[?:0.10.313-RELEASE] {re:classloading}
	at com.ldtteam.blockout.controls.Button.handleClick(Button.java:95) ~[?:0.10.313-RELEASE] {re:classloading}
	at com.ldtteam.blockout.Pane.click(Pane.java:480) ~[?:0.10.313-RELEASE] {re:classloading}
	at com.ldtteam.blockout.views.View$$Lambda$6050/1751246362.accept(Unknown Source) ~[?:?] {}
	at com.ldtteam.blockout.views.View.mouseEventProcessor(View.java:307) ~[?:0.10.313-RELEASE] {re:classloading}
	at com.ldtteam.blockout.views.View.mouseClickableEventHandler(View.java:271) ~[?:0.10.313-RELEASE] {re:classloading}
	at com.ldtteam.blockout.views.View.click(View.java:141) ~[?:0.10.313-RELEASE] {re:classloading}
	at com.ldtteam.blockout.views.View$$Lambda$6050/1751246362.accept(Unknown Source) ~[?:?] {}
	at com.ldtteam.blockout.views.View.mouseEventProcessor(View.java:307) ~[?:0.10.313-RELEASE] {re:classloading}
	at com.ldtteam.blockout.views.View.mouseClickableEventHandler(View.java:271) ~[?:0.10.313-RELEASE] {re:classloading}
	at com.ldtteam.blockout.views.View.click(View.java:141) ~[?:0.10.313-RELEASE] {re:classloading}
	at com.ldtteam.blockout.BOScreen.mouseClicked(BOScreen.java:170) ~[?:0.10.313-RELEASE] {re:classloading}
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:82) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$3777/1909504164.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:446) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:80) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:163) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$3776/1768069354.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:162) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$3197/2013611916.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:98) ~[?:?] {re:classloading}
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:296) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:946) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.15.2-31.2.20.jar:31.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$413/670283478.call(Unknown Source) [forge-1.15.2-31.2.20.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.minecolonies.coremod.client.gui.WindowMinecoloniesBuildTool.paste(WindowMinecoloniesBuildTool.java:86)
	at com.ldtteam.structurize.client.gui.WindowBuildTool.paste(WindowBuildTool.java:306)
	at com.ldtteam.structurize.client.gui.WindowBuildTool.pasteNice(WindowBuildTool.java:271)
	at com.minecolonies.coremod.client.gui.WindowMinecoloniesBuildTool.checkAndPlace(WindowMinecoloniesBuildTool.java:127)
	at com.ldtteam.structurize.client.gui.WindowBuildTool.confirmClicked(WindowBuildTool.java:1074)
	at com.ldtteam.structurize.client.gui.WindowBuildTool$$Lambda$5985/457999110.run(Unknown Source)
	at com.ldtteam.structurize.client.gui.AbstractWindowSkeleton.lambda$registerButton$0(AbstractWindowSkeleton.java:40)
	at com.ldtteam.structurize.client.gui.AbstractWindowSkeleton$$Lambda$5976/1730735.accept(Unknown Source)
	at com.ldtteam.structurize.client.gui.AbstractWindowSkeleton.onButtonClicked(AbstractWindowSkeleton.java:67)
	at com.ldtteam.blockout.controls.Button.handleClick(Button.java:95)
	at com.ldtteam.blockout.Pane.click(Pane.java:480)
	at com.ldtteam.blockout.views.View$$Lambda$6050/1751246362.accept(Unknown Source)
	at com.ldtteam.blockout.views.View.mouseEventProcessor(View.java:307)
	at com.ldtteam.blockout.views.View.mouseClickableEventHandler(View.java:271)
	at com.ldtteam.blockout.views.View.click(View.java:141)
	at com.ldtteam.blockout.views.View$$Lambda$6050/1751246362.accept(Unknown Source)
	at com.ldtteam.blockout.views.View.mouseEventProcessor(View.java:307)
	at com.ldtteam.blockout.views.View.mouseClickableEventHandler(View.java:271)
	at com.ldtteam.blockout.views.View.click(View.java:141)
	at com.ldtteam.blockout.BOScreen.mouseClicked(BOScreen.java:170)
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:82)
	at net.minecraft.client.MouseHelper$$Lambda$3777/1909504164.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: com.ldtteam.blockout.BOScreen
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:446)
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:80)
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:163)
	at net.minecraft.client.MouseHelper$$Lambda$3776/1768069354.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94)
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:162)
	at net.minecraft.client.MouseHelper$$Lambda$3197/2013611916.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:98)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['NikeTicksOnFleek'/312, l='MpServer', x=-189.46, y=67.00, z=-317.86]]
	Chunk stats: Client Chunk Cache: 841, 595
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 2948305422955190493
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-256,70,-240), Chunk: (at 0,4,0 in -16,-15; contains blocks -256,0,-240 to -241,255,-225), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 1508365 game time, 290914 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:442)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1763)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:567)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$413/670283478.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6030936952 bytes (5751 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.20.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.20.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.20.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.20.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.2.20.jar fml TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.20
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		forge-1.15.2-31.2.20-client.jar Minecraft {minecraft@1.15.2 DONE}
		Serene-Seasons-Mod-1.15.2.jar Serene Seasons {sereneseasons@1.15.2-3.0.0.49 DONE}
		Lumberjacker-Mod-1.15.2.jar Lumberjacker {lumberjacker@1.0.0 DONE}
		structurize-0.10.313-RELEASE.jar Structurize {structurize@0.10.313-RELEASE DONE}
		InstaHouses-Mod-1.15.2.jar Slashkings InstaHouses {instahouses@1.1 DONE}
		minecolonies-0.10.771-RELEASE-universal.jar Minecolonies {minecolonies@0.10.771-RELEASE DONE}
		Dungeon-Armors-Mod-1.15.2.jar Dungeon Armors {dungeon_armors@1.0.0 DONE}
		RecallPotion-Mod-1.15.2.jar Recall Potion Mod {recall_potion_mod@1.0.0 DONE}
		Overpowered-Toolset-Mod-1.15.2.jar Overpowered Toolset Mod {overpoweredtoolset@1.0.0 DONE}
		AttributeFix-Mod-1.15.2.jar AttributeFix {attributefix@7.0.2 DONE}
		Horse-Modifiers-Mod-1.15.2.jar Horse Modifiers {horsemodifiers@1.2 DONE}
		forge-1.15.2-31.2.20-universal.jar Forge {forge@31.2.20 DONE}
		Extra-Golems-Mod-1.15.2.jar Extra Golems {golems@10.0.0-beta DONE}
		Dragon-Mounts-Legacy-Mod-1.15.2.jar Dragon Mounts Legacy {dragonmounts@1.0.3 DONE}
	Launched Version: 1.15.2-forge-31.2.20
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Radeon RX 580 Series GL version 4.6.13587 Compatibility Profile Context 20.4.2 26.20.15029.27016, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: Leviosa.zip, LycanitesMobs32X.zip
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 2600 Six-Core Processor

**Comment by Raycoms** [comment]
Update to newest alphas
