### ISSUE TITLE
Crash on trying to use clipboard

### ISSUE THREAD

**Issue by adveres** [ldtteam/minecolonies#5347]
## Version: 
(`Valhelsia 2 modpack v2.2.3`. I couldn't check if the newest minecolonies fixed this because the server wouldn't start if I only updated minecolonies in-place.)
- `Minecraft 1.15.2`
- `forge-1.15.2-31.2.21-universal.jar` Forge {forge@31.2.21 DONE}
- `structurize-0.10.324-ALPHA.jar` Structurize {structurize@0.10.324-ALPHA DONE}
- `minecolonies-1.15.2-0.11.960-universal.jar` Minecolonies {minecolonies@1.15.2-0.11.960 DONE}

### Expected behavior
Clipboard + Resource Scroll should have opened.

### Actual behaviour
The resource scroll threw an error in chat.
The clipboard crashed my client game.

I first noticed the resource scroll wasn't working, and the chat in-game said so. Logs showed this:
```
[06Jul2020 10:09:48.823] [Render thread/ERROR] [structurize:blockout/]: IOException Loader.java
java.nio.channels.ClosedChannelException: null
	at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:110) ~[?:1.8.0_242]
	at sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:276) ~[?:1.8.0_242]
	at sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:50) ~[?:1.8.0_242]
	at com.sun.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:952) ~[zipfs.jar:1.8.0_242]
	at com.sun.nio.zipfs.ZipFileSystem.readFullyAt(ZipFileSystem.java:945) ~[zipfs.jar:1.8.0_242]
	at com.sun.nio.zipfs.ZipFileSystem.getDataPos(ZipFileSystem.java:931) ~[zipfs.jar:1.8.0_242]
	at com.sun.nio.zipfs.ZipFileSystem.access$400(ZipFileSystem.java:80) ~[zipfs.jar:1.8.0_242]
	at com.sun.nio.zipfs.ZipFileSystem$EntryInputStream.<init>(ZipFileSystem.java:1472) ~[zipfs.jar:1.8.0_242]
	at com.sun.nio.zipfs.ZipFileSystem.getInputStream(ZipFileSystem.java:1402) ~[zipfs.jar:1.8.0_242]
	at com.sun.nio.zipfs.ZipFileSystem.newInputStream(ZipFileSystem.java:547) ~[zipfs.jar:1.8.0_242]
	at com.sun.nio.zipfs.ZipPath.newInputStream(ZipPath.java:645) ~[zipfs.jar:1.8.0_242]
	at com.sun.nio.zipfs.ZipFileSystemProvider.newInputStream(ZipFileSystemProvider.java:278) ~[zipfs.jar:1.8.0_242]
	at java.nio.file.Files.newInputStream(Files.java:152) ~[?:1.8.0_242]
	at net.minecraftforge.fml.packs.ModFileResourcePack.func_195766_a(ModFileResourcePack.java:66) ~[?:?]
	at net.minecraftforge.fml.packs.DelegatingResourcePack.func_195766_a(DelegatingResourcePack.java:129) ~[?:?]
	at net.minecraft.resources.ResourcePack.func_195761_a(SourceFile:38) ~[?:?]
	at net.minecraft.resources.FallbackResourceManager.func_199019_a(FallbackResourceManager.java:79) ~[?:?]
	at net.minecraft.resources.FallbackResourceManager.func_199002_a(FallbackResourceManager.java:56) ~[?:?]
	at net.minecraft.resources.SimpleReloadableResourceManager.func_199002_a(SimpleReloadableResourceManager.java:59) ~[?:?]
	at com.ldtteam.blockout.Loader.lambda$null$0(Loader.java:237) ~[?:0.10.324-ALPHA]
	at net.minecraftforge.fml.DistExecutor.unsafeCallWhenOn(DistExecutor.java:72) ~[?:?]
	at com.ldtteam.blockout.Loader.createInputStream(Loader.java:237) ~[?:0.10.324-ALPHA]
	at com.ldtteam.blockout.Loader.createFromXMLFile(Loader.java:224) ~[?:0.10.324-ALPHA]
	at com.ldtteam.blockout.Loader.createFromXMLFile(Loader.java:213) ~[?:0.10.324-ALPHA]
	at com.ldtteam.blockout.views.Window.<init>(Window.java:88) ~[?:0.10.324-ALPHA]
	at com.minecolonies.coremod.client.gui.AbstractWindowSkeleton.<init>(AbstractWindowSkeleton.java:46) ~[?:1.15.2-0.11.960]
	at com.minecolonies.coremod.client.gui.WindowResourceList.<init>(WindowResourceList.java:54) ~[?:1.15.2-0.11.960]
	at com.minecolonies.coremod.proxy.ClientProxy.openResourceScrollWindow(ClientProxy.java:110) ~[?:1.15.2-0.11.960]
	at com.minecolonies.coremod.items.ItemResourceScroll.func_195939_a(ItemResourceScroll.java:72) ~[?:1.15.2-0.11.960]
	at shadows.apotheosis.deadly.asm.DeadlyHooks.lambda$onItemUse$0(DeadlyHooks.java:121) ~[?:3.1.2]
	at shadows.apotheosis.deadly.asm.DeadlyHooks.onItemUse(DeadlyHooks.java:135) ~[?:3.1.2]
	at shadows.apotheosis.deadly.asm.DeadlyHooks.onItemUse(DeadlyHooks.java:121) ~[?:3.1.2]
	at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java) ~[?:?]
	at net.minecraft.client.multiplayer.PlayerController.func_217292_a(PlayerController.java:303) ~[?:?]
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1281) ~[?:?]
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1542) ~[?:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1375) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:904) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) ~[?:?]
	at net.minecraft.client.main.Main.main(SourceFile:204) ~[1.15.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.15.2-31.2.21.jar:31.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?]
[06Jul2020 10:09:48.830] [Render thread/ERROR] [structurize:blockout/]: Exception when parsing XML.
java.net.MalformedURLException: null
	at java.net.URL.<init>(URL.java:645) ~[?:1.8.0_242]
	at java.net.URL.<init>(URL.java:508) ~[?:1.8.0_242]
	at java.net.URL.<init>(URL.java:457) ~[?:1.8.0_242]
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:620) ~[?:1.8.0_242]
	at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:148) ~[?:1.8.0_242]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:806) ~[?:1.8.0_242]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771) ~[?:1.8.0_242]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[?:1.8.0_242]
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243) ~[?:1.8.0_242]
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339) ~[?:1.8.0_242]
	at com.ldtteam.blockout.Loader.createFromXML(Loader.java:184) ~[?:0.10.324-ALPHA]
	at com.ldtteam.blockout.Loader.createFromXMLFile(Loader.java:224) ~[?:0.10.324-ALPHA]
	at com.ldtteam.blockout.Loader.createFromXMLFile(Loader.java:213) ~[?:0.10.324-ALPHA]
	at com.ldtteam.blockout.views.Window.<init>(Window.java:88) ~[?:0.10.324-ALPHA]
	at com.minecolonies.coremod.client.gui.AbstractWindowSkeleton.<init>(AbstractWindowSkeleton.java:46) ~[?:1.15.2-0.11.960]
	at com.minecolonies.coremod.client.gui.WindowResourceList.<init>(WindowResourceList.java:54) ~[?:1.15.2-0.11.960]
	at com.minecolonies.coremod.proxy.ClientProxy.openResourceScrollWindow(ClientProxy.java:110) ~[?:1.15.2-0.11.960]
	at com.minecolonies.coremod.items.ItemResourceScroll.func_195939_a(ItemResourceScroll.java:72) ~[?:1.15.2-0.11.960]
	at shadows.apotheosis.deadly.asm.DeadlyHooks.lambda$onItemUse$0(DeadlyHooks.java:121) ~[?:3.1.2]
	at shadows.apotheosis.deadly.asm.DeadlyHooks.onItemUse(DeadlyHooks.java:135) ~[?:3.1.2]
	at shadows.apotheosis.deadly.asm.DeadlyHooks.onItemUse(DeadlyHooks.java:121) ~[?:3.1.2]
	at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java) ~[?:?]
	at net.minecraft.client.multiplayer.PlayerController.func_217292_a(PlayerController.java:303) ~[?:?]
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1281) ~[?:?]
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1542) ~[?:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1375) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:904) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) ~[?:?]
	at net.minecraft.client.main.Main.main(SourceFile:204) ~[1.15.2.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.15.2-31.2.21.jar:31.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?]
Caused by: java.lang.NullPointerException
	at java.net.URL.<init>(URL.java:550) ~[?:1.8.0_242]
	... 38 more
[06Jul2020 10:09:48.916] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] Something went wrong opening the resource scroll, please try again
```

### Steps to reproduce the problem
Unclear. 

1. I was messing around in my base making a sheep farm.
2. I went to go check on resources (via scroll) the builder needed, but it didn't work.
3. Trying the clipboard then crashed the game.

I find it a little suspicious (but I have no idea how this would be the underlying issue) that the `Valhelsia 2` modpack was updated right before the crash began for me. https://github.com/ValhelsiaTeam/Valhelsia/blob/1.15/CHANGELOG.md#changelog-224 was put out at ~10am EST, and my crash was 10 minutes later.

I was also able to log back in, tossed the clipboard/scroll in a fire for good measure, and made new ones. Re-registered them to my colony and they are working fine.

### Logs: Latest.log and crashlog at https://gist.github.com/
- latest.log: https://gist.github.com/adveres/e12cbb92a8a8220dd99d6113fa2c65d1
- crashlog: https://gist.github.com/adveres/de9852524eeb5ca04abd05c8d3a882da

**Comment by adveres** [comment]
Gonna update the modpack client/server now and I can report back if it's better.

**Comment by adveres** [comment]
Updated client/server to `Valhelsia 2, 2.2.4`, which has 
- `minecolonies-0.13.18-ALPHA-universal.jar`
- `structurize-0.13.4-ALPHA.jar`

-----

I have not seen the crash since I posted this issue, either in the older/newer minecolonies version.

**Comment by Raycoms** [comment]
okay great.
