### ISSUE TITLE
Dyer AI error

### ISSUE THREAD

**Issue by MatthiasMann** [ldtteam/minecolonies#5428]
Version: 0.13.59-alpha

### Expected behavior
Dyer to dye the clay (oak) shingles.

### Actual behaviour
AI error:
[minecolonies/]: Statemachine for transition com.minecolonies.api.entity.ai.statemachine.AITarget@2f57e68c threw an exception:
java.lang.NullPointerException: null
	at com.minecolonies.coremod.colony.buildings.AbstractBuildingSmelterCrafter.getAllowedFuel(AbstractBuildingSmelterCrafter.java:199) ~[?:0.13.59-ALPHA]
	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIRequestSmelter.craft(AbstractEntityAIRequestSmelter.java:347) ~[?:0.13.59-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:79) ~[?:0.13.59-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:148) ~[?:0.13.59-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:134) ~[?:0.13.59-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:126) ~[?:0.13.59-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:105) ~[?:0.13.59-ALPHA]
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:130) ~[?:0.13.59-ALPHA]
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?]
	at com.performant.coremod.entity.ai.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:368) ~[?:1.15-2.11m]
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:595) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2262) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:1307) ~[?:?]
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:159) ~[?:?]
	at com.minecolonies.api.entity.citizen.AbstractEntityCitizen.func_70636_d(AbstractEntityCitizen.java:347) ~[?:0.13.59-ALPHA]
	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:388) ~[?:0.13.59-ALPHA]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2104) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:600) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:536) [?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:401) [?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849) [?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

### Steps to reproduce the problem
0. Have dyes in the ware house and shingles (or have a crafter making shingles)
1. Build a dyer (wooden level 1) and assign a worker (do not select a fuel type)
2. Teach dying recipes for shingles (red and orange)
3. Request a dyed shingle
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/
https://gist.github.com/MatthiasMann/f5ff09b879217928d55ff6c5fe2fd098

**Comment by Mekle001** [comment]
Ok, I know what is going on here. I'll add the fix for it to #5424
