### ISSUE TITLE
Racks lose inventory on build 0.13.62

### ISSUE THREAD

**Issue by MatthiasMann** [ldtteam/minecolonies#5441]
Version: 0.13.62-alpha

### Expected behavior
Racks work

### Actual behaviour
Exception while loading the rack content on world load:
[Server thread/ERROR] [net.minecraft.tileentity.TileEntity/]: Failed to load data for block entity minecolonies:rack
java.lang.NullPointerException: null
	at com.minecolonies.api.util.WorldUtil.isChunkLoaded(WorldUtil.java:35) ~[?:0.13.62-ALPHA]
	at com.minecolonies.api.util.WorldUtil.isBlockLoaded(WorldUtil.java:22) ~[?:0.13.62-ALPHA]
	at com.minecolonies.api.tileentities.TileEntityRack.notifyParentAboutInvChange(TileEntityRack.java:204) ~[?:0.13.62-ALPHA]
	at com.minecolonies.api.tileentities.TileEntityRack.func_145839_a(TileEntityRack.java:453) ~[?:0.13.62-ALPHA]
	at net.minecraft.tileentity.TileEntity.lambda$create$1(TileEntity.java:88) ~[?:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_252]
	at net.minecraft.tileentity.TileEntity.func_203403_c(TileEntity.java:86) ~[?:?]
	at net.minecraft.world.chunk.storage.ChunkSerializer.func_222650_a(ChunkSerializer.java:395) ~[?:?]
	at net.minecraft.world.chunk.storage.ChunkSerializer.lambda$read$2(ChunkSerializer.java:132) ~[?:?]
	at net.minecraft.world.chunk.Chunk.func_217318_w(Chunk.java:456) ~[?:?]
	at net.minecraft.world.server.ChunkManager.lambda$null$25(ChunkManager.java:576) ~[?:?]
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[datafixerupper-2.0.24.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-2.0.24.jar:?]
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[datafixerupper-2.0.24.jar:?]
	at net.minecraft.world.server.ChunkManager.lambda$func_219200_b$26(ChunkManager.java:563) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616) ~[?:1.8.0_252]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591) ~[?:1.8.0_252]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456) ~[?:1.8.0_252]
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213166_h(SourceFile:551) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213168_p(SourceFile:560) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?]
	at net.minecraft.world.server.ServerChunkProvider.func_212849_a_(SourceFile:139) [?:?]
	at net.minecraft.world.World.func_217353_a(World.java:149) [?:?]
	at net.minecraft.world.IWorldReader.func_217348_a(IWorldReader.java:101) [?:?]
	at net.minecraft.world.World.func_212866_a_(World.java:145) [?:?]
	at com.natamus.namedareas.events.SignEvent.onChuckLoad(SignEvent.java:179) [?:1.0]
	at net.minecraftforge.eventbus.ASMEventHandler_714_SignEvent_onChuckLoad_Watch.invoke(.dynamic) [?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) [eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) [eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.event.ForgeEventFactory.fireChunkWatch(ForgeEventFactory.java:698) [?:?]
	at net.minecraftforge.event.ForgeEventFactory.fireChunkWatch(ForgeEventFactory.java:706) [?:?]
	at net.minecraft.world.server.ChunkManager.func_219199_a(ChunkManager.java:718) [?:?]
	at net.minecraft.world.server.ChunkManager.func_219234_a(ChunkManager.java:823) [?:?]
	at net.minecraft.world.server.ChunkManager.func_219210_a(ChunkManager.java:940) [?:?]
	at net.minecraft.world.server.ServerChunkProvider.func_217230_c(SourceFile:489) [?:?]
	at net.minecraft.world.server.ServerWorld.func_217465_m(ServerWorld.java:987) [?:?]
	at net.minecraft.world.server.ServerWorld.func_217448_f(ServerWorld.java:886) [?:?]
	at net.minecraft.world.server.ServerWorld.func_217435_c(ServerWorld.java:863) [?:?]
	at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:167) [?:?]
	at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:116) [?:?]
	at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:63) [?:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:224) [?:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:135) [?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:866) [?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

### Steps to reproduce the problem
1. Update to 0.13.62
2. Load a world
3. All racks are empty
4. ... Profit

### Logs: Latest.log and crashlog at https://gist.github.com/
https://gist.github.com/MatthiasMann/aff0f12338f2ad27252f8b36a1e99c21

**Comment by MatthiasMann** [comment]
Um - this is 1.15 not 1.12

**Comment by Raycoms** [comment]
Wrong label

**Comment by Raycoms** [comment]
Wanted to put this on the other issues xD

**Comment by someaddons** [comment]
fixed
