### ISSUE TITLE
Smelter AI Error

### ISSUE THREAD

**Issue by MatthiasMann** [ldtteam/minecolonies#5447]
Version: 0.13.64-alpha

### Expected behavior
No AI error

### Actual behaviour
The stone smelter has an AI error:
[minecolonies/]: Statemachine for transition com.minecolonies.api.entity.ai.statemachine.AITarget@797c93c0 threw an exception:
java.lang.NullPointerException: null
	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIRequestSmelter.craft(AbstractEntityAIRequestSmelter.java:384) ~[?:0.13.64-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:79) ~[?:0.13.64-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:148) ~[?:0.13.64-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:134) ~[?:0.13.64-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:126) ~[?:0.13.64-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:105) ~[?:0.13.64-ALPHA]
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:130) ~[?:0.13.64-ALPHA]
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?]
	at com.performant.coremod.entity.ai.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:368) ~[?:1.15-2.11m]
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:595) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2262) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:1307) ~[?:?]
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:159) ~[?:?]
	at com.minecolonies.api.entity.citizen.AbstractEntityCitizen.func_70636_d(AbstractEntityCitizen.java:347) ~[?:0.13.64-ALPHA]
	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:388) ~[?:0.13.64-ALPHA]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2104) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:600) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:536) [?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:401) [?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849) [?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

### Steps to reproduce the problem
No idea, just loaded the world, let it finish townhall4 and walked around giving new build orders when I saw the AI error.

### Logs: Latest.log and crashlog at https://gist.github.com/
- latest.log: https://gist.github.com/MatthiasMann/dc83959d722e7652e447299dff964cb8

**Comment by Simaster48** [comment]
I've gotten a similar report just now.

Unknown when exactly it came as I have been letting it and the Stone Cutter work hard on supplying stone bricks for the builders.

[11:31:11] [Server thread/ERROR]: Pausing Entity Alain E. White (com.minecolonies.coremod.job.StoneSmeltery) at BlockPos{x=-203, y=63, z=174} for 6400 Seconds because of error:
[11:31:11] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: java.lang.NullPointerException
[11:31:11] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIRequestSmelter.craft(AbstractEntityAIRequestSmelter.java:384)
[11:31:11] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAICrafting$$Lambda$6731/207460023.get(Unknown Source)
[11:31:11] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:79)
[11:31:11] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:148)
[11:31:11] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:134)
[11:31:11] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:126)
[11:31:11] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:105)
[11:31:11] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:130)
[11:31:11] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55)
[11:31:11] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at com.minecolonies.api.entity.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:222)
[11:31:11] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:595)
[11:31:11] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2262)
[11:31:11] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:462)
[11:31:11] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:159)
[11:31:11] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at com.minecolonies.api.entity.citizen.AbstractEntityCitizen.func_70636_d(AbstractEntityCitizen.java:347)
[11:31:11] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:388)
[11:31:11] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2104)
[11:31:11] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274)
[11:31:11] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:600)
[11:31:11] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at net.minecraft.world.server.ServerWorld$$Lambda$6967/122415513.accept(Unknown Source)
[11:31:11] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at net.minecraft.world.World.func_217390_a(World.java:536)
[11:31:11] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:401)
[11:31:11] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849)
[11:31:11] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
[11:31:11] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114)
[11:31:11] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
[11:31:11] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:337]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by Mekle001** [comment]
I know what is going on here. Working on a fix.
