### ISSUE TITLE
[1.15.2] Lumberjack AI issue

### ISSUE THREAD

**Issue by hron84** [ldtteam/minecolonies#5621]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.152-ALPHA
- Structurize Version: 0.13.39-ALPHA
- Related Mods and their Versions:

## Expected behavior
My Lumberjack should be happy and do not run into any issue.

## Actual behavior

My Lumberjack kindly asked me to share this exception with you:

## Steps to reproduce the issue

I do not know what happened

### Logs

```
[20aug.2020 12:16:02.401] [Server thread/ERROR] [minecolonies/]: Pausing Entity Avis L. Asplin (com.minecolonies.coremod.job.Lumberjack) at BlockPos{x=1080, y=72, z=-1379} for 25600 Seconds because of error:
[20aug.2020 12:16:02.401] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: java.lang.ClassCastException: com.minecolonies.coremod.colony.buildings.workerbuildings.BuildingLumberjack cannot be cast to com.minecolonies.coremod.colony.buildings.AbstractBuildingCrafter
[20aug.2020 12:16:02.401] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAICrafting.getRequiredProgressForMakingRawMaterial(AbstractEntityAICrafting.java:383)
[20aug.2020 12:16:02.402] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAICrafting.craft(AbstractEntityAICrafting.java:289)
[20aug.2020 12:16:02.402] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:79)
[20aug.2020 12:16:02.402] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:148)
[20aug.2020 12:16:02.402] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:134)
[20aug.2020 12:16:02.402] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:126)
[20aug.2020 12:16:02.402] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:105)
[20aug.2020 12:16:02.402] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:129)
[20aug.2020 12:16:02.402] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55)
[20aug.2020 12:16:02.403] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at com.minecolonies.api.entity.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:222)
[20aug.2020 12:16:02.403] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:595)
[20aug.2020 12:16:02.403] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2262)
[20aug.2020 12:16:02.403] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:462)
[20aug.2020 12:16:02.403] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:159)
[20aug.2020 12:16:02.403] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at com.minecolonies.api.entity.citizen.AbstractEntityCitizen.func_70636_d(AbstractEntityCitizen.java:352)
[20aug.2020 12:16:02.403] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:455)
[20aug.2020 12:16:02.404] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2104)
[20aug.2020 12:16:02.404] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274)
[20aug.2020 12:16:02.404] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:600)
[20aug.2020 12:16:02.404] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at net.minecraft.world.World.func_217390_a(World.java:536)
[20aug.2020 12:16:02.404] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:401)
[20aug.2020 12:16:02.404] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849)
[20aug.2020 12:16:02.404] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
[20aug.2020 12:16:02.404] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114)
[20aug.2020 12:16:02.404] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
[20aug.2020 12:16:02.405] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at java.lang.Thread.run(Thread.java:748)
```

- latest.log: https://gist.github.com/hron84/9a2f302b3df05e1a28d7dcaaaed78e4a

### Notes

N/A

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by lebanni** [comment]
👍

**Comment by Warnapipou** [comment]
I have the same issue with the same log from the Valhelsia 3 Modpack on the 1.16.
![image](https://user-images.githubusercontent.com/2889835/90779943-81794380-e2fe-11ea-81d2-e58d6cd9d653.png)
