### ISSUE TITLE
Medieval Oak Farm 3 breaking AI

### ISSUE THREAD

**Issue by Leviwulfish** [ldtteam/minecolonies#5647]
- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

- Minecraft Version:1.15.2
- MineColonies Version: 0.13.171-BETA
- Structurize Version:0.13.42-ALPHA
- Related Mods and their Versions:

## Expected behavior
Farmer Builds the Level 3 Medieval Oak Farm

## Actual behavior
Farmer throws the following AI error
[23Aug2020 22:23:17.574] [Server thread/ERROR] [minecolonies/]: Pausing Entity Simon W. Grove (com.minecolonies.coremod.job.Builder) at BlockPos{x=2647, y=65, z=-1371} for 1600 Seconds because of error:
[23Aug2020 22:23:17.575] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: java.lang.RuntimeException: Attempted to load class net/minecraft/client/resources/I18n for invalid dist DEDICATED_SERVER
[23Aug2020 22:23:17.575] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClass(RuntimeDistCleaner.java:71)
[23Aug2020 22:23:17.576] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClass(ILaunchPluginService.java:103)
[23Aug2020 22:23:17.576] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[23Aug2020 22:23:17.577] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:115)
[23Aug2020 22:23:17.577] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:247)
[23Aug2020 22:23:17.578] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:134)
[23Aug2020 22:23:17.580] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96)
[23Aug2020 22:23:17.581] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[23Aug2020 22:23:17.581] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at cofh.lib.util.helpers.StringHelper.canLocalize(StringHelper.java:40)
[23Aug2020 22:23:17.582] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at cofh.lib.block.deco.CarvedPumpkinBlockCoFH.func_149739_a(CarvedPumpkinBlockCoFH.java:52)
[23Aug2020 22:23:17.582] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at net.minecraft.item.BlockItem.func_77658_a(BlockItem.java:181)
[23Aug2020 22:23:17.582] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at net.minecraft.item.Item.func_77667_c(Item.java:216)
[23Aug2020 22:23:17.583] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at net.minecraft.item.ItemStack.func_77977_a(ItemStack.java:401)
[23Aug2020 22:23:17.583] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at com.minecolonies.coremod.colony.buildings.AbstractBuildingStructureBuilder.buildingRequiresCertainAmountOfItem(AbstractBuildingStructureBuilder.java:128)
[23Aug2020 22:23:17.584] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic.dumpOneMoreSlot(AbstractEntityAIBasic.java:1141)
[23Aug2020 22:23:17.584] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic.dumpInventory(AbstractEntityAIBasic.java:1059)
[23Aug2020 22:23:17.585] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:79)
[23Aug2020 22:23:17.586] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:148)
[23Aug2020 22:23:17.586] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:134)
[23Aug2020 22:23:17.587] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:126)
[23Aug2020 22:23:17.587] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:105)
[23Aug2020 22:23:17.588] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:129)
[23Aug2020 22:23:17.588] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55)
[23Aug2020 22:23:17.589] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at com.minecolonies.api.entity.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:222)
[23Aug2020 22:23:17.591] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:595)
[23Aug2020 22:23:17.592] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2262)
[23Aug2020 22:23:17.592] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:462)
[23Aug2020 22:23:17.593] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:159)
[23Aug2020 22:23:17.593] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at com.minecolonies.api.entity.citizen.AbstractEntityCitizen.func_70636_d(AbstractEntityCitizen.java:370)
[23Aug2020 22:23:17.594] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:459)
[23Aug2020 22:23:17.594] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2104)
[23Aug2020 22:23:17.595] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274)
[23Aug2020 22:23:17.595] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:600)
[23Aug2020 22:23:17.596] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at net.minecraft.world.World.func_217390_a(World.java:536)
[23Aug2020 22:23:17.596] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:401)
[23Aug2020 22:23:17.596] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849)
[23Aug2020 22:23:17.597] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330)
[23Aug2020 22:23:17.597] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
[23Aug2020 22:23:17.598] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
[23Aug2020 22:23:17.598] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: 	at java.lang.Thread.run(Unknown Source)

### Notes
Judging by a brief skim it seems to be an issue with the identity of carved pumpkins.

**Comment by Leviwulfish** [comment]
Additional Note : Problem seems to also occur if you place a pumpkin in the inventory of the worker and they attempt to interact with it, such as attempting to store it in their place of work when their inventory is full.

**Comment by ravenbuilder934** [comment]
Try updating to the latest alpha.

**Comment by Raycoms** [comment]
No, this is a different problem. We did not fix this yet.

**Comment by Raycoms** [comment]
Please report to: cofh.lib.block.deco.CarvedPumpkinBlockCoFH.

They use sideOnly methods in the getTranslationKey() method which is itself NOT sideonly.
