### ISSUE TITLE
Game crashed

### ISSUE THREAD

**Issue by naughtywolf** [ldtteam/minecolonies#5663]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context MineColonies Official forge 31.2.36

- Minecraft Version: 1.15.2
- MineColonies Version: v2.2
- Structurize Version:

## Problem description
oones  i press play it trys to start up and then this coms up (ERROR Game crashed and unexpected issue occurred and the game crashed. we re sorry for the inconveniance Exit Code:0

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by naughtywolf** [comment]
cant play instant crash

**Comment by ravenbuilder934** [comment]
We need your versions to troubleshoot. Please include them.

**Comment by naughtywolf** [comment]
[cid:image003.png@01D67CCB.E9DEDAF0]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ravenbuilder934** [comment]
2.2 of the official modpack? If so, that's very weird as it works for me on the same version.

**Comment by naughtywolf** [comment]
yes

**Comment by naughtywolf** [comment]
been trying  for some time now

**Comment by Raycoms** [comment]
Log please

**Comment by naughtywolf** [comment]
it dosent open a log just a little window with an error
as i discribed

**Comment by ravenbuilder934** [comment]
The log is in a folder. Go to your instance folder, then logs, then latest.log

**Comment by naughtywolf** [comment]
[00:21:44] [main/INFO]: ModLauncher running: args [--username, NaughtyW0lf, --version, forge-31.2.36, --gameDir, C:\Users\Freddy boi\Twitch\Minecraft\Instances\MineColonies Official (6), --assetsDir, C:\Users\Freddy boi\Twitch\Minecraft\Install\assets, --assetIndex, 1.15, --uuid, 9775ebf48a284b7cbd53c2c7b9eb08ea, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 1024, --height, 768, --launchTarget, fmlclient, --fml.forgeVersion, 31.2.36, --fml.mcVersion, 1.15.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200515.085601]
[00:21:44] [main/INFO]: ModLauncher 5.1.2+70+master.2845bb9 starting: java version 1.8.0_51 by Oracle Corporation
[00:21:44] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[00:21:45] [main/FATAL]: Failed to find Minecraft resource version 1.15.2-20200515.085601 at C:\Users\Freddy boi\Twitch\Minecraft\Install\libraries\net\minecraftforge\forge\1.15.2-31.2.36\forge-1.15.2-31.2.36-client.jar
[00:21:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: Missing minecraft resource!
[00:21:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLCommonLaunchHandler.lambda$validatePaths$4(FMLCommonLaunchHandler.java:124)
[00:21:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLCommonLaunchHandler$$Lambda$156/2122049087.accept(Unknown Source)
[00:21:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
[00:21:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
[00:21:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLCommonLaunchHandler.validatePaths(FMLCommonLaunchHandler.java:121)
[00:21:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLLoader.setupLaunchHandler(FMLLoader.java:199)
[00:21:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLServiceProvider.initialize(FMLServiceProvider.java:94)
[00:21:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:68)
[00:21:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseTransformationServices$7(TransformationServicesHandler.java:107)
[00:21:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$86/1423561005.accept(Unknown Source)
[00:21:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap$Values.forEach(HashMap.java:972)
[00:21:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initialiseTransformationServices(TransformationServicesHandler.java:107)
[00:21:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:59)
[00:21:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
[00:21:45] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

**Comment by Raycoms** [comment]
That is not a minecolonies problem. Please check with your launcher and possibly reinstall it's a minecraft issue.

**Comment by naughtywolf** [comment]
but other modbacks work

**Comment by ravenbuilder934** [comment]
Redownload this modpack and try again.

**Comment by naughtywolf** [comment]
reinstalled minecraft and the modpack still same problem. i guess i m playing something else
