### ISSUE TITLE
Request system throwing IllegalArgumentException

### ISSUE THREAD

**Issue by jarquafelmu** [ldtteam/minecolonies#5672]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: 0.13.184-ALPHA
- Structurize Version: 0.13.42-ALPHA
- Related Mods and their Versions: N/A

## Expected behavior

For the request system to work properly

## Actual behavior

I was seeing that the request system was throwing this exception in 180 but I needed to update to 184 to see if it was still happening and it is. I think it might be related to the request errors that people have been having.

## Steps to reproduce the issue

1. Unsure what caused it
2. 
3. 

### Logs

- latest.log: https://gist.github.com/jarquafelmu/59007cf7a162e55bf17c2b284951f675
- crashlog: N/A

### Notes

Specific exception
```
java.lang.IllegalArgumentException: The given request: StandardToken{id=3c709fdd-56c0-42aa-8586-4aca70dfd1cf} is not resolved.
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.ResolverHandler.getResolverForRequest(ResolverHandler.java:317) ~[?:0.13.184-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.ResolverHandler.getResolverForRequest(ResolverHandler.java:333) ~[?:0.13.184-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.manager.StandardRequestManager.getResolverForRequest(StandardRequestManager.java:275) ~[?:0.13.184-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.processDirectCancellationOf(RequestHandler.java:430) ~[?:0.13.184-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.processDirectCancellationAndNotifyRequesterOf(RequestHandler.java:423) ~[?:0.13.184-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.onRequestCancelledDirectly(RequestHandler.java:415) ~[?:0.13.184-ALPHA]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408) ~[server-1.15.2-extra.jar:?]
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.onRequestCancelledDirectly(RequestHandler.java:412) ~[?:0.13.184-ALPHA]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408) ~[server-1.15.2-extra.jar:?]
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.onRequestCancelledDirectly(RequestHandler.java:412) ~[?:0.13.184-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.onRequestCancelled(RequestHandler.java:391) ~[?:0.13.184-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.manager.StandardRequestManager.updateRequestState(StandardRequestManager.java:315) ~[?:0.13.184-ALPHA]
	at com.minecolonies.coremod.network.messages.server.colony.UpdateRequestStateMessage.onExecute(UpdateRequestStateMessage.java:88) ~[?:0.13.184-ALPHA]
	at com.minecolonies.coremod.network.messages.server.AbstractColonyServerMessage.onExecute(AbstractColonyServerMessage.java:144) ~[?:0.13.184-ALPHA]
	at com.minecolonies.coremod.network.NetworkChannel.lambda$null$3(NetworkChannel.java:237) ~[?:0.13.184-ALPHA]
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[?:?]
	at com.minecolonies.coremod.network.NetworkChannel.lambda$registerMessage$4(NetworkChannel.java:237) ~[?:0.13.184-ALPHA]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_232]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:78) ~[?:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_232]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:78) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1279) ~[?:?]
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?]
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) [?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:694) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:641) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by WenXin20** [comment]
I am also seeing this, except it is repeatedly crashing my server every time I try to log on. I was fighting Barbarians when the crash occured. Is there a way to reset the request system since I cannot log on the server?
[Crash Report](https://gist.github.com/WenXin20/8a800245b111e32974428caa0035aa08)

**Comment by Raycoms** [comment]
You can in the console /mc colony requestsystem-reset-all

**Comment by Knaxia** [comment]
I recently had a similar issue, throwing the same errors, running 0.13.379-ALPHA.

Both my miner and woodcutter stopped working, they were both requesting items from different professions, the miner was requesting 100 cobblestone stairs from the stonemason, and my woodcutter wanted an axe. Both had the request up in their system, but it was showing the message "Awaiting Resolvers!" under the requested item and nothing was happening. 

What I tried:
-giving them the item, but the request stayed
-Trying to click "Cancel" the request threw this error in the the server console and the request would appear again

> [31Oct2020 16:08:11.068] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
> java.lang.IllegalArgumentException: The given request: StandardToken{id=1e00406a-42fd-4bec-afdb-32b18f961604} is not resolved.
> 	at com.minecolonies.coremod.colony.requestsystem.management.handlers.ResolverHandler.getResolverForRequest(ResolverHandler.java:317) ~[?:0.13.394-ALPHA]
> 	at com.minecolonies.coremod.colony.requestsystem.management.handlers.ResolverHandler.getResolverForRequest(ResolverHandler.java:333) ~[?:0.13.394-ALPHA]
> 	at com.minecolonies.coremod.colony.requestsystem.management.manager.StandardRequestManager.getResolverForRequest(StandardRequestManager.java:275) ~[?:0.13.394-ALPHA]
> 	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.processDirectCancellationOf(RequestHandler.java:430) ~[?:0.13.394-ALPHA]
> 	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.processDirectCancellationAndNotifyRequesterOf(RequestHandler.java:423) ~[?:0.13.394-ALPHA]
> 	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.onRequestCancelledDirectly(RequestHandler.java:415) ~[?:0.13.394-ALPHA]
> 	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408) ~[server-1.15.2-extra.jar:?]
> 	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.onRequestCancelledDirectly(RequestHandler.java:412) ~[?:0.13.394-ALPHA]
> 	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.onRequestCancelled(RequestHandler.java:391) ~[?:0.13.394-ALPHA]
> 	at com.minecolonies.coremod.colony.requestsystem.management.manager.StandardRequestManager.updateRequestState(StandardRequestManager.java:315) ~[?:0.13.394-ALPHA]
> 	at com.minecolonies.coremod.network.messages.server.colony.UpdateRequestStateMessage.onExecute(UpdateRequestStateMessage.java:88) ~[?:0.13.394-ALPHA]
> 	at com.minecolonies.coremod.network.messages.server.AbstractColonyServerMessage.onExecute(AbstractColonyServerMessage.java:144) ~[?:0.13.394-ALPHA]
> 	at com.minecolonies.coremod.network.messages.splitting.SplitPacketMessage.lambda$onExecute$1(SplitPacketMessage.java:128) ~[?:0.13.394-ALPHA]
> 	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[?:?]
> 	at com.minecolonies.coremod.network.messages.splitting.SplitPacketMessage.onExecute(SplitPacketMessage.java:128) ~[?:0.13.394-ALPHA]
> 	at com.minecolonies.coremod.network.NetworkChannel.lambda$setupInternalMessages$2(NetworkChannel.java:261) ~[?:0.13.394-ALPHA]
> 	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[?:?]
> 	at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_271]
> 	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[?:?]
> 	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[?:?]
> 	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[?:?]
> 	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.2.0-service.jar:?]
> 	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.2.0-service.jar:?]
> 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?]
> 	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[?:?]
> 	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:78) ~[?:?]
> 	at java.util.Optional.map(Unknown Source) ~[?:1.8.0_271]
> 	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:78) ~[?:?]
> 	at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1279) ~[?:?]
> 	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?]
> 	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?]
> 	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
> 	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
> 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
> 	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
> 	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) [?:?]
> 	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) [?:?]
> 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
> 	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) [?:?]
> 	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) [?:?]
> 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?]
> 	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:694) [?:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:641) [?:?]
> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
> 

-Trying to clear all of their inventory and giving it back to them
-Fire the worker and hire them again
-restart the server
-Updated to 0.13.394-ALPHA

I ended up destroying my mine (something I had planned already in the past) and redo a new one at another place, which solved the issue, even if it wasn't optimal.

For my woodcutter, I finally stumbled into this and wasn't aware of the "/mc colony requestsystem-reset-all" command, which worked like a charm.

**Comment by Raycoms** [comment]
This should be fixed now.
