### ISSUE TITLE
Crash issue when placing structure.

### ISSUE THREAD

**Issue by Mysteriaa** [ldtteam/minecolonies#5679]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.15.2
- MineColonies Version: N/A
- Structurize Version: 0.13.56

## Problem description
I've been trying to move houses to a different world due to a major glitch involving biomes (again). When attempting to preview the structure, the game crashes and I cannot place the structure. Here's a crash log. https://paste.ee/p/YDhAf#s=0&l=10560

### Notes or related things

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
Not our fault, report this to mod developer
```
Caused by: java.lang.ClassCastException: shetiphian.multibeds.common.tileentity.TileEntityMultiBed cannot be cast to shetiphian.multibeds.common.tileentity.TileEntityMultiBedClient
	at shetiphian.multibeds.client.render.RenderArtOnBed.func_225616_a_(RenderArtOnBed.java:45)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228855_a_(TileEntityRendererDispatcher.java:125)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.lambda$renderTileEntity$0(TileEntityRendererDispatcher.java:100)
	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_228853_a_(TileEntityRendererDispatcher.java:184)
```
