### ISSUE TITLE
Game crashes after builders "Skip the chit-chat" 

### ISSUE THREAD

**Issue by MichalDolharz** [ldtteam/minecolonies#5680]
At first, he wanted flint and steel to upgrade blacksmith to the 3rd level. I dropped it to him, but game till crashes when I try to "speak" with him.

`---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 30.08.20 16:53
Description: Ticking screen

java.lang.IllegalStateException: No extension for file: minecraft:missingno
	at com.ldtteam.blockout.controls.Image.getImageDimensions(Image.java:94) ~[?:0.13.37-ALPHA] {re:classloading}
	at com.ldtteam.blockout.controls.Image.loadMapDimensions(Image.java:77) ~[?:0.13.37-ALPHA] {re:classloading}
	at com.ldtteam.blockout.controls.Image.setImage(Image.java:164) ~[?:0.13.37-ALPHA] {re:classloading}
	at com.ldtteam.blockout.controls.Image.setImage(Image.java:201) ~[?:0.13.37-ALPHA] {re:classloading}
	at com.minecolonies.coremod.client.gui.AbstractWindowRequestTree$1.updateElement(AbstractWindowRequestTree.java:324) ~[?:0.13.145-ALPHA] {re:classloading}
	at com.ldtteam.blockout.views.ScrollingListContainer.refreshElementPanes(ScrollingListContainer.java:54) ~[?:0.13.37-ALPHA] {re:classloading}
	at com.ldtteam.blockout.views.ScrollingList.refreshElementPanes(ScrollingList.java:79) ~[?:0.13.37-ALPHA] {re:classloading}
	at com.ldtteam.blockout.views.ScrollingList.setDataProvider(ScrollingList.java:71) ~[?:0.13.37-ALPHA] {re:classloading}
	at com.minecolonies.coremod.client.gui.AbstractWindowRequestTree.updateRequests(AbstractWindowRequestTree.java:283) ~[?:0.13.145-ALPHA] {re:classloading}
	at com.minecolonies.coremod.client.gui.AbstractWindowRequestTree.onOpened(AbstractWindowRequestTree.java:112) ~[?:0.13.145-ALPHA] {re:classloading}
	at com.minecolonies.coremod.client.gui.WindowCitizen.onOpened(WindowCitizen.java:170) ~[?:0.13.145-ALPHA] {re:classloading}
	at com.ldtteam.blockout.BOScreen.func_231023_e_(BOScreen.java:243) ~[?:0.13.37-ALPHA] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$runTick$20(Minecraft.java:1424) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$3956/2036538800.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:421) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1423) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:928) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:582) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.1-32.0.108.jar:32.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$418/1689458432.call(Unknown Source) [forge-1.16.1-32.0.108.jar:32.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.ldtteam.blockout.controls.Image.getImageDimensions(Image.java:94)
	at com.ldtteam.blockout.controls.Image.loadMapDimensions(Image.java:77)
	at com.ldtteam.blockout.controls.Image.setImage(Image.java:164)
	at com.ldtteam.blockout.controls.Image.setImage(Image.java:201)
	at com.minecolonies.coremod.client.gui.AbstractWindowRequestTree$1.updateElement(AbstractWindowRequestTree.java:324)
	at com.ldtteam.blockout.views.ScrollingListContainer.refreshElementPanes(ScrollingListContainer.java:54)
	at com.ldtteam.blockout.views.ScrollingList.refreshElementPanes(ScrollingList.java:79)
	at com.ldtteam.blockout.views.ScrollingList.setDataProvider(ScrollingList.java:71)
	at com.minecolonies.coremod.client.gui.AbstractWindowRequestTree.updateRequests(AbstractWindowRequestTree.java:283)
	at com.minecolonies.coremod.client.gui.AbstractWindowRequestTree.onOpened(AbstractWindowRequestTree.java:112)
	at com.minecolonies.coremod.client.gui.WindowCitizen.onOpened(WindowCitizen.java:170)
	at com.ldtteam.blockout.BOScreen.func_231023_e_(BOScreen.java:243)
	at net.minecraft.client.Minecraft.lambda$runTick$20(Minecraft.java:1424)
	at net.minecraft.client.Minecraft$$Lambda$3956/2036538800.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: com.ldtteam.blockout.BOScreen
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:421)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Repti993'/524, l='ClientLevel', x=63.47, y=64.00, z=316.29]]
	Chunk stats: Client Chunk Cache: 1681, 1295
	Level dimension: minecraft:overworld
	Level spawn location: World: (83,65,333), Chunk: (at 3,4,13 in 5,20; contains blocks 80,0,320 to 95,255,335), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 6454003 game time, 2403206 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:446)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:598)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$418/1689458432.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1633333400 bytes (1557 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 6.1.1+74+master.966c698
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.1-32.0.108.jar fml TRANSFORMATIONSERVICE 
	FML: 32.0
	Forge: net.minecraftforge:32.0.108
	FML Language Providers: 
		javafml@32.0
		minecraft@1
	Mod List: 
		forge-1.16.1-32.0.108-client.jar Minecraft {minecraft@1.16.1 DONE}
		structurize-0.13.37-ALPHA.jar Structurize {structurize@0.13.37-ALPHA DONE}
		forge-1.16.1-32.0.108-universal.jar Forge {forge@32.0.108 DONE}
		minecolonies-0.13.145-ALPHA-universal.jar Minecolonies {minecolonies@0.13.145-ALPHA DONE}
	Launched Version: 1.16.1-forge-32.0.108
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 416.34, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla (incompatible), file/PureBDcraft More 3D Blocks MC116.zip (incompatible), file/PureBDcraft 128x MC116.zip (incompatible), mod_resources
	Current Language: English (United Kingdom)
	CPU: 4x Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz`

**Comment by MichalDolharz** [comment]
The problem was with fire. I checked how blacksmith lvl 3 should look like and it was supposed to have fired netherrack. I just fired it myself and reset citizens request.

**Comment by Raycoms** [comment]
fixed son
