### ISSUE TITLE
Builder AI Problem

### ISSUE THREAD

**Issue by xSlickZz** [ldtteam/minecolonies#5716]
### Prerequisites 

- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: minecolonies-0.13.213-ALPHA
- MineColonies Version: minecolonies-0.13.213-ALPHA
- Structurize Version: structurize-0.13.61

## Problem description
 I tried to upgrade a house (Lv1 -> Lv2) and my builder ran into a AI problem and he told me to report it.

### Notes or related things
 I also tried to upgrade another building but he still gets a AI error

`[17:05:27] [Render thread/INFO]: [CHAT] BuilderHenry X. Aylmer started building citizen2.
[17:07:03] [Server thread/WARN]: Statemachine for transition com.minecolonies.api.entity.ai.statemachine.AITarget@2d380cfb threw an exception:
java.lang.IllegalArgumentException: Parameters not allowed in this parameter set: [<parameter minecraft:origin>]
	at net.minecraft.loot.LootContext$Builder.func_216022_a(LootContext.java:193) ~[?:?]
	at net.minecraft.block.AbstractBlock.func_220076_a(AbstractBlock.java:210) ~[?:?]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215693_a(AbstractBlock.java:629) ~[?:?]
	at com.ldtteam.structurize.util.BlockUtils.getBlockDrops(BlockUtils.java:455) ~[?:0.13.61-ALPHA]
	at com.ldtteam.structurize.placement.StructurePlacer.handleBlockPlacement(StructurePlacer.java:294) ~[?:0.13.61-ALPHA]
	at com.ldtteam.structurize.placement.StructurePlacer.executeStructureStep(StructurePlacer.java:135) ~[?:0.13.61-ALPHA]
	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructure.structureStep(AbstractEntityAIStructure.java:284) ~[?:0.13.213-ALPHA]
	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructure$$Lambda$15325/1068008561.get(Unknown Source) ~[?:?]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:79) ~[?:0.13.213-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:148) [?:0.13.213-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:134) [?:0.13.213-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:126) [?:0.13.213-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:105) [?:0.13.213-ALPHA]
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:129) [?:0.13.213-ALPHA]
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) [?:?]
	at com.minecolonies.api.entity.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:223) [?:0.13.213-ALPHA]
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:681) [?:?]
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2410) [?:?]
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:487) [?:?]
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:126) [?:?]
	at com.minecolonies.api.entity.citizen.AbstractEntityCitizen.func_70636_d(AbstractEntityCitizen.java:378) [?:0.13.213-ALPHA]
	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:458) [?:0.13.213-ALPHA]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2157) [?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:299) [?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:604) [?:?]
	at net.minecraft.world.server.ServerWorld$$Lambda$14938/1265338079.accept(Unknown Source) [?:?]
	at net.minecraft.world.World.func_217390_a(World.java:596) [?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:397) [?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:852) [?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:788) [?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:81) [?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:643) [?:?]
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$14317/1519201224.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[17:07:03] [Server thread/ERROR]: Pausing Entity Henry X. Aylmer (com.minecolonies.coremod.job.Builder) at BlockPos{x=495, y=64, z=2263} for 100 Seconds because of error:
[17:07:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:344]: java.lang.IllegalArgumentException: Parameters not allowed in this parameter set: [<parameter minecraft:origin>]
[17:07:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:344]: 	at net.minecraft.loot.LootContext$Builder.func_216022_a(LootContext.java:193)
[17:07:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:344]: 	at net.minecraft.block.AbstractBlock.func_220076_a(AbstractBlock.java:210)
[17:07:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:344]: 	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_215693_a(AbstractBlock.java:629)
[17:07:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:344]: 	at com.ldtteam.structurize.util.BlockUtils.getBlockDrops(BlockUtils.java:455)
[17:07:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:344]: 	at com.ldtteam.structurize.placement.StructurePlacer.handleBlockPlacement(StructurePlacer.java:294)
[17:07:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:344]: 	at com.ldtteam.structurize.placement.StructurePlacer.executeStructureStep(StructurePlacer.java:135)
[17:07:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:344]: 	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructure.structureStep(AbstractEntityAIStructure.java:284)
[17:07:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:344]: 	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructure$$Lambda$15325/1068008561.get(Unknown Source)
[17:07:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:344]: 	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:79)
[17:07:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:344]: 	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:148)
[17:07:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:344]: 	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:134)
[17:07:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:344]: 	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:126)
[17:07:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:344]: 	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:105)
[17:07:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:344]: 	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:129)
[17:07:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:344]: 	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55)
[17:07:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:344]: 	at com.minecolonies.api.entity.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:223)
[17:07:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:344]: 	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:681)
[17:07:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:344]: 	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2410)
[17:07:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:344]: 	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:487)
[17:07:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:344]: 	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:126)
[17:07:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:344]: 	at com.minecolonies.api.entity.citizen.AbstractEntityCitizen.func_70636_d(AbstractEntityCitizen.java:378)
[17:07:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:344]: 	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:458)
[17:07:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:344]: 	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2157)
[17:07:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:344]: 	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:299)
[17:07:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:344]: 	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:604)
[17:07:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:344]: 	at net.minecraft.world.server.ServerWorld$$Lambda$14938/1265338079.accept(Unknown Source)
[17:07:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:344]: 	at net.minecraft.world.World.func_217390_a(World.java:596)
[17:07:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:344]: 	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:397)
[17:07:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:344]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:852)
[17:07:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:344]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:788)
[17:07:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:344]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:81)
[17:07:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:344]: 	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:643)
[17:07:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:344]: 	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230)
[17:07:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:344]: 	at net.minecraft.server.MinecraftServer$$Lambda$14317/1519201224.run(Unknown Source)
[17:07:03] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:344]: 	at java.lang.Thread.run(Thread.java:745)
[latest.log.txt](https://github.com/ldtteam/minecolonies/files/5178278/latest.log.txt)
`

---
## Viewers

* Add a thumbs-up to the issue to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
update to latest
