### ISSUE TITLE
Builder will not place torches -

### ISSUE THREAD

**Issue by dtupitza** [ldtteam/minecolonies#5763]
### Prerequisites 

- [X ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [X ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 
- Minecraft Version: minecraft_server.1.15.2.jar
- MineColonies Version: minecolonies-0.13.247-ALPHA-universal.jar Now running: minecolonies-0.13.268-ALPHA-universal.jar
- Structurize Version: structurize-0.13.64-ALPHA.jar
- Related Mods and their Versions:

## Expected behavior
Last step in build process - builder will places torches and mark done.

## Actual behavior
Builder will stand next to where the torch is and continue to just wave their hands as if unable to place torch.  If building is upgraded and torches are already complete, the builder will just stand there swinging their hands never completing anything.

## Steps to reproduce the issue

While I'm not able to link what the original cause was, building any new structure or upgrading any structure will cause this to become apparent

### Logs

[11Sep2020 14:40:14.409] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.lang.NullPointerException: null
	at com.minecolonies.coremod.colony.buildings.AbstractBuilding.onRequestedRequestComplete(AbstractBuilding.java:1599) ~[?:0.13.247-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.requesters.BuildingBasedRequester.lambda$onRequestedRequestComplete$0(BuildingBasedRequester.java:88) ~[?:0.13.247-ALPHA]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_221]
	at com.minecolonies.coremod.colony.requestsystem.requesters.BuildingBasedRequester.onRequestedRequestComplete(BuildingBasedRequester.java:88) ~[?:0.13.247-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.onRequestCompleted(RequestHandler.java:307) ~[?:0.13.247-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.manager.StandardRequestManager.updateRequestState(StandardRequestManager.java:303) ~[?:0.13.247-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.onRequestOverruled(RequestHandler.java:364) ~[?:0.13.247-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.manager.StandardRequestManager.updateRequestState(StandardRequestManager.java:307) ~[?:0.13.247-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.manager.StandardRequestManager.overruleRequest(StandardRequestManager.java:346) ~[?:0.13.247-ALPHA]
	at com.minecolonies.coremod.network.messages.server.colony.UpdateRequestStateMessage.onExecute(UpdateRequestStateMessage.java:85) ~[?:0.13.247-ALPHA]
	at com.minecolonies.coremod.network.messages.server.AbstractColonyServerMessage.onExecute(AbstractColonyServerMessage.java:144) ~[?:0.13.247-ALPHA]
	at com.minecolonies.coremod.network.NetworkChannel.lambda$null$3(NetworkChannel.java:237) ~[?:0.13.247-ALPHA]
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[?:?]
	at com.minecolonies.coremod.network.NetworkChannel.lambda$registerMessage$4(NetworkChannel.java:237) ~[?:0.13.247-ALPHA]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[?:?]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_221]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:78) ~[?:?]
	at java.util.Optional.map(Unknown Source) ~[?:1.8.0_221]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:78) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1279) ~[?:?]
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?]
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) [?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:694) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:641) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]

[latest.log](https://github.com/ldtteam/minecolonies/files/5211069/latest.log)

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
shouldn't happen in the latest anymore

**Comment by dtupitza** [comment]
> shouldn't happen in the latest anymore

This is still happening.  Now running: minecolonies-0.13.268-ALPHA-universal.jar

**Comment by Raycoms** [comment]
There is a removal step before the torches, are you sure you are patient
enough?

**Comment by dtupitza** [comment]
I noticed the removal step, as he removed the doors.  But we're still at
the same place.  I'll attempt to start a new building from the beginning
and get the error to generate again.  But the builder has been as the build
step for over 3 hours.

**Comment by Raycoms** [comment]
and you are on the latest alpha?

**Comment by Raycoms** [comment]
is there any exception in the log? Are you using any torch mods?

**Comment by dtupitza** [comment]
Yes, I snagged the latest alpha build the other day.

**Comment by dtupitza** [comment]
No mod for torches.  I've built half a city so far without issues and every
colony works except for one.  For whatever reason the builder doesn't place
flowers or torches.  (Noticed the flowers on a different building, just not
sure which get placed last).

**Comment by Raycoms** [comment]
Very strange, never ran into this issue, and no one on our servers either. Any modded block within this area?

**Comment by dtupitza** [comment]
There is no modded block in the area.  I've even started different
buildings in different areas and they all have the same issue.  This only
happens in one colony of 5 on the server.

**Comment by Raycoms** [comment]
very strange

**Comment by dtupitza** [comment]
I've started a new building, and the worker completed all steps again but
fails to complete the torch process.  While he does have the torches in his
inventory, he'll swing his arms around like he's attempting to place but
never does.  I'll let him sit here fora  few hours.  This time I did not
receive any errors like I previously received when I first opened the bug
report.

**Comment by LucidDreamer0322** [comment]
This happens ~20% of the time for me.  My observations is that whatever step is supposed to happen prior to torch placement is hanging, this verdict based on finishing a new build hangs on torch placement, waving hands as if placing torches, but no torches are being placed. the issue might also be the way the mod tells the builder to "equip" items to be placed. when it happens the builder isn't actually holding torches, but is trying to place them, this theory is based on me punching them when this happens to trigger their "flee" state, which fixes the issue usually within 2-5 reset attempts.

**Comment by ravenbuilder934** [comment]
The citizens _look_ like they're holding the last thing they held, even if they aren't anymore.
