### ISSUE TITLE
Unable to stock Racks in warehouse

### ISSUE THREAD

**Issue by Aduis1210** [ldtteam/minecolonies#5910]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.15.2
- MineColonies Version: minecolonies-0.13.335-ALPHA-universal
- Structurize Version: structurize-0.13.94-ALPHA-universal
- Related Mods and their Versions: 

## Expected behaviour
The ability to deposit in the warehouse racks

## Actual behaviour
Its like a ghost of the item goes in, then when i exit out they reappear in my inventory.

## Steps to reproduce the issue

1. Place item in rack
2. exit from window
3. poof - items back

### Logs

- latest.log: https://paste.ee/p/Wl1M1

### Notes

Huge error shows in logs with each attempt.
Unsure if its a conflict, could you advise?

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
is this in smp?

**Comment by Aduis1210** [comment]
Single player - do you need me to send anything?

**Comment by Aduis1210** [comment]
[m[1;31m[14:03:22] [Server thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Server
java.lang.RuntimeException: Slot 51 not in valid range - [0,27)
	at net.minecraftforge.items.ItemStackHandler.validateSlotIndex(ItemStackHandler.java:221) ~[?:?] {re:classloading}
	at net.minecraftforge.items.ItemStackHandler.getStackInSlot(ItemStackHandler.java:73) ~[?:?] {re:classloading}
	at com.minecolonies.api.inventory.container.ContainerRack.func_184996_a(ContainerRack.java:140) ~[?:0.13.335-ALPHA] {re:classloading}
	at net.minecraft.network.play.ServerPlayNetHandler.func_147351_a(ServerPlayNetHandler.java:1135) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:connection.ServerPlayNetHandlerMixin,pl:mixin:A}
	at net.minecraft.network.play.client.CClickWindowPacket.func_148833_a(CClickWindowPacket.java:34) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CClickWindowPacket.func_148833_a(CClickWindowPacket.java:12) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?] {re:mixin,re:classloading}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:694) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:641) [?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261] {}
MultiMC: Log upload triggered at: 12 Oct 2020 14:04:22 +0100

**Comment by Aduis1210** [comment]
its that error every time

**Comment by Aduis1210** [comment]
will this also fix the request system updating when you place items in their "huts" inventory?

**Comment by Aduis1210** [comment]
in colonists "huts" apologies

**Comment by Raycoms** [comment]
ye

**Comment by Nikademus** [comment]
This is happening in 16.3 as well

**Comment by Aduis1210** [comment]
its being looked into
