### ISSUE TITLE
1.15 - Postbox & stash problems

### ISSUE THREAD

**Issue by DrFlash99** [ldtteam/minecolonies#5946]
First seen on 0.13.350, verified to still exist on 0.13.359.

Upon placing postbox:
[12:15:46] [Server thread/INFO]: Colony 1 - new AbstractBuilding for class net.minecraft.block.BlockState at BlockPos{x=815, y=69, z=270}
[12:15:46] [Server thread/WARN]: File jar resolve FAILED for: schematics/medievalspruce/postbox1.blueprint
[12:15:46] [Render thread/WARN]: Block entity invalid: minecolonies:colonybuilding @ BlockPos{x=815, y=69, z=270}
[12:15:46] [Server thread/WARN]: Block entity invalid: minecolonies:colonybuilding @ BlockPos{x=815, y=69, z=270}
[12:15:50] [Server thread/INFO]: Colony 1 - new AbstractBuilding for class net.minecraft.block.BlockState at BlockPos{x=816, y=69, z=270}

Upon putting items in stash:
[12:15:50] [Server thread/WARN]: File jar resolve FAILED for: schematics/medievalspruce/stash1.blueprint
[12:15:57] [Render thread/INFO]: [CHAT] Courier Harper I. Coffin will come along and do a pickup shortly!
[12:15:58] [Server thread/WARN]: File jar resolve FAILED for: schematics/medievalspruce/stash1.blueprint

upon requesting items from postbox:
[12:16:06] [Server thread/WARN]: File jar resolve FAILED for: schematics/medievalspruce/postbox1.blueprint

In both cases an npc does not actually come by and pick up / deliver items.

**Comment by Raycoms** [comment]
It does take a while until the dman comes around.

**Comment by DrFlash99** [comment]
> 
> 
> It does take a while until the dman comes around.

While your statement is true, it should not take several in-game days. -- before .350 it took a few minutes for them to come around.

**Comment by Raycoms** [comment]
@someaddons I guess we should make it such that when a request bypasses another because of a good number it should also be increased in priority. I think that what causes a bti of starvation atm

**Comment by DrFlash99** [comment]
My NPC also complains about an AI error.

[12:23:43] [Server thread/ERROR]: Pausing Entity Harper I. Coffin (com.minecolonies.coremod.job.Deliveryman) at BlockPos{x=815, y=69, z=271} for 100 Seconds because of error:
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]: java.lang.NullPointerException
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at com.minecolonies.coremod.colony.buildings.AbstractBuilding.onRequestedRequestComplete(AbstractBuilding.java:1623)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at com.minecolonies.coremod.colony.requestsystem.requesters.BuildingBasedRequester.lambda$onRequestedRequestComplete$0(BuildingBasedRequester.java:88)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at com.minecolonies.coremod.colony.requestsystem.requesters.BuildingBasedRequester$$Lambda$13953/534022357.accept(Unknown Source)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at java.util.Optional.ifPresent(Optional.java:159)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at com.minecolonies.coremod.colony.requestsystem.requesters.BuildingBasedRequester.onRequestedRequestComplete(BuildingBasedRequester.java:88)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.onRequestCompleted(RequestHandler.java:307)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at com.minecolonies.coremod.colony.requestsystem.management.manager.StandardRequestManager.updateRequestState(StandardRequestManager.java:303)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.onRequestCompleted(RequestHandler.java:329)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at com.minecolonies.coremod.colony.requestsystem.management.manager.StandardRequestManager.updateRequestState(StandardRequestManager.java:303)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.onRequestResolved(RequestHandler.java:293)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at com.minecolonies.coremod.colony.requestsystem.management.manager.StandardRequestManager.updateRequestState(StandardRequestManager.java:299)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at com.minecolonies.coremod.colony.jobs.JobDeliveryman.finishRequest(JobDeliveryman.java:266)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at com.minecolonies.coremod.entity.ai.citizen.deliveryman.EntityAIWorkDeliveryman.deliver(EntityAIWorkDeliveryman.java:449)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at com.minecolonies.coremod.entity.ai.citizen.deliveryman.EntityAIWorkDeliveryman$$Lambda$12769/504465137.get(Unknown Source)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:79)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:148)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:134)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:126)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:105)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:129)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at com.minecolonies.api.entity.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:222)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:595)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2262)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:462)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:159)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at com.minecolonies.api.entity.citizen.AbstractEntityCitizen.func_70636_d(AbstractEntityCitizen.java:370)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:460)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2104)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:600)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at net.minecraft.world.server.ServerWorld$$Lambda$11894/642469951.accept(Unknown Source)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at net.minecraft.world.World.func_217390_a(World.java:536)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:401)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
[12:23:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:343]:     at java.lang.Thread.run(Thread.java:745)
[12:23:43] [Server thread/WARN]: File jar resolve FAILED for: schematics/medievalspruce/postbox1.blueprint

**Comment by someaddons** [comment]
this is no issue, follow the template
