### ISSUE TITLE
1.10.2-Build Tool Crash w/ Valkyrien Warfare

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/minecolonies#604]
### Minecolonies version

Version 0.6.2849, Forge 2221

### Valkyrien Warfare version

[Version 0.8.7b](https://minecraft.curseforge.com/projects/valkyrien-warfare)

### Expected behavior

- No crash while changing the decoration type.

### Actual behaviour

- The build tool crashes in the decorations tab once I click the button that says _walls_.
- The crash log also mentions something about the Valkyrien Warfare Mod.

### Steps to reproduce the problem

1. Right-Click the build tool.
2. Click the button that takes you to the decoration tab.
3. Press the button that says _walls_.
4. Crash

**Comment by marvin-bitterlich** [comment]
crashlog please

**Comment by WenXin20** [comment]
Forgot about that. I'll be able to post it later today.

**Comment by WenXin20** [comment]
Here is the crash reports from my single player world, it generated both of these reports:
[Crash Log-Server](http://pastebin.com/Pjgk2gwE)
[Crash Log-Client](http://pastebin.com/mYffQne6)

**Comment by marvin-bitterlich** [comment]
```
java.lang.IllegalStateException: Colony's world does not match the event.
    at com.minecolonies.coremod.colony.Colony.onWorldTick(Colony.java:794)
    at com.minecolonies.coremod.colony.ColonyManager.lambda$onWorldTick$47(ColonyManager.java:622)
    at com.minecolonies.coremod.colony.ColonyManager$$Lambda$622/1819823123.accept(Unknown Source)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
    at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
    at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1612)
    at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
    at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
    at com.minecolonies.coremod.colony.ColonyManager.onWorldTick(ColonyManager.java:622)
    at com.minecolonies.coremod.event.FMLEventHandler.onWorldTick(FMLEventHandler.java:50)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_552_FMLEventHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:269)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:718)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by WenXin20** [comment]
Does this mean there are invalid scans in the folder?

**Comment by Raycoms** [comment]
No, there is some mix up with the worlds. Does this mod add something like
a custom world?

2017-02-24 15:17 GMT-03:00 WenXin20 <notifications@github.com>:

**Comment by WenXin20** [comment]
No, it is a mod that can make airships out of any block and gives them custom physics. Though maybe it simulates a fake world in order to make the ships?

**Comment by Raycoms** [comment]
at
ValkyrienWarfareBase.PhysicsManagement.DimensionPhysObjectManager.getObjectManagingPos(DimensionPhysObjectManager.java:89)
at
ValkyrienWarfareBase.CoreMod.CallRunner.onGetDistanceSq(CallRunner.java:309)
at
net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:122)

The coremod overwrites some of our methods which we can't call then
probably.

2017-02-24 15:50 GMT-03:00 WenXin20 <notifications@github.com>:

**Comment by Tri0de** [comment]
I'm a developer of Valkyrien Warfare and I found that the crash was because of a World getting passed through that had World.getChunkProvider() returning null. I've since added a != null check which does the trick in fixing it. I'm guessing this is for a dummy world that is used by MineColonies, but I'm not familiar enough with the code to know for sure.

Anyways, its since been fixed.
