### ISSUE TITLE
My AI has run into an issue

### ISSUE THREAD

**Issue by McArgent** [ldtteam/minecolonies#6072]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.3
- MineColonies Version: 0.13.437-RELEASE
- Structurize Version: 0.13.96-ALPHA
- Related Mods and their Versions: 

## Expected behavior
Actually, it's pretty impressive that workers report bugs in game.  I'm impressed.  
AI shouldn't have issues. 

## Actual behavior
Playing along when one of my delivery guys popped up the critical wants bubble.  Checked it, and it told me to report this to your team.  Sorry if this is a duplicate.  

## Steps to reproduce the issue
I hope the attached log will help with that.  

### Logs

- latest.log: <script src="https://gist.github.com/McArgent/28cd129bfec3130534a83aa381760593.js"></script>
- crashlog: 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Aduis1210** [comment]
[m[1;31m[19:50:17] [Server thread/ERROR] [minecolonies/]: Pausing Entity Reynold S. Gardiner (com.minecolonies.coremod.job.Deliveryman) at BlockPos{x=1522, y=69, z=-4478} for 100 Seconds because of error:
[m[32m[19:50:17] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: java.lang.NullPointerException
[m[32m[19:50:17] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at com.minecolonies.coremod.colony.buildings.AbstractBuilding.onRequestedRequestCancelled(AbstractBuilding.java:1645)
[m[32m[19:50:17] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at com.minecolonies.coremod.colony.requestsystem.requesters.BuildingBasedRequester.lambda$onRequestedRequestCancelled$1(BuildingBasedRequester.java:94)
[m[32m[19:50:17] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at java.util.Optional.ifPresent(Unknown Source)
[m[32m[19:50:17] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at com.minecolonies.coremod.colony.requestsystem.requesters.BuildingBasedRequester.onRequestedRequestCancelled(BuildingBasedRequester.java:94)
[m[32m[19:50:17] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.processDirectCancellationAndNotifyRequesterOf(RequestHandler.java:424)
[m[32m[19:50:17] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.onRequestCancelledDirectly(RequestHandler.java:415)
[m[32m[19:50:17] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.onRequestCancelled(RequestHandler.java:391)
[m[32m[19:50:17] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at com.minecolonies.coremod.colony.requestsystem.management.manager.StandardRequestManager.updateRequestState(StandardRequestManager.java:311)
[m[32m[19:50:17] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at com.minecolonies.coremod.colony.jobs.JobDeliveryman.finishRequest(JobDeliveryman.java:292)
[m[32m[19:50:17] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at com.minecolonies.coremod.entity.ai.citizen.deliveryman.EntityAIWorkDeliveryman.pickup(EntityAIWorkDeliveryman.java:171)
[m[32m[19:50:17] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:79)
[m[32m[19:50:17] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:148)
[m[32m[19:50:17] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:134)
[m[32m[19:50:17] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:126)
[m[32m[19:50:17] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:105)
[m[32m[19:50:17] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:129)
[m[32m[19:50:17] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55)
[m[32m[19:50:17] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at com.performant.coremod.entity.ai.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:368)
[m[32m[19:50:17] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:595)
[m[32m[19:50:17] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2262)
[m[32m[19:50:17] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:1310)
[m[32m[19:50:17] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:159)
[m[32m[19:50:17] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at com.minecolonies.api.entity.citizen.AbstractEntityCitizen.func_70636_d(AbstractEntityCitizen.java:370)
[m[32m[19:50:17] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:460)
[m[32m[19:50:17] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2104)
[m[32m[19:50:17] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274)
[m[32m[19:50:17] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:600)
[m[32m[19:50:17] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at net.minecraft.world.World.func_217390_a(World.java:536)
[m[32m[19:50:17] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:401)
[m[32m[19:50:17] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849)
[m[32m[19:50:17] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
[m[32m[19:50:17] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114)
[m[32m[19:50:17] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
[m[32m[19:50:17] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at java.lang.Thread.run(Unknown Source)

**Comment by Aduis1210** [comment]
Error im getting @Raycoms

**Comment by xinpig** [comment]
Having same issue on 1.15.2 Enigmatica 5

[14Nov2020 23:54:19.803] [Server thread/WARN] [minecolonies/]: Statemachine for transition com.minecolonies.api.entity.ai.statemachine.AITarget@23622c81 threw an exception:
java.lang.NullPointerException: null
	at com.minecolonies.coremod.colony.buildings.AbstractBuilding.onRequestedRequestComplete(AbstractBuilding.java:1630) ~[?:0.13.415-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.requesters.BuildingBasedRequester.lambda$onRequestedRequestComplete$0(BuildingBasedRequester.java:88) ~[?:0.13.415-ALPHA]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_171]
	at com.minecolonies.coremod.colony.requestsystem.requesters.BuildingBasedRequester.onRequestedRequestComplete(BuildingBasedRequester.java:88) ~[?:0.13.415-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.onRequestCompleted(RequestHandler.java:307) ~[?:0.13.415-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.manager.StandardRequestManager.updateRequestState(StandardRequestManager.java:303) ~[?:0.13.415-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.onRequestResolved(RequestHandler.java:293) ~[?:0.13.415-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.manager.StandardRequestManager.updateRequestState(StandardRequestManager.java:299) ~[?:0.13.415-ALPHA]
	at com.minecolonies.coremod.colony.jobs.JobDeliveryman.finishRequest(JobDeliveryman.java:290) ~[?:0.13.415-ALPHA]
	at com.minecolonies.coremod.entity.ai.citizen.deliveryman.EntityAIWorkDeliveryman.pickup(EntityAIWorkDeliveryman.java:179) ~[?:0.13.415-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:79) ~[?:0.13.415-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:148) ~[?:0.13.415-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:134) ~[?:0.13.415-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:126) ~[?:0.13.415-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:105) ~[?:0.13.415-ALPHA]
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:129) ~[?:0.13.415-ALPHA]
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?]
	at com.minecolonies.api.entity.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:222) ~[?:0.13.415-ALPHA]
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:595) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2262) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:462) ~[?:?]
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:159) ~[?:?]
	at com.minecolonies.api.entity.citizen.AbstractEntityCitizen.func_70636_d(AbstractEntityCitizen.java:370) ~[?:0.13.415-ALPHA]
	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:460) ~[?:0.13.415-ALPHA]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2104) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:600) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:536) [?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:401) [?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849) [?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330) [?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) [?:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
[14Nov2020 23:54:19.805] [Server thread/ERROR] [minecolonies/]: Pausing Entity Sybil U. Crawley (com.minecolonies.coremod.job.Deliveryman) at BlockPos{x=-2353, y=67, z=-2270} for 100 Seconds because of error:
[14Nov2020 23:54:19.806] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: java.lang.NullPointerException
[14Nov2020 23:54:19.806] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at com.minecolonies.coremod.colony.buildings.AbstractBuilding.onRequestedRequestComplete(AbstractBuilding.java:1630)
[14Nov2020 23:54:19.806] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at com.minecolonies.coremod.colony.requestsystem.requesters.BuildingBasedRequester.lambda$onRequestedRequestComplete$0(BuildingBasedRequester.java:88)
[14Nov2020 23:54:19.806] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at java.util.Optional.ifPresent(Unknown Source)
[14Nov2020 23:54:19.807] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at com.minecolonies.coremod.colony.requestsystem.requesters.BuildingBasedRequester.onRequestedRequestComplete(BuildingBasedRequester.java:88)
[14Nov2020 23:54:19.807] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.onRequestCompleted(RequestHandler.java:307)
[14Nov2020 23:54:19.807] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at com.minecolonies.coremod.colony.requestsystem.management.manager.StandardRequestManager.updateRequestState(StandardRequestManager.java:303)
[14Nov2020 23:54:19.807] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.onRequestResolved(RequestHandler.java:293)
[14Nov2020 23:54:19.807] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at com.minecolonies.coremod.colony.requestsystem.management.manager.StandardRequestManager.updateRequestState(StandardRequestManager.java:299)
[14Nov2020 23:54:19.807] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at com.minecolonies.coremod.colony.jobs.JobDeliveryman.finishRequest(JobDeliveryman.java:290)
[14Nov2020 23:54:19.807] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at com.minecolonies.coremod.entity.ai.citizen.deliveryman.EntityAIWorkDeliveryman.pickup(EntityAIWorkDeliveryman.java:179)
[14Nov2020 23:54:19.807] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:79)
[14Nov2020 23:54:19.808] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:148)
[14Nov2020 23:54:19.808] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:134)
[14Nov2020 23:54:19.808] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:126)
[14Nov2020 23:54:19.808] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:105)
[14Nov2020 23:54:19.808] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:129)
[14Nov2020 23:54:19.808] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55)
[14Nov2020 23:54:19.808] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at com.minecolonies.api.entity.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:222)
[14Nov2020 23:54:19.808] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:595)
[14Nov2020 23:54:19.809] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2262)
[14Nov2020 23:54:19.809] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:462)
[14Nov2020 23:54:19.809] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:159)
[14Nov2020 23:54:19.809] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at com.minecolonies.api.entity.citizen.AbstractEntityCitizen.func_70636_d(AbstractEntityCitizen.java:370)
[14Nov2020 23:54:19.809] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:460)
[14Nov2020 23:54:19.809] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2104)
[14Nov2020 23:54:19.809] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274)
[14Nov2020 23:54:19.809] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:600)
[14Nov2020 23:54:19.810] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at net.minecraft.world.World.func_217390_a(World.java:536)
[14Nov2020 23:54:19.810] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:401)
[14Nov2020 23:54:19.810] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849)
[14Nov2020 23:54:19.810] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330)
[14Nov2020 23:54:19.810] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
[14Nov2020 23:54:19.810] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
[14Nov2020 23:54:19.810] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:345]: 	at java.lang.Thread.run(Unknown Source)
