### ISSUE TITLE
"Missing AI transition for state" after restarting builder

### ISSUE THREAD

**Issue by Spongman** [ldtteam/minecolonies#6258]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

- Minecraft Version: 1.15.2
- MineColonies Version: minecolonies-0.13.512-ALPHA-universal
- Structurize Version: structurize-0.13.94-ALPHA-universal
- 
my builder got stuck doing nothing. i paused it in the building hut and then clicked the 'restart' button that appeared.

````
[m[32m[00:38:46] [Render thread/INFO] [minecraft/NewChatGui]: [CHAT] [00:38:46] Restart for citizen Alaina S. Gray scheduled.
[m[1;31m[00:38:47] [Server thread/ERROR] [minecolonies/]: Pausing Entity Alaina S. Gray (com.minecolonies.coremod.job.Builder) at BlockPos{x=-424, y=74, z=120} for 100 Seconds because of error:
[m[32m[00:38:47] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:349]: java.lang.RuntimeException: Missing AI transition for state: START_WORKING
[m[32m[00:38:47] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:349]: 	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:186)
[m[32m[00:38:47] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:349]: 	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:149)
[m[32m[00:38:47] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:349]: 	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:129)
[m[32m[00:38:47] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:349]: 	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:100)
[m[32m[00:38:47] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:349]: 	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:129)
[m[32m[00:38:47] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:349]: 	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55)
[m[32m[00:38:47] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:349]: 	at com.minecolonies.api.entity.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:222)
[m[32m[00:38:47] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:349]: 	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:595)
[m[32m[00:38:47] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:349]: 	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2262)
[m[32m[00:38:47] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:349]: 	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:462)
[m[32m[00:38:47] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:349]: 	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:159)
[m[32m[00:38:47] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:349]: 	at com.minecolonies.api.entity.citizen.AbstractEntityCitizen.func_70636_d(AbstractEntityCitizen.java:370)
[m[32m[00:38:47] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:349]: 	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:460)
[m[32m[00:38:47] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:349]: 	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2104)
[m[32m[00:38:47] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:349]: 	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274)
[m[32m[00:38:47] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:349]: 	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:600)
[m[32m[00:38:47] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:349]: 	at net.minecraft.world.World.func_217390_a(World.java:536)
[m[32m[00:38:47] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:349]: 	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:401)
[m[32m[00:38:47] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:349]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849)
[m[32m[00:38:47] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:349]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
[m[32m[00:38:47] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:349]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:114)
[m[32m[00:38:47] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:349]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
[m[32m[00:38:47] [Server thread/INFO] [STDERR/]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:349]: 	at java.lang.Thread.run(Thread.java:748)
[m[32m[00:38:47] [Render thread/INFO] [minecraft/NewChatGui]: [CHAT] [00:38:47] Citizen Alaina S. Gray succesfully restarted.
````

**Comment by ravenbuilder934** [comment]
Please update and check if this is fixed.
