### ISSUE TITLE
Selecting Any Decisions Crashes Game

### ISSUE THREAD

**Issue by newbchu** [ldtteam/minecolonies#6298]
### Prerequisites 

- [ x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.537-ALPHA-universal
- Structurize Version: structurize-0.13.104-ALPHA-universal
- Related Mods and their Versions:

## Expected behavior

Selecting Any Decisions given by the AI Crashes Game

## Actual behavior

![image](https://user-images.githubusercontent.com/59229016/103169741-7bc9d680-4879-11eb-8136-2bdf9190de2c.png)
![image](https://user-images.githubusercontent.com/59229016/103169830-3e197d80-487a-11eb-8404-7dc39ca245b7.png)

## Steps to reproduce the issue

1. Load game
2. Talk to civilian
3. Select any choices given
4. Game Crash

### Logs

- latest.log: https://gist.github.com/newbchu/e8a03c524ab980964bc61f36dd8a7dc9
- crashlog: https://gist.github.com/newbchu/e8a03c524ab980964bc61f36dd8a7dc9

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by someaddons** [comment]
it seems to crash on displaying the next interaction with a tool, you likely got a mod installed which doesnt specify tools correctly

**Comment by newbchu** [comment]
> it seems to crash on displaying the next interaction with a tool, you likely got a mod installed which doesnt specify tools correctly

Okay so simply means I just remove the mod? Is this like JEI or libraries?

**Comment by Raycoms** [comment]
No, it's a mod that adds some kind of tool, removing the mod will fix it.

**Comment by Bidgam** [comment]
Did you identify the tool Minecolonies is trying to display newbchu? I'm getting the same error and the mod crashes the server before I can figure out what tool/item it may be.

MC mod devs, can we not have the game crash when an incompatible item is viewed? Anything but a hard crash... I can't tell which item it is and if it's possible to remove the mod or remove the item (or let the builder select another item...)

Thanks

**Comment by Bidgam** [comment]
Here is my error log in case it helps in providing a preventive measure on the MC side, or at least identifying which mod might be not playing nice. Thanks for taking a look:

`java.lang.NullPointerException: Ticking screen
	at com.minecolonies.api.colony.requestsystem.requestable.Tool$$Lambda$29301/463895430.apply(Unknown Source) ~[?:?] {}
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_51] {}
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1540) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_51] {}
	at com.minecolonies.api.colony.requestsystem.requestable.Tool.getToolClasses(Tool.java:216) ~[?:0.13.525-ALPHA] {re:classloading}
	at com.minecolonies.api.colony.requestsystem.requestable.Tool.matches(Tool.java:189) ~[?:0.13.525-ALPHA] {re:classloading}
	at com.minecolonies.coremod.colony.requestsystem.requests.AbstractRequest$$Lambda$29300/2023414797.test(Unknown Source) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_51] {}
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_51] {}
	at com.minecolonies.coremod.colony.requestsystem.requests.AbstractRequest.getDisplayStacks(AbstractRequest.java:455) ~[?:0.13.525-ALPHA] {re:classloading}
	at com.minecolonies.coremod.client.gui.WindowClipBoard.lambda$fillList$1(WindowClipBoard.java:156) ~[?:0.13.525-ALPHA] {re:classloading}
	at com.minecolonies.coremod.client.gui.WindowClipBoard$$Lambda$29293/1164135349.apply(Unknown Source) ~[?:?] {}
	at com.ldtteam.blockout.views.ScrollingList$1.updateElement(ScrollingList.java:63) ~[?:0.13.104-ALPHA] {re:classloading}
	at com.ldtteam.blockout.views.ScrollingListContainer.refreshElementPanes(ScrollingListContainer.java:54) ~[?:0.13.104-ALPHA] {re:classloading}
	at com.ldtteam.blockout.views.ScrollingList.refreshElementPanes(ScrollingList.java:79) ~[?:0.13.104-ALPHA] {re:classloading}
	at com.ldtteam.blockout.views.ScrollingList.setDataProvider(ScrollingList.java:71) ~[?:0.13.104-ALPHA] {re:classloading}
	at com.ldtteam.blockout.views.ScrollingList.setDataProvider(ScrollingList.java:52) ~[?:0.13.104-ALPHA] {re:classloading}
	at com.minecolonies.coremod.client.gui.WindowClipBoard.fillList(WindowClipBoard.java:146) ~[?:0.13.525-ALPHA] {re:classloading}
	at com.minecolonies.coremod.client.gui.WindowClipBoard.onOpened(WindowClipBoard.java:140) ~[?:0.13.525-ALPHA] {re:classloading}
	at com.ldtteam.blockout.BOScreen.func_231023_e_(BOScreen.java:242) ~[?:0.13.104-ALPHA] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$runTick$20(Minecraft.java:1450) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:APP:valhelsia_tweaks.mixins.json:RemoveExperimentalSettingsWarningMixin,pl:mixin:APP:valhelsia_tweaks.mixins.json:DisplayMemoryWarningScreenMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$20120/1201893446.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1449) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:APP:valhelsia_tweaks.mixins.json:RemoveExperimentalSettingsWarningMixin,pl:mixin:APP:valhelsia_tweaks.mixins.json:DisplayMemoryWarningScreenMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:APP:valhelsia_tweaks.mixins.json:RemoveExperimentalSettingsWarningMixin,pl:mixin:APP:valhelsia_tweaks.mixins.json:DisplayMemoryWarningScreenMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:APP:valhelsia_tweaks.mixins.json:RemoveExperimentalSettingsWarningMixin,pl:mixin:APP:valhelsia_tweaks.mixins.json:DisplayMemoryWarningScreenMixin,pl:mixin:APP:assets/botania/botania.mixins.json:AccessorMinecraft,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.13.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$477/1916559238.call(Unknown Source) [forge-1.16.4-35.1.13.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {re:classloading}`

**Comment by Bidgam** [comment]
Additional note, the builder asked for a house to live in (he didn't have one yet because of this issue) and even though I hit esc immediately after seeing that message (I didn't press any buttons on his menu), it still crashed the game.

Noting that the other few colonists menus work fine, including the others asking for housing.

**Comment by Bidgam** [comment]
I'm removing mod after mod to see what it may be, but either Minecolonies is stuck on asking for something even if it's no longer there, or it's a mod that used to be compatible (from Valhelsia) and now is not.

**Comment by gattsuru** [comment]
Which Valhelsia version are you running?  I'll see if I can track it down.

**Comment by Bidgam** [comment]
Their latest, 3.1.0. Let me know if I can help in any other way. I'll continue to sift through these mods and see what might be the root cause. To note, I've updated Minecolonies since Valhelsia was installed.

Is there no way to identify at least the item or something that gives a clue as to the source? That would obviously help a tremendous amount.

Also, I assume (carefully) that if I remove a mod that's causing the issue, that Minecolonies interface will clear whatever item it's trying to load...

**Comment by Moleculor** [comment]
> Is there no way to identify at least the item or something that gives a clue as to the source? That would obviously help a tremendous amount.

Run a separate copy of the world and a binary search of the mods. Rip out half the mods, see if it still happens. If it does, rip out half of those that remain. If it *doesn't*, put half back and see if it happens. If it does, you know it's in the half you put back. Take half of that out, repeat.

**Comment by Bidgam** [comment]
Will do, I'm in process on that now. Thanks Moleculor.

**Comment by gattsuru** [comment]
Valhesia 3 also is up to 3.1.2.  That version did not appear to be crashing on the builder, at least in a quick test.  Still would like to know a mod that does/did it.

**Comment by Bidgam** [comment]
Will let you know as soon as I complete going down the list. It's getting pretty thin, but something is jamming up the builder.

**Comment by Bidgam** [comment]
It's apparently versatileportals-1.16.4-2.2.0.2-forge

I have no idea why it has anything to do with the builder wanting a shovel, but there you have it... any insight on the possible link so I (and others) can avoid it in the future would be appreciated. I'm no coder ;).

P.S. - When I removed the mod, I noticed the portal to the nether was somehow still active with the special mod effect. I did not step through to confirm. I will be asking the mod dev how this is possible.

Thanks

**Comment by Moleculor** [comment]
So it's #6286.

**Comment by ravenbuilder934** [comment]
Not us then

**Comment by Bidgam** [comment]
Confirmed, thanks guys.
