### ISSUE TITLE
Unable to upgrade decorations/asian/bathhouse

### ISSUE THREAD

**Issue by lucasvanhalst** [ldtteam/minecolonies#6306]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
used version:  `minecolonies-0.13.531-ALPHA-universal`
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: minecolonies-0.13.531-ALPHA-universal
- Structurize Version: structurize-0.13.104-ALPHA-universal
- Related Mods and their Versions: https://www.curseforge.com/minecraft/modpacks/all-the-mods-6/relations/dependencies

## Expected behavior

You should be able to upgrade the 'asian bathhouse' decoration

## Actual behavior

An error occurs the moment you press the 'upgrade' button:
```java
[27Dec2020 21:06:54.548] [Server thread/WARN] [structurize/]: File jar resolve FAILED for: schematics//schematics/decorations/asian/bathhouse2.blueprint
[27Dec2020 21:06:54.551] [Server thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Server
java.lang.NullPointerException: null
	at com.minecolonies.coremod.util.ColonyUtils.calculateCorners(ColonyUtils.java:42) ~[minecolonies:0.13.531-ALPHA]
	at com.minecolonies.coremod.colony.workorders.WorkManager.isWorkOrderWithinColony(WorkManager.java:309) ~[minecolonies:0.13.531-ALPHA]
	at com.minecolonies.coremod.colony.workorders.WorkManager.addWorkOrder(WorkManager.java:261) ~[minecolonies:0.13.531-ALPHA]
	at com.minecolonies.coremod.network.messages.server.DecorationBuildRequestMessage.onExecute(DecorationBuildRequestMessage.java:178) ~[minecolonies:0.13.531-ALPHA]
	at com.minecolonies.coremod.network.messages.splitting.SplitPacketMessage.lambda$onExecute$1(SplitPacketMessage.java:128) ~[minecolonies:0.13.531-ALPHA]
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[forge:?]
	at com.minecolonies.coremod.network.messages.splitting.SplitPacketMessage.onExecute(SplitPacketMessage.java:128) ~[minecolonies:0.13.531-ALPHA]
	at com.minecolonies.coremod.network.NetworkChannel.lambda$setupInternalMessages$4(NetworkChannel.java:265) ~[minecolonies:0.13.531-ALPHA]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[forge:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_275]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[forge:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[forge:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[forge:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[forge:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:88) ~[forge:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_275]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:88) ~[forge:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1413) ~[?:?]
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?]
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:733) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:716) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:710) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:695) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:645) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
```

## Steps to reproduce the issue

1. Place 'Asian bathhouse' decoration
2. Try to upgrade it after it was placed
3. Error occurs

### Logs

See stacktrace above

### Notes
Other decorations can be upgraded just fine, it looks like it's just with this one that there's an issue.

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
That is #5006 

because of

```
[27Dec2020 21:06:54.548] [Server thread/WARN] [structurize/]: File jar resolve FAILED for: schematics//schematics/decorations/asian/bathhouse2.blueprint
```

**Comment by lucasvanhalst** [comment]
@Raycoms so what should be done to fix the error then? It's probably a trivial issue to fix but I can't find where the blueprints are defined/referenced in this repo

**Comment by Raycoms** [comment]
Check the path with the actual location and adjust controller
