### ISSUE TITLE
Crashed server when player connected

### ISSUE THREAD

**Issue by Sanysvo** [ldtteam/minecolonies#6472]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x ] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 0.13.596 - alpha
- Structurize Version: 0.13.113 - alpha
- Related Mods and their Versions: -

## Expected behavior

No crash server

## Steps to reproduce the issue

1. Install Forge server 1.16.5 and add world from 1.15.2 server with colonies
2. Install Minecolonies and Structurize
3. Launch Client 1.16.5 and Server
4. Connecting to server. 

### Logs

- latest.log: 
- crashlog: ---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 31.01.21 14:46
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.minecolonies.coremod.colony.managers.RaidManager.getRaidDifficultyModifier(RaidManager.java:725) ~[minecolonies:0.13.596-ALPHA] {re:classloading}
	at com.minecolonies.api.entity.mobs.RaiderMobUtils.setMobAttributes(RaiderMobUtils.java:87) ~[minecolonies:0.13.596-ALPHA] {re:classloading}
	at com.minecolonies.api.entity.mobs.AbstractEntityMinecoloniesMob.registerWithColony(AbstractEntityMinecoloniesMob.java:455) ~[minecolonies:0.13.596-ALPHA] {re:classloading}
	at com.minecolonies.api.entity.mobs.AbstractEntityMinecoloniesMob.func_70636_d(AbstractEntityMinecoloniesMob.java:387) ~[minecolonies:0.13.596-ALPHA] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:betterweather.mixins.json:server.MixinServerWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterweather.mixins.json:MixinWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:betterweather.mixins.json:server.MixinServerWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:betterweather.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:ultra_amplified_dimension.mixins.json:dimension.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:betterweather.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:ultra_amplified_dimension.mixins.json:dimension.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:betterweather.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:ultra_amplified_dimension.mixins.json:dimension.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:betterweather.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:ultra_amplified_dimension.mixins.json:dimension.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.minecolonies.coremod.colony.managers.RaidManager.getRaidDifficultyModifier(RaidManager.java:725) ~[minecolonies:0.13.596-ALPHA] {re:classloading}
	at com.minecolonies.api.entity.mobs.RaiderMobUtils.setMobAttributes(RaiderMobUtils.java:87) ~[minecolonies:0.13.596-ALPHA] {re:classloading}
	at com.minecolonies.api.entity.mobs.AbstractEntityMinecoloniesMob.registerWithColony(AbstractEntityMinecoloniesMob.java:455) ~[minecolonies:0.13.596-ALPHA] {re:classloading}
	at com.minecolonies.api.entity.mobs.AbstractEntityMinecoloniesMob.func_70636_d(AbstractEntityMinecoloniesMob.java:387) ~[minecolonies:0.13.596-ALPHA] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:betterweather.mixins.json:server.MixinServerWorld,pl:mixin:A,pl:runtimedistcleaner:A}
-- Entity being ticked --
Details:
	Entity Type: minecolonies:barbarian (com.minecolonies.coremod.entity.mobs.barbarians.EntityBarbarian)
	Entity ID: 426
	Entity Name: Barbarian
	Entity's Exact location: -5551.77, 70.00, 946.50
	Entity's Block location: World: (-5552,70,946), Chunk: (at 0,4,2 in -347,59; contains blocks -5552,0,944 to -5537,255,959), Region: (-11,1; contains chunks -352,32 to -321,63, blocks -5632,0,512 to -5121,255,1023)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterweather.mixins.json:MixinWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:betterweather.mixins.json:server.MixinServerWorld,pl:mixin:A,pl:runtimedistcleaner:A}

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Sanysvo'/89, l='ServerLevel[world]', x=-5437.11, y=72.00, z=848.69]]
	Chunk stats: ServerChunkCache: 3474
	Level dimension: minecraft:overworld
	Level spawn location: World: (-5379,97,465), Chunk: (at 13,6,1 in -337,29; contains blocks -5392,0,464 to -5377,255,479), Region: (-11,0; contains chunks -352,0 to -321,31, blocks -5632,0,0 to -5121,255,511)
	Level time: 3253789 game time, 1413300 day time
	Level name: world
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 2912 (now: false), thunder time: 81268 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:betterweather.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:ultra_amplified_dimension.mixins.json:dimension.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:betterweather.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:ultra_amplified_dimension.mixins.json:dimension.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:betterweather.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:ultra_amplified_dimension.mixins.json:dimension.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixin.terraforged.json:common.MixinMinecraftServer,pl:mixin:APP:betterweather.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:ultra_amplified_dimension.mixins.json:dimension.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_271, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4818853832 bytes (4595 MB) / 6138888192 bytes (5854 MB) up to 6138888192 bytes (5854 MB)
	CPUs: 4
	JVM Flags: 2 total; -Xmx6024M -Xms6024M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.0.13.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.0.13.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.0.13.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.0.13.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.0.13.jar fml TRANSFORMATIONSERVICE 
	FML: 36.0
	Forge: net.minecraftforge:36.0.13
	FML Language Providers: 
		javafml@36.0
		minecraft@1
	Mod List: 
		forge-1.16.5-36.0.13-server.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		useful_backpacks-1.16.4-1.11.6.87.jar             |Useful Backpacks              |usefulbackpacks               |1.11.6.87           |DONE      |f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		AmbientSounds_v3.1.4_mc1.16.4.jar                 |Ambient Sounds                |ambientsounds                 |3.0.3               |DONE      |NOSIGNATURE
		1.16.5-enchantedgoldenapplecrafting-1.0.jar       |Enchanted Golden Apple Craftin|enchantedgoldenapplecrafting  |1.0                 |DONE      |NOSIGNATURE
		CreativeCore_v2.0.10_mc1.16.42.jar                |CreativeCore                  |creativecore                  |2.0.0               |DONE      |NOSIGNATURE
		jei-1.16.4-7.6.1.65.jar                           |Just Enough Items             |jei                           |7.6.1.65            |DONE      |NOSIGNATURE
		FallingTree-Forge-1.16.5-2.10.0.jar               |Falling Tree                  |falling_tree                  |2.10.0              |DONE      |NOSIGNATURE
		abnormals_core-1.16.4-3.0.6.jar                   |Abnormals Core                |abnormals_core                |3.0.6               |DONE      |NOSIGNATURE
		astikorcarts-1.16.4-1.1.0.jar                     |AstikorCarts                  |astikorcarts                  |1.1.0               |DONE      |NOSIGNATURE
		monsterswarm.jar                                  |Mobs Swarm                    |monsterswarm                  |1.0                 |DONE      |NOSIGNATURE
		invtweaks-1.16.4-1.0.1.jar                        |Inventory Tweaks Renewed      |invtweaks                     |1.16.4-1.0.1        |DONE      |NOSIGNATURE
		extraboats-1.16.5-2.1.0.jar                       |Extra Boats                   |extraboats                    |2.1.0               |DONE      |NOSIGNATURE
		create-mc1.16.3_v0.3e.jar                         |Create                        |create                        |mc1.16.3_v0.3e      |DONE      |NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.1.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.1        |DONE      |NOSIGNATURE
		Xaeros_Minimap_21.1.1_Forge_1.16.5.jar            |Xaero's Minimap               |xaerominimap                  |21.1.1              |DONE      |NOSIGNATURE
		TerraForged-1.16.4-0.2.1.jar                      |TerraForged                   |terraforged                   |0.2.1               |DONE      |7b:73:d0:a2:c3:40:13:84:35:4f:c9:0e:2b:85:8c:08:ea:3c:3c:eb:f1:98:8b:5b:6e:ca:8a:a0:9a:cf:12:b3
		betterweather-1.2.8.jar                           |Better Weather                |betterweather                 |1.2.8               |DONE      |NOSIGNATURE
		citadel-1.5.3.jar                                 |Citadel                       |citadel                       |1.5.3               |DONE      |NOSIGNATURE
		twoplayersonemount-1.16.4-1.0.0.jar               |2 players 1 mount             |twoplayersonemount            |1.16.4-1.0.0        |DONE      |NOSIGNATURE
		yungsapi-1.16.4-forge-3.jar                       |YUNG's API                    |yungsapi                      |1.16.4-Forge-3      |DONE      |NOSIGNATURE
		HardcoreRevival_1.16.3-5.2.0.jar                  |Hardcore Revival              |hardcorerevival               |5.2.0               |DONE      |NOSIGNATURE
		DungeonCrawl-1.16.3-2.2.4.jar                     |Dungeon Crawl                 |dungeoncrawl                  |2.2.4               |DONE      |NOSIGNATURE
		Cazfps_chronicles_v1.2_fix_1.16.4.jar             |cazfps chronicle              |cazfps_chronicle              |BETA1               |DONE      |NOSIGNATURE
		betteranimalsplus-1.16.4-10.1.0.jar               |Better Animals Plus           |betteranimalsplus             |10.1.0              |DONE      |NOSIGNATURE
		structurize-0.13.116-ALPHA-universal.jar          |Structurize                   |structurize                   |0.13.113-ALPHA      |DONE      |NOSIGNATURE
		u_team_core-1.16.4-3.1.17.192.jar                 |U Team Core                   |uteamcore                     |3.1.17.192          |DONE      |f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		vanilladeathchest-1.16.3-1.11.0.7.jar             |VanillaDeathChest             |vanilladeathchest             |1.16.3-1.11.0.7     |DONE      |92:f6:29:d4:09:89:f5:f5:98:5e:20:34:31:d0:7b:58:22:06:bd:a5:d1:6a:92:6e:ac:3d:8d:18:c5:b2:5b:d7
		minecolonies-0.13.596-ALPHA-universal.jar         |MineColonies                  |minecolonies                  |0.13.596-ALPHA      |DONE      |NOSIGNATURE
		simpleplanes-1.16.3-3.2.0.3.jar                   |Simple Planes                 |simpleplanes                  |1.16.3-3.2.0.3      |DONE      |NOSIGNATURE
		iceandfire-2.1.5-1.16.4.jar                       |Ice and Fire                  |iceandfire                    |2.1.5-1.16.4        |DONE      |NOSIGNATURE
		repairgem.jar                                     |Repaire Gem                   |repairgem                     |1.0                 |DONE      |NOSIGNATURE
		Zmod+1.16.2-1.06.jar                              |ZmodSkills                    |zmod                          |1.06                |DONE      |NOSIGNATURE
		trashcans-1.0.6a-mc1.16.4.jar                     |Trash Cans                    |trashcans                     |1.0.6a              |DONE      |NOSIGNATURE
		enchantwithmob-1.16.4-2.3.3.jar                   |Enchant With Mob              |enchantwithmob                |1.16.4-2.3.3        |DONE      |NOSIGNATURE
		corail-backpack-1.16.4-045.jar                    |Corail Backpack               |corail_backpack               |1.16.4-045          |DONE      |NOSIGNATURE
		forge-1.16.5-36.0.13-universal.jar                |Forge                         |forge                         |36.0.13             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		cofh_core-1.16.3-1.1.6.jar                        |CoFH Core                     |cofh_core                     |1.1.6               |DONE      |NOSIGNATURE
		ensorcellation-1.16.3-1.1.2.jar                   |Ensorcellation                |ensorcellation                |1.1.2               |DONE      |NOSIGNATURE
		Aquaculture-1.16.4-2.1.12.jar                     |Aquaculture 2                 |aquaculture                   |1.16.4-2.1.12       |DONE      |NOSIGNATURE
		ultra_amplified_dimension-1.16.4-9.0.3-forge.jar  |Ultra Amplified Dimension     |ultra_amplified_dimension     |1.16.4-9.0.3-forge  |DONE      |NOSIGNATURE
		tl_skin_cape_forge_1.16.5-1.17.jar                |TLSkinCape                    |tlskincape                    |1.17                |DONE      |19:f5:ce:44:81:0c:e4:22:05:5e:73:c5:a8:cd:de:f3:c8:cf:a9:b3:01:70:40:a0:ee:2d:50:7a:1c:3d:1c:8a
		bettermineshafts-forge-1.16.4-2.0.1.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.1        |DONE      |NOSIGNATURE
		wanderingpets-1.2.jar                             |Wandering Pets                |wanderingpets                 |1.2                 |DONE      |NOSIGNATURE
		dungeons_gear-1.16.4-3.0.6.jar                    |Dungeons Gear                 |dungeons_gear                 |3.0.6               |DONE      |NOSIGNATURE
	Crash Report UUID: 9e33caf2-46c4-40e4-a100-388d9d8fb7fc
	Player Count: 1 / 20; [ServerPlayerEntity['Sanysvo'/89, l='ServerLevel[world]', x=-5437.11, y=72.00, z=848.69]]
	Data Packs: mod:repairgem (incompatible), vanilla, mod:usefulbackpacks, mod:ambientsounds (incompatible), mod:creativecore, mod:jei, mod:falling_tree, mod:astikorcarts, mod:monsterswarm (incompatible), mod:invtweaks (incompatible), mod:extraboats, mod:create (incompatible), mod:bettercaves (incompatible), mod:xaerominimap, mod:terraforged, mod:citadel (incompatible), mod:hardcorerevival (incompatible), mod:dungeoncrawl, mod:betteranimalsplus (incompatible), mod:structurize, mod:uteamcore, mod:vanilladeathchest (incompatible), mod:minecolonies (incompatible), mod:simpleplanes (incompatible), mod:iceandfire (incompatible), mod:zmod (incompatible), mod:trashcans, mod:enchantwithmob, mod:forge, mod:aquaculture (incompatible), mod:bettermineshafts (incompatible), mod:enchantedgoldenapplecrafting, mod:abnormals_core, mod:betterweather (incompatible), mod:twoplayersonemount, mod:yungsapi, mod:cazfps_chronicle, mod:corail_backpack, mod:cofh_core (incompatible), mod:ensorcellation (incompatible), mod:ultra_amplified_dimension, mod:tlskincape (incompatible), mod:wanderingpets, mod:dungeons_gear
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Sanysvo** [comment]
Important moment: i launch old world from 1.15.2. On server 1.15.2 work, but after update to 1.16.5 i get crash when my player connected. I not want lost my colony(

**Comment by Raycoms** [comment]
Sorry, we can't support opening 1.15.2 worlds in 1.16

**Comment by Sanysvo** [comment]
Yes, but only you can say what a problem...in error description crash called this function "java.lang.NullPointerException: Ticking entity at com.minecolonies.coremod.colony.managers.RaidManager.getRaidDifficultyModifier(RaidManager.java:725)". That is it? World good works if delete path "minecolonies" in world path. Maybe i can edit minecolonies dat for continue play in this world?

**Comment by Raycoms** [comment]
Minecolonies.dat is backup and not the actually data that we load. So editing it would not be enough.

**Comment by Sanysvo** [comment]
Why after delete this files all colony with villagers (from mod) are deleting?
