### ISSUE TITLE
Can not build grass path

### ISSUE THREAD

**Issue by xavierh** [ldtteam/minecolonies#665]
### Minecolonies version

git version/1.11

### Expected behavior

- Ask the builder to build a schematic with some grass path in it.
- The builder do it

### Actual behaviour

- The builder is puzzled about it and stand doing nothing

### Steps to reproduce the problem

1. Create a schematic with grass path
2. Ask the builder to build it
3. ...
4. Profit

**Comment by marchermans** [comment]
It probably does not know how to get Grass Paths. @Kostronor, how would you like to handle this.

**Comment by Raycoms** [comment]
The builder should know that he can make grass paths with the shovel.

2017-03-02 6:14 GMT-03:00 Orion <notifications@github.com>:

**Comment by xavierh** [comment]
I don't really know what to do about it.

The error come from https://github.com/Minecolonies/minecolonies/blob/version/1.11/src/main/java/com/minecolonies/coremod/util/BlockUtils.java#L384
`
java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class net.minecraft.block.BlockDirt$DirtType, values=[dirt, coarse_dirt, podzol]} as it does not exist in BlockStateContainer{block=minecraft:grass_path, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201) ~[atm$a.class:?]
	at com.minecolonies.coremod.util.BlockUtils.getDamageValue(BlockUtils.java:384) ~[BlockUtils.class:?]
	at com.minecolonies.coremod.util.BlockUtils.getItemStackFromBlockState(BlockUtils.java:361) ~[BlockUtils.class:?]
	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructure.requestBlockToBuildingIfRequired(AbstractEntityAIStructure.java:647) ~[AbstractEntityAIStructure.class:?]
	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructure.requestMaterials(AbstractEntityAIStructure.java:559) ~[AbstractEntityAIStructure.class:?]
	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructure.requestMaterialsIfRequired(AbstractEntityAIStructure.java:516) ~[AbstractEntityAIStructure.class:?]
	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructure.loadStructure(AbstractEntityAIStructure.java:456) ~[AbstractEntityAIStructure.class:?]
	at com.minecolonies.coremod.entity.ai.citizen.builder.EntityAIStructureBuilder.initiate(EntityAIStructureBuilder.java:105) ~[EntityAIStructureBuilder.class:?]
	at com.minecolonies.coremod.entity.ai.citizen.builder.EntityAIStructureBuilder.checkIfExecute(EntityAIStructureBuilder.java:94) ~[EntityAIStructureBuilder.class:?]
	at com.minecolonies.coremod.entity.ai.util.AITarget.test(AITarget.java:114) ~[AITarget.class:?]
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.checkOnTarget(AbstractAISkeleton.java:164) ~[AbstractAISkeleton.class:?]
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) [?:1.8.0_121]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351) [?:1.8.0_121]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) [?:1.8.0_121]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498) [?:1.8.0_121]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) [?:1.8.0_121]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) [?:1.8.0_121]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) [?:1.8.0_121]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) [?:1.8.0_121]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:1.8.0_121]
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449) [?:1.8.0_121]
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:128) [AbstractAISkeleton.class:?]
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129) [uj.class:?]
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:769) [sx.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2255) [sw.class:?]
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:573) [sx.class:?]
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:171) [sk.class:?]
	at com.minecolonies.coremod.entity.EntityCitizen.func_70636_d(EntityCitizen.java:868) [EntityCitizen.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2085) [sw.class:?]
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:296) [sx.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1961) [ajs.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840) [lw.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1931) [ajs.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1747) [ajs.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621) [lw.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [cch.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
`

**Comment by Raycoms** [comment]
we would have to detect if it is a path (manually) and then place dirt and
use a shovel on it.

2017-04-12 7:44 GMT-03:00 xavierh <notifications@github.com>:

**Comment by xavierh** [comment]
Just found out the grass path is not available in creative as a block item

**Comment by Raycoms** [comment]
Yeah it also does not work with middle mouse click. We really have to do
the manual way.

2017-04-12 9:04 GMT-03:00 xavierh <notifications@github.com>:

> Just found out the grass path is not available in creative as a block item
>
>

**Comment by xavierh** [comment]
Middle mouse click?  What is this suppose to do?
Btw the builder ask for dirt, he just can place it

**Comment by Raycoms** [comment]
You can copy a block in creative with middle button (or mousewheel) click.
He he should detect it is of dirt, place the dirt (and request is for sure)
and then use a shovel on it.

2017-04-12 9:27 GMT-03:00 xavierh <notifications@github.com>:

> Middle mouse click? What is this suppose to do?
> Btw the builder ask for dirt, he just can place it
>
>
