### ISSUE TITLE
Woodcutter AI run into an issue when stripping logs

### ISSUE THREAD

**Issue by FrancissEscamez** [ldtteam/minecolonies#6727]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.4
- MineColonies Version: 0.14.3-ALPHA

### Logs

- latest.log: https://gist.github.com/FrancissEscamez/83c813f3924779462b8dec0e50cfde86

## Steps to reproduce the issue / details

When i send the builder to upgrade a building, that use stripped oak log, and send the order to the woodcutter, this happend ![AI error minecolonies](https://user-images.githubusercontent.com/50408328/110856531-0ab29080-82b8-11eb-80be-87a1ca4a4112.png)
The build that is trying to upgrade, is that same exact woodcutter
 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Nothing in the log in relation to that

**Comment by ravenbuilder934** [comment]
There is?

**Comment by ravenbuilder934** [comment]
You need to click `View the full file` or so

**Comment by Raycoms** [comment]
meh

**Comment by Nightenom** [comment]
```
[22:13:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:348]: java.lang.ClassCastException: com.minecolonies.coremod.colony.buildings.workerbuildings.BuildingLumberjack cannot be cast to com.minecolonies.api.colony.buildings.workerbuildings.IBuildingPublicCrafter
[22:13:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:348]: 	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAICrafting.getRequiredProgressForMakingRawMaterial(AbstractEntityAICrafting.java:437)
[22:13:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:348]: 	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAICrafting.craft(AbstractEntityAICrafting.java:343)
[22:13:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:348]: 	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAICrafting$$Lambda$12344/1473416351.get(Unknown Source)
[22:13:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:348]: 	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:79)
[22:13:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:348]: 	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:163)
[22:13:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:348]: 	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:149)
[22:13:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:348]: 	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:129)
[22:13:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:348]: 	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:108)
[22:13:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:348]: 	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:129)
[22:13:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:348]: 	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55)
[22:13:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:348]: 	at com.minecolonies.api.entity.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:223)
[22:13:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:348]: 	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:682)
[22:13:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:348]: 	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411)
[22:13:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:348]: 	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488)
[22:13:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:348]: 	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:127)
[22:13:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:348]: 	at com.minecolonies.api.entity.citizen.AbstractEntityCitizen.func_70636_d(AbstractEntityCitizen.java:389)
[22:13:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:348]: 	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:449)
[22:13:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:348]: 	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158)
[22:13:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:348]: 	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300)
[22:13:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:348]: 	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611)
[22:13:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:348]: 	at net.minecraft.world.server.ServerWorld$$Lambda$10507/1929232728.accept(Unknown Source)
[22:13:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:348]: 	at net.minecraft.world.World.func_217390_a(World.java:554)
[22:13:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:348]: 	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404)
[22:13:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:348]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850)
[22:13:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:348]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786)
[22:13:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:348]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78)
[22:13:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:348]: 	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641)
[22:13:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:348]: 	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232)
[22:13:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:348]: 	at net.minecraft.server.MinecraftServer$$Lambda$9861/1527071668.run(Unknown Source)
[22:13:43] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:348]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ravenbuilder934** [comment]
ye that 😄

**Comment by Raycoms** [comment]
I always forget clicking "view full file" =D

**Comment by Raycoms** [comment]
Found the bug, making a fix PR atm

**Comment by Raycoms** [comment]
Push fixed
