### ISSUE TITLE
AI issue with the carrier

### ISSUE THREAD

**Issue by nickr4mos** [ldtteam/minecolonies#7020]
To be fair I didn't noticed anything too out of the ordinary, but since the NPC itself showed this warning, here we go. Below is the error inside latest.log, and the full file is attached here as well.

```
[00:24:58] [Server thread/ERROR]: Parent cancellation of delivery request failed! Unknown request: StandardToken{id=d3d44bc8-73bc-46eb-b10f-b23523259fc4}
java.lang.Exception: null
	at com.minecolonies.coremod.colony.requestsystem.resolvers.DeliverymenRequestResolver.onAssignedRequestCancelled(DeliverymenRequestResolver.java:157) [?:0.14.117-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.processDirectCancellationOf(RequestHandler.java:456) [?:0.14.117-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.processDirectCancellationAndNotifyRequesterOf(RequestHandler.java:422) [?:0.14.117-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.onRequestCancelledDirectly(RequestHandler.java:414) [?:0.14.117-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.onRequestCancelled(RequestHandler.java:389) [?:0.14.117-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.manager.StandardRequestManager.updateRequestState(StandardRequestManager.java:311) [?:0.14.117-ALPHA]
	at com.minecolonies.coremod.colony.jobs.JobDeliveryman.finishRequest(JobDeliveryman.java:295) [?:0.14.117-ALPHA]
	at com.minecolonies.coremod.entity.ai.citizen.deliveryman.EntityAIWorkDeliveryman.pickup(EntityAIWorkDeliveryman.java:168) [?:0.14.117-ALPHA]
	at com.minecolonies.coremod.entity.ai.citizen.deliveryman.EntityAIWorkDeliveryman$$Lambda$11270/1963607018.get(Unknown Source) [?:0.14.117-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:79) [?:0.14.117-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:163) [?:0.14.117-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:149) [?:0.14.117-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:129) [?:0.14.117-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:108) [?:0.14.117-ALPHA]
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:129) [?:0.14.117-ALPHA]
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) [?:?]
	at com.minecolonies.api.entity.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:223) [?:0.14.117-ALPHA]
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:977) [?:?]
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411) [?:?]
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:683) [?:?]
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:127) [?:?]
	at com.minecolonies.api.entity.citizen.AbstractEntityCitizen.func_70636_d(AbstractEntityCitizen.java:389) [?:0.14.117-ALPHA]
	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:455) [?:0.14.117-ALPHA]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) [?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:431) [?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) [?:?]
	at net.minecraft.world.server.ServerWorld$$Lambda$9896/1470963625.accept(Unknown Source) [?:?]
	at net.minecraft.world.World.func_217390_a(World.java:554) [?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) [?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) [?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) [?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) [?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$9155/1701966145.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[00:24:58] [Server thread/WARN]: Statemachine for transition com.minecolonies.api.entity.ai.statemachine.AITarget@5a198ca4 threw an exception:
java.lang.NullPointerException: null
	at com.minecolonies.coremod.colony.buildings.AbstractBuilding.onRequestedRequestCancelled(AbstractBuilding.java:1780) ~[?:0.14.117-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.requesters.BuildingBasedRequester.lambda$onRequestedRequestCancelled$1(BuildingBasedRequester.java:94) ~[?:0.14.117-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.requesters.BuildingBasedRequester$$Lambda$12598/960856263.accept(Unknown Source) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_51]
	at com.minecolonies.coremod.colony.requestsystem.requesters.BuildingBasedRequester.onRequestedRequestCancelled(BuildingBasedRequester.java:94) ~[?:0.14.117-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.processDirectCancellationAndNotifyRequesterOf(RequestHandler.java:423) ~[?:0.14.117-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.onRequestCancelledDirectly(RequestHandler.java:414) ~[?:0.14.117-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.onRequestCancelled(RequestHandler.java:389) ~[?:0.14.117-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.manager.StandardRequestManager.updateRequestState(StandardRequestManager.java:311) ~[?:0.14.117-ALPHA]
	at com.minecolonies.coremod.colony.jobs.JobDeliveryman.finishRequest(JobDeliveryman.java:295) ~[?:0.14.117-ALPHA]
	at com.minecolonies.coremod.entity.ai.citizen.deliveryman.EntityAIWorkDeliveryman.pickup(EntityAIWorkDeliveryman.java:168) ~[?:0.14.117-ALPHA]
	at com.minecolonies.coremod.entity.ai.citizen.deliveryman.EntityAIWorkDeliveryman$$Lambda$11270/1963607018.get(Unknown Source) ~[?:?]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:79) ~[?:0.14.117-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:163) [?:0.14.117-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:149) [?:0.14.117-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:129) [?:0.14.117-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:108) [?:0.14.117-ALPHA]
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:129) [?:0.14.117-ALPHA]
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) [?:?]
	at com.minecolonies.api.entity.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:223) [?:0.14.117-ALPHA]
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:977) [?:?]
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411) [?:?]
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:683) [?:?]
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:127) [?:?]
	at com.minecolonies.api.entity.citizen.AbstractEntityCitizen.func_70636_d(AbstractEntityCitizen.java:389) [?:0.14.117-ALPHA]
	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:455) [?:0.14.117-ALPHA]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) [?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:431) [?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) [?:?]
	at net.minecraft.world.server.ServerWorld$$Lambda$9896/1470963625.accept(Unknown Source) [?:?]
	at net.minecraft.world.World.func_217390_a(World.java:554) [?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) [?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) [?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) [?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) [?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$9155/1701966145.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
[00:24:58] [Server thread/ERROR]: Pausing Entity Peyton U. Colby (com.minecolonies.coremod.job.Deliveryman) at BlockPos{x=1783, y=82, z=5575} for 100 Seconds because of error:
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: java.lang.NullPointerException
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at com.minecolonies.coremod.colony.buildings.AbstractBuilding.onRequestedRequestCancelled(AbstractBuilding.java:1780)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at com.minecolonies.coremod.colony.requestsystem.requesters.BuildingBasedRequester.lambda$onRequestedRequestCancelled$1(BuildingBasedRequester.java:94)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at com.minecolonies.coremod.colony.requestsystem.requesters.BuildingBasedRequester$$Lambda$12598/960856263.accept(Unknown Source)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at java.util.Optional.ifPresent(Optional.java:159)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at com.minecolonies.coremod.colony.requestsystem.requesters.BuildingBasedRequester.onRequestedRequestCancelled(BuildingBasedRequester.java:94)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.processDirectCancellationAndNotifyRequesterOf(RequestHandler.java:423)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.onRequestCancelledDirectly(RequestHandler.java:414)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.onRequestCancelled(RequestHandler.java:389)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at com.minecolonies.coremod.colony.requestsystem.management.manager.StandardRequestManager.updateRequestState(StandardRequestManager.java:311)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at com.minecolonies.coremod.colony.jobs.JobDeliveryman.finishRequest(JobDeliveryman.java:295)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at com.minecolonies.coremod.entity.ai.citizen.deliveryman.EntityAIWorkDeliveryman.pickup(EntityAIWorkDeliveryman.java:168)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at com.minecolonies.coremod.entity.ai.citizen.deliveryman.EntityAIWorkDeliveryman$$Lambda$11270/1963607018.get(Unknown Source)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:79)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:163)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:149)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:129)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:108)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:129)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at com.minecolonies.api.entity.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:223)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:977)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:683)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:127)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at com.minecolonies.api.entity.citizen.AbstractEntityCitizen.func_70636_d(AbstractEntityCitizen.java:389)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:455)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:431)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at net.minecraft.world.server.ServerWorld$$Lambda$9896/1470963625.accept(Unknown Source)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at net.minecraft.world.World.func_217390_a(World.java:554)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at net.minecraft.server.MinecraftServer$$Lambda$9155/1701966145.run(Unknown Source)
[00:24:58] [Server thread/INFO]: [com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic:onException:340]: 	at java.lang.Thread.run(Thread.java:745)
```

[latest.log](https://github.com/ldtteam/minecolonies/files/6384757/latest.log)

Issues aside, I'd like to thank you guys for the great mod, I'm having a ton of fun growing my colony!

**Comment by Raycoms** [comment]
Thanks for reporting this, this is the same problem as #5672
