### ISSUE TITLE
AI issue for courier

### ISSUE THREAD

**Issue by abadger** [ldtteam/minecolonies#7396]
### Prerequisites 

- [ ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version:minecolonies-0.14.279-ALPHA-universal.jar

### Logs

- latest.log: https://gist.github.com/abadger/9be6968fbcc0988df330ae3c471760ed#file-latest-log-L5521

## Steps to reproduce the issue / details

The request to report the AI issue came from one of two couriers.  I discovered her standing in the warehouse with the icon that something was wrong.  I don't know how to reproduce or what caused it.

I've uploaded the whole latest.log but linked to the area where it looks like the problems have started.

Just reporting the AI issue. 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by leagris** [comment]
This issue is also affecting me with very same versions:
- minecolonies-0.14.288-ALPHA-universal
- structurize-0.13.200-BETA-universal

Here is a gist extract from [`latest.log`](https://gist.github.com/leagris/50cfed4edc7483520e8513393d6e97e3):
```none
[13Jul2021 14:25:12.661] [Server thread/WARN] [minecolonies/]: Statemachine for transition com.minecolonies.api.entity.ai.statemachine.AITarget@93200a4 threw an exception:
java.lang.IllegalArgumentException: The given token is not registered as a request to this manager
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.getRequest(RequestHandler.java:541) ~[minecolonies:0.14.288-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.manager.StandardRequestManager.updateRequestState(StandardRequestManager.java:288) ~[minecolonies:0.14.288-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.resolvers.PrivateWorkerCraftingProductionResolver.resolveForBuilding(PrivateWorkerCraftingProductionResolver.java:90) ~[minecolonies:0.14.288-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.resolvers.core.AbstractCraftingProductionResolver.resolveRequest(AbstractCraftingProductionResolver.java:194) ~[minecolonies:0.14.288-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.resolveRequest(RequestHandler.java:489) ~[minecolonies:0.14.288-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.onRequestCompleted(RequestHandler.java:322) ~[minecolonies:0.14.288-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.manager.StandardRequestManager.updateRequestState(StandardRequestManager.java:303) ~[minecolonies:0.14.288-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.onRequestResolved(RequestHandler.java:291) ~[minecolonies:0.14.288-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.manager.StandardRequestManager.updateRequestState(StandardRequestManager.java:299) ~[minecolonies:0.14.288-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.resolvers.BuildingRequestResolver.resolveForBuilding(BuildingRequestResolver.java:164) ~[minecolonies:0.14.288-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.resolvers.core.AbstractBuildingDependentRequestResolver.resolveRequest(AbstractBuildingDependentRequestResolver.java:63) ~[minecolonies:0.14.288-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.resolveRequest(RequestHandler.java:489) ~[minecolonies:0.14.288-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.onRequestCompleted(RequestHandler.java:322) ~[minecolonies:0.14.288-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.manager.StandardRequestManager.updateRequestState(StandardRequestManager.java:303) ~[minecolonies:0.14.288-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.RequestHandler.onRequestOverruled(RequestHandler.java:362) ~[minecolonies:0.14.288-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.manager.StandardRequestManager.updateRequestState(StandardRequestManager.java:307) ~[minecolonies:0.14.288-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.manager.StandardRequestManager.overruleRequest(StandardRequestManager.java:346) ~[minecolonies:0.14.288-ALPHA]
	at com.minecolonies.coremod.colony.buildings.AbstractBuilding.overruleNextOpenRequestWithStack(AbstractBuilding.java:1570) ~[minecolonies:0.14.288-ALPHA]
	at com.minecolonies.api.tileentities.AbstractTileEntityRack.updateWarehouseIfAvailable(AbstractTileEntityRack.java:136) ~[minecolonies:0.14.288-ALPHA]
	at com.minecolonies.api.tileentities.AbstractTileEntityRack$RackInventory.insertItem(AbstractTileEntityRack.java:99) ~[minecolonies:0.14.288-ALPHA]
	at com.minecolonies.api.inventory.api.CombinedItemHandler.insertItem(CombinedItemHandler.java:246) ~[minecolonies:0.14.288-ALPHA]
	at com.minecolonies.api.util.InventoryUtils.addItemStackToItemHandlerWithResult(InventoryUtils.java:1067) ~[minecolonies:0.14.288-ALPHA]
	at com.minecolonies.api.util.InventoryUtils.forceItemStackToItemHandler(InventoryUtils.java:406) ~[minecolonies:0.14.288-ALPHA]
	at com.minecolonies.coremod.entity.ai.citizen.deliveryman.EntityAIWorkDeliveryman.deliver(EntityAIWorkDeliveryman.java:381) ~[minecolonies:0.14.288-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:79) ~[minecolonies:0.14.288-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:163) ~[minecolonies:0.14.288-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:149) ~[minecolonies:0.14.288-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:129) ~[minecolonies:0.14.288-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:108) ~[minecolonies:0.14.288-ALPHA]
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:131) ~[minecolonies:0.14.288-ALPHA]
	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75246_d(SourceFile:55) ~[?:?]
	at com.minecolonies.api.entity.CustomGoalSelector.func_75774_a(CustomGoalSelector.java:231) ~[minecolonies:0.14.288-ALPHA]
	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:682) ~[?:?]
	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488) ~[?:?]
	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:127) ~[?:?]
	at com.minecolonies.api.entity.citizen.AbstractEntityCitizen.func_70636_d(AbstractEntityCitizen.java:400) ~[minecolonies:0.14.288-ALPHA]
	at com.minecolonies.coremod.entity.citizen.EntityCitizen.func_70636_d(EntityCitizen.java:438) ~[minecolonies:0.14.288-ALPHA]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158) ~[?:?]
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?]
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
```
