### ISSUE TITLE
Schematic crash

### ISSUE THREAD

**Issue by Azack2005** [ldtteam/minecolonies#7743]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:
- MineColonies Version:1.17
- Structurize Version:1.17
- Related Mods and their Versions:1.17

## Expected behavior
 I want to be able to load my schematics

## Actual behavior
 I have moved my scan file to schematics under structurize in the files. Any time I try to go on the "Myschematics" option in the build tool my game crashes.

## Steps to reproduce the issue

All I know is when i scan my builds levels 1 to 5 I then go and move the folder to schematics in structurize. Then I reload minecraft and then load the same world when I hit the decorations option and as soon as I switch it to myschematics the entire game frezese and crashes.

1. 
2. 
3. 

### Logs

[crash-2021-11-04_19.34.00-client.txt](https://github.com/ldtteam/minecolonies/files/7479513/crash-2021-11-04_19.34.00-client.txt)

- latest.log:  I dont know what Gist is but If u can send me a link to 1vangemertni@hdsb.ca I can try and figure it out.
- crashlog: 

### Notes

Any updates on how to fix it plz plz plz send it to 1vangemertni@hdsb.ca
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Sorry it took so long, the mod at fault is: doubleslabs:

```
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException: Cannot invoke "net.minecraft.core.RegistryAccess.m_175515_(net.minecraft.resources.ResourceKey)" because the return value of "net.minecraft.world.level.Level.m_5962_()" is null
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217) ~[guava-21.0.jar%2320!:?] {}
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[guava-21.0.jar%2320!:?] {}
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[guava-21.0.jar%2320!:?] {}
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[guava-21.0.jar%2320!:?] {}
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) ~[guava-21.0.jar%2320!:?] {}
	at net.minecraftforge.client.MinecraftForgeClient.getRegionRenderCacheOptional(MinecraftForgeClient.java:137) ~[forge-1.17.1-37.0.70-universal.jar%23111!:?] {re:classloading}
	at net.minecraftforge.client.MinecraftForgeClient.getRegionRenderCache(MinecraftForgeClient.java:129) ~[forge-1.17.1-37.0.70-universal.jar%23111!:?] {re:classloading}
	at cjminecraft.doubleslabs.client.render.SlabTileEntityRenderer.render(SlabTileEntityRenderer.java:32) ~[DoubleSlabs-1.17-4.0.0.jar%2371!:4.0.0] {re:classloading}
	at cjminecraft.doubleslabs.client.render.SlabTileEntityRenderer.m_6922_(SlabTileEntityRenderer.java:19) ~[DoubleSlabs-1.17-4.0.0.jar%2371!:4.0.0] {re:classloading}
	```

**Comment by Azack2005** [comment]
Thank you so much

**Comment by Nightenom** [comment]
Nah, this is our fault (99%)
Edi: see https://github.com/ldtteam/Structurize/issues/430
