### ISSUE TITLE
Weird error in server [1.18.1]

### ISSUE THREAD

**Issue by itsdinkd** [ldtteam/minecolonies#7874]
Running latest minecolonies version, latest forge loader. 

When my server turns on, I am greeted with this error, no crash, but a error.

```java
[05:21:02] [Server thread/WARN]: ResourceLocationException!: Non [a-z0-9/._-] character in path of location: minecraft:0 0 0
net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: minecraft:0 0 0
        at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:37) ~[server-1.18.1-20211210.034407-srg.jar%23295!:?]
        at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:42) ~[server-1.18.1-20211210.034407-srg.jar%23295!:?]
        at com.minecolonies.api.compatibility.CompatibilityManager.discoverFreeBlocksAndPos(CompatibilityManager.java:730) ~[minecolonies-1.18.1-1.0.278-RELEASE.jar%23186!:1.18.1-1.0.278-RELEASE]
        at com.minecolonies.api.compatibility.CompatibilityManager.discover(CompatibilityManager.java:203) ~[minecolonies-1.18.1-1.0.278-RELEASE.jar%23186!:1.18.1-1.0.278-RELEASE]
        at com.minecolonies.coremod.event.TagWorkAroundEventHandler.loadRecipes(TagWorkAroundEventHandler.java:55) ~[minecolonies-1.18.1-1.0.278-RELEASE.jar%23186!:1.18.1-1.0.278-RELEASE]
        at com.minecolonies.coremod.event.TagWorkAroundEventHandler$TagFMLEventHandlers.onServerStarted(TagWorkAroundEventHandler.java:186) ~[minecolonies-1.18.1-1.0.278-RELEASE.jar%23186!:1.18.1-1.0.278-RELEASE]
        at net.minecraftforge.eventbus.ASMEventHandler_1213_TagFMLEventHandlers_onServerStarted_ServerStartedEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?]
        at net.minecraftforge.server.ServerLifecycleHooks.handleServerStarted(ServerLifecycleHooks.java:107) ~[forge-1.18.1-39.0.8-universal.jar%23299!:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:645) ~[server-1.18.1-20211210.034407-srg.jar%23295!:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23295!:?]
```

**Comment by uecasm** [comment]
"Latest" is not a version of Minecolonies.  Please properly fill in the template.

I'm not sure why that's getting logged; since looking at the code, the exception should be getting caught and handled.  (Which I assume is happening since you're saying it doesn't crash.)

Do you have another mod that changes error reporting in some way?  Makes it noisier?

As for what's actually triggering this, you have "0 0 0" in your "Free-to-Interact Blocks" setting in your minecolonies-server.toml file (which is probably a mistake anyway, and you should just remove that).

**Comment by Raycoms** [comment]
Yeah, this is fine. Someone else is logging what they shouldn't
