### ISSUE TITLE
firing event: null

### ISSUE THREAD

**Issue by GlowPon3** [ldtteam/minecolonies#7875]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version:1.16.5
- MineColonies Version:1.0.309
- Structurize Version:0.13.252-ALPHA
- Related Mods and their Versions:

## Expected behavior

Being able to log in to my server like I can with my other account.  Both are Microsoft accounts.
## Actual behavior

During login the below error hits console and I cannot connect.

## Steps to reproduce the issue

1. Play normally, create a village.
2. Delete the village. Log out. OP yourself.
3. You can't log in again. (Doesn't always happen, but it did for me this one time.)

### Logs

Connection attempt:

[03:04:06] [Server thread/INFO] [minecraft/DedicatedServer]: GlowPon3 joined the game
[03:04:06] [Server thread/INFO] [Treasure Bags/]: Sending 30 bag types to GlowPon3
[03:04:06] [Server thread/INFO] [Waila/]: Syncing config to GlowPon3 (f21791e9-f95a-499c-9253-6e8dc780d220)
[03:04:06] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: null
        Index: 51
        Listeners:
                0: HIGHEST
                1: ASM: class net.silentchaos512.treasurebags.events.ServerEvents onPlayerJoinServer(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                2: ASM: io.github.noeppi_noeppi.libx.impl.config.ConfigEvents@1b7ec4b1 playerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                3: HIGH
                4: ASM: class me.shedaniel.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                5: NORMAL
                6: ASM: class net.mcreator.nethersexoticism.procedures.NethersExoticismTriggerProcedure$GlobalTrigger onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                7: ASM: net.pyromancer.PyromancerModVariables@8926839 onPlayerLoggedInSyncPlayerVariables(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                8: ASM: net.pyromancer.PyromancerModVariables@8926839 onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                9: ASM: de.erdbeerbaerlp.dcintegration.forge.DiscordIntegration@31aea089 playerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                10: ASM: class net.mehvahdjukaar.supplementaries.events.ServerEvents onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                11: net.minecraftforge.eventbus.EventBus$$Lambda$2578/244114315@2a3246f
                12: ASM: class net.mehvahdjukaar.supplementaries.world.data.GlobeData onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                13: ASM: class mod.beethoven92.betterendforge.common.event.forge.ForgeEvents loginEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                14: ASM: com.Rolfmao.upgradednetherite.handlers.ServerConfigHandler@6719b913 onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                15: ASM: class net.obscuria.aquamirae.procedures.AquamiraeAdvProcedure$GlobalTrigger onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                16: ASM: class net.mcreator.frostedfriends.procedures.FrostedFriendsTriggerProcedure$GlobalTrigger onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                17: ASM: com.buuz135.seals.Seals@3ba27bb4 onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                18: ASM: sereneseasons.handler.season.SeasonHandler@4d3f3e9d onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                19: ASM: net.minecraftforge.common.ForgeInternalHandler@47bbd094 playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                20: ASM: com.blamejared.crafttweaker.CraftTweaker@53760831 playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                21: ASM: class com.teammetallurgy.atum.misc.event.AtumEventListener onPlayerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                22: ASM: class greekfantasy.event.CommonForgeEventHandler onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                23: ASM: class com.ldtteam.structurize.event.EventSubscriber onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                24: ASM: net.obscuria.core.ObCoreModVariables@589f4288 onPlayerLoggedInSyncPlayerVariables(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                25: ASM: class net.obscuria.core.procedures.MysteriousBoxGiveProcedure$GlobalTrigger onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                26: ASM: class com.legacy.blue_skies.events.SkiesPlayerEvents onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                27: net.minecraftforge.eventbus.EventBus$$Lambda$2578/244114315@2b31603f
                28: ASM: class net.blay09.mods.kleeslabs.network.SyncHandler onLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                29: ASM: class com.github.alexthe666.alexsmobs.event.ServerEvents onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                30: net.minecraftforge.eventbus.EventBus$$Lambda$2578/244114315@346c1d98
                31: ASM: net.mcreator.undeadexpansion.UndeadExpansionModVariables@4f3db86b onPlayerLoggedInSyncPlayerVariables(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                32: ASM: class twilightforest.TFEventListener playerLogsIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                33: ASM: class twilightforest.TFEventListener onClientConnect(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                34: ASM: net.spicybanana.wilds.WildsModVariables@333ba5 onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                35: ASM: class net.spicybanana.wilds.procedures.WildsRootGrantProcedure$GlobalTrigger onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                36: ASM: class com.github.clevernucleus.playerex.init.EventHandler onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                37: ASM: class vazkii.patchouli.common.handler.PlayerJoinHandler playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                38: ASM: com.feywild.feywild.EventListener@75baaa21 playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                39: ASM: class com.hollingsworth.arsnouveau.common.event.EventHandler playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                40: ASM: class com.hollingsworth.arsnouveau.api.familiar.FamiliarCap$EventHandler onPlayerLoginEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                41: ASM: class com._idrae.travelers_index.events.EventBusSubscriber onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                42: ASM: class me.shedaniel.architectury.networking.forge.NetworkManagerImpl loggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                43: ASM: class com.baguchan.enchantwithmob.CommonEventHandler onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                44: ASM: class net.blay09.mods.waystones.handler.LoginHandler onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                45: ASM: net.mcreator.villageemployment.VillageEmploymentModVariables@6f18cdb5 onPlayerLoggedInSyncPlayerVariables(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                46: ASM: class com.simibubi.create.events.CommonEvents playerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                47: ASM: class com.simibubi.create.content.curiosities.tools.ExtendoGripItem addReachToJoiningPlayersHoldingExtendo(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                48: net.minecraftforge.eventbus.EventBus$$Lambda$2578/244114315@3ee6807c
                49: ASM: class com.oblivioussp.spartanshields.ModSpartanShields onPlayerLogIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                50: ASM: class vazkii.quark.base.handler.ContributorRewardHandler onPlayerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                51: ASM: class com.minecolonies.coremod.event.EventHandler onPlayerEnterWorld(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                52: ASM: class com.minecolonies.coremod.event.FMLEventHandler onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                53: ASM: class net.valhelsia.valhelsia_core.event.PlayerJoinWorldListener onPlayerJoinWorld(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                54: ASM: class com.bottomtextdanny.dannys_expansion.core.events.ResourceReloadHandler playerLoggedEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                55: ASM: class net.mcreator.natureexpansion.procedures.FirstAdvancementPProcedure$GlobalTrigger onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                56: ASM: snownee.kiwi.contributor.Contributors@7ef93968 onPlayerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                57: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@483b2be9 playerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                58: ASM: shadows.apotheosis.ench.EnchModuleEvents@46b82746 login(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                59: net.minecraftforge.eventbus.EventBus$$Lambda$2578/244114315@257d5b93
                60: ASM: tschipp.carryon.common.event.ItemEvents@9751ca6 onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                61: ASM: journeymap.common.events.ForgeEvents@69e823f8 onPlayerLoggedInEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                62: ASM: team.creative.creativecore.common.config.event.ConfigEventHandler@38803ef8 playerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
                63: ASM: class xratedjunior.betterdefaultbiomes.common.enchantment.EnchantmentEventSubscriber onPlayerTick(Lnet/minecraftforge/event/entity/living/LivingEvent;)V
                64: LOWEST
                65: ASM: com.brandon3055.csg.ModEventHandler@35d37498 playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
java.lang.NullPointerException
        at com.minecolonies.coremod.colony.permissions.Permissions.hasPermission(Permissions.java:584)
        at com.minecolonies.coremod.colony.permissions.Permissions.hasPermission(Permissions.java:645)
        at com.minecolonies.coremod.event.EventHandler.onPlayerEnterWorld(EventHandler.java:449)
        at net.minecraftforge.eventbus.ASMEventHandler_3685_EventHandler_onPlayerEnterWorld_PlayerLoggedInEvent.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:44)
        at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:232)
        at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118)
        at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65)
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222)
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
        at java.lang.Thread.run(Thread.java:748)

[03:04:06] [Server thread/WARN] [minecraft/NetworkSystem]: Failed to handle packet for /64.146.151.196:61065
java.lang.NullPointerException: null
        at com.minecolonies.coremod.colony.permissions.Permissions.hasPermission(Permissions.java:584) ~[minecolonies:1.16.5-1.0.309-RELEASE] {re:classloading}
        at com.minecolonies.coremod.colony.permissions.Permissions.hasPermission(Permissions.java:645) ~[minecolonies:1.16.5-1.0.309-RELEASE] {re:classloading}
        at com.minecolonies.coremod.event.EventHandler.onPlayerEnterWorld(EventHandler.java:449) ~[minecolonies:1.16.5-1.0.309-RELEASE] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraftforge.eventbus.ASMEventHandler_3685_EventHandler_onPlayerEnterWorld_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
        at net.minecraftforge.fml.hooks.BasicEventHooks.firePlayerLoggedIn(BasicEventHooks.java:44) ~[forge:?] {re:classloading}
        at net.minecraft.server.management.PlayerList.func_72355_a(PlayerList.java:232) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:betterendforge.mixins.json:PlayerListMixin,pl:mixin:APP:origins.mixins.json:LoginMixin,pl:mixin:APP:origins.forge.mixins.json:PlayerManagerMixin,pl:mixin:APP:pehkui.mixins.json:PlayerManagerMixin,pl:mixin:APP:libx.mixins.json:MixinPlayerList,pl:mixin:APP:library_of_exile-mixins.json:PlayerManagerMixin,pl:mixin:APP:blue_skies.mixins.json:PlayerListMixin,pl:mixin:APP:endergetic.mixins.json:PlayerListMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinPlayerList,pl:mixin:APP:mixins.dcintegration.json:MixinWhitelist,pl:mixin:APP:create.mixins.json:PlayerListMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.network.login.ServerLoginNetHandler.func_147326_c(ServerLoginNetHandler.java:118) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:randompatches.mixins.json:timeouts.ServerLoginNetHandlerMixin,pl:mixin:APP:kryptonreforged.mixins.json:network.shared.pipeline.encryption.ServerLoginNetworkHandlerMixin,pl:mixin:A}
        at net.minecraft.network.login.ServerLoginNetHandler.func_73660_a(ServerLoginNetHandler.java:65) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:randompatches.mixins.json:timeouts.ServerLoginNetHandlerMixin,pl:mixin:APP:kryptonreforged.mixins.json:network.shared.pipeline.encryption.ServerLoginNetworkHandlerMixin,pl:mixin:A}
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:222) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:kryptonreforged.mixins.json:network.shared.flushconsolidation.ClientConnectionMixin,pl:mixin:APP:kryptonreforged.mixins.json:network.shared.pipeline.compression.ClientConnectionMixin,pl:mixin:APP:kryptonreforged.mixins.json:network.shared.pipeline.encryption.ClientConnectionMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:paxi.mixins.json:MixinMinecraftServer,pl:mixin:APP:upstream.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:roadrunner.mixins.json:world.light_batching.MinecraftServerMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:paxi.mixins.json:MixinMinecraftServer,pl:mixin:APP:upstream.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:roadrunner.mixins.json:world.light_batching.MinecraftServerMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:paxi.mixins.json:MixinMinecraftServer,pl:mixin:APP:upstream.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:roadrunner.mixins.json:world.light_batching.MinecraftServerMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:paxi.mixins.json:MixinMinecraftServer,pl:mixin:APP:upstream.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:roadrunner.mixins.json:world.light_batching.MinecraftServerMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftServerAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312] {}

- latest.log: 
- crashlog: 

### Notes

I've tried deleting my player file, my achievements file, my ftb chunks file, ftb teams file, and my deaths file.  Every trace I could find of myself on the server.  Still it happens.
---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
This is not LAN mode, right?

**Comment by Raycoms** [comment]
Something failed during colony deletion here. Can we get the latest.log in a gist of the deletion?

**Comment by GlowPon3** [comment]
This is on a dedicated server install.  I will try and find the .log that has it in it.

**Comment by GlowPon3** [comment]
I was unable to find the log file, but I was able to solve the issue.  I erased my player file and advancements, then my ftb files, then my tags in scoreboard.dat.  But what seems to have fixed it was having someone in another colony remove me from the owner list of their colony.  Once no colony was recognizing me the issue resolved.  Hope this helps someone.

**Comment by Raycoms** [comment]
"owner list", did they have a custom rank you were part of?

**Comment by GlowPon3** [comment]
Not sure.  It is possible they did trying to stop me from getting notifications.  I opened the colony in NBT explorer.
They removed me in game.  Tag was as follows:
colony1.dat
-owners:
--3 entries
----id: f21791e9-f95a-499c-9253-6e8dc780d220
----name: GlowPon3
----rank: 5
