### ISSUE TITLE
Cowhand having an AI bug

### ISSUE THREAD

**Issue by Thabael** [ldtteam/minecolonies#7919]
### Prerequisites 

- [x ] I am running the latest **alpha** version of MineColonies for my Minecraft version.
- [x ] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.16.5
- MineColonies Version: 1.0.332-ALPHA

### Logs

- latest.log: https://gist.github.com/Thabael/391daa708aa07db33c19490763f90d6a

## Steps to reproduce the issue / details

 Unknown what caused the error, updating to the latest version of MineColonies for 1.16.5 did not fix anything. I can fire the cowhand, wait a few minutes, then re-hire him,
![Screenshot (144)](https://user-images.githubusercontent.com/45077127/148654348-9bc86ea5-a421-4775-89a1-d47d2678a074.png)
 and still the same error message.

Just reporting the AI issue. 

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
can you report this to:
```
[11:09:18] [Server thread/INFO]: [java.lang.Throwable:printStackTrace:634]: Caused by: java.lang.NullPointerException
[11:09:18] [Server thread/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at com._idrae.travelers_index.data.ItemChecklistStorage.writeNBT(ItemChecklistStorage.java:32)
[11:09:18] [Server thread/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at com._idrae.travelers_index.data.ItemChecklistStorage.writeNBT(ItemChecklistStorage.java:16)
[11:09:18] [Server thread/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at com._idrae.travelers_index.data.ItemChecklistProvider.serializeNBT(ItemChecklistProvider.java:29)
[11:09:18] [Server thread/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at com._idrae.travelers_index.data.ItemChecklistProvider.serializeNBT(ItemChecklistProvider.java:14)
[11:09:18] [Server thread/INFO]: [java.lang.Throwable:printStackTrace:634]: 	at net.minecraftforge.common.capabilities.CapabilityDispatcher.serializeNBT(CapabilityDispatcher.java:127
```

**Comment by Raycoms** [comment]
Reported to them. Will close issue then.
