### ISSUE TITLE
Citizens can't perform any jobs after updating to the latest version 1.0.346-ALPHA

### ISSUE THREAD

**Issue by pixartist** [ldtteam/minecolonies#7931]
### Prerequisites 

- [x] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [x] I made sure that **this issue is not a duplicate of any existing issue.**

### Context

- Minecraft Version: 1.18.1
- MineColonies Version: 1.0.346-ALPHA
- Structurize Version: 1.0.319-BETA
- Related Mods and their Versions: See All the Mods 0.2.22

## Expected behavior
Citizens perform job

## Actual behavior
Citizens don't perform any jobs

Server reports exceptions:
`[22:48:40] [Server thread/WARN]: Condition check for transition com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickingTransition@25cfc7f7 threw an exception:
java.lang.NullPointerException: Cannot invoke "com.minecolonies.api.client.render.modeltype.IModelType.getName()" because the return value of "com.minecolonies.api.entity.citizen.AbstractEntityCitizen.getModelType()" is null
        at com.minecolonies.coremod.entity.citizen.citizenhandlers.CitizenJobHandler.setModelDependingOnJob(CitizenJobHandler.java:88) ~[minecolonies-1.18.1-1.0.346-ALPHA.jar%23162!:1.18.1-1.0.346-ALPHA]
        at com.minecolonies.coremod.entity.citizen.citizenhandlers.CitizenJobHandler.onJobChanged(CitizenJobHandler.java:101) ~[minecolonies-1.18.1-1.0.346-ALPHA.jar%23162!:1.18.1-1.0.346-ALPHA]
        at com.minecolonies.coremod.colony.CitizenData.lambda$setJob$5(CitizenData.java:830) ~[minecolonies-1.18.1-1.0.346-ALPHA.jar%23162!:1.18.1-1.0.346-ALPHA]
        at java.util.Optional.ifPresent(Unknown Source) ~[?:?]
        at com.minecolonies.coremod.colony.CitizenData.setJob(CitizenData.java:830) ~[minecolonies-1.18.1-1.0.346-ALPHA.jar%23162!:1.18.1-1.0.346-ALPHA]
        at com.minecolonies.coremod.colony.CitizenData.setWorkBuilding(CitizenData.java:769) ~[minecolonies-1.18.1-1.0.346-ALPHA.jar%23162!:1.18.1-1.0.346-ALPHA]
        at com.minecolonies.coremod.colony.buildings.modules.WorkerBuildingModule.onAssignment(WorkerBuildingModule.java:181) ~[minecolonies-1.18.1-1.0.346-ALPHA.jar%23162!:1.18.1-1.0.346-ALPHA]
        at com.minecolonies.coremod.colony.buildings.modules.AbstractAssignedCitizenModule.assignCitizen(AbstractAssignedCitizenModule.java:50) ~[minecolonies-1.18.1-1.0.346-ALPHA.jar%23162!:1.18.1-1.0.346-ALPHA]
        at com.minecolonies.coremod.colony.buildings.modules.WorkerBuildingModule.assignCitizen(WorkerBuildingModule.java:95) ~[minecolonies-1.18.1-1.0.346-ALPHA.jar%23162!:1.18.1-1.0.346-ALPHA]
        at com.minecolonies.coremod.colony.buildings.modules.WorkerBuildingModule.onColonyTick(WorkerBuildingModule.java:145) ~[minecolonies-1.18.1-1.0.346-ALPHA.jar%23162!:1.18.1-1.0.346-ALPHA]
        at com.minecolonies.coremod.colony.buildings.AbstractBuilding.lambda$onColonyTick$5(AbstractBuilding.java:711) ~[minecolonies-1.18.1-1.0.346-ALPHA.jar%23162!:1.18.1-1.0.346-ALPHA]
        at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
        at com.minecolonies.coremod.colony.buildings.AbstractBuilding.onColonyTick(AbstractBuilding.java:711) ~[minecolonies-1.18.1-1.0.346-ALPHA.jar%23162!:1.18.1-1.0.346-ALPHA]
        at com.minecolonies.coremod.colony.managers.BuildingManager.onColonyTick(BuildingManager.java:235) ~[minecolonies-1.18.1-1.0.346-ALPHA.jar%23162!:1.18.1-1.0.346-ALPHA]
        at com.minecolonies.coremod.colony.Colony.worldTickSlow(Colony.java:434) ~[minecolonies-1.18.1-1.0.346-ALPHA.jar%23162!:1.18.1-1.0.346-ALPHA]
        at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.checkCondition(BasicTransition.java:87) ~[minecolonies-1.18.1-1.0.346-ALPHA.jar%23162!:1.18.1-1.0.346-ALPHA]
        at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:138) ~[minecolonies-1.18.1-1.0.346-ALPHA.jar%23162!:1.18.1-1.0.346-ALPHA]
        at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:129) ~[minecolonies-1.18.1-1.0.346-ALPHA.jar%23162!:1.18.1-1.0.346-ALPHA]
        at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:108) ~[minecolonies-1.18.1-1.0.346-ALPHA.jar%23162!:1.18.1-1.0.346-ALPHA]
        at com.minecolonies.coremod.colony.Colony.onWorldTick(Colony.java:1086) ~[minecolonies-1.18.1-1.0.346-ALPHA.jar%23162!:1.18.1-1.0.346-ALPHA]
        at com.minecolonies.coremod.colony.ColonyManager.lambda$onWorldTick$4(ColonyManager.java:657) ~[minecolonies-1.18.1-1.0.346-ALPHA.jar%23162!:1.18.1-1.0.346-ALPHA]
        at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
        at com.minecolonies.coremod.colony.ColonyManager.onWorldTick(ColonyManager.java:657) ~[minecolonies-1.18.1-1.0.346-ALPHA.jar%23162!:1.18.1-1.0.346-ALPHA]
        at com.minecolonies.coremod.event.FMLEventHandler.onWorldTick(FMLEventHandler.java:62) ~[minecolonies-1.18.1-1.0.346-ALPHA.jar%23162!:1.18.1-1.0.346-ALPHA]
        at net.minecraftforge.eventbus.ASMEventHandler_1117_FMLEventHandler_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?]
        at net.minecraftforge.event.ForgeEventFactory.onPostWorldTick(ForgeEventFactory.java:866) ~[forge-1.18.1-39.0.17-universal.jar%23253!:?]
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:874) ~[server-1.18.1-20211210.034407-srg.jar%23249!:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328) ~[server-1.18.1-20211210.034407-srg.jar%23249!:?]
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[server-1.18.1-20211210.034407-srg.jar%23249!:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[server-1.18.1-20211210.034407-srg.jar%23249!:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23249!:?]
        at java.lang.Thread.run(Unknown Source) [?:?]`

## Steps to reproduce the issue

1. Create a Server on a pre 0.2.22 version of ATM7
2. Build a colony 
2. Update to 2.22 of ATM7
3. Connect

### Notes

---
## Viewers

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Did you try 347?

**Comment by pixartist** [comment]
no as 346 is bundled with atm

**Comment by Raycoms** [comment]
Darn it, ATM just updated to the wrong one

**Comment by Raycoms** [comment]
fixed in latest
