### ISSUE TITLE
Farmer crash checking for hoe

### ISSUE THREAD

**Issue by BlackGSS** [ldtteam/minecolonies#7935]
I was playing for a month with the server in which the error occurs suddenly, the problem is the server got stuck at this point and when I start the server and It's on, it stays a couple of seconds after crash and I can't enter in this time to see what's happening inside

Time: 1/12/22, 7:39 PM
Description: Ticking entity

java.lang.NoSuchFieldError: DIRT
	at com.minecolonies.coremod.entity.ai.citizen.farmer.EntityAIWorkFarmer.shouldHoe(EntityAIWorkFarmer.java:407) ~[minecolonies-1.18.1-1.0.278-RELEASE.jar%2349!:1.18.1-1.0.278-RELEASE] {re:classloading}
	at com.minecolonies.coremod.entity.ai.citizen.farmer.EntityAIWorkFarmer.lambda$prepareForFarming$1(EntityAIWorkFarmer.java:279) ~[minecolonies-1.18.1-1.0.278-RELEASE.jar%2349!:1.18.1-1.0.278-RELEASE] {re:classloading}
	at com.minecolonies.coremod.entity.ai.citizen.farmer.EntityAIWorkFarmer.checkIfShouldExecute(EntityAIWorkFarmer.java:348) ~[minecolonies-1.18.1-1.0.278-RELEASE.jar%2349!:1.18.1-1.0.278-RELEASE] {re:classloading}
	at com.minecolonies.coremod.entity.ai.citizen.farmer.EntityAIWorkFarmer.prepareForFarming(EntityAIWorkFarmer.java:278) ~[minecolonies-1.18.1-1.0.278-RELEASE.jar%2349!:1.18.1-1.0.278-RELEASE] {re:classloading}
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:79) ~[minecolonies-1.18.1-1.0.278-RELEASE.jar%2349!:1.18.1-1.0.278-RELEASE] {re:classloading}
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:163) ~[minecolonies-1.18.1-1.0.278-RELEASE.jar%2349!:1.18.1-1.0.278-RELEASE] {re:classloading}
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:149) ~[minecolonies-1.18.1-1.0.278-RELEASE.jar%2349!:1.18.1-1.0.278-RELEASE] {re:classloading}
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:129) ~[minecolonies-1.18.1-1.0.278-RELEASE.jar%2349!:1.18.1-1.0.278-RELEASE] {re:classloading}
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:108) ~[minecolonies-1.18.1-1.0.278-RELEASE.jar%2349!:1.18.1-1.0.278-RELEASE] {re:classloading}
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.m_8037_(AbstractAISkeleton.java:133) ~[minecolonies-1.18.1-1.0.278-RELEASE.jar%2349!:1.18.1-1.0.278-RELEASE] {re:classloading}
	at net.minecraft.world.entity.ai.goal.WrappedGoal.m_8037_(WrappedGoal.java:65) ~[server-1.18.1-20211210.034407-srg.jar%2359!:?] {re:classloading}
	at com.minecolonies.api.entity.CustomGoalSelector.m_25373_(CustomGoalSelector.java:231) ~[minecolonies-1.18.1-1.0.278-RELEASE.jar%2349!:1.18.1-1.0.278-RELEASE] {re:classloading}
	at net.minecraft.world.entity.Mob.m_6140_(Mob.java:698) ~[server-1.18.1-20211210.034407-srg.jar%2359!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2498) ~[server-1.18.1-20211210.034407-srg.jar%2359!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.Mob.m_8107_(Mob.java:495) ~[server-1.18.1-20211210.034407-srg.jar%2359!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.AgeableMob.m_8107_(AgeableMob.java:127) ~[server-1.18.1-20211210.034407-srg.jar%2359!:?] {re:classloading}
	at com.minecolonies.api.entity.citizen.AbstractEntityCitizen.m_8107_(AbstractEntityCitizen.java:345) ~[minecolonies-1.18.1-1.0.278-RELEASE.jar%2349!:1.18.1-1.0.278-RELEASE] {re:classloading}
	at com.minecolonies.coremod.entity.citizen.EntityCitizen.m_8107_(EntityCitizen.java:466) ~[minecolonies-1.18.1-1.0.278-RELEASE.jar%2349!:1.18.1-1.0.278-RELEASE] {re:classloading}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2245) ~[server-1.18.1-20211210.034407-srg.jar%2359!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:307) ~[server-1.18.1-20211210.034407-srg.jar%2359!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:649) ~[server-1.18.1-20211210.034407-srg.jar%2359!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:A}
	at net.minecraft.world.level.Level.m_46653_(Level.java:487) ~[server-1.18.1-20211210.034407-srg.jar%2359!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:316) ~[server-1.18.1-20211210.034407-srg.jar%2359!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[server-1.18.1-20211210.034407-srg.jar%2359!:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:296) ~[server-1.18.1-20211210.034407-srg.jar%2359!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[server-1.18.1-20211210.034407-srg.jar%2359!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328) ~[server-1.18.1-20211210.034407-srg.jar%2359!:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[server-1.18.1-20211210.034407-srg.jar%2359!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[server-1.18.1-20211210.034407-srg.jar%2359!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%2359!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

	Mod List: 
		
		theoneprobe-1.18-5.0.2.jar
		structurize-1.18.1-1.0.319-BETA.jar 
		TheVeggieWay-Forge-1.18.1-2.4.3.jar
		sophisticatedbackpacks-1.18.1-3.15.0.494.jar 
		ImmersiveEngineering-1.18.1-7.1.0-145.jar  
		EasierSleeping-1.18.1-2.1.0.jar   
		balm-2.4.0+0.jar                
		jei-1.18.1-9.1.1.48.jar       
		appliedenergistics2-10.0.0-beta.2.jar    
		movingelevators-1.2.34a-mc1.18.jar        
		domum_ornamentum-1.18-1.0.31-ALPHA-universal.jar 
		CopperEquipment-Forge1.18-1.1.jar            
		forge-1.18.1-39.0.19-universal.jar       
		appleskin-forge-mc1.18-2.2.0.jar        
		blockui-1.18-0.0.34-ALPHA.jar              
		multi-piston-1.18-1.2.2-ALPHA.jar    
		minecolonies-1.18.1-1.0.278-RELEASE.jar   
		waystones-forge-1.18.1-9.0.1.jar           
		journeymap-1.18.1-5.8.0beta5.jar       
		ironchest-1.18-13.0.7.jar                
		cookingforblockheads-forge-1.18-11.0.0.jar   
		NaturesCompass-1.18.1-1.9.4-forge.jar

**Comment by someaddons** [comment]
forge issue, they removed the DIRT tag, rolling back to 39.0.17 should work for now

**Comment by MotionlessTrain** [comment]
It seems like this crash has been fixed in Minecolonies 1.0.249

**Comment by someaddons** [comment]
true ray hotfixed it already
