### ISSUE TITLE
crashes when trying out the forge (i didn't know it was WIP or just bugged)

### ISSUE THREAD

**Issue by scigeotech** [ldtteam/minecolonies#795]
### Minecolonies version
version 0.6.3360

version X.X.XXXX or curse X.X.XX
version 1.11.2

### Expected behavior
to work
- XXX

### Actual behaviour
crashes
- YYY

### Steps to reproduce the problem
place down the forge (i wanted to try it out because i had cheats in survival)

attempt to banish the forge (it was weird so i tried to destroy it)

and watch it resist the power of left-clicking (it just keeps coming back)

1. XYZ
2. ZYX
3. ...
4. Profit

crash report:

> ---- Minecraft Crash Report ----

WARNING: coremods are present:
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.2-beta2-anarchy.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 4/10/17 12:38 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at com.minecolonies.structures.helpers.Structure.getSize(Structure.java:204)
	at com.minecolonies.structures.helpers.StructureProxy.rotateWithMirror(StructureProxy.java:229)
	at com.minecolonies.coremod.util.StructureWrapper.rotate(StructureWrapper.java:157)
	at com.minecolonies.coremod.entity.ai.citizen.builder.ConstructionTapeHelper.removeConstructionTape(ConstructionTapeHelper.java:239)
	at com.minecolonies.coremod.entity.ai.citizen.builder.ConstructionTapeHelper.removeConstructionTape(ConstructionTapeHelper.java:213)
	at com.minecolonies.coremod.colony.buildings.AbstractBuilding.onDestroyed(AbstractBuilding.java:530)
	at com.minecolonies.coremod.colony.buildings.AbstractBuildingWorker.onDestroyed(AbstractBuildingWorker.java:165)
	at com.minecolonies.coremod.colony.buildings.AbstractBuilding.destroy(AbstractBuilding.java:512)
	at java.util.ArrayList.forEach(Unknown Source)
	at com.minecolonies.coremod.colony.Colony.cleanUpBuildings(Colony.java:1091)
	at com.minecolonies.coremod.colony.Colony.onWorldTick(Colony.java:1016)
	at com.minecolonies.coremod.colony.ColonyManager.lambda$onWorldTick$46(ColonyManager.java:657)
	at java.util.ArrayList.forEach(Unknown Source)
	at com.minecolonies.coremod.colony.ColonyManager.onWorldTick(ColonyManager.java:657)
	at com.minecolonies.coremod.event.FMLEventHandler.onWorldTick(FMLEventHandler.java:50)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_95_FMLEventHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:285)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:705)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (x86) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 164507992 bytes (156 MB) / 449429504 bytes (428 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.38 Powered by Forge 13.20.0.2259 Optifine OptiFine_1.11.2_HD_U_B7 34 mods loaded, 34 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2259.jar) 
	UCHIJAAAA	forge{13.20.0.2259} [Minecraft Forge] (forge-1.11.2-13.20.0.2259.jar) 
	UCHIJAAAA	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCHIJAAAA	qwebnm_multiversepouch{v1.1} [Multiverse Pouch] ([1.11.2]Multiverse Pouch v1.1.jar) 
	UCHIJAAAA	animania{1.0.4.6} [Animania] (animania-1.11.2-1.0.4.6.jar) 
	UCHIJAAAA	jei{4.3.1.259} [Just Enough Items] (jei_1.11.2-4.3.1.259.jar) 
	UCHIJAAAA	appleskin{1.0.6} [AppleSkin] (AppleSkin-mc1.11-1.0.6.jar) 
	UCHIJAAAA	bedbugs{@VERSION@} [Bed Bugs] (BedBugs-1.11.2-1.1.7.jar) 
	UCHIJAAAA	birdsnests{1.5.1} [Bird's Nests] (BirdsNests1.11.2-1.5.1.jar) 
	UCHIJAAAA	blocklings{4.1.0} [WillR27's Blocklings] (Blocklings 4.1.0 - 1.11.2.jar) 
	UCHIJAAAA	clarity{1.0} [Clarity] (clarity-1.0.jar) 
	UCHIJAAAA	cleanview{1.10.2-v1} [CleanView] (CleanView-1.10.2-v1.jar) 
	UCHIJAAAA	compot{${version}} [Combined Potions] (CombinedPotions-1.11-1.1-beta1.jar) 
	UCHIJAAAA	craftsaddlesmod{1.0} [Craft Saddles and Horse Armor] (craftsaddlesmod-1.0.jar) 
	UCHIJAAAA	crystalcaves{1.0} [Crystal Caves] (CrystalCaves-1.0.jar) 
	UCHIJAAAA	epicsiegemod{12.0.153} [Epic Siege Mod] (EpicSiegeMod-12.0.153.jar) 
	UCHIJAAAA	foamfix{@VERSION@} [FoamFix] (foamfix-0.6.2-beta2-anarchy.jar) 
	UCHIJAAAA	ftfragileglass{1.8.1} [Fragile Glass and Thin Ice] (Fragile Glass and Thin Ice 1.11-1.8.1.jar) 
	UCHIJAAAA	grapplemod{1.11-v9} [Grappling hook mod] (grapplemod-1.11-v9.jar) 
	UCHIJAAAA	minecolonies{1.11-0.6.3360} [MineColonies] (minecolonies-universal-1.11-0.6.3360.jar) 
	UCHIJAAAA	neat{1.4-13} [Neat] (Neat 1.4-13.jar) 
	UCHIJAAAA	notes{1.1.0} [Notes] (Notes-1.11.2-1.1.0.jar) 
	UCHIJAAAA	overlord{2.3.0} [Overlord] (Overlord-1.11.2-2.3.0.jar) 
	UCHIJAAAA	harvestcraft{1.11.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2g.jar) 
	UCHIJAAAA	sandwichmod{1.0} [Sandwich Mod] (sandwichmod-1.0.jar) 
	UCHIJAAAA	showarmsstand{1.3.1} [ShowArmsStand] (ShowArmsStand-1.11.2-1.3.1.jar) 
	UCHIJAAAA	sophisticatedwolves{3.6.5} [Sophisticated Wolves] (SophisticatedWolves-3.6.5.jar) 
	UCHIJAAAA	supplydrop{1.0.1} [Supply Drop] (Supply Drop-1.11.2-1.0.1.jar) 
	UCHIJAAAA	sushimod{1.0} [Sushi Mod] (sushimod-1.0.jar) 
	UCHIJAAAA	tombmanygraves{1.11.2-3.0.5} [Tomb Many Graves] (TombManyGraves-1.11.2-3.0.5.jar) 
	UCHIJAAAA	torohealthmod{1.11.2-11} [ToroHealth Damage Indicators] (torohealth-1.11.2-11.jar) 
	UCHIJAAAA	tumat{1.8.0-RC3} [TUMAT] (TUMAT-1.8.0-RC3-1.8.0-RC3.jar) 
	Loaded coremods (and transformers): 
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.2-beta2-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.11.2_HD_U_B7
	Render Distance Chunks: 7
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.3.0 - Build 20.19.15.4531
	OpenGlRenderer: Intel(R) HD Graphics 4400
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by scigeotech** [comment]
sorry, i tried to fit the crash report in a spoiler but for some reason it doesn't work. please quickly fix the bug! i can't enter my world without it crashing first.

**Comment by Raycoms** [comment]
Hmm its not a bug its really not yet implemented. You should be able to remove the block of your world with mcEdit or similar.
We will soon remove those blocks since people are getting used to cheating the not implemented things =D
