### ISSUE TITLE
CTD on clicking "Build Options"

### ISSUE THREAD

**Issue by TheDadDude** [ldtteam/minecolonies#7992]
Other notification was "OpenJDK binary not present"
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 1/25/22, 12:48 PM
Description: Ticking screen

java.lang.NoSuchFieldError: DIRT
	at com.ldtteam.structurize.placement.handlers.placement.PlacementHandlers$GrassPlacementHandler.canHandle(PlacementHandlers.java:274) ~[structurize-1.18.1-1.0.319-BETA.jar%2366!/:1.18.1-1.0.319-BETA] {re:classloading}
	at com.ldtteam.structurize.placement.StructurePlacer.getResourceRequirements(StructurePlacer.java:443) ~[structurize-1.18.1-1.0.319-BETA.jar%2366!/:1.18.1-1.0.319-BETA] {re:classloading}
	at com.ldtteam.structurize.placement.StructurePlacer.executeStructureStep(StructurePlacer.java:150) ~[structurize-1.18.1-1.0.319-BETA.jar%2366!/:1.18.1-1.0.319-BETA] {re:classloading}
	at com.minecolonies.coremod.client.gui.WindowBuildBuilding.updateResources(WindowBuildBuilding.java:359) ~[minecolonies-1.18.1-1.0.278-RELEASE.jar%2361!/:1.18.1-1.0.278-RELEASE] {re:classloading}
	at com.minecolonies.coremod.client.gui.WindowBuildBuilding.onStyleDropDownChanged(WindowBuildBuilding.java:465) ~[minecolonies-1.18.1-1.0.278-RELEASE.jar%2361!/:1.18.1-1.0.278-RELEASE] {re:classloading}
	at com.ldtteam.blockui.views.DropDownList.setSelectedIndex(DropDownList.java:202) ~[blockui-1.18-0.0.40-ALPHA.jar%2353!/:1.18-0.0.40-ALPHA] {re:classloading}
	at com.minecolonies.coremod.client.gui.WindowBuildBuilding.updateStyles(WindowBuildBuilding.java:268) ~[minecolonies-1.18.1-1.0.278-RELEASE.jar%2361!/:1.18.1-1.0.278-RELEASE] {re:classloading}
	at com.minecolonies.coremod.client.gui.WindowBuildBuilding.onOpened(WindowBuildBuilding.java:490) ~[minecolonies-1.18.1-1.0.278-RELEASE.jar%2361!/:1.18.1-1.0.278-RELEASE] {re:classloading}
	at com.ldtteam.blockui.BOScreen.m_96624_(BOScreen.java:344) ~[blockui-1.18-0.0.40-ALPHA.jar%2353!/:1.18-0.0.40-ALPHA] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$tick$30(Minecraft.java:1641) ~[client-1.18.1-20211210.034407-srg.jar%2370!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:527) ~[client-1.18.1-20211210.034407-srg.jar%2370!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1640) ~[client-1.18.1-20211210.034407-srg.jar%2370!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1015) ~[client-1.18.1-20211210.034407-srg.jar%2370!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.18.1-20211210.034407-srg.jar%2370!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%2370!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.59.jar%2323!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.ldtteam.structurize.placement.handlers.placement.PlacementHandlers$GrassPlacementHandler.canHandle(PlacementHandlers.java:274) ~[structurize-1.18.1-1.0.319-BETA.jar%2366!/:1.18.1-1.0.319-BETA] {re:classloading}
	at com.ldtteam.structurize.placement.StructurePlacer.getResourceRequirements(StructurePlacer.java:443) ~[structurize-1.18.1-1.0.319-BETA.jar%2366!/:1.18.1-1.0.319-BETA] {re:classloading}
	at com.ldtteam.structurize.placement.StructurePlacer.executeStructureStep(StructurePlacer.java:150) ~[structurize-1.18.1-1.0.319-BETA.jar%2366!/:1.18.1-1.0.319-BETA] {re:classloading}
	at com.minecolonies.coremod.client.gui.WindowBuildBuilding.updateResources(WindowBuildBuilding.java:359) ~[minecolonies-1.18.1-1.0.278-RELEASE.jar%2361!/:1.18.1-1.0.278-RELEASE] {re:classloading}
	at com.minecolonies.coremod.client.gui.WindowBuildBuilding.onStyleDropDownChanged(WindowBuildBuilding.java:465) ~[minecolonies-1.18.1-1.0.278-RELEASE.jar%2361!/:1.18.1-1.0.278-RELEASE] {re:classloading}
	at com.ldtteam.blockui.views.DropDownList.setSelectedIndex(DropDownList.java:202) ~[blockui-1.18-0.0.40-ALPHA.jar%2353!/:1.18-0.0.40-ALPHA] {re:classloading}
	at com.minecolonies.coremod.client.gui.WindowBuildBuilding.updateStyles(WindowBuildBuilding.java:268) ~[minecolonies-1.18.1-1.0.278-RELEASE.jar%2361!/:1.18.1-1.0.278-RELEASE] {re:classloading}
	at com.minecolonies.coremod.client.gui.WindowBuildBuilding.onOpened(WindowBuildBuilding.java:490) ~[minecolonies-1.18.1-1.0.278-RELEASE.jar%2361!/:1.18.1-1.0.278-RELEASE] {re:classloading}
	at com.ldtteam.blockui.BOScreen.m_96624_(BOScreen.java:344) ~[blockui-1.18-0.0.40-ALPHA.jar%2353!/:1.18-0.0.40-ALPHA] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$tick$30(Minecraft.java:1641) ~[client-1.18.1-20211210.034407-srg.jar%2370!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:527) ~[client-1.18.1-20211210.034407-srg.jar%2370!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Affected screen --
Details:
	Screen name: com.ldtteam.blockui.BOScreen
Stacktrace:
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:527) ~[client-1.18.1-20211210.034407-srg.jar%2370!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1640) ~[client-1.18.1-20211210.034407-srg.jar%2370!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1015) ~[client-1.18.1-20211210.034407-srg.jar%2370!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.18.1-20211210.034407-srg.jar%2370!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%2370!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.59.jar%2323!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['TheDadDude'/172, l='ClientLevel', x=-623.33, y=65.00, z=395.57]]
	Chunk stats: 2209, 1537
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,70,0), Section: (at 0,6,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 71544 game time, 80885 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:407) ~[client-1.18.1-20211210.034407-srg.jar%2370!/:?] {re:classloading,xf:fml:xaerominimap:xaero_clientworldclass,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2248) ~[client-1.18.1-20211210.034407-srg.jar%2370!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:677) ~[client-1.18.1-20211210.034407-srg.jar%2370!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%2370!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.59.jar%2323!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Mod Resources, Default, Winthor_Medieval_1.18_v6.8.zip

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 3480089488 bytes (3318 MiB) / 7851737088 bytes (7488 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-4430 CPU @ 3.00GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 3.00
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GTX 760
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 1536.00
	Graphics card #0 deviceId: 0x1185
	Graphics card #0 versionInfo: DriverVersion=25.21.14.1634
	Graphics card #1 name: Intel(R) HD Graphics 4600
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x0412
	Graphics card #1 versionInfo: DriverVersion=10.18.14.4264
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 32599.65
	Virtual memory used (MB): 19864.75
	Swap memory total (MB): 16298.90
	Swap memory used (MB): 1797.63
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.18.1-forge-39.0.59
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: GeForce GTX 760/PCIe/SSE2 GL version 3.2.0 NVIDIA 416.34, NVIDIA Corporation
	Window size: 1920x1054
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: mod_resources, vanilla, file/Winthor_Medieval_1.18_v6.8.zip
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-4430 CPU @ 3.00GHz
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['TheDadDude'/172, l='ServerLevel[Big Forge]', x=-623.33, y=65.00, z=395.57]]
	Data Packs: vanilla, mod:mcwbridges, mod:torchmaster (incompatible), mod:repurposed_structures, mod:structurize, mod:mcwdoors, mod:cfm (incompatible), mod:packingtape (incompatible), mod:soaringstructures2 (incompatible), mod:advancedcompass, mod:domum_ornamentum (incompatible), mod:mcwwindows, mod:forge, mod:blockui, mod:multipiston (incompatible), mod:minecolonies (incompatible), mod:xaerominimap, mod:exp_bottling (incompatible), mod:gravestone (incompatible), mod:xaeroworldmap, file/HammerHead.zip (incompatible), file/mineralmassacre-1556230115.zip (incompatible), file/treecapitator-v2-7-2.zip (incompatible)
	ModLauncher: 9.1.0+9.1.0+main.6690ee51
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		mcw-bridges-2.0.1-mc1.18.1.jar                    |Macaw's Bridges               |mcwbridges                    |2.0.1               |DONE      |Manifest: NOSIGNATURE
		torchmaster-18.0.2-beta.jar                       |Torchmaster                   |torchmaster                   |18.0.2-beta         |DONE      |Manifest: NOSIGNATURE
		repurposed_structures_forge-4.0.9+1.18.1.jar      |Repurposed Structures         |repurposed_structures         |4.0.9+1.18.1        |DONE      |Manifest: NOSIGNATURE
		structurize-1.18.1-1.0.319-BETA.jar               |Structurize                   |structurize                   |1.18.1-1.0.319-BETA |DONE      |Manifest: NOSIGNATURE
		mcw-doors-1.0.5-mc1.18.1.jar                      |Macaw's Doors                 |mcwdoors                      |1.0.5               |DONE      |Manifest: NOSIGNATURE
		furniture-7.0.0-pre27-1.18.1.jar                  |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre27         |DONE      |Manifest: NOSIGNATURE
		PackingTape-1.18-0.12.2.jar                       |Packing Tape                  |packingtape                   |0.12.2              |DONE      |Manifest: NOSIGNATURE
		Soaring-Structures-2-1.18.1-2.0.jar               |Soaring Structures 2          |soaringstructures2            |1.18.1 - 2.0        |DONE      |Manifest: NOSIGNATURE
		AdvancedCompas-forge-1.18-1.2.6.jar               |Advanced Compass              |advancedcompass               |1.2.6               |DONE      |Manifest: NOSIGNATURE
		domum_ornamentum-1.18-1.0.31-ALPHA-universal.jar  |Domum Ornamentum              |domum_ornamentum              |1.18-1.0.31-ALPHA   |DONE      |Manifest: NOSIGNATURE
		mcw-windows-2.0.2-mc1.18.1.jar                    |Macaw's Windows               |mcwwindows                    |2.0.2               |DONE      |Manifest: NOSIGNATURE
		forge-1.18.1-39.0.59-universal.jar                |Forge                         |forge                         |39.0.59             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		blockui-1.18-0.0.40-ALPHA.jar                     |UI Library Mod                |blockui                       |1.18-0.0.40-ALPHA   |DONE      |Manifest: NOSIGNATURE
		multi-piston-1.18-1.2.2-ALPHA.jar                 |Multi-Piston                  |multipiston                   |1.18-1.2.2-ALPHA    |DONE      |Manifest: NOSIGNATURE
		minecolonies-1.18.1-1.0.278-RELEASE.jar           |MineColonies                  |minecolonies                  |1.18.1-1.0.278-RELEA|DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_22.1.0_Forge_1.18.jar              |Xaero's Minimap               |xaerominimap                  |22.1.0              |DONE      |Manifest: NOSIGNATURE
		exp_bottling-1.18.1-0.jar                         |EXP Bottling                  |exp_bottling                  |1.18.1-0            |DONE      |Manifest: NOSIGNATURE
		gravestone-1.18.1-1.0.0.jar                       |Gravestone Mod                |gravestone                    |1.18.1-1.0.0        |DONE      |Manifest: NOSIGNATURE
		XaerosWorldMap_1.20.0_Forge_1.18.jar              |Xaero's World Map             |xaeroworldmap                 |1.20.0              |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 535f97fd-9682-4be7-96a8-c4328490e66b
	FML: 39.0
	Forge: net.minecraftforge:39.0.59

**Comment by uecasm** [comment]
Update to the latest ALPHA.  Ensure that the dependencies are the correct version as well (read the changelog on curseforge), and that you don't have duplicates in your mods folder.
