### ISSUE TITLE
Game freeze on build completion

### ISSUE THREAD

**Issue by apfelgluck89** [ldtteam/minecolonies#7996]
### Prerequisites 
- [X] I am running the latest **alpha** version of MineColonies and Structurize for my Minecraft version.
- [ X] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure my issue is not covered there.
- [ X] I made sure that **this issue is not a duplicate of any existing issue.**

### Context 

- Minecraft Version: 1.18.1
- MineColonies Version: 1.18.1-1.0.355-ALPHA
- Structurize Version: 1.18.1-1.0.326-ALPHA

## Problem description
on building completion the game freezes

### Notes or related things
log extract :

[26janv.2022 15:10:40.386] [Render thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: class net.minecraft.world.entity.projectile.FireworkRocketEntity cannot be cast to class net.minecraft.world.entity.projectile.AbstractArrow (net.minecraft.world.entity.projectile.FireworkRocketEntity and net.minecraft.world.entity.projectile.AbstractArrow are in module minecraft@1.18.1 of loader 'TRANSFORMER' @433ef204)
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: class com.zainjx.pickup_arrows.events.EventHandler onProjectileHit(Lnet/minecraftforge/event/entity/ProjectileImpactEvent;)V
java.lang.ClassCastException: class net.minecraft.world.entity.projectile.FireworkRocketEntity cannot be cast to class net.minecraft.world.entity.projectile.AbstractArrow (net.minecraft.world.entity.projectile.FireworkRocketEntity and net.minecraft.world.entity.projectile.AbstractArrow are in module minecraft@1.18.1 of loader 'TRANSFORMER' @433ef204)
	at TRANSFORMER/pickup_arrows@1.0/com.zainjx.pickup_arrows.events.EventHandler.onProjectileHit(EventHandler.java:20)
	at net.minecraftforge.eventbus.ASMEventHandler_87_EventHandler_onProjectileHit_ProjectileImpactEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/forge@39.0.9/net.minecraftforge.event.ForgeEventFactory.onProjectileImpact(ForgeEventFactory.java:635)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.entity.projectile.FireworkRocketEntity.m_6532_(FireworkRocketEntity.java:152)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.entity.projectile.FireworkRocketEntity.m_8119_(FireworkRocketEntity.java:130)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.client.multiplayer.ClientLevel.m_104639_(ClientLevel.java:222)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.level.Level.m_46653_(Level.java:487)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.client.multiplayer.ClientLevel.m_194182_(ClientLevel.java:204)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.client.multiplayer.ClientLevel.m_104804_(ClientLevel.java:202)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1674)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1015)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.client.main.Main.main(Main.java:205)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.18.1-39.0.9/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@0.1.17/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90)

---

**Comment by uecasm** [comment]
Please post a paste/gist link to the full log in the future.

However it looks like this is a bug in the Pickup Arrows mod; you should remove it and report the crash to them.  They appear to not be dealing with the fact that things other than arrows (such as fireworks) are also projectiles.

**Comment by apfelgluck89** [comment]
Fool of me not to see that. It's fine now.
Thanks a lot.
