### ISSUE TITLE
My Modded 1.18.1 Minecraft Keeps Crashing When I Join My World

### ISSUE THREAD

**Issue by Doglover2185** [ldtteam/minecolonies#8011]
Hi Randomly I Went To Join My World Im In Then It Crashes Please Help Heres This "The game crashed whilst unexpected error
Error: java.util.ConcurrentModificationException: null
Exit Code: -1" And Heres The Crash Report "---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 1/30/22, 9:04 AM
Description: Unexpected error

java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?] {}
	at java.util.HashMap$KeyIterator.next(HashMap.java:1620) ~[?:?] {}
	at net.minecraft.client.renderer.texture.TextureManager.m_7673_(TextureManager.java:161) ~[client-1.18.1-20211210.034407-srg.jar%23109!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1616) ~[client-1.18.1-20211210.034407-srg.jar%23109!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1015) ~[client-1.18.1-20211210.034407-srg.jar%23109!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.18.1-20211210.034407-srg.jar%23109!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%23109!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.59.jar%2323!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?] {}
	at java.util.HashMap$KeyIterator.next(HashMap.java:1620) ~[?:?] {}
	at net.minecraft.client.renderer.texture.TextureManager.m_7673_(TextureManager.java:161) ~[client-1.18.1-20211210.034407-srg.jar%23109!/:?] {re:classloading,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['Doglover2185'/154, l='ClientLevel', x=236.62, y=68.00, z=3071.65]]
	Chunk stats: 729, 453
	Level dimension: minecraft:overworld
	Level spawn location: World: (-32,75,64), Section: (at 0,11,0 in -2,4,4; chunk contains blocks -32,-64,64 to -17,319,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 775698 game time, 1086233 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:407) ~[client-1.18.1-20211210.034407-srg.jar%23109!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:create.mixins.json:DestroyProgressMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2248) ~[client-1.18.1-20211210.034407-srg.jar%23109!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:682) ~[client-1.18.1-20211210.034407-srg.jar%23109!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%23109!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.59.jar%2323!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Mod Resources, quark-emote-pack, Custom Music Disk.zip

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 5942310880 bytes (5667 MiB) / 9328132096 bytes (8896 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 60 Stepping 3
	Microarchitecture: Haswell (Client)
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GT 730
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x0f02
	Graphics card #0 versionInfo: DriverVersion=23.21.13.9135
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 1.60
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 1.60
	Memory slot #1 type: DDR3
	Memory slot #2 capacity (MB): 4096.00
	Memory slot #2 clockSpeed (GHz): 1.60
	Memory slot #2 type: DDR3
	Memory slot #3 capacity (MB): 4096.00
	Memory slot #3 clockSpeed (GHz): 1.60
	Memory slot #3 type: DDR3
	Virtual memory max (MB): 22467.66
	Virtual memory used (MB): 19110.79
	Swap memory total (MB): 6144.00
	Swap memory used (MB): 999.75
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12288m -Xms256m
	Launched Version: forge-39.0.59
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: GeForce GT 730/PCIe/SSE2 GL version 3.2.0 NVIDIA 391.35, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources, quark:emote_resources (incompatible), file/Custom Music Disk.zip
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Doglover2185'/154, l='ServerLevel[Qulity Of Life Minecraft]', x=236.62, y=68.00, z=3071.65]]
	Data Packs: vanilla, mod:fullbrightnesstoggle, mod:theoneprobe (incompatible), mod:bk, mod:craftablesaddle (incompatible), mod:jei (incompatible), mod:kleeslabs, mod:collective, mod:clumps (incompatible), mod:journeymap, mod:justenoughprofessions, mod:oreexcavation, mod:customvillagertrades, mod:dolberhats (incompatible), mod:cfm, mod:balm (incompatible), mod:jeresources, mod:diamond (incompatible), mod:craftabletotemofundying (incompatible), mod:forge, mod:portablecraftingtable (incompatible), mod:stackableeverything, mod:cosmeticarmorreworked (incompatible), mod:mob_grinding_utils, mod:chiselsandbits, mod:emerald (incompatible), mod:flywheel, mod:create, mod:betterfurnacesreforged (incompatible), mod:copperequipment, mod:ultimatefurnaces_bfr (incompatible), mod:createfa, mod:clienttweaks, mod:repurposed_structures, mod:swingthroughgrass, mod:no_null_processors, mod:trashslot, mod:inventorytotem, mod:maincard, mod:caelus, mod:curios, mod:feature_nbt_deadlock_be_gone, mod:jeed (incompatible), mod:curiouselytra, mod:corpse, mod:craftpresence, mod:doggytalents, mod:zombieawareness (incompatible), mod:coroutil (incompatible), mod:ore_tree, mod:amethyst_tweakz, mod:bonsaitrees3, mod:forgottenrecipes (incompatible), mod:autoreglib (incompatible), mod:quark (incompatible), mod:actuallyusefulstonecutter (incompatible), mod:betteradvancements, mod:puzzleslib, mod:enchantinginfuser
	ModLauncher: 9.1.0+9.1.0+main.6690ee51
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		CraftPresence-Forge-1.18.1-Release-1.8.8.jar      |CraftPresence                 |craftpresence                 |1.8.8               |DONE      |Manifest: NOSIGNATURE
		clienttweaks-forge-1.18-7.0.0.jar                 |Client Tweaks                 |clienttweaks                  |7.0.0               |DONE      |Manifest: NOSIGNATURE
		fullbrightnesstoggle_1.18.1-1.4.jar               |Full Brightness Toggle        |fullbrightnesstoggle          |1.4                 |DONE      |Manifest: NOSIGNATURE
		no_null_processors_forge-2.0.2+1.18.1.jar         |No Null Processors            |no_null_processors            |2.0.2+1.18.1        |DONE      |Manifest: NOSIGNATURE
		trashslot-forge-1.18-11.0.0.jar                   |TrashSlot                     |trashslot                     |11.0.0              |DONE      |Manifest: NOSIGNATURE
		CraftableSaddle-1.18.1-2.0.0.jar                  |Craftable Saddle              |craftablesaddle               |2.0.0               |DONE      |Manifest: NOSIGNATURE
		jei-1.18.1-9.2.1.69.jar                           |Just Enough Items             |jei                           |9.2.1.69            |DONE      |Manifest: NOSIGNATURE
		DoggyTalents-1.18.1-2.4.2.jar                     |Doggy Talents 2               |doggytalents                  |2.4.2               |DONE      |Manifest: NOSIGNATURE
		caelus-forge-1.18-3.0.0.1.jar                     |Caelus API                    |caelus                        |1.18-3.0.0.1        |DONE      |Manifest: NOSIGNATURE
		kleeslabs-forge-1.18.1-11.0.1.jar                 |KleeSlabs                     |kleeslabs                     |11.0.1              |DONE      |Manifest: NOSIGNATURE
		Clumps-forge-1.18.1-8.0.0+5.jar                   |Clumps                        |clumps                        |8.0.0+5             |DONE      |Manifest: NOSIGNATURE
		journeymap-1.18.1-5.8.0beta11.jar                 |Journeymap                    |journeymap                    |5.8.0beta11         |DONE      |Manifest: NOSIGNATURE
		customvillagertrades-1.18_V14.jar                 |Custom Villager Trades        |customvillagertrades          |1.18 v14            |DONE      |Manifest: NOSIGNATURE
		zombieawareness-1.18.1-1.12.3.jar                 |Zombie Awareness              |zombieawareness               |1.18.1-1.12.3       |DONE      |Manifest: NOSIGNATURE
		feature_nbt_deadlock_be_gone_forge-1.0.0+1.18.1.ja|Feature NBT Deadlock Be Gone  |feature_nbt_deadlock_be_gone  |1.0.0+1.18.1        |DONE      |Manifest: NOSIGNATURE
		bonsaitrees3-3.0.0.jar                            |Bonsai Trees 3                |bonsaitrees3                  |3.0.0               |DONE      |Manifest: NOSIGNATURE
		ore_tree-0.2.3.jar                                |Ore Tree                      |ore_tree                      |0.2.3               |DONE      |Manifest: NOSIGNATURE
		ncobc-1.18.1-1.4.jar                              |Non Craftable Items Become Cra|dolberhats                    |1.4                 |DONE      |Manifest: NOSIGNATURE
		jeed-1.18-1.6.jar                                 |Just Enough Effect Description|jeed                          |1.18-1.6            |DONE      |Manifest: NOSIGNATURE
		balm-2.4.1+0.jar                                  |Balm                          |balm                          |2.4.1+0             |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.18.1-0.13.1.141.jar         |Just Enough Resources         |jeresources                   |0.13.1.141          |DONE      |Manifest: NOSIGNATURE
		CopperEquipment-Forge1.18.1-1.2.jar               |Copper Equipment              |copperequipment               |1.2                 |DONE      |Manifest: NOSIGNATURE
		forge-1.18.1-39.0.59-universal.jar                |Forge                         |forge                         |39.0.59             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		createfa-1.18.1_v1.0.8.jar                        |CreateFoodAdditions           |createfa                      |1.0.8               |DONE      |Manifest: NOSIGNATURE
		mob_grinding_utils-1.18.1-0.4.33.jar              |Mob Grinding Utils            |mob_grinding_utils            |1.18.1-0.4.33       |DONE      |Manifest: NOSIGNATURE
		forgottenrecipes-forge-1.18.1-1.0.0.jar           |Forgotten Recipes             |forgottenrecipes              |1.18.1-1.0.0        |DONE      |Manifest: NOSIGNATURE
		corpse-1.18.1-1.0.4.jar                           |Corpse                        |corpse                        |1.18.1-1.0.4        |DONE      |Manifest: NOSIGNATURE
		Easy Emerald-1.18.1-3.2.0.jar                     |Easy Emerald                  |emerald                       |3.2.0               |DONE      |Manifest: NOSIGNATURE
		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		repurposed_structures_forge-4.2.4+1.18.1.jar      |Repurposed Structures         |repurposed_structures         |4.2.4+1.18.1        |DONE      |Manifest: NOSIGNATURE
		theoneprobe-1.18-5.0.3.jar                        |The One Probe                 |theoneprobe                   |1.18-5.0.3          |DONE      |Manifest: NOSIGNATURE
		swingthroughgrass-1.18.1-1.8.0.jar                |SwingThroughGrass             |swingthroughgrass             |1.18.1-1.8.0        |DONE      |Manifest: NOSIGNATURE
		AmethystTweakz.jar                                |Amethyst Tweakz               |amethyst_tweakz               |1.0                 |DONE      |Manifest: NOSIGNATURE
		inventorytotem_1.18.1-1.6.jar                     |Inventory Totem               |inventorytotem                |1.6                 |DONE      |Manifest: NOSIGNATURE
		Beekeeper-1.18-1.0.0.4.jar                        |Beekeeper                     |bk                            |1.0.0.4             |DONE      |Manifest: NOSIGNATURE
		keycard  ink v1.1.jar                             |Card Mod by eXe               |maincard                      |1.1                 |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.18-0.6.0.jar                     |Flywheel                      |flywheel                      |1.18-0.6.0          |DONE      |Manifest: NOSIGNATURE
		create-mc1.18.1_v0.4d.jar                         |Create                        |create                        |0.4d                |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.18.1-5.0.6.0.jar                   |Curios API                    |curios                        |1.18.1-5.0.6.0      |DONE      |Manifest: NOSIGNATURE
		collective-1.18.1-3.8.jar                         |Collective                    |collective                    |3.8                 |DONE      |Manifest: NOSIGNATURE
		JustEnoughProfessions-1.18-1.2.2.jar              |Just Enough Professions (JEP) |justenoughprofessions         |1.2.2               |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.7-52.jar                             |AutoRegLib                    |autoreglib                    |1.7-52              |DONE      |Manifest: NOSIGNATURE
		Quark-3.0-334.jar                                 |Quark                         |quark                         |3.0-334             |DONE      |Manifest: NOSIGNATURE
		OreExcavation-1.10.159.jar                        |OreExcavation                 |oreexcavation                 |1.10.159            |DONE      |Manifest: NOSIGNATURE
		coroutil-1.18.1-1.2.37.jar                        |CoroUtil                      |coroutil                      |1.18.1-1.2.37       |DONE      |Manifest: NOSIGNATURE
		Actually Useful Stonecutter-3.0.0 mc 1.18.1.jar   |Actually Useful Stonecutter   |actuallyusefulstonecutter     |3.0.0 mc 1.18.1     |DONE      |Manifest: NOSIGNATURE
		furniture-7.0.0-pre28-1.18.1.jar                  |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre28         |DONE      |Manifest: NOSIGNATURE
		BetterFurnacesReforged-1.18.1-1.2.4.jar           |BetterFurnaces Reforged       |betterfurnacesreforged        |1.18.1-1.2.4        |DONE      |Manifest: NOSIGNATURE
		curiouselytra-forge-1.18.1-5.0.1.0.jar            |Curious Elytra                |curiouselytra                 |1.18.1-5.0.1.0      |DONE      |Manifest: NOSIGNATURE
		PuzzlesLib-v3.1.3-1.18.1-Forge.jar                |Puzzles Lib                   |puzzleslib                    |3.1.3               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		Easy Diamond-1.18.1-3.2.0.jar                     |Easy Diamond                  |diamond                       |3.2.0               |DONE      |Manifest: NOSIGNATURE
		CraftableTotemOfUndying-1.18.1-3.0.0.jar          |Craftable Totem Of Undying    |craftabletotemofundying       |3.0.0               |DONE      |Manifest: NOSIGNATURE
		Ultimate-Furnaces-BFR-1.18.1-1.1.1.jar            |Ultimate Furnaces             |ultimatefurnaces_bfr          |1.18.1-1.1.1        |DONE      |Manifest: NOSIGNATURE
		PortableCraftingTable-1.18.1-3.0.0.jar            |Portable Crafting Table       |portablecraftingtable         |3.0.0               |DONE      |Manifest: NOSIGNATURE
		stackableeverything-1.18.1-1.0.jar                |Everything is Stackable!      |stackableeverything           |1.0                 |DONE      |Manifest: NOSIGNATURE
		CosmeticArmorReworked-1.18.1-v1a.jar              |CosmeticArmorReworked         |cosmeticarmorreworked         |1.18.1-v1a          |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		ChiselsBits-forge-1.18.1-1.2.77-universal.jar     |Chisels & bits                |chiselsandbits                |1.2.77              |DONE      |Manifest: NOSIGNATURE
		EnchantingInfuser-v3.1.1-1.18.1-Forge.jar         |Enchanting Infuser            |enchantinginfuser             |3.1.1               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		BetterAdvancements-1.18.1-0.1.2.122.jar           |Better Advancements           |betteradvancements            |0.1.2.122           |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: c6b21447-d83c-4bd5-98bc-6ee96b97b17c
	Flywheel Backend: GL33 Instanced Arrays
	FML: 39.0
	Forge: net.minecraftforge:39.0.59" Please Help Me Fix This

**Comment by Raycoms** [comment]
Doesn't seem to be a MineColonies issue. For general support -> discord.minecolonies.com
