### ISSUE TITLE
Field marker causing crash

### ISSUE THREAD

**Issue by Nachtflame** [ldtteam/minecolonies#838]
### Minecolonies version

version 0.6.3277

### Expected behavior

- Placing Scarecrow Field marker allowing Farmer to work.

### Actual behaviour

- After placement by either Player or Colonist, 'Field' causes crash upon activation of tile-entity, seemingly by attempting to cause Non-Farmer colonist to try to pathfind to it.  (Verified even that the name of the Entity being ticked is an UnEmployed colonist.)
[crash-2017-04-21_16.17.42-server.txt](https://github.com/Minecolonies/minecolonies/files/948611/crash-2017-04-21_16.17.42-server.txt)

**Comment by marvin-bitterlich** [comment]
```
java.lang.NullPointerException: Ticking entity
	at com.minecolonies.coremod.util.EntityUtils.getEntityFromUUID(EntityUtils.java:214)
	at com.minecolonies.coremod.tileentities.ScarecrowTileEntity.onLoad(ScarecrowTileEntity.java:112)
	at net.minecraft.world.chunk.Chunk.func_177426_a(Chunk.java:821)
	at net.minecraft.world.chunk.Chunk.func_150813_a(Chunk.java:798)
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:490)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:96)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:115)
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:86)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:132)
	at net.minecraft.world.World.func_72964_e(World.java:303)
	at net.minecraft.world.ChunkCache.<init>(ChunkCache.java:37)
	at com.minecolonies.coremod.entity.pathfinding.AbstractPathJob.<init>(AbstractPathJob.java:146)
	at com.minecolonies.coremod.entity.pathfinding.AbstractPathJob.<init>(AbstractPathJob.java:126)
	at com.minecolonies.coremod.entity.pathfinding.PathJobMoveToLocation.<init>(PathJobMoveToLocation.java:35)
	at com.minecolonies.coremod.entity.pathfinding.PathNavigate.moveToXYZ(PathNavigate.java:165)
	at com.minecolonies.coremod.entity.pathfinding.PathNavigate.func_75492_a(PathNavigate.java:113)
	at com.minecolonies.coremod.entity.ai.minimal.EntityAICitizenWander.func_75249_e(EntityAICitizenWander.java:124)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:102)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:773)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2183)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:155)
	at com.minecolonies.coremod.entity.EntityCitizen.func_70636_d(EntityCitizen.java:886)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Nachtflame** [comment]
After Further testing, I have NOT been able to replicate the issue on any other world.  Also, our world seems to be suffering the same crash issue no matter how far into our backups I go.  

In short, I now feel this issue is more of a Localized Server issue than a bug in the mod.  Thank you for taking the time to look at this though.

Odd circumstances of note on our server - 
I'm currently the Owner of a town Placed by another player (happened during an update before the ownership change commands).  That town is Thousands of blocks away from where I was building the Field in the town I actually placed (Which I am only an officer in, NO mayor).  
Is it possible that in such a situation, the Field would call out to an 'Auto-Assign-Fields' Farmer in the town I am the Mayor of, rather than a local farmer?  If so, I could certainly understand the problems trying to pathfind such a distance (through unloaded areas) causing a crash.

**Comment by Raycoms** [comment]
Please reopen this as soon as able to reproduce.
Seems like the scarecrow lost its tile entity.
