### ISSUE TITLE
[BUG] Builder broke, told to report to dev

### ISSUE THREAD

**Issue by TheonlyTazz** [ldtteam/minecolonies#8740]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.18

### MineColonies Version

minecolonies-1.18.2-1.0.1075-ALPHA.jar

### Structurize Version

structurize-1.18.2-1.0.424-ALPHA.jar

### Related Mods and their Versions

FTB Inferno V1.1.1 Modpack

Forge 40.1.80

### Current Behavior

Builder wont work anymore
![image](https://user-images.githubusercontent.com/3908847/198949651-34035dd9-4b9b-4657-986e-32ac30104d53.png)

### Expected Behavior

for the Builder to work again

### Reproduction Steps

unsure how this happened, happened to a user on Threefolds discord who reached out to me

### Logs

https://gist.github.com/TheonlyTazz/2e60a4914a5cc5ff4a64eb6ee22acd07

### Anything else?

```js
[28Oct2022 22:15:30.270] [Server thread/ERROR] [minecolonies/]: Pausing Entity Madalynn J. Grimbald (com.minecolonies.job.builder) at BlockPos{x=241, y=128, z=5427} for 400 Seconds because of error:
[28Oct2022 22:16:12.272] [Server thread/WARN] [minecolonies/]: Statemachine for transition com.minecolonies.api.entity.ai.statemachine.AITarget@7f9db137 threw an exception:
java.lang.IllegalArgumentException: The given request: StandardToken{id=63a3896f-4928-4bd7-a156-44f825926ce4} is not resolved.
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.ResolverHandler.getResolverForRequest(ResolverHandler.java:405) ~[minecolonies-1.18.2-1.0.1075-ALPHA.jar%23220!/:1.18.2-1.0.1075-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.ResolverHandler.getResolverForRequest(ResolverHandler.java:421) ~[minecolonies-1.18.2-1.0.1075-ALPHA.jar%23220!/:1.18.2-1.0.1075-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.manager.StandardRequestManager.getResolverForRequest(StandardRequestManager.java:275) ~[minecolonies-1.18.2-1.0.1075-ALPHA.jar%23220!/:1.18.2-1.0.1075-ALPHA]
	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic.lookForRequests(AbstractEntityAIBasic.java:596) ~[minecolonies-1.18.2-1.0.1075-ALPHA.jar%23220!/:1.18.2-1.0.1075-ALPHA]
	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic.waitForRequests(AbstractEntityAIBasic.java:540) ~[minecolonies-1.18.2-1.0.1075-ALPHA.jar%23220!/:1.18.2-1.0.1075-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:79) ~[minecolonies-1.18.2-1.0.1075-ALPHA.jar%23220!/:1.18.2-1.0.1075-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:163) ~[minecolonies-1.18.2-1.0.1075-ALPHA.jar%23220!/:1.18.2-1.0.1075-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:149) ~[minecolonies-1.18.2-1.0.1075-ALPHA.jar%23220!/:1.18.2-1.0.1075-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:129) ~[minecolonies-1.18.2-1.0.1075-ALPHA.jar%23220!/:1.18.2-1.0.1075-ALPHA]
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:108) ~[minecolonies-1.18.2-1.0.1075-ALPHA.jar%23220!/:1.18.2-1.0.1075-ALPHA]
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.m_8037_(AbstractAISkeleton.java:133) ~[minecolonies-1.18.2-1.0.1075-ALPHA.jar%23220!/:1.18.2-1.0.1075-ALPHA]
	at net.minecraft.world.entity.ai.goal.WrappedGoal.m_8037_(WrappedGoal.java:65) ~[client-1.18.2-20220404.173914-srg.jar%23309!/:?]
	at com.minecolonies.api.entity.CustomGoalSelector.m_25373_(CustomGoalSelector.java:231) ~[minecolonies-1.18.2-1.0.1075-ALPHA.jar%23220!/:1.18.2-1.0.1075-ALPHA]
	at net.minecraft.world.entity.Mob.m_6140_(Mob.java:698) ~[client-1.18.2-20220404.173914-srg.jar%23309!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8107_(LivingEntity.java:2506) ~[client-1.18.2-20220404.173914-srg.jar%23309!/:?]
	at net.minecraft.world.entity.Mob.m_8107_(Mob.java:495) ~[client-1.18.2-20220404.173914-srg.jar%23309!/:?]
	at net.minecraft.world.entity.AgeableMob.m_8107_(AgeableMob.java:127) ~[client-1.18.2-20220404.173914-srg.jar%23309!/:?]
	at com.minecolonies.api.entity.citizen.AbstractEntityCitizen.m_8107_(AbstractEntityCitizen.java:400) ~[minecolonies-1.18.2-1.0.1075-ALPHA.jar%23220!/:1.18.2-1.0.1075-ALPHA]
	at com.minecolonies.coremod.entity.citizen.EntityCitizen.m_8107_(EntityCitizen.java:706) ~[minecolonies-1.18.2-1.0.1075-ALPHA.jar%23220!/:1.18.2-1.0.1075-ALPHA]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2253) ~[client-1.18.2-20220404.173914-srg.jar%23309!/:?]
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:307) ~[client-1.18.2-20220404.173914-srg.jar%23309!/:?]
	at com.minecolonies.api.entity.citizen.AbstractCivilianEntity.m_8119_(AbstractCivilianEntity.java:114) ~[minecolonies-1.18.2-1.0.1075-ALPHA.jar%23220!/:1.18.2-1.0.1075-ALPHA]
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:652) ~[client-1.18.2-20220404.173914-srg.jar%23309!/:?]
	at dev.wuffs.itshallnottick.TickOptimizer.handleGuardEntityTick(TickOptimizer.java:59) ~[ItShallNotTick-1.0.22-build.34.jar%23194!/:1.0.22-build.34]
	at dev.wuffs.itshallnottick.TickOptimizer.entityTicking(TickOptimizer.java:27) ~[ItShallNotTick-1.0.22-build.34.jar%23194!/:1.0.22-build.34]
	at net.minecraft.world.level.Level.m_46653_(Level.java:2071) ~[client-1.18.2-20220404.173914-srg.jar%23309!/:?]
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:319) ~[client-1.18.2-20220404.173914-srg.jar%23309!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.18.2-20220404.173914-srg.jar%23309!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:299) ~[client-1.18.2-20220404.173914-srg.jar%23309!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[client-1.18.2-20220404.173914-srg.jar%23309!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%23309!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23309!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%23309!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23309!/:?]
	at java.lang.Thread.run(Unknown Source) [?:?]```

**Comment by EvaRaud** [comment]
same problem

**Comment by Rockdrigo713** [comment]
I also ran into the same problem

**Comment by Raycoms** [comment]
Is there any way to reproduce this?

**Comment by TheonlyTazz** [comment]
the person in question who reached out the me about this issue has told me that =>

Firing and re-hiring a colonist should fix the AI incase this happen to anyone

**Comment by Phoenixavenger21** [comment]
Yeah although I didn't re-hire the builder back to being a builder so idk if that would work, but switching your builder and letting the broken colonist find another job seemed to have worked

**Comment by kakol20** [comment]
I encountered the same issue too. I am not sure how relevant this is but - I have two builders and only one of them showed this message. The broken builder was almost finished placing blocks, while the unbroken builder just started and was clearing terrain.
