### ISSUE TITLE
Minecolonies : my game crashed when i placed supply camp

### ISSUE THREAD

**Issue by Locha006** [ldtteam/minecolonies#8979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

minecolonies-1.19.2-1.0.1247-BETA.jar

### Structurize Version

structurize-1.19.2-1.0.472-BETA.jar

### Related Mods and their Versions

1. Newest

### Logs

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2023-02-27 22:53:32
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot get property EnumProperty{name=variant, clazz=class com.minecolonies.api.blocks.types.RackType, values=[blockrackemptysingle, blockrackfullsingle, blockrackempty, blockrackfull, blockrackair]} as it does not exist in Block{minecolonies:blockhutdeliveryman}
	at net.minecraft.world.level.block.state.StateHolder.m_61143_(StateHolder.java:98) ~[client-1.19.2-20220805.130853-srg.jar%23235!/:?] {re:classloading,re:mixin}
	at com.minecolonies.api.tileentities.TileEntityRack.getCapability(TileEntityRack.java:441) ~[minecolonies-1.19.2-1.0.1226-BETA.jar%23213!/:1.19.2-1.0.1226-BETA] {re:classloading}
	at com.minecolonies.api.tileentities.TileEntityColonyBuilding.getCapability(TileEntityColonyBuilding.java:608) ~[minecolonies-1.19.2-1.0.1226-BETA.jar%23213!/:1.19.2-1.0.1226-BETA] {re:classloading}
	at com.ldtteam.structurize.api.util.ItemStackUtils.getItemHandlersFromProvider(ItemStackUtils.java:116) ~[structurize-1.19.2-1.0.480-ALPHA.jar%23223!/:1.19.2-1.0.480-ALPHA] {re:classloading}
	at com.ldtteam.structurize.api.util.ItemStackUtils.getItemStacksOfTileEntity(ItemStackUtils.java:71) ~[structurize-1.19.2-1.0.480-ALPHA.jar%23223!/:1.19.2-1.0.480-ALPHA] {re:classloading}
	at com.minecolonies.coremod.placementhandlers.HutPlacementHandler.getRequiredItems(HutPlacementHandler.java:129) ~[minecolonies-1.19.2-1.0.1226-BETA.jar%23213!/:1.19.2-1.0.1226-BETA] {re:classloading}
	at com.ldtteam.structurize.placement.StructurePlacer.getResourceRequirements(StructurePlacer.java:476) ~[structurize-1.19.2-1.0.480-ALPHA.jar%23223!/:1.19.2-1.0.480-ALPHA] {re:classloading}
	at com.ldtteam.structurize.placement.StructurePlacer.executeStructureStep(StructurePlacer.java:151) ~[structurize-1.19.2-1.0.480-ALPHA.jar%23223!/:1.19.2-1.0.480-ALPHA] {re:classloading}
	at com.minecolonies.coremod.client.gui.WindowBuildBuilding.lambda$updateResources$6(WindowBuildBuilding.java:319) ~[minecolonies-1.19.2-1.0.1226-BETA.jar%23213!/:1.19.2-1.0.1226-BETA] {re:classloading}
	at com.ldtteam.structurize.storage.ClientFutureProcessor.onWorldTick(ClientFutureProcessor.java:57) ~[structurize-1.19.2-1.0.480-ALPHA.jar%23223!/:1.19.2-1.0.480-ALPHA] {re:classloading}
	at com.ldtteam.structurize.storage.__ClientFutureProcessor_onWorldTick_ClientTickEvent.invoke(.dynamic) ~[structurize-1.19.2-1.0.480-ALPHA.jar%23223!/:1.19.2-1.0.480-ALPHA] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2375!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2375!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2375!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPostClientTick(ForgeEventFactory.java:830) ~[forge-1.19.2-43.2.0-universal.jar%23240!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1850) ~[client-1.19.2-20220805.130853-srg.jar%23235!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1078) ~[client-1.19.2-20220805.130853-srg.jar%23235!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23235!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23235!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23235!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.0.jar%2391!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2378!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2378!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2378!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2378!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2378!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2378!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2378!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at crystallauncher.MinecraftConstructor.run(MinecraftConstructor.java:29) [proxyserver.jar:?] {}
	at crystallauncher.MineClient.start(MineClient.java:228) [proxyserver.jar:?] {}
	at crystallauncher.MineClient.main(MineClient.java:36) [proxyserver.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.world.level.block.state.StateHolder.m_61143_(StateHolder.java:98) ~[client-1.19.2-20220805.130853-srg.jar%23235!/:?] {re:classloading,re:mixin}
	at com.minecolonies.api.tileentities.TileEntityRack.getCapability(TileEntityRack.java:441) ~[minecolonies-1.19.2-1.0.1226-BETA.jar%23213!/:1.19.2-1.0.1226-BETA] {re:classloading}
	at com.minecolonies.api.tileentities.TileEntityColonyBuilding.getCapability(TileEntityColonyBuilding.java:608) ~[minecolonies-1.19.2-1.0.1226-BETA.jar%23213!/:1.19.2-1.0.1226-BETA] {re:classloading}
	at com.ldtteam.structurize.api.util.ItemStackUtils.getItemHandlersFromProvider(ItemStackUtils.java:116) ~[structurize-1.19.2-1.0.480-ALPHA.jar%23223!/:1.19.2-1.0.480-ALPHA] {re:classloading}
	at com.ldtteam.structurize.api.util.ItemStackUtils.getItemStacksOfTileEntity(ItemStackUtils.java:71) ~[structurize-1.19.2-1.0.480-ALPHA.jar%23223!/:1.19.2-1.0.480-ALPHA] {re:classloading}
	at com.minecolonies.coremod.placementhandlers.HutPlacementHandler.getRequiredItems(HutPlacementHandler.java:129) ~[minecolonies-1.19.2-1.0.1226-BETA.jar%23213!/:1.19.2-1.0.1226-BETA] {re:classloading}
	at com.ldtteam.structurize.placement.StructurePlacer.getResourceRequirements(StructurePlacer.java:476) ~[structurize-1.19.2-1.0.480-ALPHA.jar%23223!/:1.19.2-1.0.480-ALPHA] {re:classloading}
	at com.ldtteam.structurize.placement.StructurePlacer.executeStructureStep(StructurePlacer.java:151) ~[structurize-1.19.2-1.0.480-ALPHA.jar%23223!/:1.19.2-1.0.480-ALPHA] {re:classloading}
	at com.minecolonies.coremod.client.gui.WindowBuildBuilding.lambda$updateResources$6(WindowBuildBuilding.java:319) ~[minecolonies-1.19.2-1.0.1226-BETA.jar%23213!/:1.19.2-1.0.1226-BETA] {re:classloading}
	at com.ldtteam.structurize.storage.ClientFutureProcessor.onWorldTick(ClientFutureProcessor.java:57) ~[structurize-1.19.2-1.0.480-ALPHA.jar%23223!/:1.19.2-1.0.480-ALPHA] {re:classloading}
	at com.ldtteam.structurize.storage.__ClientFutureProcessor_onWorldTick_ClientTickEvent.invoke(.dynamic) ~[structurize-1.19.2-1.0.480-ALPHA.jar%23223!/:1.19.2-1.0.480-ALPHA] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2375!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2375!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2375!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPostClientTick(ForgeEventFactory.java:830) ~[forge-1.19.2-43.2.0-universal.jar%23240!/:?] {re:classloading}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['walterwhite'/28591, l='ClientLevel', x=551.34, y=66.00, z=-588.68]]
	Chunk stats: 441, 375
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,127,0), Section: (at 0,15,0 in 0,7,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1647980 game time, 756045 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:450) ~[client-1.19.2-20220805.130853-srg.jar%23235!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:blue_skies.mixins.json:ClientLevelMixin,pl:mixin:APP:citadel.mixins.json:client.ClientLevelMixin,pl:mixin:APP:entityculling.mixins.json:ClientWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2278) ~[client-1.19.2-20220805.130853-srg.jar%23235!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:722) ~[client-1.19.2-20220805.130853-srg.jar%23235!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23235!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23235!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.0.jar%2391!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2378!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2378!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2378!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2378!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2378!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2378!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2378!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at crystallauncher.MinecraftConstructor.run(MinecraftConstructor.java:29) [proxyserver.jar:?] {}
	at crystallauncher.MineClient.start(MineClient.java:228) [proxyserver.jar:?] {}
	at crystallauncher.MineClient.main(MineClient.java:36) [proxyserver.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Mod Resources

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Microsoft
	Memory: 1662867752 bytes (1585 MiB) / 4294967296 bytes (4096 MiB) up to 10603200512 bytes (10112 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Intel(R) UHD Graphics 630
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x3e9b
	Graphics card #0 versionInfo: DriverVersion=26.20.100.6911
	Graphics card #1 name: NVIDIA GeForce GTX 1660 Ti
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x2191
	Graphics card #1 versionInfo: DriverVersion=27.21.14.5167
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 34658.61
	Virtual memory used (MB): 15206.59
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 30.04
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10096M -Xms4096M -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.19.2-forge-43.2.0
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: GeForce GTX 1660 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 451.67, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, mod_resources
	Current Language: Polski (Polska)
	CPU: 12x Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		YungsBetterDungeons-1.19.2-Forge-3.2.2.jar        |YUNG's Better Dungeons        |betterdungeons                |1.19.2-Forge-3.2.2  |DONE      |Manifest: NOSIGNATURE
		blue_skies-1.19.2-1.3.20.jar                      |Blue Skies                    |blue_skies                    |1.3.20              |DONE      |Manifest: NOSIGNATURE
		Cucumber-1.19.2-6.0.6.jar                         |Cucumber Library              |cucumber                      |6.0.6               |DONE      |Manifest: NOSIGNATURE
		infernal-expansion-1.19.2-2.5.3.jar               |Infernal Expansion            |infernalexp                   |2.5.1               |DONE      |Manifest: NOSIGNATURE
		jei-1.19.2-forge-11.5.2.1007.jar                  |Just Enough Items             |jei                           |11.5.2.1007         |DONE      |Manifest: NOSIGNATURE
		The_Graveyard_2.2_(FORGE)_for_1.19.2.jar          |The Graveyard                 |graveyard                     |2.2                 |DONE      |Manifest: NOSIGNATURE
		paragon-forge-3.0.2-1.19x.jar                     |Paragon                       |paragon                       |3.0.2               |DONE      |Manifest: NOSIGNATURE
		MobsPropertiesRandomness-4.1.1-mc1.19.2.jar       |Mobs Properties Randomness    |mobspropertiesrandomness      |4.1.1               |DONE      |Manifest: NOSIGNATURE
		Undefeatables+1.7.jar                             |Undefeatables                 |undefeatables                 |1.7                 |DONE      |Manifest: NOSIGNATURE
		InsaneLib-1.7.5-mc1.19.2.jar                      |InsaneLib                     |insanelib                     |1.7.5               |DONE      |Manifest: NOSIGNATURE
		waystones-forge-1.19-11.1.0.jar                   |Waystones                     |waystones                     |11.1.0              |DONE      |Manifest: NOSIGNATURE
		Sorcerium+1.1.3+(1.19.2).jar                      |Sorcerium                     |sorcerium                     |1.1.3               |DONE      |Manifest: NOSIGNATURE
		journeymap-1.19.2-5.9.3-forge.jar                 |Journeymap                    |journeymap                    |5.9.3               |DONE      |Manifest: NOSIGNATURE
		More-Enchantments-Mod-Forge-1.19.3.jar            |More Enchantments             |more_enchantments             |1.4.2               |DONE      |Manifest: NOSIGNATURE
		citadel-2.1.1-1.19.jar                            |Citadel                       |citadel                       |2.1.1               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.21.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.21.1              |DONE      |Manifest: NOSIGNATURE
		TravelersBackpack-1.19.2-8.2.13.jar               |Traveler's Backpack           |travelersbackpack             |8.2.13              |DONE      |Manifest: NOSIGNATURE
		zombieawareness-1.19.2-1.12.3.jar                 |Zombie Awareness              |zombieawareness               |1.19.2-1.12.3       |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.19.2-Forge-3.8.2.jar                   |YUNG's API                    |yungsapi                      |1.19.2-Forge-3.8.2  |DONE      |Manifest: NOSIGNATURE
		DungeonCrawl-1.19-2.3.11.jar                      |Dungeon Crawl                 |dungeoncrawl                  |2.3.11              |DONE      |Manifest: NOSIGNATURE
		toolleveling-forge-1.19.2-1.4.1.jar               |Tool Leveling                 |toolleveling                  |1.19.2-1.4.1        |DONE      |Manifest: NOSIGNATURE
		redstructure-1.0.4-forge-1.19.2.jar               |Reds More Structures          |redmorestructure              |1.0.4-1.19.2        |DONE      |Manifest: NOSIGNATURE
		balm-4.5.3.jar                                    |Balm                          |balm                          |4.5.3               |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.19.2-1.2.1.193.jar          |Just Enough Resources         |jeresources                   |1.2.1.193           |DONE      |Manifest: NOSIGNATURE
		forge-1.19.2-43.2.0-universal.jar                 |Forge                         |forge                         |43.2.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		structure_gel-1.19.2-2.7.1.jar                    |Structure Gel API             |structure_gel                 |2.7.1               |DONE      |Manifest: NOSIGNATURE
		MysticalAgriculture-1.19.2-6.0.7.jar              |Mystical Agriculture          |mysticalagriculture           |6.0.7               |DONE      |Manifest: NOSIGNATURE
		infernalmobs-1.19.2.4.jar                         |Infernal Mobs                 |infernalmobs                  |1.19.2.4            |DONE      |Manifest: NOSIGNATURE
		EnemyExpansion1.11requiresgeckolib.jar            |Enemy Expansion               |enemyexpansion                |1.11.0              |DONE      |Manifest: NOSIGNATURE
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		cofh_core-1.19.2-10.2.1.40.jar                    |CoFH Core                     |cofh_core                     |10.2.1              |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		ensorcellation-1.19.2-4.2.0.14.jar                |Ensorcellation                |ensorcellation                |4.2.0.14            |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		EasierSleeping-1.19.2-2.1.2.jar                   |Easier Sleeping               |easier_sleeping               |2.1.2               |DONE      |Manifest: NOSIGNATURE
		born_in_chaos_1.19_1.2.jar                        |Born in Chaos                 |born_in_chaos_v1              |1.0.0               |DONE      |Manifest: NOSIGNATURE
		dungeons_enhanced-1.19.2-4.1.jar                  |Dungeons Enhanced             |dungeons_enhanced             |4.1                 |DONE      |Manifest: NOSIGNATURE
		domum_ornamentum-1.19-1.0.76-ALPHA-universal.jar  |Domum Ornamentum              |domum_ornamentum              |1.19-1.0.76-ALPHA   |DONE      |Manifest: NOSIGNATURE
		blockui-1.19-0.0.64-ALPHA.jar                     |UI Library Mod                |blockui                       |1.19-0.0.64-ALPHA   |DONE      |Manifest: NOSIGNATURE
		gravestone-1.19.2-1.0.1.jar                       |Gravestone Mod                |gravestone                    |1.19.2-1.0.1        |DONE      |Manifest: NOSIGNATURE
		entityculling-forge-1.5.2-mc1.19.1.jar            |EntityCulling                 |entityculling                 |1.5.1               |DONE      |Manifest: NOSIGNATURE
		structurize-1.19.2-1.0.480-ALPHA.jar              |Structurize                   |structurize                   |1.19.2-1.0.480-ALPHA|DONE      |Manifest: NOSIGNATURE
		coroutil-1.19.2-1.2.37.jar                        |CoroUtil                      |coroutil                      |1.19.2-1.2.37       |DONE      |Manifest: NOSIGNATURE
		minecolonies-1.19.2-1.0.1226-BETA.jar             |MineColonies                  |minecolonies                  |1.19.2-1.0.1226-BETA|DONE      |Manifest: NOSIGNATURE
		deeperdarker-forge-1.1.6-forge.jar                |Deeper and Darker             |deeperdarker                  |1.1.6               |DONE      |Manifest: NOSIGNATURE
		toms_storage-1.19-1.3.10.jar                      |Tom's Simple Storage Mod      |toms_storage                  |1.3.10              |DONE      |Manifest: NOSIGNATURE
		Towns-and-Towers-v.1.10-_FORGE-1.19.2_.jar        |Towns and Towers              |t_and_t                       |1.10                |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.19-3.1.39.jar                    |GeckoLib                      |geckolib3                     |3.1.39              |DONE      |Manifest: NOSIGNATURE
		xptome-1.19-2.1.7.jar                             |XP Tome                       |xpbook                        |2.1.7               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 961e2463-d9e7-48bb-8058-858f75b4c694
	FML: 43.2
	Forge: net.minecraftforge:43.2.0

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Raycoms** [comment]
Without a log we won't be able to do anything

**Comment by Locha006** [comment]
> Without a log we won't be able to do anything
I hope now you can help me with that problem. I added crash report

**Comment by Thodor12** [comment]
Please upload your crash report in a gist, if you paste it here like text it's not readable

**Comment by Thodor12** [comment]
Also why are you stating your version is "minecolonies-1.19.2-1.0.1247-BETA.jar"
when the log says "~[minecolonies-1.19.2-1.0.1226-BETA.jar%23213!/:1.19.2-1.0.1226-BETA]"

Either you are giving us the wrong log or you have stated the incorrect version.
This looks to be a crash related to the deliveryman, nothing related to a supply camp...

**Comment by Raycoms** [comment]
This bug was fixed recently, so you might be on too old of a version.

**Comment by Thodor12** [comment]
Closing because of invalid problem description, feel free to reopen with correct information if the bug still appears
