### ISSUE TITLE
Crash/Can't Create World/Crash on World Creation

### ISSUE THREAD

**Issue by ghost** [ldtteam/minecolonies#899]
forge 2285, minecolonies-universal-1.11.2-0.7.664.jar. please help, thanks.
[crash-2017-04-29_19.38.29-server.txt](https://github.com/Minecolonies/minecolonies/files/966274/crash-2017-04-29_19.38.29-server.txt)

edit: it doesn't happen with minecolonies-universal-1.11-0.6.3360.jar
edit2: it happens with **minecolonies-universal-1.11.2-0.7.683** too.

**Comment by ghost** [comment]
still waiting for help :(

**Comment by Terpo** [comment]
https://gist.github.com/Terpo/ca262da8de4517a8da7308d2f27073d8
with version minecolonies-universal-1.11.2-0.7.683 on forge 2282

When only playing with JEI + Minecolonies it works. If I add a small modlist around it I get the same crash as above mentioned.
Here the small modlist: https://gist.github.com/Terpo/45c74d7509ff6453ccfa028d96e8b126

**Comment by ghost** [comment]
i just look at your small modlist, it happens with recurrentcomplex mod is installed (with ivtoolkit)

**Comment by Terpo** [comment]
I'm currently testing and I come to the same result. IvToolkit itself is working. When activating recurrentcomplex again it crashes.

**Comment by VladimirMangos** [comment]
But downgrade recent version minecolonies also resolve crash.

**Comment by ghost** [comment]
yeah. i'm using minecolonies-universal-1.11-0.6.3360.jar

**Comment by marvin-bitterlich** [comment]
We are looking at this.

**Comment by ghost** [comment]
thanks a lot ^^ get luck with.

**Comment by ghost** [comment]
btw, it crashes on dedicated server too.

**Comment by xavierh** [comment]
Will fix that, shortly 😕

**Comment by Auriel1** [comment]
It is not a specific bug of the 1.11 versions .
In 1.10, all the 0.7.xxx versions don't work any more in the presence of the Recurrent complex mod.

On world creation screen, we can see Loading world, but never Building terrain appear, and we get stuck there. It is not even possible to return to the launcher.

To solve, either downgrade to 1.10.2-0.6.71 (or previous), or delete Recurrent complex mod, what is inconceivable ^^'

<details>
  <summary>---- Minecraft Crash Report ----</summary>
  
at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:113)
	at java.nio.file.FileSystems.newFileSystem(Unknown Source)
	at java.nio.file.FileSystems.newFileSystem(Unknown Source)
	at com.minecolonies.coremod.colony.Structures.loadStyleMaps(Structures.java:122)
	at com.minecolonies.coremod.colony.Structures.init(Structures.java:111)
	at com.minecolonies.coremod.colony.ColonyManager.onWorldLoad(ColonyManager.java:693)
	at com.minecolonies.coremod.event.EventHandler.onWorldLoad(EventHandler.java:370)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1669_EventHandler_onWorldLoad_Load.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.call(Reflector.java:819)
	at Reflector.postForgeBusEvent(Reflector.java:956)
	at Reflector.postForgeBusEvent(Reflector.java:942)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:101)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:197)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Unknown Source)

</details>

**Comment by xavierh** [comment]
should be fixed
