### ISSUE TITLE
[BUG] Unexpected crash

### ISSUE THREAD

**Issue by anonymous563** [ldtteam/minecolonies#9122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.19

### MineColonies Version

minecolonies-1.19.2-1.0.1392-ALPHA

### Structurize Version

structurize-1.19.2-1.0.491-ALPHA

### Related Mods and their Versions

domum_ornamentum-1.19-1.0.83-ALPHA-universal
blockui-1.19-0.0.69-ALPHA

### Reproduction Steps

N/A; was in another window, then Minecraft closed out and came up with the "crashed unexpectedly" error. Logs attached below. Wanted to send this in just in case!

### Logs

https://gist.github.com/anonymous563/edb3d2352652bf7a0ffacbb7dea400bf

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Nightenom** [comment]
U've run out of memory, can't see how much you have "-Xmx"ed, also might be some memory polution from any mod

**Comment by ImEr1c** [comment]
> U've run out of memory, can't see how much you have "-Xmx"ed, also might be some memory polution from any mod

I see a crash from minecolonies, a NullPointerException to be more specific

`Caused by: java.lang.NullPointerException: Cannot invoke "com.minecolonies.api.colony.requestsystem.data.IDataStoreManager.get(com.minecolonies.api.colony.requestsystem.token.IToken, com.google.common.reflect.TypeToken)" because "this.dataStoreManager" is null
	at com.minecolonies.coremod.colony.requestsystem.management.manager.StandardRequestManager.getRequestResolverIdentitiesDataStore(StandardRequestManager.java:581) ~[minecolonies-1.19.2-1.0.1392-ALPHA.jar%23168!/:1.19.2-1.0.1392-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.handlers.ResolverHandler.getResolver(ResolverHandler.java:282) ~[minecolonies-1.19.2-1.0.1392-ALPHA.jar%23168!/:1.19.2-1.0.1392-ALPHA]
	at com.minecolonies.coremod.colony.requestsystem.management.manager.StandardRequestManager.getPlayerResolver(StandardRequestManager.java:386) ~[minecolonies-1.19.2-1.0.1392-ALPHA.jar%23168!/:1.19.2-1.0.1392-ALPHA]
	at com.minecolonies.coremod.client.gui.WindowClipBoard.getOpenRequestsFromBuilding(WindowClipBoard.java:91) ~[minecolonies-1.19.2-1.0.1392-ALPHA.jar%23168!/:1.19.2-1.0.1392-ALPHA]
	at com.minecolonies.coremod.client.gui.AbstractWindowRequestTree.getOpenRequestTreeOfBuilding(AbstractWindowRequestTree.java:176) ~[minecolonies-1.19.2-1.0.1392-ALPHA.jar%23168!/:1.19.2-1.0.1392-ALPHA]
	at com.minecolonies.coremod.client.gui.AbstractWindowRequestTree$1.getElementCount(AbstractWindowRequestTree.java:301) ~[minecolonies-1.19.2-1.0.1392-ALPHA.jar%23168!/:1.19.2-1.0.1392-ALPHA]`

**Comment by MotionlessTrain** [comment]
That happened after the outofmemoryerror. I guess the JVM was probably cleaning/crashing everything ungracefully

**Comment by Nightenom** [comment]
You have to look more carefully, there are two crashes at once `Preparing crash report with UUID ...`, the second - ticking from ui which really shouldn't happen during shutdown, the first started by `java.lang.OutOfMemoryError: Java heap space` which is followed by RS NPE. Also you have got a lot of lag warnings before that, with exponential occurrences - so im almost sure that some mod had bad memory management

**Comment by ImEr1c** [comment]
Then yeah i just looked at the last one

**Comment by anonymous563** [comment]
Is this an mcol issue, or did my computer just derp out for some other reason? Is there anything I need to do?

**Comment by MotionlessTrain** [comment]
It may be caused by another mod, a memory leak or something like that

**Comment by Raycoms** [comment]
Ran out of memory, couldnt establish datastructures, died. There is nothing we can do about this.
