### ISSUE TITLE
[1.11.2-0.7.683] Build Scepter crash

### ISSUE THREAD

**Issue by wilsondgonzales** [ldtteam/minecolonies#915]
### Minecolonies version

1.11.2-0.7.683

### Expected behavior

- not to crash

### Actual behaviour

- crashes

### Steps to reproduce the problem

1. only have a build scepter and no huts in inventory
2. Right click

```at com.google.common.base.Absent.get(Absent.java:47)
	at net.minecraft.nbt.NBTUtil.func_190007_a(SourceFile:201)
	at net.minecraft.nbt.NBTUtil.func_190008_d(SourceFile:192)
	at net.minecraft.world.gen.structure.template.Template.func_186256_b(Template.java:539)
	at com.minecolonies.structures.helpers.Structure.readTemplateFromStream(Structure.java:416)
	at com.minecolonies.structures.helpers.Structure.<init>(Structure.java:133)
	at com.minecolonies.coremod.client.gui.WindowBuildTool.changeSchematic(WindowBuildTool.java:715)
	at com.minecolonies.coremod.client.gui.WindowBuildTool.onDropDownListChanged(WindowBuildTool.java:579)
	at com.minecolonies.blockout.views.DropDownList.setSelectedIndex(DropDownList.java:165)
	at com.minecolonies.coremod.client.gui.WindowBuildTool.updateSchematics(WindowBuildTool.java:548)
	at com.minecolonies.coremod.client.gui.WindowBuildTool.onDropDownListChanged(WindowBuildTool.java:575)
	at com.minecolonies.blockout.views.DropDownList.setSelectedIndex(DropDownList.java:165)
	at com.minecolonies.coremod.client.gui.WindowBuildTool.updateStyles(WindowBuildTool.java:491)
	at com.minecolonies.coremod.client.gui.WindowBuildTool.onDropDownListChanged(WindowBuildTool.java:571)
	at com.minecolonies.blockout.views.DropDownList.setSelectedIndex(DropDownList.java:165)
	at com.minecolonies.coremod.client.gui.WindowBuildTool.setStructureName(WindowBuildTool.java:613)
	at com.minecolonies.coremod.client.gui.WindowBuildTool.onOpened(WindowBuildTool.java:405)
	at com.minecolonies.blockout.Screen.func_73866_w_(Screen.java:97)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:489)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:966)
	at net.minecraftforge.fml.client.FMLClientHandler.showGuiScreen(FMLClientHandler.java:542)
	at net.minecraftforge.fml.common.FMLCommonHandler.showGuiScreen(FMLCommonHandler.java:317)
	at com.minecolonies.blockout.views.Window.open(Window.java:167)
	at com.minecolonies.coremod.proxy.ClientProxy.openBuildToolWindow(ClientProxy.java:91)
	at com.minecolonies.coremod.items.ItemBuildTool.func_180614_a(ItemBuildTool.java:47)
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:166)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:452)
	at PlayerControllerOF.func_187099_a(PlayerControllerOF.java:87)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1521)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2179)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1956)```

**Comment by xavierh** [comment]
@Raycoms It is for me that one too I guess. Still unsure about version number 1.11.2-0.7.683

**Comment by xavierh** [comment]
@wilsondgonzales  Is that in MP or SP?

**Comment by xavierh** [comment]
Also may I have the full log file ?

**Comment by wilsondgonzales** [comment]
it's sp. here's the log. https://paste.ee/p/xN3Br

**Comment by xavierh** [comment]
Wow, so many errors in you log. codechicken does not seems to play nice.

I can not see the error you reported in your log, no trace of at **com.minecolonies.structures.helpers.Structure.<init>(Structure.java:133)**

Did you update since ?

**Comment by wilsondgonzales** [comment]
@xavierh
must've posted a wrong log. i recreated the issue with a new log. the error should be at the end of the log.

https://paste.ee/p/nEikz

**Comment by xavierh** [comment]
Did you customize the schematics ?
Which schematic are you previewing when the crash happen ?

**Comment by wilsondgonzales** [comment]
initially it's the first click of the build scepter. if i have any hut in my inventory, it'll display that, then i can select what type of schem i'm doing.

no customizations were done

**Comment by xavierh** [comment]
If I give you a jar with more logging, will you be able to test it and send me the log ?

**Comment by xavierh** [comment]
Could you try this and send me the log ?
[minecolonies.zip](https://github.com/Minecolonies/minecolonies/files/972856/minecolonies.zip)

**Comment by wilsondgonzales** [comment]
ok i'll get back to you on it

**Comment by wilsondgonzales** [comment]
@xavierh here's the log with the version you gave https://paste.ee/p/9foHI

**Comment by xavierh** [comment]
May I ask you to test again with this build ?
I did not add enough logging in the previous build.
This build contain some fixes not related to your problem too.
[minecolonies.zip](https://github.com/Minecolonies/minecolonies/files/975714/minecolonies.zip)

**Comment by wilsondgonzales** [comment]
@xavierh Here you go https://paste.ee/p/kUUK5
The bug from #914 should also be in the log

**Comment by xavierh** [comment]
Sorry I must have done a mistake, looking at you log, I did not send you the right version.
[minecolonies.zip](https://github.com/Minecolonies/minecolonies/files/976207/minecolonies.zip)
This one should solve #913 and give me more infromation about this one.

Do you mind to try again and send me the log ?
I really appreciate

**Comment by wilsondgonzales** [comment]
here you go @xavierh  https://paste.ee/p/cITUp
The delivery `handoff bug` is still present
just to avoid any version error on my part, the lastest zip is `minecolonies-universal-1.11.2-0.6.1493890637`

**Comment by xavierh** [comment]
No, this one: minecolonies-universal-1.11.2-0.7.1493902175.jar
https://github.com/Minecolonies/minecolonies/files/976207/minecolonies.zip

**Comment by wilsondgonzales** [comment]
@xavierh here you go https://paste.ee/p/YPG22 
this build seems to have fixed the stalled [inventory full] issue from the previous builds
the delivery of items is still there though

**Comment by xavierh** [comment]
You're schematic "scans/Processing plant" schematic seems to be the problem, could you attached it to this issue.
Could you also remove it from your scan folder and look if this does fix it ?

I would not use the delivery man at the moment, he is loosing every item he is meant to deliver.

We will find a fix ASAP for him

**Comment by wilsondgonzales** [comment]
@xavierh that fixed it. the schematic was a scan of some 'refined storage' parts from prior to the mod doing a slight overhaul. everything works. Thanks for taking time to resolve this

**Comment by xavierh** [comment]
no problem
Could you post you schematic ? I need to make some changes so that minecraft does not crash in those situations

**Comment by wilsondgonzales** [comment]
here you go @xavierh 

[Processing plant.zip](https://github.com/Minecolonies/minecolonies/files/978721/Processing.plant.zip)

**Comment by xavierh** [comment]
Does not crash on my computer. @Raycoms @OrionDevelopment Could you try this schematic ?

**Comment by wilsondgonzales** [comment]
@xavierh try loading a save, don't have any huts etc on inventory. i find it only crashes on first click without a hut in inventory coz i think it'll automatically default to the hut selection versus not having one and it defaults to 'my schematics'. it stops crashing on me if i first carry a hut, goto say a wall deco to build. on the next time i click, it opens up with the previous selection.

**Comment by xavierh** [comment]
Will try that. Thanks

**Comment by xavierh** [comment]
Btw I can see the preview of your schematic. So I don't think I will crash for me :(
