### ISSUE TITLE
Crashing when colonist goes to sleep

### ISSUE THREAD

**Issue by anton021** [ldtteam/minecolonies#933]
### Minecolonies version

minecolonies-universal-1.10.2-0.7.713

### Expected behavior

Colonist goes home and sleep

### Actual behaviour

Server crashes. the crash can be prevented by visting the colony on daytime when the colonist aren't going to their hut to sleep or to just outright destroy the citizen hut. On my friends colony sometimes he finds item that has a red zero on the citizen hut chest too.

### Crash log
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.10.2-2221-5.1.0-BETA-2117.jar)
  BiomeTweakerCore (BiomeTweaker-1.10.2-2.1.230.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 5/4/17 9:17 AM
Description: Ticking entity

java.lang.ArrayIndexOutOfBoundsException: -1
	at com.minecolonies.coremod.inventory.InventoryCitizen.func_70299_a(InventoryCitizen.java:539)
	at com.minecolonies.coremod.entity.ai.minimal.EntityAIGoHome.handleSaturation(EntityAIGoHome.java:145)
	at com.minecolonies.coremod.entity.ai.minimal.EntityAIGoHome.func_75249_e(EntityAIGoHome.java:118)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:102)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:773)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2183)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:155)
	at com.minecolonies.coremod.entity.EntityCitizen.func_70636_d(EntityCitizen.java:1052)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:152)
	at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zjm000(WorldServer.java:2757)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:5223)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2122)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.minecolonies.coremod.inventory.InventoryCitizen.func_70299_a(InventoryCitizen.java:539)
	at com.minecolonies.coremod.entity.ai.minimal.EntityAIGoHome.handleSaturation(EntityAIGoHome.java:145)
	at com.minecolonies.coremod.entity.ai.minimal.EntityAIGoHome.func_75249_e(EntityAIGoHome.java:118)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:102)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:773)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2183)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:155)
	at com.minecolonies.coremod.entity.EntityCitizen.func_70636_d(EntityCitizen.java:1052)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:152)
	at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zjm000(WorldServer.java:2757)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1934)

-- Entity being ticked --
Details:
	Entity Type: minecolonies.Citizen (com.minecolonies.coremod.entity.EntityCitizen)
	Entity ID: 391
	Entity Name: Nathan H. Addicock
	Entity's Exact location: -679.93, 64.00, 3194.44
	Entity's Block location: World: (-680,64,3194), Chunk: (at 8,4,10 in -43,199; contains blocks -688,0,3184 to -673,255,3199), Region: (-2,6; contains chunks -64,192 to -33,223, blocks -1024,0,3072 to -513,255,3583)
	Entity's Momentum: -0.02, -0.08, -0.01
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:5223)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2122)

-- Affected level --
Details:
	Level name: world
	All players: 8 total; [EntityPlayerMP['The12thSpaz'/153, l='world', x=-1310.53, y=70.00, z=-4194.02], EntityPlayerMP['StrongShovel'/246, l='world', x=-670.12, y=68.50, z=3238.95], EntityPlayerMP['SalientGreen'/485, l='world', x=-783.70, y=66.00, z=561.84], EntityPlayerMP['swed1shf1sh'/556, l='world', x=2128.30, y=27.30, z=839.30], EntityPlayerMP['brett0007'/1288, l='world', x=-92.90, y=65.00, z=-2685.72], EntityPlayerMP['iHitman_'/1978, l='world', x=-4092.08, y=134.85, z=2905.70], EntityPlayerMP['thatdutchguy87'/2348, l='world', x=-555.65, y=70.00, z=349.15], EntityPlayerMP['TheValkyrieHeart'/3039, l='world', x=2129.24, y=27.00, z=840.70]]
	Chunk stats: ServerChunkCache: 1766 Drop: 0
	Level seed: -909876109
	Level generator: ID 11 - RTG, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-59,68,3), Chunk: (at 5,4,3 in -4,0; contains blocks -64,0,0 to -49,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 121634853 game time, 37433 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (amd64) version 2.6.32-642.4.2.el6.x86_64
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 861176048 bytes (821 MB) / 4784734208 bytes (4563 MB) up to 8502706176 bytes (8108 MB)
	JVM Flags: 4 total; -Xmx8192M -Xms128M -XX:MaxMetaspaceSize=256M -XX:+UseConcMarkSweepGC
	IntCache: cache: 0, tcache: 0, allocated: 9, tallocated: 61
	FML: MCP 9.32 Powered by Forge 12.18.3.2221 31 mods loaded, 30 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (custom_server.jar) 
	UCHIJAAAA	Forge{12.18.3.2221} [Minecraft Forge] (custom_server.jar) 
	UCHIJAAAA	spongeapi{5.1.0-SNAPSHOT-c82cd9e} [SpongeAPI] (minecraft.jar) 
	UCHIJAAAA	sponge{1.10.2-2221-5.1.0-BETA-2117} [SpongeForge] (spongeforge-1.10.2-2221-5.1.0-BETA-2117.jar) 
	UCHIJAAAA	nucleus-mixin{0.25.2-5.1} [Nucleus Mixins] (NucleusMixins-0.25.2-5.1.jar) 
	UCHIJAAAA	BiomeTweaker{2.1.230} [BiomeTweaker] (BiomeTweaker-1.10.2-2.1.230.jar) 
	UCHIJAAAA	BiomesOPlenty{5.0.0.2142} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2142-universal.jar) 
	UCHIJAAAA	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.10.2.jar) 
	UCHIJAAAA	chiselsandbits{12.11} [Chisels & Bits] (chiselsandbits-12.11.jar) 
	UCHIJAAAA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.3.6.1_1.10.2.jar) 
	UCHIJAAAA	props{2.3.6.1} [Decocraft] (Decocraft-2.3.6.1_1.10.2.jar) 
	UCHIJAAAA	pixelmon{5.0.4} [Pixelmon] (Pixelmon-1.10.2-5.0.4-universal.jar) 
	UCHIJAAAA	gameshark{5.0.0} [Gameshark] (Gameshark-1.10.2-5.0.0-universal.jar) 
	UCHIJAAAA	latch{0.4.1} [Latch] (latch-0.4.1.jar) 
	UCHIJAAAA	minecolonies{1.10.2-0.7.713} [MineColonies] (minecolonies-universal-1.10.2-0.7.713.jar) 
	UCHIJAAAA	mysterygift{0.3.1} [Mystery Gift] (MysteryGift-1.10.2-0.3.1-universal.jar) 
	UCHIJAAAA	NBTEdit{1.10.2-2.0.0} [In-game NBTEdit] (NBTEdit-1.10.2-2.0.0.jar) 
	UCHIJAAAA	nucleus{0.22.0-S6.0} [Nucleus] (Nucleus-0.22.0-1.11.2-S6.0-plugin.jar) 
	UCHIJAAAA	permissionsex{2.0-SNAPSHOT-b147} [PermissionsEx] (PermissionsEx-Sponge.jar) 
	UCHIJAAAA	pixelextras{2.2.4} [Pixel Extras] (PixelExtras-1.10.2-2.2.4-universal.jar) 
	UCHIJAAAA	pixelmoneconomybridge{1.2.2} [PixelmonEconomyBridge] (PixelmonEconomyBridge-1.10.2-1.3.0.jar) 
	UCHIJAAAA	playershopsrpg{1.1.0} [PlayerShopsRPG] (PlayerShopsRPG-v1.1.0.jar) 
	UCHIJAAAA	prism{3.0.0} [Prism] (Prism-3.0.0-beta2-28-g5087827-all.jar) 
	UCHIJAAAA	redprotect{7.0.0} [RedProtect] (RedProtect-Sponge-7.0.0-b3.jar) 
	UCHIJAAAA	RTG{4.1.2.2} [Realistic Terrain Generation] (RTG-1.10.2-4.1.2.2.jar) 
	UCHIJAAAA	spawnofpsy{2.3.2} [SpawnOfPsyduck] (SpawnOfPsyduck-1.10.2-2.3.2-universal.jar) 
	UCHIJAAAA	totaleconomy{1.5.3} [Total Economy] (TotalEconomy-v1.5.3.jar) 
	UCHIJAAAA	wondertrade{4.4.5} [Wondertrade] (WonderTrade-1.10.2-4.4.5-universal.jar) 
	UCHIJAAAA	worldedit{6.1.4} [WorldEdit] (worldedit-forge-mc1.10.2-6.1.4-dist.jar) 
	UD	BiomeTweakerCore{2.1.230} [BiomeTweaker Core] (minecraft.jar) 
	Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.10.2-2221-5.1.0-BETA-2117.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
BiomeTweakerCore (BiomeTweaker-1.10.2-2.1.230.jar)
  me.superckl.biometweaker.core.BiomeTweakerASMTransformer
	Profiler Position: N/A (disabled)
	Player Count: 8 / 30; [EntityPlayerMP['The12thSpaz'/153, l='world', x=-1310.53, y=70.00, z=-4194.02], EntityPlayerMP['StrongShovel'/246, l='world', x=-670.12, y=68.50, z=3238.95], EntityPlayerMP['SalientGreen'/485, l='world', x=-783.70, y=66.00, z=561.84], EntityPlayerMP['swed1shf1sh'/556, l='world', x=2128.30, y=27.30, z=839.30], EntityPlayerMP['brett0007'/1288, l='world', x=-92.90, y=65.00, z=-2685.72], EntityPlayerMP['iHitman_'/1978, l='world', x=-4092.08, y=134.85, z=2905.70], EntityPlayerMP['thatdutchguy87'/2348, l='world', x=-555.65, y=70.00, z=349.15], EntityPlayerMP['TheValkyrieHeart'/3039, l='world', x=2129.24, y=27.00, z=840.70]]
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)

**Comment by Raycoms** [comment]
Does this happen all the time?

2017-05-04 12:55 GMT-03:00 anton021 <notifications@github.com>:

**Comment by anton021** [comment]
Once the problem occurs, it keeps happening on that same citizen hut so the only fix is to destroy it

**Comment by Raycoms** [comment]
Will look at that tomorrow morning

2017-05-04 21:30 GMT-03:00 DaveSpencer <notifications@github.com>:

**Comment by Raycoms** [comment]
2017-05-04 22:27 GMT-03:00 Ray Neiheiser <ray.neiheiser@gmail.com>:

**Comment by marvin-bitterlich** [comment]
closing as fixed
