### ISSUE TITLE
Crashing from entity ticks, tinkers mod compability

### ISSUE THREAD

**Issue by korsman** [ldtteam/minecolonies#938]
### Minecolonies version

version 1.10.2-0.7.776 or forge 1.10.2-12.18.3.2254

### Expected behavior

Game was left running over night for test of the hunger system.
Only MineColonies ond Journymap is installed.
Game had crashed and now he test world is crashing on try to open.
Crashfile say : Ticking entityjava.lang.NoSuchMethodError from try to check for tinker compability with tinker weapon for guard.
And tinkers construct isnt installed in my little test pack

### Actual behaviour

- YYY

### Steps to reproduce the problem

1. Dont know how to reproduce, game was running unwatched
2. 
3. 
4. 

---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 5/4/17 11:32 PM
Description: Ticking entity

java.lang.NoSuchMethodError: com.minecolonies.compatibility.tinkers.TinkersWeaponHelper.isTinkersSword(Lnet/minecraft/item/ItemStack;)Z
	at com.minecolonies.compatibility.Compatibility.isTinkersWeapon(Compatibility.java:98)
	at com.minecolonies.coremod.util.Utils.doesItemServeAsWeapon(Utils.java:151)
	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic.lambda$checkForWeapon$14(AbstractEntityAIBasic.java:906)
	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic$$Lambda$261/773086480.test(Unknown Source)
	at com.minecolonies.coremod.util.InventoryFunctions.lambda$null$0(InventoryFunctions.java:43)
	at com.minecolonies.coremod.util.InventoryFunctions$$Lambda$265/1768488245.test(Unknown Source)
	at com.minecolonies.coremod.util.InventoryFunctions.matchInProvider(InventoryFunctions.java:94)
	at com.minecolonies.coremod.util.InventoryFunctions.matchFirstInProvider(InventoryFunctions.java:63)
	at com.minecolonies.coremod.util.InventoryFunctions.matchFirstInProvider(InventoryFunctions.java:41)
	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic.checkForWeapon(AbstractEntityAIBasic.java:904)
	at com.minecolonies.coremod.entity.ai.citizen.guard.EntityAIMeleeGuard.searchTarget(EntityAIMeleeGuard.java:116)
	at com.minecolonies.coremod.entity.ai.citizen.guard.EntityAIMeleeGuard$$Lambda$256/1361961829.get(Unknown Source)
	at com.minecolonies.coremod.entity.ai.util.AITarget.apply(AITarget.java:125)
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.applyTarget(AbstractAISkeleton.java:201)
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.checkOnTarget(AbstractAISkeleton.java:175)
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton$$Lambda$153/1147973125.test(Unknown Source)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:128)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:773)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2183)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:155)
	at com.minecolonies.coremod.entity.EntityCitizen.func_70636_d(EntityCitizen.java:1060)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.minecolonies.compatibility.Compatibility.isTinkersWeapon(Compatibility.java:98)
	at com.minecolonies.coremod.util.Utils.doesItemServeAsWeapon(Utils.java:151)
	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic.lambda$checkForWeapon$14(AbstractEntityAIBasic.java:906)
	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic$$Lambda$261/773086480.test(Unknown Source)
	at com.minecolonies.coremod.util.InventoryFunctions.lambda$null$0(InventoryFunctions.java:43)
	at com.minecolonies.coremod.util.InventoryFunctions$$Lambda$265/1768488245.test(Unknown Source)
	at com.minecolonies.coremod.util.InventoryFunctions.matchInProvider(InventoryFunctions.java:94)
	at com.minecolonies.coremod.util.InventoryFunctions.matchFirstInProvider(InventoryFunctions.java:63)
	at com.minecolonies.coremod.util.InventoryFunctions.matchFirstInProvider(InventoryFunctions.java:41)
	at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIBasic.checkForWeapon(AbstractEntityAIBasic.java:904)
	at com.minecolonies.coremod.entity.ai.citizen.guard.EntityAIMeleeGuard.searchTarget(EntityAIMeleeGuard.java:116)
	at com.minecolonies.coremod.entity.ai.citizen.guard.EntityAIMeleeGuard$$Lambda$256/1361961829.get(Unknown Source)
	at com.minecolonies.coremod.entity.ai.util.AITarget.apply(AITarget.java:125)
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.applyTarget(AbstractAISkeleton.java:201)
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.checkOnTarget(AbstractAISkeleton.java:175)
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton$$Lambda$153/1147973125.test(Unknown Source)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:128)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:773)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2183)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577)
	at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:155)
	at com.minecolonies.coremod.entity.EntityCitizen.func_70636_d(EntityCitizen.java:1060)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)
	at net.minecraft.world.World.func_72870_g(World.java:1934)

-- Entity being ticked --
Details:
	Entity Type: minecolonies.Citizen (com.minecolonies.coremod.entity.EntityCitizen)
	Entity ID: 24340276
	Entity Name: Geoffrey K. Archer
	Entity's Exact location: 922.11, 4.00, -1709.21
	Entity's Block location: World: (922,4,-1710), Chunk: (at 10,0,2 in 57,-107; contains blocks 912,0,-1712 to 927,255,-1697), Region: (1,-4; contains chunks 32,-128 to 63,-97, blocks 512,0,-2048 to 1023,255,-1537)
	Entity's Momentum: 0.10, -0.08, -0.02
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['daddy_korsman'/98, l='New World', x=886.50, y=16.50, z=-1702.51]]
	Chunk stats: ServerChunkCache: 657 Drop: 0
	Level seed: -883998180947695904
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (792,4,-1774), Chunk: (at 8,0,2 in 49,-111; contains blocks 784,0,-1776 to 799,255,-1761), Region: (1,-4; contains chunks 32,-128 to 63,-97, blocks 512,0,-2048 to 1023,255,-1537)
	Level time: 157719 game time, 163217 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 77024 (now: false), thunder time: 38646 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 551173088 bytes (525 MB) / 2663383040 bytes (2540 MB) up to 5249695744 bytes (5006 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5632m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2254 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2254.jar) 
	UCHIJAAAA	Forge{12.18.3.2254} [Minecraft Forge] (forge-1.10.2-12.18.3.2254.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.4.6} [JourneyMap] (journeymap-1.10.2-5.4.6.jar) 
	UCHIJAAAA	minecolonies{1.10.2-0.7.776} [MineColonies] (minecolonies-universal-1.10.2-0.7.776.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['daddy_korsman'/98, l='New World', x=886.50, y=16.50, z=-1702.51]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by anton021** [comment]
can he connect when its day time? also is Level spawn location: World: (792,4,-1774), a location for a citizen hut?

**Comment by marvin-bitterlich** [comment]
@Raycoms told ya :P Please fix.

**Comment by marvin-bitterlich** [comment]
closing, fixed
