### ISSUE TITLE
[BUG] ai crash

### ISSUE THREAD

**Issue by Ironarc-corp** [ldtteam/minecolonies#9414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.19.2

### MineColonies Version

1.19.2 - 1.1.151-beta

### Structurize Version

All the mods 8-1.0.27

### Related Mods and their Versions

![Capture d'écran 2023-09-28 105043](https://github.com/ldtteam/minecolonies/assets/108798657/aca49202-bdc7-4823-a1fb-36dec789438f)

### Current Behavior

des porteur on eu un engrenage rouge 

### Expected Behavior

je ne comprend pas

### Reproduction Steps

pas de chose faite spécifiquement

### Logs

<script src="https://gist.github.com/Ironarc-corp/330b4780e88d62d29d594ae826f680b3.js"></script>

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by jaeggr** [comment]
Same thing still happening with 1.1.240-RELEASE.  It seems to be related to a null reference to a building. I just so happen to have a guard tower in my colony that says it's "missing its respective building" so I wonder if that is it...  This has happened before with another tower, and the only fix was picking it up and reconstructing it.

<details>
  <summary>reveal log snippet</summary>
    
  ```
  [00:37:25] [Server thread/ERROR] [minecolonies/]: Pausing Citizen Katie G. Hammond (com.minecolonies.job.deliveryman) in colony:1 at BlockPos{x=-259, y=69, z=1696} for 800 Seconds because of error:
java.lang.NullPointerException: Cannot invoke "com.minecolonies.api.colony.buildings.IBuilding.getCapability(net.minecraftforge.common.capabilities.Capability, net.minecraft.core.Direction)" because "targetBuilding" is null
        at TRANSFORMER/minecolonies@1.20.1-1.1.240-RELEASE/com.minecolonies.coremod.entity.ai.citizen.deliveryman.EntityAIWorkDeliveryman.deliver(EntityAIWorkDeliveryman.java:397)
        at TRANSFORMER/minecolonies@1.20.1-1.1.240-RELEASE/com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:79)
        at TRANSFORMER/minecolonies@1.20.1-1.1.240-RELEASE/com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:163)
        at TRANSFORMER/minecolonies@1.20.1-1.1.240-RELEASE/com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:149)
        at TRANSFORMER/minecolonies@1.20.1-1.1.240-RELEASE/com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:127)
        at TRANSFORMER/minecolonies@1.20.1-1.1.240-RELEASE/com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:103)
        at TRANSFORMER/minecolonies@1.20.1-1.1.240-RELEASE/com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.tick(AbstractAISkeleton.java:61)
        at TRANSFORMER/minecolonies@1.20.1-1.1.240-RELEASE/com.minecolonies.coremod.entity.ai.citizen.CitizenAI.lambda$registerWorkAI$4(CitizenAI.java:95)
        at TRANSFORMER/minecolonies@1.20.1-1.1.240-RELEASE/com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:79)
        at TRANSFORMER/minecolonies@1.20.1-1.1.240-RELEASE/com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:163)
        at TRANSFORMER/minecolonies@1.20.1-1.1.240-RELEASE/com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:149)
        at TRANSFORMER/minecolonies@1.20.1-1.1.240-RELEASE/com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:127)
        at TRANSFORMER/minecolonies@1.20.1-1.1.240-RELEASE/com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:103)
        at TRANSFORMER/minecolonies@1.20.1-1.1.240-RELEASE/com.minecolonies.coremod.entity.citizen.EntityCitizen.lambda$new$11(EntityCitizen.java:297)
        at TRANSFORMER/minecolonies@1.20.1-1.1.240-RELEASE/com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.checkCondition(BasicTransition.java:87)
        at TRANSFORMER/minecolonies@1.20.1-1.1.240-RELEASE/com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:138)
        at TRANSFORMER/minecolonies@1.20.1-1.1.240-RELEASE/com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:127)
        at TRANSFORMER/minecolonies@1.20.1-1.1.240-RELEASE/com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:103)
        at TRANSFORMER/minecolonies@1.20.1-1.1.240-RELEASE/com.minecolonies.api.entity.citizen.AbstractEntityCitizen.m_8107_(AbstractEntityCitizen.java:418)
        at TRANSFORMER/minecolonies@1.20.1-1.1.240-RELEASE/com.minecolonies.coremod.entity.citizen.EntityCitizen.m_8107_(EntityCitizen.java:708)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2298)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.Mob.m_8119_(Mob.java:337)
        at TRANSFORMER/minecolonies@1.20.1-1.1.240-RELEASE/com.minecolonies.api.entity.citizen.AbstractCivilianEntity.m_8119_(AbstractCivilianEntity.java:117)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.m_46653_(Level.java:479)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
        at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
        at java.base/java.lang.Thread.run(Thread.java:833)
  ```
  
</details>

**Comment by Talyda** [comment]
> 1.1.240-RELEASE.

Can you try with newer versions?

**Comment by Ironarc-corp** [comment]
malheureusement non car comme c'est un mod pack je ne peut pas le modifier
