### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by romamuravey** [ldtteam/minecolonies#9454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Verison?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### Minecraft Version

1.2

### MineColonies Version

idk its ATM9 0.1.12

### Structurize Version

idk its ATM9 0.1.12

### Related Mods and their Versions

![image](https://github.com/ldtteam/minecolonies/assets/147654625/321d2b23-2787-4345-9292-192ff5ed6748)

### Logs

https://gist.github.com/romamuravey/085b7c0b2a7cd6251a5d555fd01ded0a/56af004b158fc9034470538eefb9812d3c8a2213

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
Can't find anything related to Minecolonies, and the issue template is not filled in correctly.,

**Comment by Nightenom** [comment]
You have to look better then :)
```[23:01:28] [Server thread/WARN]: Statemachine for state ATTACKING threw an exception:
java.lang.ClassCastException: class twilightforest.entity.projectile.SeekerArrow cannot be cast to class com.minecolonies.coremod.entity.CustomArrowEntity (twilightforest.entity.projectile.SeekerArrow is in module twilightforest@4.3.1850 of loader 'TRANSFORMER' @2b06681c; com.minecolonies.coremod.entity.CustomArrowEntity is in module minecolonies@1.20.1-1.1.195-BETA of loader 'TRANSFORMER' @2b06681c)
	at com.minecolonies.coremod.entity.ai.citizen.guard.RangerCombatAI.calculateDamage(RangerCombatAI.java:243) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
	at com.minecolonies.coremod.entity.ai.citizen.guard.RangerCombatAI.doAttack(RangerCombatAI.java:167) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
	at com.minecolonies.coremod.entity.ai.combat.AttackMoveAI.tryAttack(AttackMoveAI.java:148) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:79) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:163) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:149) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:127) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:103) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.tick(AbstractAISkeleton.java:61) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
	at com.minecolonies.coremod.entity.ai.citizen.CitizenAI.lambda$registerWorkAI$4(CitizenAI.java:95) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:79) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:163) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:149) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:127) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:103) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
	at com.minecolonies.coremod.entity.citizen.EntityCitizen.lambda$new$11(EntityCitizen.java:297) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.checkCondition(BasicTransition.java:87) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:138) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:127) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:103) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
	at com.minecolonies.api.entity.citizen.AbstractEntityCitizen.m_8107_(AbstractEntityCitizen.java:415) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
	at com.minecolonies.coremod.entity.citizen.EntityCitizen.m_8107_(EntityCitizen.java:708) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2292) ~[client-1.20.1-20230612.114412-srg.jar%23872!/:?]
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:337) ~[client-1.20.1-20230612.114412-srg.jar%23872!/:?]
	at com.minecolonies.api.entity.citizen.AbstractCivilianEntity.m_8119_(AbstractCivilianEntity.java:113) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
	at net.minecraft.server.level.ServerLevel.track(ServerLevel.java:6169) ~[client-1.20.1-20230612.114412-srg.jar%23872!/:?]
	at net.minecraft.server.level.ServerLevel.redirect$cjl000$onTickNonPassenger(ServerLevel.java:6185) ~[client-1.20.1-20230612.114412-srg.jar%23872!/:?]
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[client-1.20.1-20230612.114412-srg.jar%23872!/:?]
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[client-1.20.1-20230612.114412-srg.jar%23872!/:?]
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[client-1.20.1-20230612.114412-srg.jar%23872!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23872!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[client-1.20.1-20230612.114412-srg.jar%23872!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23872!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23872!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23872!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23872!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23872!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]```

**Comment by Thodor12** [comment]
> You have to look better then :)
> 
> ```
> java.lang.ClassCastException: class twilightforest.entity.projectile.SeekerArrow cannot be cast to class com.minecolonies.coremod.entity.CustomArrowEntity (twilightforest.entity.projectile.SeekerArrow is in module twilightforest@4.3.1850 of loader 'TRANSFORMER' @2b06681c; com.minecolonies.coremod.entity.CustomArrowEntity is in module minecolonies@1.20.1-1.1.195-BETA of loader 'TRANSFORMER' @2b06681c)
> 	at com.minecolonies.coremod.entity.ai.citizen.guard.RangerCombatAI.calculateDamage(RangerCombatAI.java:243) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
> 	at com.minecolonies.coremod.entity.ai.citizen.guard.RangerCombatAI.doAttack(RangerCombatAI.java:167) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
> 	at com.minecolonies.coremod.entity.ai.combat.AttackMoveAI.tryAttack(AttackMoveAI.java:148) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
> 	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:79) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
> 	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:163) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
> 	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:149) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
> 	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:127) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
> 	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:103) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
> 	at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.tick(AbstractAISkeleton.java:61) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
> 	at com.minecolonies.coremod.entity.ai.citizen.CitizenAI.lambda$registerWorkAI$4(CitizenAI.java:95) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
> 	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.getNextState(BasicTransition.java:79) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
> 	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.transitionToNext(BasicStateMachine.java:163) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
> 	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:149) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
> 	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:127) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
> 	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:103) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
> 	at com.minecolonies.coremod.entity.citizen.EntityCitizen.lambda$new$11(EntityCitizen.java:297) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
> 	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicTransition.checkCondition(BasicTransition.java:87) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
> 	at com.minecolonies.api.entity.ai.statemachine.basestatemachine.BasicStateMachine.checkTransition(BasicStateMachine.java:138) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
> 	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.checkTransition(TickRateStateMachine.java:127) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
> 	at com.minecolonies.api.entity.ai.statemachine.tickratestatemachine.TickRateStateMachine.tick(TickRateStateMachine.java:103) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
> 	at com.minecolonies.api.entity.citizen.AbstractEntityCitizen.m_8107_(AbstractEntityCitizen.java:415) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
> 	at com.minecolonies.coremod.entity.citizen.EntityCitizen.m_8107_(EntityCitizen.java:708) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
> 	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2292) ~[client-1.20.1-20230612.114412-srg.jar%23872!/:?]
> 	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:337) ~[client-1.20.1-20230612.114412-srg.jar%23872!/:?]
> 	at com.minecolonies.api.entity.citizen.AbstractCivilianEntity.m_8119_(AbstractCivilianEntity.java:113) ~[minecolonies-1.20.1-1.1.195-BETA.jar%23734!/:1.20.1-1.1.195-BETA]
> 	at net.minecraft.server.level.ServerLevel.track(ServerLevel.java:6169) ~[client-1.20.1-20230612.114412-srg.jar%23872!/:?]
> 	at net.minecraft.server.level.ServerLevel.redirect$cjl000$onTickNonPassenger(ServerLevel.java:6185) ~[client-1.20.1-20230612.114412-srg.jar%23872!/:?]
> 	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693) ~[client-1.20.1-20230612.114412-srg.jar%23872!/:?]
> 	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[client-1.20.1-20230612.114412-srg.jar%23872!/:?]
> 	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343) ~[client-1.20.1-20230612.114412-srg.jar%23872!/:?]
> 	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23872!/:?]
> 	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323) ~[client-1.20.1-20230612.114412-srg.jar%23872!/:?]
> 	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893) ~[client-1.20.1-20230612.114412-srg.jar%23872!/:?]
> 	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23872!/:?]
> 	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23872!/:?]
> 	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23872!/:?]
> 	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23872!/:?]
> 	at java.lang.Thread.run(Thread.java:833) ~[?:?]```
> ```

File was truncated, I missed that

**Comment by Raycoms** [comment]
fixed
