### ISSUE TITLE
[BUG] <WHY THE STRUCTURIZE CRUSHES GAME>

### ISSUE THREAD

**Issue by lsj0513** [ldtteam/minecolonies#9569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.2.1-1.1.240

### Structurize Version

1.20.1-1.0.662

### Related Mods and their Versions

1. Forge Version: 47.2.0
2. BlockUI Version: 1.20.1-0.0.98
3.  Domum Ornametum Version: 1.20-1.0.110

### Current Behavior

When I used Build wand..or stick? Well When I used Build stick, It looks everything is fine. But when I click any button on the Structurize menu, the Game crushed. Why this happened? I can't enjoy the game because of it. I tried to Build a Building without the stick, but the Minecolonies Blocks didn't sense my building. 
I using a Samsung laptop, Windows 11 OS.
(Sorry for it, I can't find the my game record include that error.)

### Expected Behavior

Building should builded. But It didn't.

### Reproduction Steps

1. Open the Forge minecraft that include Minecolonies on a Laptop, Windows 11.
2. Open the inventory and take out Build tool.
3. Right click.
4. Press Switch Pack Menu and choice any pack, and confirm. or go to 5.
5. Choose any buildings, and Press check button.
6. Press one of three buttons.
7. Then it happen.
8. But It can not happened on a Desktop.

### Logs

// My bad.

Time: 2023-11-15 19:00:51
Description: Exception in server tick loop

java.lang.NullPointerException: Cannot invoke "com.minecolonies.api.colony.buildings.IBuilding.setDeconstructed()" because the return value of "com.minecolonies.api.tileentities.AbstractTileEntityColonyBuilding.getBuilding()" is null
	at com.minecolonies.api.util.CreativeBuildingStructureHandler.triggerSuccess(CreativeBuildingStructureHandler.java:114) ~[minecolonies-1.20.1-1.1.314-BETA.jar%23164!/:1.20.1-1.1.314-BETA] {re:classloading}
	at com.ldtteam.structurize.placement.AbstractBlueprintIterator.iterateWithCondition(AbstractBlueprintIterator.java:126) ~[structurize-1.20.1-1.0.662-BETA.jar%23166!/:1.20.1-1.0.662-BETA] {re:classloading}
	at com.ldtteam.structurize.placement.AbstractBlueprintIterator.decrement(AbstractBlueprintIterator.java:97) ~[structurize-1.20.1-1.0.662-BETA.jar%23166!/:1.20.1-1.0.662-BETA] {re:classloading}
	at com.ldtteam.structurize.util.TickedWorldOperation.lambda$apply$1(TickedWorldOperation.java:227) ~[structurize-1.20.1-1.0.662-BETA.jar%23166!/:1.20.1-1.0.662-BETA] {re:classloading}
	at com.ldtteam.structurize.placement.StructurePlacer.executeStructureStep(StructurePlacer.java:171) ~[structurize-1.20.1-1.0.662-BETA.jar%23166!/:1.20.1-1.0.662-BETA] {re:classloading}
	at com.ldtteam.structurize.util.TickedWorldOperation.apply(TickedWorldOperation.java:226) ~[structurize-1.20.1-1.0.662-BETA.jar%23166!/:1.20.1-1.0.662-BETA] {re:classloading}
	at com.ldtteam.structurize.management.Manager.onWorldTick(Manager.java:68) ~[structurize-1.20.1-1.0.662-BETA.jar%23166!/:1.20.1-1.0.662-BETA] {re:classloading}
	at com.ldtteam.structurize.event.EventSubscriber.onWorldTick(EventSubscriber.java:70) ~[structurize-1.20.1-1.0.662-BETA.jar%23166!/:1.20.1-1.0.662-BETA] {re:classloading}
	at com.ldtteam.structurize.event.__EventSubscriber_onWorldTick_LevelTickEvent.invoke(.dynamic) ~[structurize-1.20.1-1.0.662-BETA.jar%23166!/:1.20.1-1.0.662-BETA] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPreLevelTick(ForgeEventFactory.java:925) ~[forge-1.20.1-47.2.0-universal.jar%23173!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:890) ~[client-1.20.1-20230612.114412-srg.jar%23168!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23168!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23168!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23168!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23168!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 836997888 bytes (798 MiB) / 2227175424 bytes (2124 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: 13th Gen Intel(R) Core(TM) i7-1355U
	Identifier: Intel64 Family 6 Model 186 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 2.61
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 12
	Graphics card #0 name: Intel(R) Iris(R) Xe Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0xa7a1
	Graphics card #0 versionInfo: DriverVersion=31.0.101.4502
	Memory slot #0 capacity (MB): 2048.00
	Memory slot #0 clockSpeed (GHz): 4.27
	Memory slot #0 type: LPDDR4
	Memory slot #1 capacity (MB): 2048.00
	Memory slot #1 clockSpeed (GHz): 4.27
	Memory slot #1 type: LPDDR4
	Memory slot #2 capacity (MB): 2048.00
	Memory slot #2 clockSpeed (GHz): 4.27
	Memory slot #2 type: LPDDR4
	Memory slot #3 capacity (MB): 2048.00
	Memory slot #3 clockSpeed (GHz): 4.27
	Memory slot #3 type: LPDDR4
	Memory slot #4 capacity (MB): 2048.00
	Memory slot #4 clockSpeed (GHz): 4.27
	Memory slot #4 type: LPDDR4
	Memory slot #5 capacity (MB): 2048.00
	Memory slot #5 clockSpeed (GHz): 4.27
	Memory slot #5 type: LPDDR4
	Memory slot #6 capacity (MB): 2048.00
	Memory slot #6 clockSpeed (GHz): 4.27
	Memory slot #6 type: LPDDR4
	Memory slot #7 capacity (MB): 2048.00
	Memory slot #7 clockSpeed (GHz): 4.27
	Memory slot #7 type: LPDDR4
	Virtual memory max (MB): 18496.88
	Virtual memory used (MB): 12771.61
	Swap memory total (MB): 2432.00
	Swap memory used (MB): 138.99
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Seojuncoco0513'/240, l='ServerLevel[새로운 세계]', x=1.57, y=80.77, z=-2.15]]
	Data Packs: vanilla, mod:domum_ornamentum, mod:structurize, mod:forge, mod:blockui, mod:multipiston, mod:minecolonies, mod:towntalk (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Launched Version: forge-47.2.0
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		domum_ornamentum-1.20-1.0.147-BETA-universal.jar  |Domum Ornamentum              |domum_ornamentum              |1.20-1.0.147-BETA   |DONE      |Manifest: NOSIGNATURE
		structurize-1.20.1-1.0.662-BETA.jar               |Structurize                   |structurize                   |1.20.1-1.0.662-BETA |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.2.0-universal.jar                 |Forge                         |forge                         |47.2.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		blockui-1.20.1-1.0.123-BETA.jar                   |UI Library Mod                |blockui                       |1.20.1-1.0.123-BETA |DONE      |Manifest: NOSIGNATURE
		multipiston-1.20-1.2.31-ALPHA.jar                 |Multi-Piston                  |multipiston                   |1.20-1.2.31-ALPHA   |DONE      |Manifest: NOSIGNATURE
		minecolonies-1.20.1-1.1.314-BETA.jar              |MineColonies                  |minecolonies                  |1.20.1-1.1.314-BETA |DONE      |Manifest: NOSIGNATURE
		towntalk-1.20.1-1.0.0.jar                         |TownTalk                      |towntalk                      |1.0.0               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: a8e3cd0e-7041-4828-8c98-fb8113962661
	FML: 47.2
	Forge: net.minecraftforge:47.2.0
### Anything else?

No

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by MotionlessTrain** [comment]
Update minecolonies. The crash has been fixed already

**Comment by lsj0513** [comment]
Oh Okay Thanks you

**Comment by lsj0513** [comment]
No It's not working

**Comment by lsj0513** [comment]
I added the logs

**Comment by lsj0513** [comment]
**Check it**
