### ISSUE TITLE
Crash when upgrading or repairing buildings

### ISSUE THREAD

**Issue by Arthebas** [ldtteam/minecolonies#957]
### Minecolonies version

minecolonies-universal-1.11.2-0.7.887.jar

### Expected behavior

- Upgrading a building to level 2 or repair it

### Actual behaviour

- Builder take ressources, go to build spot to upgrade and doesn't do anything (problem occurs for my friend and me, not the same city or building but can't go to level 2 building like Citizen's Hut or Sawmill. Here is the console log: 

[13:42:04] [Server thread/ERROR] [minecolonies]: Pausing Entity Melanie L. Cheyne (com.minecolonies.coremod.job.Builder) at BlockPos{x=310, y=63, z=561} for 0 Seconds because of error:
[13:42:04] [Server thread/INFO]: [STDERR]: java.lang.NullPointerException: The validated object is null
[13:42:04] [Server thread/INFO]: [STDERR]: at org.apache.commons.lang3.Validate.notNull(Validate.java:222)
[13:42:04] [Server thread/INFO]: [STDERR]: at org.apache.commons.lang3.Validate.notNull(Validate.java:203)
[13:42:04] [Server thread/INFO]: [STDERR]: at net.minecraft.util.NonNullList.set(SourceFile:45)
[13:42:04] [Server thread/INFO]: [STDERR]: at net.minecraft.entity.EntityLiving.func_184201_a(EntityLiving.java:919)
[13:42:04] [Server thread/INFO]: [STDERR]: at com.minecolonies.coremod.placementhandlers.PlacementHandlers$AirPlacementHandler.handle(PlacementHandlers.java:271)
[13:42:04] [Server thread/INFO]: [STDERR]: at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructure.placeBlockAt(AbstractEntityAIStructure.java:547)
[13:42:04] [Server thread/INFO]: [STDERR]: at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructure.structureStep(AbstractEntityAIStructure.java:241)
[13:42:04] [Server thread/INFO]: [STDERR]: at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructure$$Lambda$98/1586102803.apply(Unknown Source)
[13:42:04] [Server thread/INFO]: [STDERR]: at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructure.lambda$generateStructureGenerator$3(AbstractEntityAIStructure.java:279)
[13:42:04] [Server thread/INFO]: [STDERR]: at com.minecolonies.coremod.entity.ai.basic.AbstractEntityAIStructure$$Lambda$97/1515049437.get(Unknown Source)
[13:42:04] [Server thread/INFO]: [STDERR]: at com.minecolonies.coremod.entity.ai.util.AITarget.apply(AITarget.java:125)
[13:42:04] [Server thread/INFO]: [STDERR]: at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.applyTarget(AbstractAISkeleton.java:201)
[13:42:04] [Server thread/INFO]: [STDERR]: at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.checkOnTarget(AbstractAISkeleton.java:175)
[13:42:04] [Server thread/INFO]: [STDERR]: at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton$$Lambda$138/411806598.test(Unknown Source)
[13:42:04] [Server thread/INFO]: [STDERR]: at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
[13:42:04] [Server thread/INFO]: [STDERR]: at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
[13:42:04] [Server thread/INFO]: [STDERR]: at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
[13:42:04] [Server thread/INFO]: [STDERR]: at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
[13:42:04] [Server thread/INFO]: [STDERR]: at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
[13:42:04] [Server thread/INFO]: [STDERR]: at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
[13:42:04] [Server thread/INFO]: [STDERR]: at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
[13:42:04] [Server thread/INFO]: [STDERR]: at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
[13:42:04] [Server thread/INFO]: [STDERR]: at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[13:42:04] [Server thread/INFO]: [STDERR]: at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
[13:42:04] [Server thread/INFO]: [STDERR]: at com.minecolonies.coremod.entity.ai.basic.AbstractAISkeleton.func_75246_d(AbstractAISkeleton.java:128)
[13:42:04] [Server thread/INFO]: [STDERR]: at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)
[13:42:04] [Server thread/INFO]: [STDERR]: at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:769)
[13:42:04] [Server thread/INFO]: [STDERR]: at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2258)
[13:42:04] [Server thread/INFO]: [STDERR]: at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:573)
[13:42:04] [Server thread/INFO]: [STDERR]: at net.minecraft.entity.EntityAgeable.func_70636_d(EntityAgeable.java:171)
[13:42:04] [Server thread/INFO]: [STDERR]: at com.minecolonies.coremod.entity.EntityCitizen.func_70636_d(EntityCitizen.java:1061)
[13:42:04] [Server thread/INFO]: [STDERR]: at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2088)
[13:42:04] [Server thread/INFO]: [STDERR]: at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:296)
[13:42:04] [Server thread/INFO]: [STDERR]: at net.minecraft.world.World.func_72866_a(World.java:1963)
[13:42:04] [Server thread/INFO]: [STDERR]: at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
[13:42:04] [Server thread/INFO]: [STDERR]: at net.minecraft.world.World.func_72870_g(World.java:1932)
[13:42:04] [Server thread/INFO]: [STDERR]: at net.minecraft.world.World.func_72939_s(World.java:1748)
[13:42:04] [Server thread/INFO]: [STDERR]: at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
[13:42:04] [Server thread/INFO]: [STDERR]: at net.
minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
[13:42:04] [Server thread/INFO]: [STDERR]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
[13:42:04] [Server thread/INFO]: [STDERR]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
[13:42:04] [Server thread/INFO]: [STDERR]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
[13:42:04] [Server thread/INFO]: [STDERR]: at java.lang.Thread.run(Thread.java:745)

### Steps to reproduce the problem

1. Launch Minecraft with forge 1.11.2-13.20.0.2282
2. Launch upgrade level 2 for sawmill (wood) or citizen's hut (stone)
3. Huge lag on server and if we don't stop builder, server crash

Thanks for your help :)

**Comment by Raycoms** [comment]
Thanks for the report, fixing it right now.

2017-05-09 8:49 GMT-03:00 Arthebas <notifications@github.com>:

**Comment by Raycoms** [comment]
Should fix this:
http://teamcity.smithsmodding.com/guestAuth/repository/download/Minecolonies_Branches/917:id/minecolonies-universal-1.11.2-0.7.917.jar

**Comment by Arthebas** [comment]
Perfect work, we tried many buildings and all can upgrade level 2 without crash or problem.
Many thanks from us :+1:  :)
