### ISSUE TITLE
[BUG] Crash with Queen Bee installed, when looking at Request

### ISSUE THREAD

**Issue by drakray** [ldtteam/minecolonies#9599]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **alpha** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.1.333-BETA

### Structurize Version

1.0.662-BETA

### Related Mods and their Versions

NeoForge 47.1.79
[QueenBee 3.1.3](https://legacy.curseforge.com/minecraft/mc-mods/queen-bee)

### Current Behavior

Crashes when looking at Guard Request, or the Clipboard, when QueenBee is installed

### Expected Behavior

Not to crash?

### Reproduction Steps

1. Have colony with Guard with no armor
2. Try to look at request, when having related mods installed
3. Crash

### Logs

https://pastebin.com/dBGqWwdJ

### Anything else?

<details>
<summary>Crash snippet</summary>

```
Description: Ticking/Updating BO screen

java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.EnumMap.get(Object)" is null
	at com.cerbon.queen_bee.item.QBArmorMaterials.m_7366_(QBArmorMaterials.java:54) ~[queenbee-1.20.1-3.1.3.jar%23876!/:3.1.3] {re:classloading}
	at com.minecolonies.api.util.ItemStackUtils.getArmorLevel(ItemStackUtils.java:505) ~[minecolonies-1.20.1-1.1.333-BETA.jar%23854!/:1.20.1-1.1.333-BETA] {re:classloading}
	at com.minecolonies.api.util.ItemStackUtils.getMiningLevel(ItemStackUtils.java:329) ~[minecolonies-1.20.1-1.1.333-BETA.jar%23854!/:1.20.1-1.1.333-BETA] {re:classloading}
	at com.minecolonies.api.util.ItemStackUtils.hasToolLevel(ItemStackUtils.java:270) ~[minecolonies-1.20.1-1.1.333-BETA.jar%23854!/:1.20.1-1.1.333-BETA] {re:classloading}
	at com.minecolonies.api.colony.requestsystem.requestable.Tool.lambda$matches$2(Tool.java:193) ~[minecolonies-1.20.1-1.1.333-BETA.jar%23854!/:1.20.1-1.1.333-BETA] {re:classloading}
```
</details>

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Thodor12** [comment]
Please report to QueenBee, they seem to be unable to obtain armor levels from itemstacks. If they're lacking info for that they should return default values and not crash.
