### ISSUE TITLE
[BUG] Beekeeper AI will crash upon trying to read honey level from non beehive

### ISSUE THREAD

**Issue by Thodor12** [ldtteam/minecolonies#9991]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest MineColonies Version?

- [X] I am running the latest **beta** version of MineColonies for my Minecraft version.

### Did you check on the Wiki? or ask on Discord?

- [X] I checked the MineColonies Wiki and made sure my issue is not covered there. Or I was sent from discord to open an issue here.

### What were you playing at the time? Were you able to reproduce it in both settings?

- [X] Single Player
- [ ] Multi Player

### Minecraft Version

1.20.1

### MineColonies Version

1.20.1-1.1.593-BETA

### Structurize Version

1.20.1-1.0.737-BETA

### Current Behavior

The Beekeeper is somehow able to read the honey level from non beehive blocks, causing a crash

### Expected Behavior

The Beekeeper should first check if the block is a beehive, before attempting to read a property that does not exist.

### Reproduction Steps

None were provided by the OP, but a good guess:
- Place an apiary
- Tag beehives with the hive tool
- Destroy one of the beehives by hand
- Crash should appear upon the next cycle of the AI

### Logs

https://mclo.gs/y1GLSJ9

### Anything else?

* Add a thumbs-up to the bug report if you are also affected. This helps the bug report become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by armele** [comment]
I attempted to reproduce this in 1.21 (MineColonies 1.1.978) and could not. The AI handled my replacement of hives gracefully.  With a code review of EntityAIWorkBeekeeper.decideWhatToDo() I see that there is a check of the block instance that removes a hive block from the set of configured hives if it is not a BeehiveBlock.  

I suggest this could probably be closed.

**Comment by Thodor12** [comment]
@armele This needs fixing, whilst in an ideal world, yes the hive is removed.
However if the player or something else destroys the hive that the beekeeper was intending to go to, it'll cause a crash the moment you land in the harvest method, which has no protection against this.

Given that the beekeeper has a delay between the decision and harvest stages, this is most definitely a cause for concern.

**Comment by armele** [comment]
Ok, thanks for the explanation!  I'll see if I can reliably reproduce (and then fix).

**Comment by Thodor12** [comment]
This is mostly a timing thing, you'd have to catch it at the right time, but it should be somewhat doable if you purposelly cause extra delays.

**Comment by armele** [comment]
Reproduced:
[08Aug2025 08:26:24.690] [Server thread/ERROR] [minecolonies/]: Pausing Citizen Drake G. Cranford (com.minecolonies.job.beekeeper) in colony:1 at BlockPos{x=-24, y=81, z=282} for 100 Seconds because of error:
[08Aug2025 08:26:34.687] [Server thread/WARN] [minecolonies/]: Statemachine for state BEEKEEPER_HARVEST threw an exception:
java.lang.IllegalArgumentException: Cannot get property IntegerProperty{name=honey_level, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5]} as it does not exist in Block{minecraft:air}
	at net.minecraft.world.level.block.state.StateHolder.getValue(StateHolder.java:91) ~[forge-1.20.1-47.1.3_mapped_official_1.20.1-recomp.jar%23191!/:?]
	at net.minecraft.world.level.block.entity.BeehiveBlockEntity.getHoneyLevel(BeehiveBlockEntity.java:121) ~[forge-1.20.1-47.1.3_mapped_official_1.20.1-recomp.jar%23191!/:?]
	at com.minecolonies.core.entity.ai.workers.production.agriculture.EntityAIWorkBeekeeper.lambda$harvestHoney$4(EntityAIWorkBeekeeper.java:327) ~[%23196!/:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at com.minecolonies.core.entity.ai.workers.production.agriculture.EntityAIWorkBeekeeper.harvestHoney(EntityAIWorkBeekeeper.java:328) ~[%23196!/:?]
